### ISSUE TITLE
New Command - Test-DbaAgSpn for AG Listeners

### ISSUE THREAD

**Issue by pokorourk** [dataplat/dbatools#1005]
### Is this a *feature* OR *bug*:
Bug, though I am unsure whether this cmdlet is intended to cover listener names; in any event, information relevant to SPNs for listeners is interesting to us.

### System Details

- Operating system name and version: Windows Server 2016
- Output from `$PSVersionTable`:
```
Evaluate $PSVersionTable in PowerShell and paste the output here
```
Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
- Output of dbatools version:

```
Evaluate (Get-Module dbatools -ListAvailable).Version and paste output here
```
Major  Minor  Build  Revision
-----  -----  -----  --------
0      8      944    -1
- SQL Server version for source/target
2012 and 2016

### Steps to Reproduce
1) Install SQL Server and create an availability group with a listener
2) Run Test-DbaSpn and inspect results for SPNs corresponding to AlwaysOn Availability Group listener names

### Action Results
No SPNs listed for listener names

### Expected Results
SPNs listed for listener names

### Attached Logs or any exception errors

- Use of Start-Transcript can help collection of console output and exceptions
- Certain commands will generate an exception log that you can find in following directory: `dir $env:USERPROFILE\Documents\dbatools-exceptions.txt`

**Comment by wsmelton** [comment]
We will likely need to create a different command to test this properly. There are some [nuances and special setups](https://blogs.technet.microsoft.com/rhartskeerl/kerberos-and-availabilitygroups-what-you-need-to-know/) for an SPN with an AG (at least to truly catch it).

I'll let others comment as to which path we need to take.

**Comment by wsmelton** [comment]
We will actually need a function to pull the listener information, or add that to the `Get-DbaAvailabiltyGroup` command.

**Comment by peturgretars** [comment]
Hi, Here is some T-SQL I have been using to generating the command for me. Not sure if it is of any use to you at all but I thought I might share it just in case. 

`-- Copy and execute result from the 2 below queries for AlwaysOn installation
--------------------------------------------------------------------------------------------------------------------
-- Listener name 
DECLARE @domain_name varchar(128), @key varchar(128);
SET @key = 'SYSTEM\ControlSet001\Services\Tcpip\Parameters\';
EXEC master..xp_regread @rootkey='HKEY_LOCAL_MACHINE', @key=@key,@value_name='Domain',@value=@domain_name OUTPUT;

SELECT 'setspn -A MSSQLSvc/' 
+ (SELECT dns_name FROM sys.availability_group_listeners)  + '.'
+ (SELECT LOWER(CONVERT(varchar(100),@domain_name))) + ' '
+ (SELECT LOWER(service_account) FROM sys.dm_server_services WHERE servicename NOT LIKE '%Agent%') AS Command;
GO

-- Listener name with port number
DECLARE @domain_name varchar(128), @key varchar(128);
SET @key = 'SYSTEM\ControlSet001\Services\Tcpip\Parameters\';
EXEC master..xp_regread @rootkey='HKEY_LOCAL_MACHINE', @key=@key,@value_name='Domain',@value=@domain_name OUTPUT;

SELECT 'setspn -A MSSQLSvc/' 
+ (SELECT dns_name FROM sys.availability_group_listeners)  + '.'
+ (SELECT LOWER(CONVERT(varchar(100),@domain_name))) + ':1433 '
+ (SELECT LOWER(service_account) FROM sys.dm_server_services WHERE servicename NOT LIKE '%Agent%') AS Command;
GO`

Has worked for me so far but I would love to see that Test- and Set-DbaSpn had the possibility to configure for listener names as well.

**Comment by potatoqualitee** [comment]
Seems that this would be `Test-DbaAgSpn` 👍

**Comment by wsmelton** [comment]
I'm not really seeing likelihood of this command coming to fruition. I have not seen anyone asking about it and it is unique, environmental setup to need an SPN for a listener as well. Not sure we could build an setup to fully develop it properly.

**Comment by potatoqualitee** [comment]
this one seems kind of fun, tho. once windows 11 comes out, im gonna swap machines and setup use OftenOn to test AG stuff https://codykonior.github.io/OftenOn/

**Comment by andreasjordan** [comment]
This project looks very interesting - but is a bit stale. And it needs specific versions of some modules:
```
Install-Module OftenOn
Install-Module ComputerManagementDsc -RequiredVersion 8.0.0
Install-Module SqlServerDsc -RequiredVersion 13.3.0
Install-Module xFailOverCluster -RequiredVersion 1.14.1
Install-Module xPSDesiredStateConfiguration -RequiredVersion 9.0.0
Install-Module NetworkingDsc -RequiredVersion 7.4.0.0
Install-Module xSystemSecurity -RequiredVersion 1.5.0
```

**Comment by potatoqualitee** [comment]
I've run it before and it worked without a hitch. I literally just executed just one command and my lab was all setup 45 mins later. It even downloaded the ISOs I needed 🤩  One of the coolest projects I've played with. I think he added sql 2017 a while back.
