### ISSUE TITLE
New Command: Set-DbaDatabaseCollation

### ISSUE THREAD

**Issue by artyq** [dataplat/dbatools#2356]
## Feature Request

  I would be interested in seeing a function that could perform a collation change on a database and all existing data that is in that database.

**Comment by potatoqualitee** [comment]
Thanks for your request! Seems to be a popular one, but we'll need some time because it's complex and hard. Hoping @ClaudioESSilva can carve some time out in 2018 for it ;)

**Comment by wsmelton** [comment]
Yeah, this is one that is the same case as the balancing data files. If you want to [get a glimpse of what goes into the process](https://www.sqlservercentral.com/Forums/FindPost822173.aspx).

You also have to account for the effect it will have so while a command could be built, although I would likely never trust it to be honest as covering every scenario would be hard, you [have to consider the impact it will have and test](https://dba.stackexchange.com/a/152980/507).

**Comment by wsmelton** [comment]
Not sure we will ever get to this before it's a lot to handle in a single command.

If someone wants to take a stab they can reference this issue in the PR.
