### ISSUE TITLE
New Command - Get/New/Export Event Notifications

### ISSUE THREAD

**Issue by gbargsley** [dataplat/dbatools#3367]
I saw a #sqlhelp this morning about generating scripts for event notifications.  I looked and dbatools does not seem to have any commands around this option.  I will look in to creating functions for this.

https://docs.microsoft.com/en-us/sql/t-sql/statements/create-event-notification-transact-sql

**Comment by wsmelton** [comment]
If anyone is interested in picking this up after 2.0 release please create a new feature issue.
