### ISSUE TITLE
New Commands - DBCC CLEANTABLE and Get-DbaDbUnusedPages

### ISSUE THREAD

**Issue by awickham10** [dataplat/dbatools#3450]
## Feature Request
New command to execute DBCC CLEANTABLE - Reclaims space from dropped variable-length columns in tables or indexed views.

Suggested Name:
Invoke-DbaDbccCleanTable
Invoke-DbaCleanTable
Remove-DbaDbUnusedPages

Suggested Parameters:
SqlInstance
Database
Table or View (different parametersets? Object?)
Batch Size

A few new commands could be added to support this - Get-DbaDbUnusedPages (get # of unused pages by object) and Test-DbaDbUnusedPages (show objects with a large percentage of unused pages).

### Problem to solve
Reclaim unused pages after removing variable-length column(s).

**Comment by potatoqualitee** [comment]
Love the suggestion! I like `Remove-DbUnUsedPage` - it's clearest on what it does IMO. (Gotta stay singular, mostly)

Also add `InputObject` which is a `[Microsoft.SqlServer.Management.Smo.Table[]]`

**Comment by potatoqualitee** [comment]
alternatively, if the Table or View objects support a clean method, you could make the InputObject a generic `[object[]]` and then execute their methods.

**Comment by potatoqualitee** [comment]
looping in @sqllensman for feedback

**Comment by potatoqualitee** [comment]
patrick, i also created a dbcc label for you to make it easy to track

**Comment by sqllensman** [comment]
Thanks. I have a first set of commands almost ready. Need to create the Pester tests and will then create Pull request.

**Comment by sqllensman** [comment]
Implementing DBCC Cleantable is on the list of Database level commands to create.

**Comment by potatoqualitee** [comment]
looking super forward to it @sqllensman !

**Comment by andreasjordan** [comment]
Looks interesting...

**Comment by wsmelton** [comment]
If anyone is interested in picking this up after 2.0 please create a new feature issue.
