### ISSUE TITLE
Set-DbaInstance, Clear-DbaInstance

### ISSUE THREAD

**Issue by niphlod** [dataplat/dbatools#3637]
---
name: Feature request/idea 💣 
about: having a set of functions that permit the human interactive user to not repeat parameters if the target doesn't change. Think `Connect-ViServer` of PowerCLI

---

### Summary of new feature

do not type `-sqlinstance 'foo'` for each function if an instance is set. Fortunately, PS has intrinsec support for it, but probably is not well known.
with those function, you could

```
Set-DbaInstance -SqlInstance 'foo'
Get-DbaDatabase .....
Backup-DbaDatabase .....
....
```
instead of what usually happens now
```
Get-DbaDatabase -SqlInstance 'foo'
Backup-DbaDatabase -SqlInstance 'foo'
....
```

### Proposed technical details (if applicable)

Thanks @SQLDBAWithABeard , 
`$PSDefaultParameterValues = @{"*-Dba*:SqlInstance" = 'foo'}`
suffice for the set. Clear will just remove the previously set value (if any)

Not sure if the same should support, e.g., `-Database`, '-ExcludeDatabase`, etc etc etc

### Latest version of dbatools as of writing

0.9.338

**Comment by SQLDBAWithABeard** [comment]
and also SQLCredential

**Comment by wsmelton** [comment]
Just curious but how is this different than doing:

```powershell
Set-DbaInstance -SqlInstance 'foo'
Get-DbaDatabase .....
Backup-DbaDatabase .....
....```

As

```powershell
$server = Connect-DbaInstance 'foo'
Get-DbaDatabase -SqlInstance $server...
Backup-DbaDatabase -SqlInstance $server.....
....

**Comment by SQLDBAWithABeard** [comment]
saves on the keystrokes no need to keep specifying SqlInstance and sqlcredential

````
Set-DbaInstance -SqlInstance 'foo'
Get-DbaDatabase 
Backup-DbaDatabase
`````
So if you are working on foo (or a group of foos you specify once at the beginning of session and then all future commands use it

**Comment by wsmelton** [comment]
That seems redundant the way it is being explained but I'll wait to see the commands. I see that as basically a CMS at the command line.

**Comment by potatoqualitee** [comment]
I love this and have wanted something similar. I'll work on it.

**Comment by potatoqualitee** [comment]
Right now, this is in my Core profile

```
$password = ConvertTo-SecureString "dbatools.IO" -AsPlainText -Force
$cred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList "sqladmin", $password
$PSDefaultParameterValues["*:SqlInstance"] = "localhost:14333"
$PSDefaultParameterValues["*:Source"] = "localhost:14333"
$PSDefaultParameterValues["*:Destination"] = "localhost:14334"
$PSDefaultParameterValues["*:Primary"] = "localhost:14333"
$PSDefaultParameterValues["*:Mirror"] = "localhost:14334"
$PSDefaultParameterValues["*:SqlCredential"] = $cred
$PSDefaultParameterValues["*:SourceSqlCredential"] = $cred
$PSDefaultParameterValues["*:DestinationSqlCredential"] = $cred
$PSDefaultParameterValues["*:PrimarySqlCredential"] = $cred
$PSDefaultParameterValues["*:MirrorSqlCredential"] = $cred
$PSDefaultParameterValues["*:WitnessSqlCredential"] = $cred
$PSDefaultParameterValues["*:Confirm"] = $false
$PSDefaultParameterValues["*:SharedPath"] = "/shared"
```

Perhaps I can mix and match that with our config tool.

**Comment by niphlod** [comment]
yup, found out about psdefaultparameters on 2019.

**Comment by potatoqualitee** [comment]
lol, wait we can create two commands to hand hold

**Comment by wsmelton** [comment]
If anyone is interested in picking this up after 2.0 release please create a new feature issue.

I would say at this point it benefits users more to be made aware of how to set param values for any command in a given module.
