### ISSUE TITLE
New function: Set-DbaIdentity

### ISSUE THREAD

**Issue by michalporeba** [dataplat/dbatools#3647]
---
name: Feature idea - Set-DbaIdentity 
about: Suggest a new feature or enhancement

---

### Summary of new feature

Today I was asked to reseed all identity columns in tens of databases. I found the Test-DbaIdentityUsage function was very useful to collect the necessary data and I was quickly able to complete the change using Invoke-DbaSqlQuery -Query "dbcc checkident ..." but...

perhaps it would be useful to have a function which would allow making it even easier? Or perhaps a pair of functions? 

`Get-DbaIdentity | % { $_.LastValue = [int]($_.LastValue * 1.2) } | Set-DbaIdentity`

### Latest version of dbatools as of writing

* 0.9.338

**Comment by wsmelton** [comment]
How would `Get-DbaDbIdentity` differ from the output of `Test-DbaIdentityUsage`?

**Comment by wsmelton** [comment]
If anyone is interested in picking this up after 2.0 release please create a new feature issue.
