### ISSUE TITLE
Add ability to set the Dump Directory using Set-DbaStartupParameter

### ISSUE THREAD

**Issue by gbargsley** [dataplat/dbatools#3770]
---
name: Feature request/idea :bomb:
about: Suggest a new feature or enhancement

---

### Summary of new feature

* Clear/concise description of what the problem is that the new feature can solve.

### Proposed technical details (if applicable)

* e.g. Blog post reference that shows example code or functionality

### Latest version of dbatools as of writing

* Please provide the latest released version of dbatools module.

**Comment by tboggiano** [comment]
Mike Fal has a function for this could be utilized http://www.mikefal.net/2015/12/15/set-sqlstartupparameters-powershell-module/.

**Comment by mikepetrak** [comment]
Here is another write-up and PowerShell script that can help with this one: https://maq.guru/sqlserverdumpdirectory/

**Comment by wsmelton** [comment]
If anyone is interested in picking this up after 2.0 release please create a new feature issue.
