### ISSUE TITLE
Invoke-DbaDbShrink - speed changes

### ISSUE THREAD

**Issue by olegstrutinskii** [dataplat/dbatools#3895]
### Summary of new feature

1. Make things faster, change default function behaviour to do not gather index statistics and don't update usage statistics.

* ExcludeIndexStat > AnalyzeIndexStat
* ExcludeUpdateUsage > UpdateUsage

2. Shrink files in one FG to the same size

**Comment by potatoqualitee** [comment]
i like #2 but would like input from the team on #1

**Comment by Zhunya** [comment]
Add:
3. Shrink only `-LogicalFileName`
4. Shrink only `-FileGroup`

**Comment by niphlod** [comment]
ExcludeIndexStats, ExcludeUpdateUsage in, 3 and 4 still to go.

**Comment by Zhunya** [comment]
Is it possible to create tabcompletion for second object in hierarchy, in this situation filegroupname or logical filename?

**Comment by niphlod** [comment]
not with the usual magic (that I'm aware of)

**Comment by wsmelton** [comment]
If anyone is interested in picking this up after 2.0 release please create a new feature issue.
