### ISSUE TITLE
File groups, files and data manipulation commands 

### ISSUE THREAD

**Issue by olegstrutinskii** [dataplat/dbatools#3938]
### Summary of new feature
Manage `FILEGROUP`s, data/log files, move data between data files and `FILEGROUP`

#### FILEGROUP
Get Info, create new, change parameters, delete 

Suggested name - `New`|`Delete`|`Get`|`Set`/`-DbaDbFilegroup`

#### FILES
`Get-DbaDatabaseFile` - we already have this one
- Create one file, create files in batch with the same size, growth size and maxsize 
- Delete, delete with moving data to another file/filegroup
- Set parameters on file, on all files in a file group

Suggested name - `New`|`Delete`|`Get`|`Set`/`-DbaDbFile`

#### Move DATA
Can be achieved with `Invoke-DbaDbShrink` with changes 

### Latest version of dbatools as of writing
* 0.9.394

Please add your suggestion, ideas, opinions, pros and cons! 

All this is an idea by @marcingminski, he shared in Slack

**Comment by VolkerBachmann** [comment]
Filegroup and Files looks good for me, move Data with Invoke-DbaDbShrink? is this not confusing with the shrink?
Thanks, Volker

**Comment by Zhunya** [comment]
You have two options to move data - partitions/indexes and DBCC SHRINK EMPTYFILE

**Comment by wsmelton** [comment]
Please check other issues before creating new ones. There are multiple issues around filegroup commands and balancing data between files.

**Comment by wsmelton** [comment]
Moving data between files already exist. #2357

**Comment by niphlod** [comment]
@Zhunya : is this still valid ? If so, what's missing ?

**Comment by Zhunya** [comment]
Missing all, except, balancing data which is in place.

**Comment by wsmelton** [comment]
If anyone is interested in picking this up after 2.0 release please create a new feature issue.
