### ISSUE TITLE
Install-DbaMaintenanceSolution: Add support for separate locations for Full, Diff, Log, and System Database Backups

### ISSUE THREAD

**Issue by nanoDBA** [dataplat/dbatools#4050]
### Summary of new feature

* Add support for utilizing separate locations for Full, Diff, Log, and System Database backups when creating jobs for Ola Hallengren's maintenance solution when the **-InstallJobs** switch parameter is called.  This functionality is not currently provided in Ola's MaintenanceSolution.sql script.  A single variable, @BackupDirectory , is used.

### Proposed technical details (if applicable)
Hypothetical Example:
```
$splat_OlaMaintSolution = @{
SqlInstance = 'SQL16'
Database = 'DBA_Stuffs'
FullBackupPath = '\\S01\share01, \\S02\share02, \\S03\share03'
DiffBackupPath = '\\S01\share01, \\S02\share02, \\S03\share03'
LogBackupPath = '\\S12\tlog'
SysDbBackupPath = '\\S14\sysdb'
FullCleanupTime = 792
DiffCleanupTime = 216
LogCleanupTime = 168
SysDbCleanupTime = 1080
LogToTable = $true
OutputFileDirectory = 'NULL'
InstallJobs = $true
}

Install-DbaMaintenanceSolution @splat_OlaMaintSolution
```

The following SQL Agent jobs that are created would be potentially affected:
```
'DatabaseBackup - SYSTEM_DATABASES - FULL',
'DatabaseBackup - USER_DATABASES - DIFF',
'DatabaseBackup - USER_DATABASES - FULL',
'DatabaseBackup - USER_DATABASES - LOG'
```

### Latest version of dbatools as of writing

0.9.431

**Comment by wsmelton** [comment]
If anyone is interested in picking this up after 2.0 release please create a new feature issue.
