### ISSUE TITLE
Get-DbaAgAgentJob

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dbatools#4652]
get jobs associated with dbs (get-dbaagdatabase) in an ag?

![image](https://user-images.githubusercontent.com/8278033/48959167-fd94fa80-ef63-11e8-80d2-6f7f1a4f25c6.png)

**Comment by potatoqualitee** [comment]
Here are some potential approaches that I'd like to document

* By Name: https://twitter.com/AMtwo/status/1066309407150100480
* Categories and primary detection: https://twitter.com/HiramFleitas/status/1066393647833382912
* List stored in db: https://twitter.com/PeterVandivier/status/1066298086945894400 along with table size tracking and then whoisactive at instance level
* Depends on app "for our env it depends heavily on the app.  We have some that are  database specific, those have the DB listed.  Others (much fewer) that function across multiple databases and are written expecting them all to be on the same server so they have master listed and use database.owner.table in the steps definitions as some steps operate on Database A and other steps on Database B and other steps joining data between mulitple databases in the AG.  Cant get the vendor to use linked servers  been trying to break up the AG and previously a cluster for years. "
* Another categories "I have three categories for job. And also one job manages jobs. if server primary and selected primary category then job enabled. if server primary and selected secondary then job disabled. etc.. Also another job copy all jobs to secondary server every one hour." 

![image](https://user-images.githubusercontent.com/8278033/48972441-b9b8f880-f02a-11e8-9bd6-16a6294ca5c9.png)

**Comment by potatoqualitee** [comment]
trying to figure out how to best handle related agent jobs, not sure there is a univeral approach so may prescribe one

**Comment by potatoqualitee** [comment]
unsure, still thinking things through

**Comment by wsmelton** [comment]
I mean from an AG perspective I see no reason for a special command with jobs. You can't guarantee any job is associated directly to it short of those that go to the level of detail to actually set that database drop down (note that tsql step supports the '"use" statement).

Is there something driving the need for another process with this command?

**Comment by wsmelton** [comment]
Ah. I would only improve how they can pass jobs in. When I've done this for clients they have it documented what jobs where required for the AG and needed to be in all replicas.

I have not hit an environment yet that had any standard to job names or anything that would let you filter on.

I would say allow a config item to be used that lets you store a hash table or json file path that let you update that list separate from having to change code.... Just imo

**Comment by potatoqualitee** [comment]
i'm thinking pipable job input.. yah?

**Comment by wsmelton** [comment]
If anyone is interested in picking this up after 2.0 release please create a new feature issue.
