### ISSUE TITLE
Invoke-DbaDumpArchive - New Command

### ISSUE THREAD

**Issue by ClaudioESSilva** [dataplat/dbatools#4712]
Suggested name: **`Invoke-DbaDumpArchive`**

### Summary of new feature

Command that backups (generate a zip?) all dump files generated before certain datetime and then delete the files.

### Proposed technical details (if applicable)

If we don't get the dumps on the time they were generated, they can sit there forever.
With dbachecks we already have a checks for MemoryDumps using the `Get-DbaDump`. 

If we found a dump during an initial checks, after checking the patch level we can decide to remove some dumps (probably the problem is arelady solved on recent version).

### Latest version of dbatools as of writing
0.9.534

**Comment by wsmelton** [comment]
If anyone is interested in picking this up after 2.0 release please create a new feature issue.
