### ISSUE TITLE
Sync-DbaAvailabilityGroup report objects to be synced when using -WhatIf

### ISSUE THREAD

**Issue by nocentino** [dataplat/dbatools#4748]
---
name: Feature request/idea Sync-DbaAvailabilityGroup
about: Sync-DbaAvailabilityGroup report objects to be sync when using -WhatIf

---

### Summary of new feature
Hi team, totally dig the Sync-DbaAvailabilityGroup cmdlet...thanks so much! When using -WhatIf (or possibly -Verbose) can you have the cmdlet report the changes it will make? Some shops might not want to have this automagically syncing objects and would prefer to see what's going to be changed before taking corrective measures. Stay fab y'all and thanks again :)

### Latest version of dbatools as of writing

0.9.704

**Comment by potatoqualitee** [comment]
😅 hooh happy there was not an uncaught whatif. i can explore this, whatif is not a huge fan when you embed commands, lemme see what i can do.

**Comment by wsmelton** [comment]
We might be able to address this in 2.0 release.

**Comment by ClaudioESSilva** [comment]
What would be the best way to achieve this? 🤔 
Would you remove the `$PSCmdlet.ShouldProcess` from L244, L251, and rely on the `-WhatIf` within each of the commands being called?
Or move the `Copy-*` command to the outside of the `$PSCmdlet.ShouldProcess` so we can have both WhatIf messages (from Sync and from Copy commands)?

I'm leaning towards the second option but want to get some feedback 😄
