### ISSUE TITLE
[Sync-DbaAvailabilityGroup] Real SYNC operation

### ISSUE THREAD

**Issue by lacarvalhoBR** [dataplat/dbatools#5555]
Hi developers.
I would like to know if it´s possible to consider a future new version of command Sync-DbaAvailabilityGroup, considering the **REAL** sync functionally.
Explaning....
Today, it works perfectly, but it´s a one-way direction. The objects are copied (not synced) between primary and the secondary replicas. But if you drop any objects at the primary replica, they´re not dropped at the secondary server.
Find it useful especially for agent jobs that one can can be deleted at the primary replica but, in the case of a failover, it still remais at the failover replica and it´s going to run improperly.

released version of dbatools module: Latest, installed natively available available in Windows Server 2016

**Comment by potatoqualitee** [comment]
eek, this is scary. unsure if ill tackle this one but will keep it in mind.

**Comment by BitDesert** [comment]
I have the same problem.
Currently the command is not really a sync but rather just a copy. If you drop any logins or jobs on the primary server I would assume that they are dropped on the secondary too.

**Comment by wsmelton** [comment]
If anyone is interested in picking this up after 2.0 release please create a new feature issue.
