### ISSUE TITLE
Mark as supported by Azure

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dbatools#5636]
Kinda like how we show if it's supported on Linux, let's explore showing which commands work on Azure.

**Comment by ThatShadowyPlace** [comment]
Is the current Linux indicator tied to the AppVeyor testing process at all, or is it purely manually maintained?

**Comment by potatoqualitee** [comment]
manually maintained. When i add a new command to the index, i test to see if it works then add it to a specific export collection. so if its xplat, then it works on linux, if it's just in the windows collection, then it's windows only.

**Comment by wsmelton** [comment]
Do you want to use the tags to accomplish this?

**Comment by potatoqualitee** [comment]
Yeah i think we have to

**Comment by potatoqualitee** [comment]
you fixing this @wsmelton ? it is not on my radar and seems like at least a month of work

**Comment by wsmelton** [comment]
No afraid not anymore 🫤

**Comment by potatoqualitee** [comment]
one more down! 😆

**Comment by potatoqualitee** [comment]
this'll never happen 😅
