### ISSUE TITLE
Export Xel to JSON for the purpose of ingesting to Elasticsearch easily

### ISSUE THREAD

**Issue by Angrboda2** [dataplat/dbatools#5678]
### Summary of new feature

There is an existing function to export XelToCsv. I would like to ingest XE data into an ElasticSearch index, which is very simply to do from a JSON format. If dbatools could export from a .Xel to a .JSON that would be awesome. (Maybe there is an even better approach of directly sending from a .XEL into logstash or ElasticSearch directly)

### Latest version of dbatools as of writing

1.0

**Comment by andreasjordan** [comment]
@Angrboda2 Can you provide a litte more technical detail? Maybe some code that shows the needed transformation? Then we can try to build a command around it.

**Comment by potatoqualitee** [comment]
This is a fun idea! We wrap our commands our @spaghettidba's XESmartTarget, so this would first have to be a request on his repo at https://github.com/spaghettidba/XESmartTarget, then we could add support once he adds support

**Comment by spaghettidba** [comment]
Hi! XESmartTarget can write to Graylog using a response type like GelfTcpResponse, which writes directly to the graylog server. We also have a [TelegrafAppenderResponse](https://github.com/spaghettidba/XESmartTarget/wiki/TelegrafAppenderResponse) to write to InfluxDb, which is very similar to ElasticSearch on that regard. If you describe the way you would like the data, I can implement it in XESmartTarget

**Comment by andreasjordan** [comment]
So this would be best solved with XESmartTarget and is not in scope for dbatools? Can we close this?

**Comment by wsmelton** [comment]
Yep, can't incorporate anything until upstream has support.
