### ISSUE TITLE
last good check db for azure

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dbatools#5739]
detect if azure or sql server 2017 and above and run this

` SELECT DATABASEPROPERTYEX('abc', 'LastGoodCheckDbTime')`

**Comment by andreasjordan** [comment]
It's already part of the Database SMO:
https://docs.microsoft.com/de-de/dotnet/api/microsoft.sqlserver.management.smo.database.lastgoodcheckdbtime?view=sql-smo-160
@potatoqualitee : What do you want to do with it?

**Comment by potatoqualitee** [comment]
oh la la! gotta make sure our SMO version is high enough. But either approach works.

**Comment by jpomfret** [comment]
Hey @potatoqualitee\ @wsmelton - what are we looking for on this issue? 🤔
Is it a new command or adding to one?

**Comment by wsmelton** [comment]
Support for it in current command should be fine.

**Comment by jpomfret** [comment]
Yeah, new command isn't a bad idea - definitely important.

Is this something that needs to happen before dbatools 2.0? (going by the label)

**Comment by ClaudioESSilva** [comment]
As a bit of learning:

With this new way to get this info, we don't need `sysadmin` (required by `DBCC DBINFO()` ) anymore.

I did a quick test and even just connected to `master` and without any other permissions, I was able to read the info from other databases.

On the other hand, if the database name doesn't exist it will return `NULL`. With `DBCC INFO()` it returns an error.

**Comment by wsmelton** [comment]
You tested the SMO route or the database property T-SQL?

**Comment by ClaudioESSilva** [comment]
Both

**Comment by wsmelton** [comment]
In SMO I wouldn't expect it to error if something doesn't exist.

**Comment by ClaudioESSilva** [comment]
I will double-check that part. I was thinking you were asking about the permission path.

**Comment by ClaudioESSilva** [comment]
Normally it outputs "nothing".
Here is an example of selecting:
1 - Property that doesn't exist
2 - Existing property but on a database that doesn't exists
![image](https://user-images.githubusercontent.com/19521315/218721141-62966f37-55c9-486b-ae5b-c7a097d01c63.png)

**Comment by wsmelton** [comment]
So using SMO will be more friendly and limits the need for error handling.

**Comment by potatoqualitee** [comment]
preclosing per approval and merging of open pr
