### ISSUE TITLE
Grant permissions on a database Application Role to an existing Db User

### ISSUE THREAD

**Issue by ddraillantclark** [dataplat/dbatools#5781]
### Summary of new feature

New/updated command to grant permissions to an existing Db User on an Application Role of a Database.

### Proposed technical details (if applicable)

`Add-DbaDbRoleMember -SqlInstance sqlserver2017 -Database DB1 -Username JohnSmith -Role my_app_role -Permission Control`

Current workaround using Invoke-DbaQuery
```
function Add-DbaDbRoleMember {
    param(
        [String]$SqlInstance,
        [String]$Database,
        [String]$Username,
	[String]$Role,
	[String]$Permission
    )
    Invoke-DbaQuery -SqlInstance $SqlInstance -Database $Database "GRANT $($Permission) ON APPLICATION ROLE::[$($Role)] TO [$($Username)]"
}
```

### Latest version of dbatools as of writing

0.9.701

**Comment by pollusb** [comment]
This function was added. So I guess we can close this feature request.

**Comment by pollusb** [comment]
But I am wondering why this function ask for confirmation when Restart-DbaInstance does not? Should we open a Issue for that?

**Comment by ClaudioESSilva** [comment]
Hi @pollusb, the specific feature request is not implemented.

Currently dbatools `Add-DbaDbRoleMember` only works with Database Roles. Application roles as requested per @ddraillantclark are not yet in place.

Regarding your second observation, this command ( `Add-DbaDbRoleMember`) has `ConfirmImpact = 'High'` and Restart-DbaService (I think that is the one you mention) don't have it set, iirc, will be medium. You can open an issue to improve that.
Thanks

**Comment by andreasjordan** [comment]
As [application roles](https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/application-roles) don't have members, `Add-DbaDbRoleMember` is the wrong command for that.
You just want to grant permissions - and we don't have a command for that at the moment.

**Comment by andreasjordan** [comment]
Will close this now, but can reopen if needed.
