### ISSUE TITLE
Sync Logins between servers with drop operations

### ISSUE THREAD

**Issue by triglavan** [dataplat/dbatools#5862]
### Summary of new feature

Creating script for removing logins from secondary MS AOHAG servers, which are not present on the primary MS AOHAG (AlwaysOn High Availability Group)

### Proposed technical details (if applicable)

We have 3 MS SQL servers that are connected over AOHAG. On first we have one primary AG and on second we also have one primary AG. In this AG groups are different databases that need different logins. But from time to time we remove some obsolete logins from first or second server (we also have third server, which is passive standby). We must done this on all three servers separately. It would be very useful, if there would be a script - for example Remove-DbaLogin - if run from first or second server, that would removed all logins from other two server, that are not also present on the first server - that would automatically put logins on all three servers in some consisted state. Script Copy-DbaLogin only add logins from one server to other, but there is also need to delete logins from other servers, if logins are not present on source/primary server where script would be run.

### Latest version of dbatools as of writing

[1.0.0] - 2019-06-20

**Comment by BitDesert** [comment]
That's basically the same problem as https://github.com/sqlcollaborative/dbatools/issues/5555

The copy/sync function does not have a an option to drop the obsolete logins fron the destination servers.

**Comment by andreasjordan** [comment]
As referenced #5555 is closed, I will close this as well.
