### ISSUE TITLE
Copy-DbaDatabase to Managed Instance WARNING

### ISSUE THREAD

**Issue by rnikolov** [dataplat/dbatools#6119]
Hi all,

When using `Copy-DbaDatabase` to clone a database from Azure VM to Azure Managed Instance, I get the following warning:

```
WARNING: [04:14:17][Copy-DbaDatabase] Failure setting DBAdmin to read-write on destination server | This ALTER DATABASE statement is not suppo
rted. Correct the syntax and execute the statement again.
ALTER DATABASE statement failed.
```

Many Thanks,

Richard
![DBClone_Warning](https://user-images.githubusercontent.com/11937225/66372867-b8da4c80-e9d9-11e9-8219-575e18a69d1e.JPG)

**Comment by wsmelton** [comment]
Please provide warning text in the issue so it allows others to search.

**Comment by rnikolov** [comment]
No problems, the warning text is:

WARNING: [04:14:17][Copy-DbaDatabase] Failure setting DBAdmin to read-write on destination server | This ALTER DATABASE statement is not suppo
rted. Correct the syntax and execute the statement again.
ALTER DATABASE statement failed.

Kind Regards,

Richard

**Comment by andreasjordan** [comment]
@rnikolov - This issue is very old. Do you still have the issue with the current version of dbatools? As I don't have a MI at hand I can not test this myself.

**Comment by rnikolov** [comment]
Hi Andreas,

 

Indeed it is very old and it can be closed.

 

Many Thanks,

 

____________________________________________________________________________

 

Richard Nikolov

Brolly Enterprises Pty Ltd

CRN: 153 411 815

ABN: 25 153 411 815

 

Mobile: (+61) 0418 932 458

Email: ***@***.***
