### ISSUE TITLE
Set-DbaPrivilege - Add support for "Log on as a service" (SeServiceLogonRight)

### ISSUE THREAD

**Issue by danpousson** [dataplat/dbatools#6191]
### Summary of new feature

* Can you please add the SQL Service Account to Local Security Policy "**Log on as a service**" when using ~Update-DbaServiceAccount~ Set-DbaPrivilege?

This is added to "Log on as a Service" sec pol when using Install-DBAInstance. The same behavior would be great.

### Proposed technical details (if applicable)
My current work around it to use this module: https://gallery.technet.microsoft.com/scriptcenter/Grant-Revoke-Query-user-26e259b0

**Comment by wsmelton** [comment]
This would not go under Update-DbaServiceAccount. You would use `Set-DbaPrivilege` for this functionality.

**Comment by niphlod** [comment]
TBF I seem to recall that changing via WMI took care of rights automatically....

**Comment by wsmelton** [comment]
Changing the service account does this yes. You can't update the permissions using WMI though.

**Comment by danpousson** [comment]
Thank you for the updates/comments. @wsmelton Shawn via which method does changing the service account accomplish this? 

when using DBATools to set the service account (Update-DbaServiceAccount) it does not set the SeServiceLogonRight privilege, however it sounds like it is not intended to.

**Comment by wsmelton** [comment]
We do not have a command that does it directly, but using SQLWMI you can set a service account for the SQL Server database engine. (Basically coded version of changing the service account in SSCM). This operation will set the permissions for the service account.

Having a command that does this would be something like `Set-DbaService`, which I do not believe has ever been requested. We do have a Get-DbaService.

**Comment by andreasjordan** [comment]
As Set-DbaPrivilege can now set SeServiceLogonRight I will close this.
