### ISSUE TITLE
Test-DbaLastBackup -VerifyOnly report Success even if backup file is corrupted

### ISSUE THREAD

**Issue by vesalo** [dataplat/dbatools#6414]
### Environmental information

```
#### PowerShell version:

Name                           Value                                                                                                                                                    
----                           -----                                                                                                                                                    
PSVersion                      5.1.14393.0                                                                                                                                              
PSEdition                      Desktop                                                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                  
BuildVersion                   10.0.14393.0                                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                                          
WSManStackVersion              3.0                                                                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                                                                      
SerializationVersion           1.1.0.1                                                                                                                                                  




#### dbatools Module version:


Name    : dbatools
Path    : C:\Program Files\WindowsPowerShell\Modules\dbatools\dbatools.psd1
Version : 1.0.75

Name    : dbatools
Path    : C:\Windows\system32\WindowsPowerShell\v1.0\Modules\dbatools\dbatools.psd1
Version : 1.0.101


#### SQL Server:
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) 
```

### Report

When running this code below it will result it Success, even if database file is corrupted. It doesn´t matter if you use FULL or DIFF backups. Tried to run this from ISE, powershell.exe and SQL Agent job.

Test-DbaLastBackup -SqlInstance "SQLFCI" -Database "AdventureWorksDW2017" -VerifyOnly -EnableException -Verbose

PS C:\Users\sqladmin> Test-DbaLastBackup -SqlInstance "SQLFCI" -Database "AdventureWorksDW2017" -VerifyOnly -EnableException -Verbose
VERBOSE: [01:01:24][Test-DbaLastBackup] Getting recent backup history for AdventureWorksDW2017 on SQLFCI.
VERBOSE: [01:01:24][Get-DbaDbBackupHistory] Processing AdventureWorksDW2017
VERBOSE: [01:01:24][Get-DbaDbBackupHistory] Executing sql query.
VERBOSE: [01:01:24][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [01:01:24][Get-DbaDbBackupHistory] 1 result-groups found.
VERBOSE: [01:01:24][Get-DbaDbBackupHistory] Processing AdventureWorksDW2017
VERBOSE: [01:01:24][Get-DbaDbBackupHistory] Executing sql query.
VERBOSE: [01:01:25][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [01:01:25][Get-DbaDbBackupHistory] 1 result-groups found.
VERBOSE: [01:01:25][Get-DbaDbBackupHistory] No Diff found
VERBOSE: [01:01:25][Get-DbaDbBackupHistory] Executing sql query.
VERBOSE: [01:01:25][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [01:01:25][Get-DbaDbBackupHistory] 1 result-groups found.
VERBOSE: [01:01:25][Test-DbaLastBackup] Looking good.
VERBOSE: [01:01:25][Read-DbaBackupHeader] Checking: C:\ClusterStorage\Volume4\SQLBackup\SQLFCI\AdventureWorksDW2017\FULL\SQLFCI_AdventureWorksDW2017_FULL_20200312_055157.bak
VERBOSE: [01:01:25][Read-DbaBackupHeader] 1 unique files to scan.
VERBOSE: [01:01:25][Read-DbaBackupHeader] Checking accessibility for all the files.
VERBOSE: [01:01:25][Read-DbaBackupHeader] Scanning file C:\ClusterStorage\Volume4\SQLBackup\SQLFCI\AdventureWorksDW2017\FULL\SQLFCI_AdventureWorksDW2017_FULL_20200312_055157.bak.
**WARNING: [01:01:26][Read-DbaBackupHeader] Problem found with C:\ClusterStorage\Volume4\SQLBackup\SQLFCI\AdventureWorksDW2017\FULL\SQLFCI_AdventureWorksDW2017_FULL_20200312_055157.bak. |
 The media family on device 'C:\ClusterStorage\Volume4\SQLBackup\SQLFCI\AdventureWorksDW2017\FULL\SQLFCI_AdventureWorksDW2017_FULL_20200312_055157.bak' is incorrectly formed. SQL Server
 cannot process this media family.
RESTORE HEADERONLY is terminating abnormally.**
VERBOSE: Performing the operation "Restoring AdventureWorksDW2017 as dbatools-testrestore-AdventureWorksDW2017." on target "SQLFCI".
VERBOSE: [01:01:26][Test-DbaLastBackup] Performing restore.
VERBOSE: [01:01:26][Restore-DbaDatabase] Changing statement timeout to infinity
VERBOSE: [01:01:26][Restore-DbaDatabase] ParameterSet  = Restore
VERBOSE: [01:01:26][Restore-DbaDatabase] Trust Database Backup History Set
VERBOSE: [01:01:26][Restore-DbaDatabase] adding BackupPath - C:\ClusterStorage\Volume4\SQLBackup\SQLFCI\AdventureWorksDW2017\FULL\SQLFCI_AdventureWorksDW2017_FULL_20200312_055157.bak
VERBOSE: [01:01:26][Restore-DbaDatabase] Processing DatabaseName - 
VERBOSE: [01:01:26][Format-DbaBackupInformation] Starting
VERBOSE: [01:01:26][Format-DbaBackupInformation] String passed in for DB rename
VERBOSE: [01:01:26][Format-DbaBackupInformation]  1 PhysicalName = C:\ClusterStorage\Volume2\MSSQL14.MSSQLSERVER\MSSQL\DATA\AdventureWorksDW2017.mdf 
VERBOSE: [01:01:26][Format-DbaBackupInformation] PhysicalName = C:\ClusterStorage\Volume2\MSSQL14.MSSQLSERVER\MSSQL\DATA\dbatools-testrestore-AdventureWorksDW2017.mdf 
VERBOSE: [01:01:26][Format-DbaBackupInformation]  1 PhysicalName = C:\ClusterStorage\Volume1\MSSQL14.MSSQLSERVER\MSSQL\Data\AdventureWorksDW2017_log.ldf 
VERBOSE: [01:01:26][Format-DbaBackupInformation] PhysicalName = C:\ClusterStorage\Volume1\MSSQL14.MSSQLSERVER\MSSQL\Data\dbatools-testrestore-AdventureWorksDW2017_log.ldf 
VERBOSE: [01:01:26][Restore-DbaDatabase] VerifyOnly = True
VERBOSE: [01:01:27][Test-DbaBackupInformation] Testing restore for dbatools-testrestore-AdventureWorksDW2017
**VERBOSE: [01:01:27][Test-DbaBackupInformation] VerifyOnly = True
VERBOSE: [01:01:27][Test-DbaBackupInformation] Marking dbatools-testrestore-AdventureWorksDW2017 as verified**
VERBOSE: [01:01:27][Restore-DbaDatabase] dbatools-testrestore-AdventureWorksDW2017 passed testing
VERBOSE: [01:01:27][Restore-DbaDatabase] Passing in to restore
VERBOSE: [01:01:27][Invoke-DbaAdvancedRestore] Performing restore action
VERBOSE: [01:01:27][Invoke-DbaAdvancedRestore] VerifyOnly restore
VERBOSE: [01:01:27][Invoke-DbaAdvancedRestore] VerifyOnly restore Failed
VERBOSE: [01:01:27][Invoke-DbaAdvancedRestore] Succeeded, Closing Server connection
VERBOSE: Performing the operation "Showing results" on target "console".

SourceServer   : SQLFCI
TestServer     : SQLFCI
Database       : AdventureWorksDW2017
FileExists     : True
Size           : 96.09 MB
**RestoreResult  : Success**
DbccResult     : Skipped
RestoreStart   : 2020-03-13 01:01:26.687
RestoreEnd     : 2020-03-13 01:01:27.434
RestoreElapsed : 00:00:00
DbccStart      : 
DbccEnd        : 
DbccElapsed    : 
BackupDates    : {03/12/2020 05:51:57}
BackupFiles    : {C:\ClusterStorage\Volume4\SQLBackup\SQLFCI\AdventureWorksDW2017\FULL\SQLFCI_AdventureWorksDW2017_FULL_20200312_055157.bak}

#### Host used

- [x] powershell.exe
- [x] ISE
- [ ] VS Code
- [ ] Other (please specify)

If anything other than powershell.exe was used, please confirm that you can duplicate the issue with powershell.exe

- [x] Still buggy in powershell.exe

#### Errors Received

```
writeErrorStream      : True
PSMessageDetails      : 
Exception             : System.Exception: You cannot call a method on a null-valued expression. ---> System.Management.Automation.RuntimeException: You cannot call a method on a 
                        null-valued expression.
                           at CallSite.Target(Closure , CallSite , Object , String )
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           --- End of inner exception stack trace ---
TargetObject          : C:\ClusterStorage\Volume4\SQLBackup\SQLFCI\AdventureWorksDW2017\FULL\SQLFCI_AdventureWorksDW2017_FULL_20200312_055157.bak
CategoryInfo          : InvalidOperation: (C:\ClusterStora...0312_055157.bak:PSObject) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Read-DbaBackupHeader,Stop-Function
ErrorDetails          : You cannot call a method on a null-valued expression.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1: line 81886
                        at Read-DbaBackupHeader<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1: line 54657
                        at Test-DbaLastBackup<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\allcommands.ps1: line 70848
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

```

#### Expected Behavior

RestoreResult should be Failed, when running VerifyOnly to corrupted file. And it should also fail the SQL Agent job as a result.

#### Actual Behavior

Script and SQL Agent job ended as a Success.

**Comment by HansLindgren** [comment]
Is this still an open issue? I.e. can I expect my SQL Agent jobs not to fail if the process encounters corrupt backup files?

**Comment by potatoqualitee** [comment]
this is important and must be tested

**Comment by potatoqualitee** [comment]
agreed, but that is the second part (perhaps anotehr good  blog post) but it seems we are faulty on the first part.

**Comment by potatoqualitee** [comment]
any idea how i can corrupt a backup, @vesalo ?

**Comment by potatoqualitee** [comment]
sweet got it -- used a hex editor in vs code
