### ISSUE TITLE
docs.dbatools.io/bogus is out of date

### ISSUE THREAD

**Issue by headspeak** [dataplat/dbatools#6663]
The https://docs.dbatools.io/bogus/ web page is not up to date because for example Context is not supported. (I found this page by Google.) Maybe it is no longer required.

**Comment by andreasjordan** [comment]
@sanderstad Do you know something about this website?

**Comment by andreasjordan** [comment]
@niphlod Because it is in the docs-domain: Do you know something about this website?

**Comment by niphlod** [comment]
need to ping @potatoqualitee , was a onetime generation done 2 years ago. https://github.com/sqlcollaborative/docs/blob/master/bogus/index.md

**Comment by potatoqualitee** [comment]
thanks for the report, @headspeak. i barely remember this one. @sanderstad is it still useful for your commands?

**Comment by andreasjordan** [comment]
Hi @sanderstad - can we remove the bogus folder?

**Comment by potatoqualitee** [comment]
I'm kind of leaning to at least it gives us something instead of nothing? Perhaps we can just add a note at the top that it's a reference that is known to be out of date.

**Comment by andreasjordan** [comment]
Good idea, then we can close this issue.

**Comment by sanderstad** [comment]
We could do that. At the moment I'm totally swamped. When I get the time I will look into improving the documentation

**Comment by potatoqualitee** [comment]
added a note 📓
