### ISSUE TITLE
Connect-DbaInstance - Property NonPooledConnection cannot be changed or read after a connection string has been set.

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dbatools#7546]
### Verified issue does not already exist?

Yes

### What error did you receive?

```
WARNING: [22:52:39][Write-DbaDbTableData] Error occurred while establishing connection to localhost | Property NonPooledConnection cannot be changed or read after a connection string has been set.
```

### Steps to Reproduce

```
$server = Connect-DbaInstance -SqlInstance "localhost,14333"
$server | Watch-DbaDbLogin -SqlInstance localhost -Database tempdb
WARNING: [22:52:39][Write-DbaDbTableData] Error occurred while establishing connection to localhost | Property NonPooledConnection cannot be changed or read after a connection string has been set.
```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

PS 7 on Windows

### SQL Server Edition and Build number

docker

**Comment by andreasjordan** [comment]
```
$connContext = $connContext.GetDatabaseConnection($Database)
```
opens the new connection and thus has to be the last change and not the first made in the copied connection context.

**Comment by simonsabin** [comment]
Still getting this on 142, Looks like logic for setting NonPooledConnection needs more thought. 

https://github.com/dataplat/dbatools/blob/1f6498ddb71e4bfa6d8a4df3e19ec28625b2fddc/functions/Connect-DbaInstance.ps1#L603

**Comment by potatoqualitee** [comment]
check the dev branch, @andreasjordan -- i made some changes recently that may have changed your evaluation.

**Comment by simonsabin** [comment]
@andreasjordan see other comment, the setting of the value isn't the thing. Its the defaulting to $true is the problem.

**Comment by andreasjordan** [comment]
The default for a nonpooled connection is needed for some commands that issue more than one batch and using a temp table - so all batches have to be executed in the same session. And we have situations where the connection pooling routes different batches over different sessions - so some batches don't see the temp tables.

**Comment by simonsabin** [comment]
I get that but if the inbound connection is set, and not set to NonPooledConnections, then you can't change it.

**Comment by simonsabin** [comment]
Whats changed?

**Comment by potatoqualitee** [comment]
A lot

**Comment by simonsabin** [comment]
LOL

**Comment by simonsabin** [comment]
```
$DBAConnection = Connect-DbaInstance -ConnectionString $connection -Database "SSISDB"
Write-Host "connected"
$LastExecutionEzVetRestore = (Get-DbaSsisExecutionHistory -SqlInstance $DBAConnection -Project "<ssis project>"  -Folder "<folder>" -Environment '<environment>' -verbose -EnableException  
```
Try that. 
Seems to be something about Get-DbaSsisExecutionHistory that might also be causing it.

**Comment by potatoqualitee** [comment]
aw dang, i dont have ssis setup. let me see if other commands fit a similar pattern

**Comment by potatoqualitee** [comment]
ohh wait! now that i know how to do the dll version redirect, i can add back the other SSIS commands. I'll do all that and report back once I'm done.

**Comment by potatoqualitee** [comment]
added back in https://github.com/dataplat/dbatools/pull/8843 to be released in preview 3 🎉
