### ISSUE TITLE
Update-Dbatools - Cleanup Switch Current Version In Use 

### ISSUE THREAD

**Issue by mattcargile** [dataplat/dbatools#7707]
### Verified issue does not already exist?

Yes

### What error did you receive?

```powershell
PSMessageDetails      :
Exception             : System.Exception: Module 'dbatools' is in currently in use or you 
                        don't have the required
                        permissions.
TargetObject          : Microsoft.PowerShell.PackageManagement.Cmdlets.UninstallPackage
CategoryInfo          : InvalidOperation: (Microsoft.Power...ninstallPackage:
                        UninstallPackage) [Uninstall-Package],
                        Exception
FullyQualifiedErrorId : ModuleIsInUse,Uninstall-Package,Microsoft.PowerShell.PackageManagement.
                        Cmdlets.UninstallPackage
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Uninstall-Module<Process>, C:\Program
                        Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1: 
                        line 12733
                        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.10\
                        cleanup.ps1: line
                        61
                        at Update-Dbatools, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.9\
                        allcommands.ps1:
                        line 81633
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

### Steps to Reproduce

```powershell
Update-Dbatools -Cleanup
```

#### Direct Output from Powershell.exe

```powershell
PS C:\WINDOWS\system32> Update-Dbatools -Cleanup
Untrusted repository
You are installing the modules from an untrusted repository. If you trust this repository, change its
InstallationPolicy value by running the Set-PSRepository cmdlet. Are you sure you want to install the modules from
'PSGallery'?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): Y
Updated using the PowerShell Gallery
The currently installed version(s) of dbatools is/are:
1.1.10
1.1.9

The latest version of dbatools in the PSGallery is: 1.1.10
Latest version of dbatools found on ComputerName.
Older versions of dbatools also found. These will be uninstalled now.

Confirm
Are you sure you want to perform this action?
Performing the operation "Removing old versions of dbatools." on target "ComputerName".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y
WARNING: The version '1.1.9' of module 'dbatools' is currently in use. Retry the operation after closing the
applications.
WARNING: Unable to remove dbatools version [1.1.9] due to:
 System.Exception: Module 'dbatools' is in currently in use or you don't have the required permissions.
The End
```

#### P.S.
I was using an Administrator console. I was upgrading from `1.1.9` to `1.1.10`. I want to say this worked previously because I was running it from a cloned repo in my personal directory ( as opposed to from the PSGallery ).

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

```powershell
Name                           Value                  
----                           -----                  
PSVersion                      5.1.18362.1171         
PSEdition                      Desktop                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1171        
CLRVersion                     4.0.30319.42000        
WSManStackVersion              3.0                    
PSRemotingProtocolVersion      2.3                    
SerializationVersion           1.1.0.1                
```

### SQL Server Edition and Build number

Not applicable

**Comment by potatoqualitee** [comment]
i actually wondered how your suggestion worked because of the DLLs, and a cloned repo + other versions makes sense. i'm not sure there is a resolution to this. Would it be to skip a version?

**Comment by mattcargile** [comment]
Would you have to spawn another `powershell` session and then close the current session? It may not be great from a user perspective because then the original session doesn't know if the cleanup was successful. Maybe there is some create `[runspace]` method that can be used.

**Comment by wsmelton** [comment]
If you spawn another session and then kill the original you lose control over that spawned session/process.

This is the way modules with client libraries work, any session on the device/server will lock those DLLs once it is loaded. `Remove-Module` nor `Uninstall-Module` will remove the lock on those files.

**Comment by mattcargile** [comment]
So `-Cleanup` should probably be removed, I suppose. 

Maybe an entirely different module would be more ideal to perform the cleanup? I get that the `script` can cleanup other modules as well. It would be slightly easier with a `Cleanup-Module` cmdlet I *think*. Or is it just not worth the squeeze?

**Comment by wsmelton** [comment]
It is trying to solve an issue that is "by design" with PowerShell (Windows and Pwsh). Everyone manages that part of their environment differently (I use DSC in some to keep things clean).

Any number of things can cause PowerShell to auto-load a module so even in a different module or script it won't guarantee that it will clean up every version. I don't see this as being worth the effort to maintain.

**Comment by mattcargile** [comment]
It is still relevant issue. I would guess this parameter should be removed at this point.

**Comment by mattcargile** [comment]
Still a bug. Parameter should be removed.

**Comment by mattcargile** [comment]
Command is deprecated as of _v2.0_. Closing.

**Comment by mattcargile** [comment]
Closing again?
