### ISSUE TITLE
 Test-DbaWindowsLogin to accept input from Get-DbaLogin

### ISSUE THREAD

**Issue by MikeyBronowski** [dataplat/dbatools#7721]
### Summarize Functionality

Be able to pass the logins from Get-DbaLogin into Test-DbaWindowsLogin command.

`Get-DbaLogin -SqlInstance sql01 -Login DOMAIN\Mikey | Test-DbaWindowsLogin`

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

I think Test-DbaLoginPassword works this way.

`Get-DbaLogin -SqlInstance sql01 -Login DOMAIN\Mikey | Test-DbaLoginPassword`

**Comment by andreasjordan** [comment]
This is one of the examples and works. Can this be closed?

**Comment by wsmelton** [comment]
This issue has not been resolved in v2.0.3, still not accepting input. The command has not been updated to handle `InputObject` which any command expecting to have full piping support will need.

![image](https://github.com/dataplat/dbatools/assets/11204251/df807bc7-328a-4821-ac5d-80e2af360f92)

**Comment by andreasjordan** [comment]
Ups, I look at the wrong code (Test-DbaLoginPassword).
