### ISSUE TITLE
Missing firewall commands on dbatools.io/commands

### ISSUE THREAD

**Issue by wsuhoey** [dataplat/dbatools#7812]
### Verified issue does not already exist?

Yes

### What error did you receive?

dbatools.io/commands does not show any of the 3 new firewall commands:
```
Get-DbaFirewallRule
New-DbaFirewallRule
Remove-DbaFirewallRule
```

I'm guessing they should be under the `Security and Encryption` category, if not a new or other category?

NOTE: The commands do appear successfully in docs.dbatools.io

### Steps to Reproduce

Navigate to dbatools.io/commands.
Do a CTRL+F (Find) for "firewall"
0 results :(

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe), VS Code (terminal), VS Code (integrated terminal)

### PowerShell Host Version

n/a

### SQL Server Edition and Build number

n/a

**Comment by niphlod** [comment]
ping @ClaudioESSilva that should be "the boss" of the commands page. @potatoqualitee sooner or later we should use docs for the command list (better reorganizing tags, maybe) ? keeping commands in sync "by hand" is a daunting task.

**Comment by potatoqualitee** [comment]
agreed @niphlod - I've wanted to automate it based on tags. I can work on tags -- redo them based on the webpage. and make the first tag align with the webpage category.

AvailabilityGroups, BackupAndRestore, etc. Then after that, make an action step and add it to my release thing.
