### ISSUE TITLE
Set-DbaDbCompression error when multiple databases

### ISSUE THREAD

**Issue by utirpan** [dataplat/dbatools#7864]
### Verified issue does not already exist?

Yes

### What error did you receive?

WARNING: [15:55:11][Set-DbaDbCompression] Compression failed for localhost - [DB1] | Error connecting to [localhost]: Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named
 'op_Addition'.
WARNING: [15:55:11][Set-DbaDbCompression] Compression failed for localhost - [DB2] | Error connecting to [localhost]: Method invocation failed because [System.Management.Automation.PSObject] does not contain a method
named 'op_Addition'.
WARNING: [15:55:11][Set-DbaDbCompression] Compression failed for localhost - [DB3] | Error connecting to [localhost]: Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named
'op_Addition'.
 named 'op_Addition'.
WARNING: [15:55:11][Set-DbaDbCompression] Compression failed for localhost - [DB4] | Error connecting to [localhost]: Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named
'op_Addition'.
WARNING: [15:55:11][Set-DbaDbCompression] Compression failed for localhost - [DB5] | Error connecting to [localhost]: Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named
 'op_Addition'.
WARNING: [15:55:11][Set-DbaDbCompression] Compression failed for localhost - [DB6] | Error connecting to [localhost]: Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named
'op_Addition'.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
$InputObject = Test-DbaDbCompression -SqlInstance <instancename> -ExcludeDatabase master,model,msdb,tempdb -SqlCredential $cred | where { $_.SizeCurrent.Megabyte -gt 100.0 -and $_.PercentCompression -ge 25.0 }
Set-DbaDbCompression -SqlInstance <instancename> -SqlCredential $cred -InputObject $InputObject

### Are you running the latest release?

Yes

### Other details or mentions

Test-DbaDbCompression completes without error (takes a long time though).
Set-DbaDbCompression throws warnings immediately and quits.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      5.1.17763.2183
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.2183
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU12) (KB5004524) - 15.0.4153.1 (X64)   Jul 19 2021 15:37:34   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -recurse |
>> Get-ItemProperty -name Version,Release -EA 0 |
>> Where { $_.PSChildName -match '^(?!S)\p{L}'} |
>> Select PSChildName, Version, Release

PSChildName Version   Release
----------- -------   -------
Client      4.7.03190  461814
Full        4.7.03190  461814
Client      4.0.0.0

[System.Runtime.InteropServices.RuntimeInformation]::get_FrameworkDescription() did not work.
Method invocation failed because [System.Runtime.InteropServices.RuntimeInformation] does not contain a method named 'get_FrameworkDescription'.
At line:1 char:1
+ [System.Runtime.InteropServices.RuntimeInformation]::get_FrameworkDes ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

**Comment by utirpan** [comment]
How to tell the version of dbatools?

**Comment by andreasjordan** [comment]
`Get-Module -Name dbatools`

**Comment by utirpan** [comment]
"Get-Module -Name dbatools" returns blank (nothing)

**Comment by andreasjordan** [comment]
First import the module. Or execute `Get-Module -Name dbatools -ListAvailable`, that will show all installed versions.

**Comment by utirpan** [comment]
Directory: C:\Users\SQLAdmin\Documents\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.24     dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, ...

**Comment by andreasjordan** [comment]
Ok, not the latest version, but not too old.
Can you reproduce the error and then run `Get-DbatoolsError`?

**Comment by utirpan** [comment]
Working on it, will post results as soon as I can...

**Comment by utirpan** [comment]
PS C:\Users\ut> Get-DbatoolsError


CategoryInfo          : InvalidOperation: ([TESTDB1]:PSObject) [Write-Error], Exception
ErrorDetails          : Error connecting to [10.10.4.4]: Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
Exception             : System.Exception: Error connecting to [10.10.4.4]: Method invocation failed because [System.Management.Automation.PSObject] does not contain a method
                        named 'op_Addition'. ---> System.Management.Automation.RuntimeException: Method invocation failed because [System.Management.Automation.PSObject] does
                        not contain a method named 'op_Addition'.
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           --- End of inner exception stack trace ---
FullyQualifiedErrorId : dbatools_Set-DbaDbCompression,Stop-Function
InvocationInfo        : System.Management.Automation.InvocationInfo
PipelineIterationInfo : {0, 1}
PSMessageDetails      :
ScriptStackTrace      : at Stop-Function, C:\Users\ut\Documents\WindowsPowerShell\Modules\dbatools\1.1.24\allcommands.ps1: line 91905
                        at Set-DbaDbCompression<Process>, C:\Users\ut\Documents\WindowsPowerShell\Modules\dbatools\1.1.24\allcommands.ps1: line 69987
                        at <ScriptBlock>, <No file>: line 1
TargetObject          : [TESTDB1]

**Comment by utirpan** [comment]
To reproduce this error, make sure $InputObject has multiple tables from multiple databases. If you have objects from 1 single database it is not erroring out.

**Comment by andreasjordan** [comment]
It is difficult for me to setup a lab for that.
Can you run the command with `-Verbose` to see what the last verbose message before the failure is? And use `-EnableException` to fail at the first error and not continue with the other databases.

**Comment by andreasjordan** [comment]
Most likely it is line 69839 in the allcommands.ps1:
```
$results += $compressionSuggestion | Select-Object *, @{l = 'AlreadyProcessed'; e = { "False" } }
```
 Can you change the line and remove the "+" from "+="?

**Comment by utirpan** [comment]
I will work on that and let you know...

**Comment by andreasjordan** [comment]
Hi @utirpan have you had a chance to test that?

**Comment by utirpan** [comment]
No I have not, but I believe I pinpointed the code with the problem. There is no enumeration (for loop) in the code it coded to expect 1 item only.  And once you pass multiple tables it is choking, I will provide more info as soon as I can.

**Comment by potatoqualitee** [comment]
Reading through this suggests that a whole lot more is going on than our compression command. @utirpan are you loading Microsoft's `SqlServer` or `SQLPS` module in the same session? Does the problem happen when you `Get-process *powershe* | Stop-Process` then starting it again via `powershell -noprofile`?

I was thinking perhaps it was a .NET issue but your .NET exceeds requirements

```
Client 4.7.03190 461814
Full 4.7.03190 461814
Client 4.0.0.0
```

Can you repro on a totally different computer?
