### ISSUE TITLE
Appveyor build changes

### ISSUE THREAD

**Issue by wsmelton** [dataplat/dbatools#7867]
### Verified issue does not already exist?

Yes

### What error did you receive?

![image](https://user-images.githubusercontent.com/11204251/137604854-0d5dfa93-55c9-4b93-88d2-9faa44cdb44c.png)

### Steps to Reproduce

N/A - this is issue with Appveyor runs

### Are you running the latest release?

Yes

### Other details or mentions

https://github.com/sqlcollaborative/dbatools/commit/588e3cbce6bb90b3744cd19d0f0b939f3335e85d

Changes in this PR bumped the .NET/dotnet SDK to 5.0 which is not supported for our library class file. Our project is not written to compile under 5.0 release right now. (And actually never can because it breaks functionality with PowerShell library for cross-platform support.)

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

N/A

### SQL Server Edition and Build number

N/A

### .NET Framework Version

Whatever Appveyor runs 🤷🏻

**Comment by wsmelton** [comment]
This run from a current PR also shows the failure but a different error message:

https://ci.appveyor.com/project/sqlcollaborative/dbatools/builds/41175424/job/4yclemy7kr3vhtty

![image](https://user-images.githubusercontent.com/11204251/137646669-b80767f0-05de-4356-b0bc-dc0a0ca6b154.png)

**Comment by andreasjordan** [comment]
What can we do here?

**Comment by wsmelton** [comment]
How the library is built during Appveyor setup would need to be adjusted. 

I'd personally like to move the library project to it's own project on GitHub so we can build and test it separately (using GitHub Actions). Then setup an action to publish it as a formal Nuget. Not an overnight change though :shrug:.

**Comment by wsmelton** [comment]
If I recall from last looking at it the version of dotnet SDK we point at is wrong. Our library does not support dotnet 5.0.

**Comment by andreasjordan** [comment]
@potatoqualitee : Is this something you have to keep in mind for the new library module or 2.0?

**Comment by potatoqualitee** [comment]
yep! ty

**Comment by andreasjordan** [comment]
Looks like this is solved now. Can you confirm, @wsmelton ?
