### ISSUE TITLE
Copy-DbaDatabase - DetachAttach Same Instance Can't Access Local Drive

### ISSUE THREAD

**Issue by mattcargile** [dataplat/dbatools#7882]
### Verified issue does not already exist?

Yes

### What error did you receive?

Powershell Core Basic Ouput:
```powershell
WARNING: [09:36:46][Copy-DbaDatabase] Can't access remote Sql directories on REMOTESERVER which is required to perform detach/copy/attach.
WARNING: [09:36:46][Copy-DbaDatabase] You can manually try accessing D:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA to diagnose any issues.
WARNING: [09:36:46][Copy-DbaDatabase] Halting database migration
```

Full `$Error` output:
```powershell
PSMessageDetails      : 
Exception             : System.Exception: Halting database migration
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Copy-DbaDatabase,Stop-Function
ErrorDetails          : Halting database migration
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.25\allcommands.ps1: line 91956
                        at Copy-DbaDatabase<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.25\allcommands.ps1: line 6493
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
```

### Steps to Reproduce

```powershell
New-DbaDatabase -SqlInstance REMOTESERVER -Name t
Copy-DbaDatabase -Source REMOTESERVER-Destination REMOTESERVER -Database t -DetachAttach -NewName t_copy -Reattach 
```

### Are you running the latest release?

Yes

### Other details or mentions

Spoke with @andreasjordan on Slack. Here is his note from Slack.

_Quick fix for me was do remove the internal function Join-AdminUnc inside of the command as we have an "official " internal command with that name. Only difference: The "internal-internal" command tests for source beeing destination and in that case returns "local" paths and not UNC paths. But these "local" paths where tested with Test-Path from the "powershell client" - and fails._

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

```sql
Microsoft SQL Server 2017 (RTM-CU20) (KB4541283) - 14.0.3294.2 (X64) 
	Mar 13 2020 14:53:45 
	Copyright (C) 2017 Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)
```

### .NET Framework Version

`.NET 5.0.11`

**Comment by andreasjordan** [comment]
Hi @potatoqualitee - can you have a look?
First of all: Do you think this is a valid use case for the function?
Then: Do we need the "command-internal" function Join-AdminUnc with the extra test of "$script:sameserver -or (-not $script:isWindows" which results in returning the local path instead of an unc path.

**Comment by andreasjordan** [comment]
Hi @potatoqualitee - can you have a look?

**Comment by mattcargile** [comment]
Not sure it this needs to be pursued. I think it would be a convenient test usage.

**Comment by potatoqualitee** [comment]
I loved the suggestion and added it as an Example -- i think a lot of ppl will find this handy. Works on both remote and local. Thank you including the solution from @andreasjordan as well.

I did accidentally push to Development. If anything fails, I'll create another PR and fix it before next release.
