### ISSUE TITLE
Copy-DbaDatabase not works on macos 

### ISSUE THREAD

**Issue by Pierpa** [dataplat/dbatools#7961]
### Verified issue does not already exist?

Yes

### What error did you receive?

PSMessageDetails      :
Exception             : Microsoft.SqlServer.Management.Smo.SmoException: Microsoft.Data.SqlClient.SqlError: Directory lookup for the file "R:\mount\SQL_Data\E:\mount\Data\My_DB.mdf" failed with the ope
                        rating system error 123(The filename, directory name, or volume label syntax is incorrect.).
                           at Microsoft.SqlServer.Management.Smo.ExecutionManager.ExecuteNonQueryWithMessage(StringCollection queries, ServerMessageEventHandler dbccMessageHandler, Boolean errorsAsMessages, Boolean retry)
                           at Microsoft.SqlServer.Management.Smo.BackupRestoreBase.ExecuteSql(Server server, StringCollection queries)
                           at Microsoft.SqlServer.Management.Smo.Restore.SqlRestore(Server srv)
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Write-Error], SmoException
FullyQualifiedErrorId : dbatools_Copy-DbaDatabase,Stop-Function
ErrorDetails          : Microsoft.Data.SqlClient.SqlError: Directory lookup for the file "R:\mount\SQL_Data\E:\mount\Data\My_DB.mdf" failed with the operating system error 123(The filename, directory n
                        ame, or volume label syntax is incorrect.).
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, /Users/pierpa/.local/share/powershell/Modules/dbatools/1.1.35/allcommands.ps1: line 92342
                        at Copy-DbaDatabase<Process>, /Users/pierpa/.local/share/powershell/Modules/dbatools/1.1.35/allcommands.ps1: line 6823
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

### Steps to Reproduce

Copy-DbaDatabase -Source sql2016 -Destination sql2016b -Database MY_DB -BackupRestore -WithReplace -SharedPath \\fileshare\sql\migration

### Are you running the latest release?

Yes

### Other details or mentions

I've got the error only when i ran the command in macos: the backup part worked but when it tried to restore the database i've received the error.
I've also tried the same command from windows system and all work well.

### What PowerShell host was used when producing this error

VS Code (terminal)

### PowerShell Host Version

PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Darwin 19.6.0 Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP2-CU16) (KB5000645) - 13.0.5882.1 (X64)   Jan 25 2021 21:40:32   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) 

### .NET Framework Version

.NET 6.0.0-rtm.21522.10

**Comment by andreasjordan** [comment]
Hi @potatoqualitee - do you use MacOS?

**Comment by Pierpa** [comment]
Hi @andreasjordan yes i use MacOs (catalina version: 10.15.7)

**Comment by potatoqualitee** [comment]
@andreasjordan I do. @Pierpa is the destination server a windows machine?

**Comment by Pierpa** [comment]
Hi @potatoqualitee . Yes the destination server is a windows machine.

**Comment by potatoqualitee** [comment]
I have an idea about what this could be, but it'll be after the holidays till I have the capacity to take a look. Thank you for the report! I'll keep this issue as unread.

**Comment by lowlydba** [comment]
@potatoqualitee What was your hunch on this? Starting to look into this myself after running into the same issue with Restore-DbaDatabase on Mac.

**Comment by potatoqualitee** [comment]
hey @lowlydba - my hunch is that the path resolution logic is messed up. It's SO hard to figure this out bc it's so tempting to resolve a path on the client instead of the server. I imagine that the solution will end up being solved by `Join-DbaPath -SqlInstance` which figures out the target directory. If it's already there, there logic has to be fixed.

**Comment by potatoqualitee** [comment]
INTERESTING! I would have never thought to compare the two! Please feel free to address. No wonder it was so confusing, this is a bug.
