### ISSUE TITLE
Write-DbaDbTableData breaks json data on import

### ISSUE THREAD

**Issue by danbuntu** [dataplat/dbatools#8002]
### Verified issue does not already exist?

Yes

### What error did you receive?

Nested json imports as '......' and not as the json string 

### Steps to Reproduce

```powershell
        $data | ConvertTo-DbaDataTable -Raw | Write-DbaDbTableData -SqlInstance $TargetServer -Database $TargetDb -Schema $schema -Verbose -Table $call.serviceName -AutoCreateTable  -Confirm:$false -EnableException;
```

My source Sdata is coming from a a json api feed. The feed includes other sections of JSON within it - nested json.

When the above powershell is run the nested json parts  (courses and qualifations) are imported as '......'. All other data that they contain is stripped out.

JSOJN example below
```
[{
		"Id": 351314,

		"Question3": null,
		"Question3Answer": null,
		"Question4": null,
		"Question4Answer": null,
		"Question5": null,
		"Question5Answer": null,
		"Preference": "#",
		"Qualifications": [{
				"QualificationTypeId": 8,
				"Qualification": "GCSE or Equivalent",
				"QualificationCode": "QT8",
				"Subject": "English Language",
				"ActualGradeId": null,
				"ActualGrade": null,
				"EstimatedGradeId": 3,
				"EstimatedGrade": "3",
				"CompletionDate": "2022-06-01T00:00:00.0000000",
				"QANCode": null,
				"Source": "Manual"
			},
			{
				"QualificationTypeId": 8,
				"Qualification": "GCSE or Equivalent",
				"QualificationCode": "QT8",
				"Subject": "English Literature",
				"ActualGradeId": null,
				"ActualGrade": null,
				"EstimatedGradeId": 3,
				"EstimatedGrade": "3",
				"CompletionDate": "2022-06-01T00:00:00.0000000",
				"QANCode": null,
				"Source": "Manual"
			},
			{
				"QualificationTypeId": 8,
				"Qualification": "GCSE or Equivalent",
				"QualificationCode": "QT8",
				"Subject": "Maths",
				"ActualGradeId": null,
				"ActualGrade": null,
				"EstimatedGradeId": 3,
				"EstimatedGrade": "3",
				"CompletionDate": "2022-06-01T00:00:00.0000000",
				"QANCode": null,
				"Source": "Manual"
			},
			{
				"QualificationTypeId": 8,
				"Qualification": "GCSE or Equivalent",
				"QualificationCode": "QT8",
				"Subject": "Science",
				"ActualGradeId": null,
				"ActualGrade": null,
				"EstimatedGradeId": 3,
				"EstimatedGrade": "3",
				"CompletionDate": "2022-06-01T00:00:00.0000000",
				"QANCode": null,
				"Source": "Manual"
			},
			{
				"QualificationTypeId": 8,
				"Qualification": "GCSE or Equivalent",
				"QualificationCode": "QT8",
				"Subject": "Health and Social Care",
				"ActualGradeId": null,
				"ActualGrade": null,
				"EstimatedGradeId": 4,
				"EstimatedGrade": "4",
				"CompletionDate": "2022-06-01T00:00:00.0000000",
				"QANCode": null,
				"Source": "Manual"
			},
			{
				"QualificationTypeId": 8,
				"Qualification": "GCSE or Equivalent",
				"QualificationCode": "QT8",
				"Subject": "Business",
				"ActualGradeId": null,
				"ActualGrade": null,
				"EstimatedGradeId": 2,
				"EstimatedGrade": "2",
				"CompletionDate": "2022-06-01T00:00:00.0000000",
				"QANCode": null,
				"Source": "Manual"
			},
			{
				"QualificationTypeId": 8,
				"Qualification": "GCSE or Equivalent",
				"QualificationCode": "QT8",
				"Subject": "Statistics",
				"ActualGradeId": null,
				"ActualGrade": null,
				"EstimatedGradeId": 3,
				"EstimatedGrade": "3",
				"CompletionDate": "2022-06-01T00:00:00.0000000",
				"QANCode": null,
				"Source": "Manual"
			},
			{
				"QualificationTypeId": 8,
				"Qualification": "GCSE or Equivalent",
				"QualificationCode": "QT8",
				"Subject": "Geography",
				"ActualGradeId": null,
				"ActualGrade": null,
				"EstimatedGradeId": 4,
				"EstimatedGrade": "4",
				"CompletionDate": "2022-06-01T00:00:00.0000000",
				"QANCode": null,
				"Source": "Manual"
			}
		],
		"Courses": [{
			"OpportunityId": 90485,
			"Preference": 1,
			"Title": "",
			"TitleExtension": "",
			"Code": "",
			"LARACode": null,
			"QualificationType": "Other Regulated/Accredited Qualification",
			"QualificationTypeCode": "QT7",
			"QualificationLevel": "Level 2",
			"QualificationLevelCode": "LV2"
		}],
		"WhyChosenCourses": "I want to be a qualified nursery nurse",
		"Reference": null
	}

]
```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.1237                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.1237                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Server 2017 (RTM-CU26) (KB5005226) - 14.0.3411.3 (X64) 
	Aug 24 2021 09:59:15 
	Copyright (C) 2017 Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

Microsoft SQL Server 2017 (RTM-CU26) (KB5005226) - 14.0.3411.3 (X64) 
	Aug 24 2021 09:59:15 
	Copyright (C) 2017 Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

### .NET Framework Version

 4.8.04084

**Comment by niphlod** [comment]
let's start with the basics, your input is a json, Qualifications column in there is a JSON object, not a string, what would you like for Write-DbaDbTableData to do ?

**Comment by danbuntu** [comment]
I would like to store that json object as an nvarchar in a field called Qualifications. 

Then when our import routines run they will loop through each row in the table processing each field. The Qualifications field will be used as an object or converted into a hashtable and each entry it processed.

**Comment by niphlod** [comment]
yeah, so you'd need to pass to write-dbadbtabledata the json string representation of the innermost json object for Qualifications

**Comment by andreasjordan** [comment]
@danbuntu is this issue resolved?

**Comment by andreasjordan** [comment]
Will close this now. Issue can be reopened in needed.
