### ISSUE TITLE
Error: " strong-name signing is not supported on this platform "

### ISSUE THREAD

**Issue by techvslife** [dataplat/dbatools#8014]
### Verified issue does not already exist?

Yes.

### What error did you receive?

When using dbatools to backup a SQL server database's code (using dacpac, but same error using SMO only), I'm getting a "strong-name signing is not supported on this platform" error--probably due to updating to Powershell 7.2 (64 bit, on windows 10), or some other .net 6.0 update.  (The code worked fine before the latest updates.)  

Error text:

> Exception: C:\Users\usr\Documents\PowerShell\Modules\dbatools\1.1.41\allcommands.ps1:92646
>  Line |
> 92646 |          throw $records[0]
>       |          ~~~~~~~~~~~~~~~~~
>       | Error connecting to [NP:.]: Strong-name signing is not supported on this platform.

Others have reported it or a similar error message, e.g.:
https://githubmemory.com/repo/microsoft/DacFx/issues/33

The latest release of dacfx is supposed to solve the problem, but I'm not sure how to install it in a way dbatools can use, or if dbatools has to incorporate it in some way: 
https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15

Thanks in advance for any help or suggestions.

### Steps to Reproduce

```powershell
$sql_server='.'
$dbs = "MyDbs"

Export-DbaDacPackage -SqlInstance $sql_server -Database $dbs -FilePath .\testfile.dacpac -EnableException
```
### Are you running the latest release?

Yes

### Other details or mentions

no

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU14) (KB5007182) - 15.0.4188.2 (X64)   Nov  3 2021 19:19:51   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19044: ) (Hypervisor) 

### .NET Framework Version

.NET 6.0.0-rtm.21522.10

**Comment by andreasjordan** [comment]
Can you just try to connect to the instance with named pipes?
```
$server = Connect-DbaInstance -SqlInstance '.'
```

Or do you want to connect using TCP/IP to the localhost? Then use `$sql_server = $env:COMPUTERNAME`.

**Comment by techvslife** [comment]
Thanks, but that change made no difference. The error does not lie in the connection, but apparently in the need to upgrade some part of dbatools to support .net 6.0. Others have been running into this issue, for example:
https://githubmemory.com/repo/microsoft/DacFx/issues/33

**Comment by andreasjordan** [comment]
Ok, I see. Don't know if (or when) we plan to support .NET 6.0 - maybe @potatoqualitee can help?

**Comment by techvslife** [comment]
Thank you. --Presumably more and more people will run into this issue as they upgrade to .net 6.0, so it probably will eventually get fixed. It may also be that one would have to wait for Microsoft to release an upgrade to dacpac -- that's also discussed in the dacpac link I sent (I think the fix is now only in pre-release):
https://githubmemory.com/repo/microsoft/DacFx/issues/33
But there may be a broader issue than just dacpac: I get the same error when using smo to backup the database code.

**Comment by potatoqualitee** [comment]
oof, that blows. we try our hardest to maintain backwards compatibility because so many people are stuck in older environments. .NET 6 is far higher than our current requirement. I imagine a possible solution to this is to include two versions of dacfx -- and load the newer one when someone has a higher version of .NET. I think it will still be compatible with our current version of SMO, but it'll have to be tested bc I still don't understand how DLLs work 😆

**Comment by techvslife** [comment]
Thank you.  (--I wonder if there is a way to force this to work on any form of powershell 7.2 installation--but probably not, as I believe powershell 7.2 is .NET 6.0 based.)

**Comment by code-atom** [comment]
the preview version of dacfx with this fix is now available in nuget.org.
https://www.nuget.org/packages/Microsoft.SqlServer.DacFx/160.5323.3-preview

**Comment by techvslife** [comment]
@code-atom 
Thanks, the issue is incorporating the fix into dbatools:

> The following update to dacfx promises to solve the problem, but I'm not sure how to install it in a way dbatools can use, or if dbatools has to incorporate it in some way.

**Comment by potatoqualitee** [comment]
sweet! thank you both so much. I'll see what I can do.

**Comment by techvslife** [comment]
@potatoqualitee 
This may not be of help, but in case it is, please note this comment from the DacFx site:

> Maybe an important detail: I'm deploying a net6.0 app to Azure AppService ("framework-dependent"), where it fails with PNSE. I have temporarily worked around it by disabling signing of the assembly which uses DacFX, but I'd rather not.
[https://githubmemory.com/repo/microsoft/DacFx/issues/33?page=2](url)

**Comment by techvslife** [comment]
fyi, the new dacpac release is available here:
(https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15)

However installing the new version did not solve the dbatools "strong-name signing" error.

**Comment by potatoqualitee** [comment]
Thanks, @techvslife. There's nothing within our toolset that uses or requires strong name signing. It's something with SMO or sqlpackage. Unless you replaced the DLLs in your copy of dbatools, your external installation would not have an impact. I'll take a look when I get a moment, perhaps I can update SMO while I'm at it too.

Chrissy

**Comment by techvslife** [comment]
@potatoqualitee, Thank you. I checked the dlls packaged in the new version of dacpac (I mean in the .net core zip file also downloadable from the same site: 
https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15
), 
but it I didn't see any obvious way to upgrade the files used by dbatools to the new version. 

Ditto for the new smo files here:
https://www.nuget.org/packages/Microsoft.SqlServer.SqlManagementObjects

**Comment by EklipZgit** [comment]
I'm running into this as well where we're using PS 7.2 in our company environment. Running the command under 5.2 seems to work but would be nice if the dbatools module used the newer DacFx lib that doesn't have this issue

**Comment by potatoqualitee** [comment]
it'll be a lil bit before i can get back to this :/ tho im eager for a sollution as well. ping me in 2 weeks if i have not, please 🙇🏼

**Comment by techvslife** [comment]
Just checking back on this (as you requested). Thanks.

**Comment by gassyelmo** [comment]
yes, same!

**Comment by techvslife** [comment]
@potatoqualitee 
btw, I don't see a way of pinging you, except to post a message here.

**Comment by potatoqualitee** [comment]
its true, ive been setting this notification as unread bc im burned out :( not sure when i'll be up for the in-depth exploration but it may be a bit

**Comment by wsmelton** [comment]
I can try and look at this this coming week.

I'll see if I can get a configuration added where users can have the module reference an external version of the DLL going forward if they want.

**Comment by techvslife** [comment]
@potatoqualitee It's staggering the amount of uncompensated (and inadequately acknowledged!) work that goes into this project!
@wsmelton Thanks, that would be a great solution. My understanding is that if one is using a .net 6 based powershell (such as the latest powershell 7.x versions), only the updated DacFX dlls will work. (I'm less clear on what happens with smo.)

**Comment by potatoqualitee** [comment]
oh, @techvslife -- sorry I should have reported. This is now fixed and can be found in the latest version. Works for Windows, Mac and Linux.

**Comment by techvslife** [comment]
@potatoqualitee Thanks, I confirm this all works now!
