### ISSUE TITLE
New-DbaComputerCertificate fails if DNS parameter has more than 254 chars

### ISSUE THREAD

**Issue by KlugerSteffen** [dataplat/dbatools#8044]
### Verified issue does not already exist?

Yes

### What error did you receive?

Exception calling "Format" with "2" argument(s): "Format specifier was invalid."
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.145\allcommands.ps1:52890 char:36
+ ...  -gt 127) { [String]::Format("{0:X2}", 128 + ($hex.Length / 2)) + $he ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FormatException

### Steps to Reproduce

```powershell
$dns = $('sql-restinmain.sta-inmain.rest.xy', ' sql-nepmisc.sta-inmain.rest.xy', ' sql-storage.sta-inmain.rest.xy', ' sql-accessbroker.sta-inmain.rest.xy', ' sql-accessbrokerapi.sta-inmain.rest.xy', ' stasql.sta-ffm-inmain.rest.xy', ' stasql.sta-ff2-inmain.rest.xy', ' STArestinmainAG', 'STANepMiscAG')

function GetHexLength {
            [cmdletbinding()]
            param(
                [int]$strLen
            )
            $hex = [String]::Format("{0:X2}", $strLen)

            if ($strLen -gt 127) { [String]::Format("{0:X2}", 128 + ($hex.Length / 2)) + $hex }
            else { $hex }
        }

        function Get-SanExt {
            [cmdletbinding()]
            param(
                [string[]]$hostName
            )
            # thanks to Lincoln of
            # https://social.technet.microsoft.com/Forums/windows/en-US/f568edfa-7f93-46a4-aab9-a06151592dd9/converting-ascii-to-asn1-der

            $temp = ''
            foreach ($fqdn in $hostName) {
                # convert each character of fqdn to hex
                $hexString = ($fqdn.ToCharArray() | ForEach-Object { [String]::Format("{0:X2}", [int]$_) }) -join ''

                # length of hex fqdn, in hex
                $hexLength = GetHexLength ($hexString.Length / 2)

                # concatenate special code 82, hex length, hex string
                $temp += "82${hexLength}${hexString}"
            }
            # calculate total length of concatenated string, in hex
            $totalHexLength = GetHexLength ($temp.Length / 2)
            # concatenate special code 30, hex length, hex string
            $temp = "30${totalHexLength}${temp}"
            # convert to binary
            $bytes = $(
                for ($i = 0; $i -lt $temp.Length; $i += 2) {
                    [byte]"0x$($temp.SubString($i, 2))"
                }
            )
            # convert to base 64
            $base64 = [Convert]::ToBase64String($bytes)
            # output in proper format
            for ($i = 0; $i -lt $base64.Length; $i += 64) {
                $line = $base64.SubString($i, [Math]::Min(64, $base64.Length - $i))
                if ($i -eq 0) { "2.5.29.17=$line" }
                else { "_continue_=$line" }
            }
        }

$san = Get-SanExt $dns
```

### Are you running the latest release?

Yes

### Other details or mentions

result of ($hex.Length/2) is 1.5 Format expects integer

But don't understand what following line is intended to do: 
            if ($strLen -gt 127) { [String]::Format("{0:X2}", 128 + ($hex.Length / 2)) + $hex }
            

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.17763.2268                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.17763.2268                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Server 2017 (RTM-CU27) (KB5006944) - 14.0.3421.10 (X64)   Oct 14 2021 00:47:52   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.7.3875.0

**Comment by KlugerSteffen** [comment]
Workaround:
Certficate can be generated by get-certificate https://docs.microsoft.com/en-us/powershell/module/pki/get-certificate?view=windowsserver2019-ps

But result and behaviour is slightly different - however encrypted Connections seem to work.
- Sql Server Configruation Manager does not show the certificate
- SAN Extention is not marked critical

```powershell
$dns = $('sql-restinmain.sta-inmain.rest.xy', ' sql-nepmisc.sta-inmain.rest.xy', ' sql-storage.sta-inmain.rest.xy', ' sql-accessbroker.sta-inmain.rest.xy', ' sql-accessbrokerapi.sta-inmain.rest.xy', ' stasql.sta-ffm-inmain.rest.xy', ' stasql.sta-ff2-inmain.rest.xy', ' STArestinmainAG', 'STANepMiscAG')

$cert = get-certificate -SubjectName "CN=vm-sql-01.rest.xy" -dnsName $dns -Template "TemplateWebserver" -CertStoreLocation cert:\LocalMachine\My
($cert.Certificate).FriendlyName = 'SQL Server SSL/TLS Certificate'
$sslcert = get-DbaComputerCertificate -Thumbprint $cert.Certificate.Thumbprint
$sslcert |  Set-DbaNetworkCertificate -SQLInstance "vm-sql-01.rest.xy\STASQL" 
```

**Comment by KlugerSteffen** [comment]
seems to be a transscription of
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ff625722(v=ws.10)
But the "if mod 2" to get even digits is missing in Powershell

``` VB
Function ComputeASN1 (iStrLen) 
    Dim sLength
    If Len(Hex(iStrLen)) Mod 2 = 0 then 
        sLength = Hex(iStrLen) 
    else 
        sLength = "0" & Hex(iStrLen) 
    end if 
    if iStrLen > 127 then 
        ComputeASN1 = Hex (128 + (Len(sLength) / 2)) & sLength 
    else 
        ComputeASN1 = sLength 
    End If 
End Function
```

**Comment by KlugerSteffen** [comment]
Suggested solution.

``` powershell
function GetHexLength {
            [cmdletbinding()]
            param(
                [int]$strLen
            )
            $hex = [String]::Format("{0:X2}", $strLen)

            if (($hex.length % 2) -gt 0) { $hex = "0$hex" }

            if ($strLen -gt 127) { [String]::Format("{0:X2}", 128 + ($hex.Length / 2)) + $hex }
            else { $hex }
        }
```

**Comment by andreasjordan** [comment]
Looks good to me. Would you like to open a pull request for that or should I do it?
