### ISSUE TITLE
Backup-DbaDatabase: Issue with path output when running on Windows against a container

### ISSUE THREAD

**Issue by jpomfret** [dataplat/dbatools#8061]
### Verified issue does not already exist?

Yes

### What error did you receive?

The path returned from `Backup-DbaDatabase` is incorrect when running from a Windows OS client against a container:

``` PowerShell
PS > backup-dbadatabase -SqlInstance $conn -Database pubs -Path /var/opt/mssql/data/ | select Path
```

```
Path
----
{C:\var\opt\mssql\data\pubs_202201071641.bak}
```

### Steps to Reproduce

```powershell
$conn = Connect-DbaInstance -SqlInstance mssql1 -SqlCredential sqladmin
Backup-DbaDatabase -SqlInstance $conn -Database pubs -Path /var/opt/mssql/data/ | select Path
```

### Are you running the latest release?

Yes

### Other details or mentions

Tested on both these dbatools versions and both return the issue described:
1.1.39
1.1.49

Using containers from https://dbatools.io/docker

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                           
----                           -----                                                                                                                           
PSVersion                      5.1.19041.1320                                                                                                                  
PSEdition                      Desktop                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                         
BuildVersion                   10.0.19041.1320                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                 
WSManStackVersion              3.0                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                             
SerializationVersion           1.1.0.1                                                                                                                         

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU14) (KB5007182) - 15.0.4188.2 (X64) 
	Nov  3 2021 19:19:51 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 20.04.3 LTS) <X64>

### .NET Framework Version

I get an error running that:

```
[17:46:43][21 ms] C:\Users\Jess> [System.Runtime.InteropServices.RuntimeInformation]::get_FrameworkDescription()
Method invocation failed because [System.Runtime.InteropServices.RuntimeInformation] does not contain a method named 'get_FrameworkDescription'.
At line:1 char:1
+ [System.Runtime.InteropServices.RuntimeInformation]::get_FrameworkDes ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

**Comment by potatoqualitee** [comment]
This goes back to a bug that I found and tried to fix. @Stuart-Moore has code in there where it seems that the path has to be resolved, but when you mix Mac/Linux as the PowerShell Host and then Windows/Linux as the SQL Server host, it gets complicated.

I do not know how to resolve this issue. It doesn't break anything, but it is inaccurate.

**Comment by potatoqualitee** [comment]
there is a parameter that i cant think of right now that's like [io.file] that accepts both text and the results of get-childitem, perhaps we can use that to "Expand" but damn, it may just be the same OS expansion, k, nevermind.

**Comment by potatoqualitee** [comment]
fixed! my brain was working tonight 🧠 🥳
