### ISSUE TITLE
Combo command for TDE

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dbatools#8064]
### Summarize Command's Functionality

Setting up TDE from scratch is a ton of steps. I'll be creating a combo command (like new-dbaavailabitygroup) to do everything including backing up the certs. if anyone has a name for a suggestion, please let me know.

the idea is that it'll tde every database on the server if `-All` is specified.

### Is there a command that is similiar or close to what you are looking for?

No

**Comment by potatoqualitee** [comment]
Combo remove too

**Comment by tkronawitter** [comment]
Is New-DbaDbTransparentDataEncryption to obvious/long?

Removal needs to wait for decryption of the data too.
So maybe:
Get-DbaDbTransparentDataEncyption
Remove-DbaDbTransparentDataEncryption

And while we are at it Set-DbaDbDatabaseEncryptionKey cycle the DEK?

**Comment by potatoqualitee** [comment]
Oh, thank you, @tkronawitter! I ended up going with `Start-DbaDbEncryption`. You can see the PR here: https://github.com/sqlcollaborative/dbatools/pull/8063

**Comment by potatoqualitee** [comment]
done
