### ISSUE TITLE
Invoke-DbaDbDataGenerator - String data longer than supported column definition

### ISSUE THREAD

**Issue by DBA-Jason** [dataplat/dbatools#8070]
### Verified issue does not already exist?

Yes

### What error did you receive?

String or binary data would be truncated in table 'SQL_Admin.dbo.Testing', column 'SomeTextOrWhatever'. Truncated value: 'JnpR2tGN568hKjTs74uoupZ90n8tcC59GPrxvlI7bamu2WTpEJYojTNtyp0OunKDa9L42v7WwwnudEheETZDNR0Wc89fu3NYzTt2'.
The statement has been terminated.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.109\allcommands.ps1:82931 char:9
+         throw $records[0]
+         ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (SET IDENTITY_IN....[Testing] OFF;:String) [], Exception
    + FullyQualifiedErrorId : dbatools_Invoke-DbaDbDataGenerator

### Steps to Reproduce

```sql
CREATE TABLE [dbo].[Testing](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SomeTextOrWhatever] [varchar](128) NOT NULL,
	[YesNo] [bit] NOT NULL,
	[RandomNum] [int] NOT NULL,
	[Deci] [decimal](10,2) NOT NULL,
	[Created] [datetime] NOT NULL DEFAULT (getdate()),
CONSTRAINT [PK_ID] PRIMARY KEY CLUSTERED ([ID] ASC))
```

```powershell
#New-DbaDbDataGeneratorConfig -SqlInstance {server} -Database SQL_Admin -Table Testing -Path 'C:\Users\{user}\Temp' -Rows 10

Invoke-DbaDbDataGenerator -SqlInstance {server} -Database SQL_Admin -Table Testing -FilePath 'C:\Users\{user}\Temp\{server}.SQL_Admin.DataGeneratorConfig.json' -ExcludeColumn Created -EnableException
```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                                                
----                           -----                                                                                                                                                                                                
PSVersion                      5.1.14393.4583                                                                                                                                                                                       
PSEdition                      Desktop                                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                              
BuildVersion                   10.0.14393.4583                                                                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                  
SerializationVersion           1.1.0.1                                                                                                                                                                                              

### SQL Server Edition and Build number

Microsoft SQL Server 2017 (RTM-CU27) (KB5006944) - 14.0.3421.10 (X64)   Oct 14 2021 00:47:52   Copyright (C) 2017 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.8.4430.0

**Comment by DBA-Jason** [comment]
I'm seeing this and wondering if this is an older release:
...C:\Program Files\WindowsPowerShell\Modules\dbatools\1.0.109...

But I checked the module version before running and as part of posting this issue so...

**Comment by andreasjordan** [comment]
Yes, you are definitiy running a very old version. Please update to the latest version.

**Comment by DBA-Jason** [comment]
This can be closed. Sorry!
