### ISSUE TITLE
Add checking if  indirect checkpoint (target_recovery_time_in_seconds) is turned on in Invoke-DbaDBUpgrade for MS SQL Server 2016+

### ISSUE THREAD

**Issue by cogsciapps** [dataplat/dbatools#8094]
### Summarize Functionality

Indirect checkpoint was introduced in MS SQL 2016+ and is on by default, it is an proven improvement over the automatic checkpoint in older versions. However, if a database is restored from a backup of an older version, the option stays the same as being off.    

It would be great if Invoke-DbaDBUpgrade could include a checking if this option is turned on for MSSQL 2016+. 

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

This post https://www.mssqltips.com/sqlservertip/7108/sql-server-indirect-checkpoints-why-enable/,  describes the proof the benefit of indirect checkpoint. 

Here is the MS document about the feature of indirect checkpoint: https://techcommunity.microsoft.com/t5/datacat/changes-in-sql-server-2016-checkpoint-behavior/ba-p/305342

**Comment by andreasjordan** [comment]
The corresponding SMO property is TargetRecoveryTime:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.database.targetrecoverytime

So there is no problem implementing this, I can open a pull request for that.
I would NOT add a switch to disable it, so it would be done always like changing the compatibility level.

But what do the others think? Are there votes against it? @potatoqualitee / @nvarscar / @niphlod / @wsmelton 

Side note: Some changes are done via T-SQL, which could also be done via SMO - should we change that?

**Comment by nvarscar** [comment]
I agree that the main purpose of this command is to fix all the leftover legacy settings, so this should be also included. As far SMO vs TSQL, the former is always preferred to adhoc sql code.

**Comment by andreasjordan** [comment]
Ok, I started to code that, feedback on the pull request is welcome.
