### ISSUE TITLE
Backup-DBADatabase with piped in databases and using -ReplaceInName creates empty servername, causing error

### ISSUE THREAD

**Issue by wgshef** [dataplat/dbatools#8100]
### Verified issue does not already exist?

Yes

### What error did you receive?

SQL Server cannot check if V:\\Backup\<MyDBName>\Full exists. You can try disabling this check with -IgnoreFileChecks

### Steps to Reproduce

Get-DBADatabase -SqlInstance . -RecoveryModel Full | Backup-DbaDatabase -Path V:\servername\Backup\dbname\backuptype -FilePath dbname-backuptype-timestamp.bak -ReplaceInName -CompressBackup -Checksum -Type Full -WhatIf

### Are you running the latest release?

Yes

### Other details or mentions

Actual database name redacted with "<MyDBName>". Tried using the server name instead of ".".

Workaround is to embed the databases in the Backup-DBADatabase command:
Backup-DBADatabase -SqlInstance . -Database ((Get-DBADatabase -SqlInstance . -RecoveryModel Full | Sort-Object $_.Name).Name) -Path V:\servername\Backup\dbname\backuptype -FilePath dbname-backuptype-timestamp.bak -ReplaceInName -CompressBackup -Checksum -Type Full -WhatIf

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                 
----                           -----                                                                                                 
PSVersion                      5.1.17763.2268                                                                                        
PSEdition                      Desktop                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                               
BuildVersion                   10.0.17763.2268                                                                                       
CLRVersion                     4.0.30319.42000                                                                                       
WSManStackVersion              3.0                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                   
SerializationVersion           1.1.0.1                                                                                               

### SQL Server Edition and Build number

Microsoft SQL Server 2017 (RTM-CU27) (KB5006944) - 14.0.3421.10 (X64) 
	Oct 14 2021 00:47:52 
	Copyright (C) 2017 Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervi

### .NET Framework Version

.NET Framework 4.7.3875.0

**Comment by potatoqualitee** [comment]
oops, we forgot to ask what version of dbatools you are using. Please confirm.

**Comment by potatoqualitee** [comment]
I may have fixed this in one of the very recent releases

```
[15ms] C:/github❯ Get-DBADatabase -SqlInstance sqlcs -RecoveryModel Full | Backup-DbaDatabase -Path C:\temp -FilePath dbname-backuptype-timestamp.bak -ReplaceInName -CompressBackup
 -Checksum -Type Full -WhatIf
What if: Performing the operation "Backing up model to C:\temp\model-Full-202201192214.bak" on target "sqlcs".
What if: Performing the operation "Backing up testdev to C:\temp\testdev-Full-202201192215.bak" on target "sqlcs".
What if: Performing the operation "Backing up dbatoolscopycred to C:\temp\dbatoolscopycred-Full-202201192215.bak" on target "sqlcs".
[16s] C:/github❯ Get-DBADatabase -SqlInstance sqlcs -RecoveryModel Full | Backup-DbaDatabase -Path C:\temp -FilePath dbname-backuptype-timestamp.bak -ReplaceInName -CompressBackup -Checksum -Type Full

SqlInstance Database         Type TotalSize DeviceType Start                   Duration End
----------- --------         ---- --------- ---------- -----                   -------- ---
sqlcs       model            Full 2.83 MB   Disk       2022-01-19 13:15:33.000 00:00:00 2022-01-19 13:15:33.000
sqlcs       testdev          Full 3.89 MB   Disk       2022-01-19 13:15:35.000 00:00:00 2022-01-19 13:15:35.000
sqlcs       dbatoolscopycred Full 3.70 MB   Disk       2022-01-19 13:15:35.000 00:00:01 2022-01-19 13:15:36.000
```

**Comment by wgshef** [comment]
Hi Chrissy,
I'm running 1.1.44. When I run Update-Module dbatools, it fails with an
"access denied" error message.
When running in Verbose mode, it returns:
VERBOSE: Hash for package 'dbatools' does not match hash provided from the
server.
Then everything disappears out of the download folder.

In Debug mode, it's then looking to run/open dbatools.nupkg after this, so
the error message makes sense - the nupkg file is gone.
I haven't been able to figure out yet why this is happening.

An update on another computer went fine. So with it now being at 1.1.57 (as
shown from Get-InstalledModule -Name dbatools), I tried the command again.

Using a slight modification to the path that you used to include the
servername and path parameters (since the specific issue involved the
servername placeholder):
Get-DbaDatabase -SqlInstance . | Backup-DbaDatabase -Path
C:\Temp\servername\dbname -FilePath dbname-backuptype-timestamp.bak
-ReplaceInName -CompressBackup -Checksum -Type Full -WhatIf

Returns this message:
SQL Server cannot check if C:\Temp\\DBA exists. You can try disabling this
check with -IgnoreFileChecks
Note that the path has an empty string for where the servername placeholder
was.

Thanks,
Wayne Sheffield

**Comment by potatoqualitee** [comment]
Whoa! Okay I see it.

![image](https://user-images.githubusercontent.com/8278033/150290283-ba7c1d62-b76f-4467-bc13-3fbfd23b31b5.png)

I should be able to fix that, brb

**Comment by potatoqualitee** [comment]
oh wait lol i mkdir'd on my own comp

**Comment by potatoqualitee** [comment]
Okay now it acts as I expected it to, let me reread your expectation of how it should work. 
![image](https://user-images.githubusercontent.com/8278033/150290424-57c24cd1-be3d-4ade-a64f-3e431fe24563.png)

**Comment by potatoqualitee** [comment]
is your server a named instance?

**Comment by potatoqualitee** [comment]
does that directory exist?

**Comment by wgshef** [comment]
1. Not a named instance.
2. Yes, the directory already exists (well, up until the path has the
database name).
3. In the command that you are using, replace "-Path C:\temp\sqlcs" with
"-Path C:\temp\servername". That placeholder for "servername" is supposed
to be replaced with the server's actual name automatically. Just like
"dbname" gets the database name, and "backuptype" get the backup type, and
"timestamp" gets the current date/time. And servername does work if you run
the Backup-DbaDatabase without having databases piped into it. The issue is
that when having the databases piped into it, "servername" becomes ""
instead of the server's name. The actual string that I'm using is
"V:\servername\Backup\dbname\backuptype", so that should be converted to
"V:\xyz\Backup\master\Full" where xyz is my actual server name. What it is
getting converted to is "V:\\Backup\master\Full" - note that there are two
"\\" together and the "servername" was not replaced. Again, this only
happens when piping in the databases; when using Backup-DbaDatabase with
the -SqlInstance parameter, it works properly.

From the docs at https://docs.dbatools.io/Backup-DbaDatabase:

> -ReplaceInName
> If this switch is set, the following list of strings will be replaced in
> the FilePath and Path strings: instancename - will be replaced with the
> instance Name *servername - will be replaced with the server name *dbname
> - will be replaced with the database name timestamp - will be replaced with
> the timestamp (either the default, or the format provided) backuptype -
> will be replaced with Full, Log or Differential as appropriate

**Comment by potatoqualitee** [comment]
ah aha! thank you, this is one of the commands that im more hands off and dont know the details. this is important, however, I'll ask @Stuart-Moore to take a look as I'm backed up with the encryption stuff I'm doing.

**Comment by wgshef** [comment]
Sounds good, thanks!

Here's a screenshot:
[image: image.png]
When you run Backup-DbaDatabase by itself, the "servername" is being
replaced with "WS-P7740". Ignore the path not existing warning - that's
deliberate to get this message to show that the "servername" was replaced.

When you pipe databases into Backup-DbaDatabase, the "servername" becomes
an empty string, creating an invalid path.

**Comment by Stuart-Moore** [comment]
The issue is that it's written to take a SqlInstance object as pipeline input, not a Database object. 

It should be fixable, just trying to find a way that isn't lots of if/else bodging. I'll have a look over the weekend

**Comment by wgshef** [comment]
Using dbatools version 1.1.44
