### ISSUE TITLE
Make DbaService commands use uniform param for 'SqlInstance'

### ISSUE THREAD

**Issue by lowlydba** [dataplat/dbatools#8104]
### Verified issue does not already exist?

Yes

### What error did you receive?

Start/Stop/Restart/Get-DbaService all use `InstanceName` instead of the standard `SqlInstance` for the instance parameter. I am assuming it can/should be in line with all other commands by using SqlInstance instead, or in addition to, InstanceName.

https://github.com/dataplat/dbatools/blob/8a63f160a675704f32859d311739a6ea7d0525eb/functions/Restart-DbaService.ps1#L14-L15

Will wait for confirmation this is the case before opening a PR to either switch to `SqlInstance` and alias `InstanceName` or add it as a separate option while keeping the original.

### Steps to Reproduce

N/A

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

N/A

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

**Comment by nvarscar** [comment]
InstanceName is a string parameter, you can't alias SqlInstance to it. You should alias ComputerName instead, which would accept both computer name and specific instance if needed. You could then check in the code whether the instance name was passed as a part of `-SqlInstance` parameter, and if `-InstanceName` wasn't specified, use the the instance name derived from the SqlInstance parameter.

But this is definitely a good addition.

**Comment by wsmelton** [comment]
If we are going to do this to the service commands it should be done across the board. We use `Computer` for those commands that are operating at the OS level, and then if SQL comes into play we add the `InstanceName`

We do this for a number of commands, not just the service ones:

![image](https://user-images.githubusercontent.com/11204251/150599230-9b1f88a9-aec2-475e-b41f-e1d796bf9942.png)

**Comment by wsmelton** [comment]
This change should include updating any referenced commands that call a service command. Our commands should not depend on alias parameter names:

![image](https://user-images.githubusercontent.com/11204251/150599350-f5ee47e7-9f71-4790-ae5e-0fcd87a112cb.png)

**Comment by andreasjordan** [comment]
Yes, more than once I had to add more lines of code to my scripts because of these two parameters `-ComputerName` and `-InstanceName`instead of just one `-SqlInstance`. I would be happy to review a pull request for that. Call me if you need any help or advice.

**Comment by lowlydba** [comment]
I won't have time soon to work on this, so if anyone else wants to pick it up, feel free to 🙏🏻

**Comment by andreasjordan** [comment]
We can not use an alias as a ComputerName 'sql01' is now "get all instances on sql01", SqlInstance 'sql01' has to be "get only the default instance on sql01".
But have look at the linked pull request and give feedback.
