### ISSUE TITLE
Restore-DbaDatabase - add ability to perform diff/log restores on existing database

### ISSUE THREAD

**Issue by wgshef** [dataplat/dbatools#8109]
### Summarize Functionality

Scenario: 
Multiple databases are in an Availability Group
One of the replicas needs some extended maintenance work.
This replica is removed from the AG (and those affected databases are now in the restoring state).
After the maintenance, the replica is added back to the Availability Group.
Now we want to bring those databases up-to-date by restoring diff/log backups to those databases and then joining them back to the AG on that replica.

Request to add a switch (-BringCurrent) to Restore-DbaDatabase to restore the necessary diff/log backups. Currently, it requires restoring the entire database.

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by Stuart-Moore** [comment]
Have you tried using the `-continue` parameter? As long as the dbs are in standby/restoring states then it should apply further backups.

**Comment by wgshef** [comment]
No I didn’t, because of the docs. They state that “WithReplace” will be set, which will replace the existing databases.

-Continue
If specified we will to attempt to recover more transaction log backups onto database(s) in Recovering or Standby states When specified, WithReplace will be set to true.


-WithReplace
Switch indicated is the restore is allowed to replace an existing database.


——————————————————-

**Comment by Stuart-Moore** [comment]
That looks like something that should have been an internal comment has gone public. Under the hood we use $WithReplace to turn off some of the file checking, which is needed in this case. But with Continue it doesn't remove the db.

I'll fix the CBH up to make it less confusing
