### ISSUE TITLE
Install-DbaSqlWatch -LocalFile can't handle manually downloaded file

### ISSUE THREAD

**Issue by fmabx** [dataplat/dbatools#8114]
### Verified issue does not already exist?

Yes

### What error did you receive?

PSMessageDetails      :
Exception             : System.Management.Automation.ItemNotFoundException: Der Pfad
                        "C:\Users\username\AppData\Local\Temp\dbatools_software_download_1774043985.zip" kann nicht
                        gefunden werden, da er nicht vorhanden ist.
                           bei System.Management.Automation.LocationGlobber.ExpandMshGlobPath(String path, Boolean
                        allowNonexistingPaths, PSDriveInfo drive, ContainerCmdletProvider provider,
                        CmdletProviderContext context)
                           bei System.Management.Automation.LocationGlobber.ResolveDriveQualifiedPath(String path,
                        CmdletProviderContext context, Boolean allowNonexistingPaths, CmdletProvider& providerInstance)
                           bei System.Management.Automation.LocationGlobber.GetGlobbedMonadPathsFromMonadPath(String
                        path, Boolean allowNonexistingPaths, CmdletProviderContext context, CmdletProvider&
                        providerInstance)
                           bei Microsoft.PowerShell.Commands.RemoveItemCommand.ProcessRecord()
TargetObject          : C:\Users\username\AppData\Local\Temp\dbatools_software_download_1774043985.zip
CategoryInfo          : ObjectNotFound: (C:\Users\usern..._1774043985.zip:String) [Remove-Item], ItemNotFoundException
FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : bei Save-DbaCommunitySoftware<Process>, C:\Program
                        Files\WindowsPowerShell\Modules\dbatools\1.1.48\allcommands.ps1: Zeile 67958
                        bei Install-DbaSqlWatch<Begin>, C:\Program
                        Files\WindowsPowerShell\Modules\dbatools\1.1.48\allcommands.ps1: Zeile 42272
                        bei <ScriptBlock>, <Keine Datei>: Zeile 1
PipelineIterationInfo : {0, 1}

### Steps to Reproduce

```powershell
# Download latest stable SQLWATCH Release in Browser as ZIP from "https://github.com/marcingminski/sqlwatch/releases"
Install-DbaSqlWatch -SqlInstance "localhost\MSSQLSERVER2017" -Database SQLWATCH -LocalFile $zippath
# version.txt is not found
# it's usually generated when running "Save-DbaCommunitySoftware", which isn't the case when you provide your own ZIP file
# the installation itself finishes afterwards
```

### Are you running the latest release?

Yes

### Other details or mentions

probably the version should be determined through other means than the ZIP filename and the text file

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.1320                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.1320                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19042: ) (Hypervisor) 

### .NET Framework Version

.NET 6.0.0-rtm.21522.10

**Comment by andreasjordan** [comment]
A fix is one its way...
