### ISSUE TITLE
Error in Test-DBAConnection when using FQDN for server

### ISSUE THREAD

**Issue by gpollokoff** [dataplat/dbatools#8116]
### Verified issue does not already exist?

Yes

### What error did you receive?

When using the FQDN of a server, the TcpPort test fails because it does not use the FQDN.  This is true even if commands.resolve-dbanetworkname.bypass is set to True.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Test-DBAConnection -SqlInstance Server.domain.corp

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                                        
----                           -----                                                                                                                                                                                        
PSVersion                      5.1.19041.1320                                                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                      
BuildVersion                   10.0.19041.1320                                                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                                          
SerializationVersion           1.1.0.1                                                                                                                                                                                      

### SQL Server Edition and Build number

All versions of SQL Server

### .NET Framework Version

.NET Framework 4.8.4420.0

**Comment by andreasjordan** [comment]
This is a bit tricky. We connect to the instance using Connect-DbaInstance and then use Get-DbaTcpPort to get the port. The full name goes to Connect-DbaInstance, but the returned Server SMO only knows the short name. So Get-DbaTcpPort can only open a new TCP connection using the short name.

Can you use Get-DbaTcpPort with the full name to get the port information?

**Comment by andreasjordan** [comment]
As Get-DbaTcpPort opens a new connection anyway, we should call the command with $instance instead of $server. Will open a pull request for that.
