### ISSUE TITLE
Get-DbaPrivilege Produces No Output in Remote Session

### ISSUE THREAD

**Issue by awickham10** [dataplat/dbatools#8118]
### Verified issue does not already exist?

Yes

### What error did you receive?

Some or all identity references could not be translated.
    + CategoryInfo          : NotSpecified: (SVDSQLMORPH1:String) [], Exception
    + FullyQualifiedErrorId : dbatools_Get-DbaPrivilege

### Steps to Reproduce

Running remotely with -ComputerName returns the appropriate information.
![image](https://user-images.githubusercontent.com/7840633/151197534-5f31d2c7-8df3-4242-a58e-19342404c372.png)

Running in a remote session does not return any information and errors that the identity references could not be translated. The same happens when running remotely with pwsh.
![image](https://user-images.githubusercontent.com/7840633/151197667-8089fe33-7c3f-4570-b045-e2e4cd16fd0f.png)

### Are you running the latest release?

Yes

### Other details or mentions

The same error occurs when running locally, but does not prevent results from being displaying. When running remotely, no results are displayed. I understand there may be an unknown/orphaned SID on the system but I would expect the result to be the same whether running locally or remotely.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe)

### PowerShell Host Version

Local Session
```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Remote Session Windows PowerShell
```
Name                           Value
----                           -----
PSVersion                      5.1.17763.2268
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.2268
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Remote Session PowerShell Core
```
Name                           Value
----                           -----
PSEdition                      Core
PSRemotingProtocolVersion      2.3
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
OS                             Microsoft Windows 10.0.17763
PSVersion                      7.1.3
WSManStackVersion              3.0
GitCommitId                    7.1.3
SerializationVersion           1.1.0.1
```

### SQL Server Edition and Build number

N/A

### .NET Framework Version

Local Session: 5.0.4
Remote Session Windows PowerShell: 4.8.4420.0
Remote Session PowerShell Core: 5.0.4

**Comment by andreasjordan** [comment]
Can you run the command with -Verbose to see where the execption is thrown?

**Comment by awickham10** [comment]
![image](https://user-images.githubusercontent.com/7840633/152386394-1067f03e-8a55-49b5-abc8-54123a182610.png)

**Comment by andreasjordan** [comment]
I think we should add a try-catch to Convert-SIDToUserName.

But can you try to use `$ErrorActionPreference = 'Continue'`? Maybe that helps - I can not test that at the moment.

**Comment by awickham10** [comment]
No change in behavior when changing ErrorActionPreference. I moved ```Convert-SIDToUserName``` to a try/catch and that does fire off the catch block, and then outputs the expected results.

**Comment by andreasjordan** [comment]
What should we do in the catch block? Use Write-Warning or silently ignore?

**Comment by awickham10** [comment]
What do you think about adding SID to the output object, excluding unresolvable SIDs by default but warning (to maintain backwards compatibility), and then having an IncludeOrphanedSids switch that would include them in the output with a null User property?

i.e.
```
PS C:\> Get-DbaPrivilege
WARNING: [11:34:53][Get-DbaPrivilege] Some or all identity references could not be translated.
ComputerName              : MyServerName
User                      : NT SERVICE\SQLSERVERAGENT
SID                       :  S-1-5-32-544
LogonAsBatch              : False
InstantFileInitialization : False
LockPagesInMemory         : False
GenerateSecurityAudit     : False
LogonAsAService           : True
```


```
PS C:\> Get-DbaPrivilege -IncludeOrphanedSids

ComputerName              : MyServerName
User                      : NT SERVICE\SQLSERVERAGENT
SID                       : S-1-5-32-544
LogonAsBatch              : False
InstantFileInitialization : False
LockPagesInMemory         : False
GenerateSecurityAudit     : False
LogonAsAService           : True

ComputerName              : MyServerName
User                      : 
SID                       : S-1-5-32-138
LogonAsBatch              : False
InstantFileInitialization : False
LockPagesInMemory         : False
GenerateSecurityAudit     : False
LogonAsAService           : True
```

**Comment by andreasjordan** [comment]
Sounds good to me.

**Comment by andreasjordan** [comment]
Will you open a pull request for that?

**Comment by awickham10** [comment]
I've submitted a PR for this, which is different than what we discussed. After looking at how the command was written it would require quite a bit of rewrite to make it function that way (at least that I can come up with). Instead I wrapped the SID translation in a try/catch and do not return a username if the SID cannot be translated.
