### ISSUE TITLE
Add-DbaDbRoleMember not honoring -Confirm switch?

### ISSUE THREAD

**Issue by freerider75** [dataplat/dbatools#8119]
### Verified issue does not already exist?

Yes

### What error did you receive?

Performing the operation "Adding User MyUser to role: [db_datawriter] in database [MyDatabase]" on target "[Instance]".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):

### Steps to Reproduce

```powershell
Add-DbaDbRoleMember -SqlInstance Instance -Database MyDatabase -User MyUser -Role "db_datawriter"
```

### Are you running the latest release?

Yes

### Other details or mentions

It seems that the command prompts for confirmation even if no -Confirm switch is stated which, according to the docs, should not happen.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                  
----                           -----                                                                                                                                  
PSVersion                      5.1.19041.1320                                                                                                                         
PSEdition                      Desktop                                                                                                                                
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                
BuildVersion                   10.0.19041.1320                                                                                                                        
CLRVersion                     4.0.30319.42000                                                                                                                        
WSManStackVersion              3.0                                                                                                                                    
PSRemotingProtocolVersion      2.3                                                                                                                                    
SerializationVersion           1.1.0.1                                                                                                                                

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP2-CU17) (KB5001092) - 13.0.5888.11 (X64)   Mar 19 2021 19:41:38   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

### .NET Framework Version

can't get to obtain it

**Comment by andreasjordan** [comment]
The code says:

```
[CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'High')]
```

That's why the default value of -Confirm is $true.

So this is intended and not a bug.

**Comment by andreasjordan** [comment]
`-Confirm:$false` will suppress the prompts.

**Comment by niphlod** [comment]
jm2c, @freerider75 : this is the default behaviour of Powershell, dbatools just adheres to the standard. -Confirm is a "global thingy" in Powershell and must be treated by every module in the same way (even if at first it seems counterintuitive to have to pass -Confirm:$false to NOT require any confirmations)

**Comment by freerider75** [comment]
Thank you, I'm no ps guru; actually, as @niphlod wrote the -Confirm param is really ambiguous.

**Comment by BeginTry** [comment]
May I offer a suggestion: add another example to the docs (https://docs.dbatools.io/Add-DbaDbRoleMember) that shows how to suppress the confirmation? I probably would have found it there before reviewing the source code and/or going to the #dbatools Slack channel. 😀

For instance:
`Add-DbaDbRoleMember -SqlInstance localhost -Database DEMODB -Role db_owner -User user1 -Confirm:$false`
