### ISSUE TITLE
CompressBackup option to Add-DbaAgDatabase

### ISSUE THREAD

**Issue by cdbunch72** [dataplat/dbatools#8120]
### Summarize Functionality

When using the manual seeding mode with backup and restore it would be nice to have the option to compress the backup as the shared path may not be as large as the regular backup location.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

When calling Backup-DbaDatabase in the Add-DbaAgDatabase function it would be useful if you could specify -CompressBackup

**Comment by wsmelton** [comment]
I would recommend this be added as an input object to pass advanced parameters to the Backup call. In place of us having to add all the possible parameters the command accepts to this AG command.

```powershell
$addParams = @{
    SqlInstance = 'sql2017a'
    AvailabilityGroup = 'ag1'
    ....
    AdvancedBackupParams = @{
        CompressBackup = $true
        FileCount = 6
    }
}
Add-DbaAgDatabase @addParams
```

Each call to `Backup-DbaDatabase` would adding that splatted object: `@AdvancedBackupParams`

https://github.com/dataplat/dbatools/blob/bbccbfb77b376c684c5f5a23350f9f7dd5608311/functions/Add-DbaAgDatabase.ps1#L284-L287

One-off test shows it should work:

```powershell
function t {param([psobject]$AdvancedInput) Get-Process @AdvancedInput}
t -AdvancedInput @{Name = 'pwsh'}
```

![image](https://user-images.githubusercontent.com/11204251/152244569-58c0ff38-4047-4592-8cb9-2ed7ebe89a7d.png)

**Comment by andreasjordan** [comment]
Good idea, will put that on my to do list...

**Comment by andreasjordan** [comment]
I had some spare minutes...
