### ISSUE TITLE
add the attribute "IsUnique" to Find-DbaDbDuplicateIndex

### ISSUE THREAD

**Issue by ALZDBA** [dataplat/dbatools#8133]
### Summarize Functionality

Can you please add the attribute "IsUnique" to Find-DbaDbDuplicateIndex ? ( not as a comparison criteria, but as metadata. I've noticed on our db, people have dropped indexes blindly picking one of the reported ones. Dropping a unique index has its implications to the data model !
[DBATools - Find-DbaDbDuplicateIndex - IsUnique.ps1.txt](https://github.com/dataplat/dbatools/files/7993060/DBATools.-.Find-DbaDbDuplicateIndex.-.IsUnique.ps1.txt)
)

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

not as a comparison criteria, but as metadata. 
I've noticed on our db, people have dropped indexes blindly picking one of the reported ones. 
Dropping a unique index has its implications to the data model !
I have attached the modified function

**Comment by andreasjordan** [comment]
Thanks for the Feature Request - as you've already provides the code, I just opened a pull request for that.
