### ISSUE TITLE
Invoke-DbaQuery: Support 'NOEXEC' mode

### ISSUE THREAD

**Issue by lowlydba** [dataplat/dbatools#8158]
### Summarize Functionality

Add functionality to Invoke-DbaQuery to prefix the query supplied with [`NOEXEC`](https://docs.microsoft.com/en-us/sql/t-sql/statements/set-noexec-transact-sql?view=sql-server-ver15). This would allow the command to be used for parsing/compiling error checking, and help to round out the lack of `WhatIf` capabilities like most other commands have.

Full disclosure, I'm working on an Ansible collection for SQL Server management ([lowlydba.sqlserver](https://github.com/lowlydba/lowlydba.sqlserver)) that is Powershell Core compatible, heavily leaning on DBATools. This functionality would be great to support [`check_mode`](https://docs.ansible.com/ansible/2.3/playbooks_checkmode.html) for the query module.

### Is there a command that is similiar or close to what you are looking for?

Yes - Invoke-DbaQuery

### Technical Details

Prepending the query with `SET NOEXEC ON;` and then suffixing it with `SET NOEXEC OFF;` should work.

**Comment by niphlod** [comment]
hum, interesting angle. 
note to remember: we execute batches, so the dance of noexec must be done for each batch.
as for how much this is going to be useful .... I get that you can "discover" errors earlier but the point of -WhatIf (on PS's side) and -DryRun on a query you don't execute misses my brain by a lot ....
Given that I can somehow see how the NOEXEC dance can be useful for "pre-elaborating" errors, and I'm in no way against having this, could you elaborate a bit on what is it the real-case scenario of a query which doesn't run ? Is is something among the lines of "this is a checker step that if fails signals that something BEFORE this step errored out" ?

**Comment by lowlydba** [comment]
> note to remember: we execute batches, so the dance of noexec must be done for each batch.
...
> could you elaborate a bit on what is it the real-case scenario of a query which doesn't run ? Is is something among the lines of "this is a checker step that if fails signals that something BEFORE this step errored out" ?

I think there are two angles: being able to WhatIf (either literally or effectively) the function and the query.

1. For the function, NOEXEC could be implemented via WhatIf and allow for some of the same benefits for other functions by allowing you to run the command safely and "pre-elaborate" errors:
  - Is my SqlInstance valid?
  - Does the database exist on the host?
  - Is the database accessible?
  - etc. 

Arguably this could be done with or without NOEXEC, but the latter would probably require more refactoring to achieve.

2. For the query, I can also pre-elaborate errors just like I would in SSMS (hello Parse button). If my query being run is generated, dynamic, from an end user, etc. I may have a real benefit to parsing & compiling it in advance rather than letting it fail at execution time, wherein it may have left things in a weird state if some batches succeeded and others didn't. 

The NOEXEC approach gets closer to what (I think) the point of WhatIf is - which is to see what would happen if you ran the function, only in this case we're leaning on the SQL Server engine to do some "validation" of the sql parameter, rather than pre-elaborating the potential errors in PowerShell. The exact outcome of the query (i.e. rows change) is still out of reach, but this gets us as close as possible.

**Comment by niphlod** [comment]
sorry if it's taking a bit, I'm trying different variations. We'll go for a new switch separate from -Confirm -Whatif because they pop up in the Verbose output and it's not going to be a tight fit with the Verbose output of this command which has a special behaviour different from any other function.
