### ISSUE TITLE
Add-DbaAgReplica doesn't add req 'NT AUTHORITY\SYSTEM' perms

### ISSUE THREAD

**Issue by lowlydba** [dataplat/dbatools#8178]
### Verified issue does not already exist?

Yes

### What error did you receive?

When creating a new AG, `New-DbaAvailabilityGroup` handles adding the necessary `NT AUTHORITY\SYSTEM` permissions for both the primary and all secondary replicas:

https://github.com/dataplat/dbatools/blob/afc87cb27e21fd08c30c847a9e64718672d7317a/functions/New-DbaAvailabilityGroup.ps1#L548-L557

But `Add-DbaAgReplica` doesn't, so attempting to fail over to a replica added with the latter command could have [issues](https://docs.microsoft.com/en-us/troubleshoot/sql/availability-groups/troubleshooting-automatic-failover-problems#case-2-insufficient-nt-authoritysystem-account-permissions).

`Add-DbaAgReplica` should also add permissions for the system account.

### Steps to Reproduce

1. Create an AG
2. Add a replica on a new instance that hasn't already been configured for AG yet via `Add-DbaAgReplica`
3. Try to failover to new replica, observe error as described in [documentation](https://docs.microsoft.com/en-us/troubleshoot/sql/availability-groups/troubleshooting-automatic-failover-problems#case-2-insufficient-nt-authoritysystem-account-permissions) due to permission issues with `NT AUTHORITY\SYSTEM` account.

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

N/A

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

**Comment by lowlydba** [comment]
I can do a quick PR if copying and pasting the permissioning from the other function is acceptable.

**Comment by andreasjordan** [comment]
Let me have a look...

**Comment by andreasjordan** [comment]
I would be ok to add the parameter to Add-DbaAgReplica with the same definition as in New-DbaAvailabilityGroup:
```
        [ValidateSet('Wsfc', 'External', 'None')]
        [string]$ClusterType = (Get-DbatoolsConfigValue -FullName 'AvailabilityGroups.Default.ClusterType' -Fallback 'Wsfc'),
```

**Comment by andreasjordan** [comment]
And please have a second look at New-DbaAvailabilityGroup - are there more parts that need to be moved to Add-DbaAgReplica?

**Comment by lowlydba** [comment]
> I don't like to copy the code, but would rather move it to Add-DbaAgReplica.

That does seem ideal 👍🏻 . Defaulting to WSFC sounds good.

> And please have a second look at New-DbaAvailabilityGroup - are there more parts that need to be moved to Add-DbaAgReplica?

Will do. I think everything else that is necessary is good - this was born out of some issues we had in a DR exercise and the only issue of its kind, so I'm fairly confident everything else split correctly between the two.

**Comment by andreasjordan** [comment]
Setting the grant for SeedingMode Automatic could be another issue. This is also set in New-DbaAvailabilityGroup, not in Add-DbaAgReplica. But in case Add-DbaAgDatabase is used this is no problem as this grant is set there. It would only be a problem if a user adds a replica and then adds a database with T-SQL.

**Comment by lowlydba** [comment]
Seems like all three have it and do it differently:

https://github.com/dataplat/dbatools/blob/afc87cb27e21fd08c30c847a9e64718672d7317a/functions/New-DbaAvailabilityGroup.ps1#L627-L634

https://github.com/dataplat/dbatools/blob/4e6a64689fa2935feff323019f3d1ef462f30d7d/functions/Add-DbaAgDatabase.ps1#L270-L274

https://github.com/dataplat/dbatools/blob/4e6a64689fa2935feff323019f3d1ef462f30d7d/functions/Add-DbaAgReplica.ps1#L280-L284

So presumably New-DbaAvailability group doesn't need it.

**Comment by andreasjordan** [comment]
As we try to use SMO whenever possible, `.GrantAvailabilityGroupCreateDatabasePrivilege($AvailabilityGroup)` should be the way (that was my last change).

I think `Grant-DbaAgPermission` has at least one issue: Search for $perm in the code...

If you have time to open a pull request I'll be happy to review it. Otherwise I will try to find some time later this week.

**Comment by andreasjordan** [comment]
Maybe we address one issue at a time, so maybe just start with the original NT AUTHORITY\SYSTEM issue...
