### ISSUE TITLE
Invoke-DbaQuery segfaults on Linux with PowerShell 7.2 when using Kerberos auth

### ISSUE THREAD

**Issue by ajansveld** [dataplat/dbatools#8179]
### Verified issue does not already exist?

Yes

### What error did you receive?

Segmentation fault (core dumped)
EXIT STATUS 139

### Steps to Reproduce

```powershell
Invoke-DbaQuery -SqlInstance myserver -Query 'USE AdventureWorks2017; SELECT TOP 10 * FROM Sales.SalesOrderHeader'
```

### Are you running the latest release?

Yes

### Other details or mentions

This is a known issue: https://github.com/dotnet/SqlClient/issues/1390.
It was fixed in Microsoft.Data.SqlClient v4.0.1, can we upgrade the bundled package to the latest version?

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Linux 3.10.0-1160.53.1.el7.jane2.x86_64 #1 SMP Thu Jan 20 14:27:34 HKT 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

```
Microsoft SQL Server 2017 (RTM-CU28) (KB5008084) - 14.0.3430.2 (X64)
        Dec 17 2021 14:30:27
        Copyright (C) 2017 Microsoft Corporation
        Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)
```

### .NET Framework Version

.NET 6.0.0-rtm.21522.10

**Comment by danpousson** [comment]
I get the same error from docker

**Comment by ajansveld** [comment]
This was supposedly fixed in Microsoft.Data.SqlClient v4.0.1 (and System.Data.SqlClient v4.8.4).
Are there any plans to update to that (or the latest) version?

**Comment by potatoqualitee** [comment]
That is what I'm working on now, actually -- trying to get it to System.Data.SqlClient 5.0 but I'm in DLL hell. I imagine I'll figure it out by the weekend. For reference (tho I have new problems): https://github.com/microsoft/sqlmanagementobjects/issues/114

**Comment by garyhampson** [comment]
Have there been any updates to this? I too am experiencing seg faults when running a simple Invoke-DbaQuery call in PS 7.3.0 on Centos 7.

**Comment by potatoqualitee** [comment]
@garyhampson yes, this will be resolved when dbatools 2.0 is released in the upcoming weeks. I have tested invoke-dbaquery with success.

**Comment by potatoqualitee** [comment]
```
PS /mnt/c/github> kinit -l 9h  -r  6d cl@AD.LOCAL
Password for cl@AD.LOCAL:
PS /mnt/c/github> ipmo ../gallery/dbatools.core.library
PS /mnt/c/github> ipmo ./dbatools

PS /mnt/c/github> Connect-DbaInstance -SqlInstance sqlcs

ComputerName Name  Product              Version   HostPlatform IsAzure IsClustered ConnectedAs
------------ ----  -------              -------   ------------ ------- ----------- -----------
sqlcs        sqlcs Microsoft SQL Server 15.0.4236 Windows      False   False       AD\cl

PS /mnt/c/github> Invoke-DbaQuery -SqlInstance sqlcs -Query "select 1"

Column1
-------
      1
```

gonna mark this as done but you'll have to wait for dbatools 2.0 in the gallery before it'll work

**Comment by potatoqualitee** [comment]
it'll probably be about 2 weeks, @garyhampson
