### ISSUE TITLE
Add DatabaseID to the return object for relevant commands

### ISSUE THREAD

**Issue by lancasteradam** [dataplat/dbatools#8183]
### Summarize Functionality

As noted in #8053 if the database name has been changed it can cause matching issues when comparing historical data. 

For this feature request the goal is to identify which other commands would benefit from adding the DatabaseID to the return object. For example, the Get-DbaDb* commands.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

See #8175 as an example of adding the DatabaseID to a command's return object.

**Comment by andreasjordan** [comment]
Are there more commands to work on? Or can this be closed?

**Comment by wsmelton** [comment]
I'd say if more need to be worked on open new issue(s).
