### ISSUE TITLE
Add-DbaAGDatabase - Restores in the default locations 

### ISSUE THREAD

**Issue by JDA65** [dataplat/dbatools#8192]
### Verified issue does not already exist?

Yes

### What error did you receive?

PSMessageDetails      : 
Exception             : System.InvalidOperationException: Cannot force the member with name "PSStandardMembers" and type "MemberSet" to be added. A member with that name and type already exists, and the existing 
                        member is not an instance extension.
TargetObject          : [ActiveDirectory]
CategoryInfo          : InvalidOperation: ([ActiveDirectory]:PSObject) [Add-Member], InvalidOperationException
FullyQualifiedErrorId : CannotRemoveTypeDataMember,Microsoft.PowerShell.Commands.AddMemberCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Select-DefaultView<Process>, C:\Program Files\WindowsPowerShell\Modules\DBATools\1.1.72\allcommands.ps1: line 91318
                        at Get-DbaAgDatabase<Process>, C:\Program Files\WindowsPowerShell\Modules\DBATools\1.1.72\allcommands.ps1: line 19129
                        at Add-DbaAgDatabase<Process>, C:\Program Files\WindowsPowerShell\Modules\DBATools\1.1.72\allcommands.ps1: line 259
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {1, 1}

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Add-DbaAGDatabase -SqlInstance "2019-SQL1" -AvailabilityGroup "2019-SQL" -Database "ActiveDirectory" -Secondary "2019-SQL2" -SeedingMode Manual -SharedPath "\\sungro-DPM1\SQLBackups\AG" -Verbose 

### Are you running the latest release?

Yes

### Other details or mentions

Have a script that was created to add an database to the availabity group after house, testing using a small database I am finding that the following command is always changing the files location to the default SQL location. 

Tested in Versions 1.0.145 and 1.1.72

Add-DbaAGDatabase -SqlInstance $Primary.Name -AvailabilityGroup $Instance -Database $DB.Name -Secondary $Secondary.Name -SeedingMode Manual -SharedPath $Fileshare -Verbose 

VERBOSE: [11:16:03][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [11:16:03][Connect-DbaInstance] authentication method is 'local integrated'
VERBOSE: [11:16:04][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:05][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [11:16:05][Connect-DbaInstance] authentication method is 'local integrated'
VERBOSE: [11:16:05][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:06][Test-DbaAvailabilityGroup] Database [ActiveDirectory] will need a restore on replica 2019-SQL2. The replica is already configured accordingly.
VERBOSE: [11:16:06][Add-DbaAgDatabase] Test for prerequisites returned 1 databases that will be joined to the Availability Group 2019-SQL.
VERBOSE: [11:16:06][Add-DbaAgDatabase] Step 1/5: Setting seeding mode if needed.
VERBOSE: [11:16:06][Add-DbaAgDatabase] Setting seeding mode to Manual.
VERBOSE: [11:16:06][Add-DbaAgDatabase] Step 2/5: Running backup and restore if needed.
VERBOSE: Performing the operation "Taking full and log backup of database ActiveDirectory" on target "[2019-SQL1]".
VERBOSE: [11:16:06][Add-DbaAgDatabase] Taking full and log backup of database ActiveDirectory.
VERBOSE: [11:16:07][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [11:16:07][Backup-DbaDatabase] 1 database to backup
VERBOSE: [11:16:07][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:07][Backup-DbaDatabase] Backup database [ActiveDirectory]
VERBOSE: [11:16:07][Backup-DbaDatabase] Creating full backup
VERBOSE: [11:16:07][Backup-DbaDatabase] Building file name
VERBOSE: [11:16:07][Backup-DbaDatabase] Setting filename - 202202221116
VERBOSE: [11:16:07][Backup-DbaDatabase] Building backup path
VERBOSE: [11:16:07][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:07][Backup-DbaDatabase] Devices added
VERBOSE: [11:16:13][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:13][Get-DbaDbBackupHistory] Processing ActiveDirectory
VERBOSE: [11:16:13][Get-DbaDbBackupHistory] Executing sql query on [2019-SQL1].
VERBOSE: [11:16:13][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [11:16:13][Get-DbaDbBackupHistory] 1 result-groups found.
VERBOSE: [11:16:14][Backup-DbaDatabase] Setting Default timestampformat
VERBOSE: [11:16:14][Backup-DbaDatabase] 1 database to backup
VERBOSE: [11:16:14][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:14][Backup-DbaDatabase] Backup database [ActiveDirectory]
VERBOSE: [11:16:14][Backup-DbaDatabase] Creating log backup
VERBOSE: [11:16:14][Backup-DbaDatabase] Building file name
VERBOSE: [11:16:14][Backup-DbaDatabase] Setting filename - 202202221116
VERBOSE: [11:16:14][Backup-DbaDatabase] Building backup path
VERBOSE: [11:16:14][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:14][Backup-DbaDatabase] Devices added
VERBOSE: [11:16:14][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:15][Get-DbaDbBackupHistory] Processing ActiveDirectory
VERBOSE: [11:16:15][Get-DbaDbBackupHistory] Executing sql query on [2019-SQL1].
VERBOSE: [11:16:15][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [11:16:15][Get-DbaDbBackupHistory] 1 result-groups found.
VERBOSE: Performing the operation "Restore database ActiveDirectory to replica 2019-SQL2" on target "[2019-SQL2]".
VERBOSE: [11:16:15][Add-DbaAgDatabase] Restore database ActiveDirectory to replica 2019-SQL2.
VERBOSE: [11:16:15][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:15][Connect-DbaInstance] Database provided. Does not match ConnectionContext.CurrentDatabase, copying ConnectionContext and setting the CurrentDatabase
VERBOSE: [11:16:15][Restore-DbaDatabase] Changing statement timeout to infinity
VERBOSE: [11:16:15][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:15][Restore-DbaDatabase] ParameterSet  = Restore
VERBOSE: [11:16:15][Restore-DbaDatabase] Trust Database Backup History Set
VERBOSE: [11:16:15][Restore-DbaDatabase] ParameterSet  = Restore
VERBOSE: [11:16:15][Restore-DbaDatabase] Trust Database Backup History Set
VERBOSE: [11:16:15][Restore-DbaDatabase] Processing DatabaseName - 
VERBOSE: [11:16:15][Format-DbaBackupInformation] Starting
VERBOSE: [11:16:15][Format-DbaBackupInformation] String passed in for DB rename
VERBOSE: [11:16:15][Format-DbaBackupInformation]  1 PhysicalName = D:\Agawam\ActiveDirectory.mdf 
VERBOSE: [11:16:15][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ActiveDirectory.mdf 
VERBOSE: [11:16:15][Format-DbaBackupInformation]  1 PhysicalName = D:\Agawam\ActiveDirectory_log.ldf 
VERBOSE: [11:16:15][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ActiveDirectory_log.ldf 
VERBOSE: [11:16:15][Format-DbaBackupInformation]  1 PhysicalName = D:\Agawam\ActiveDirectory.mdf 
VERBOSE: [11:16:15][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ActiveDirectory.mdf 
VERBOSE: [11:16:15][Format-DbaBackupInformation]  1 PhysicalName = D:\Agawam\ActiveDirectory_log.ldf 
VERBOSE: [11:16:15][Format-DbaBackupInformation] PhysicalName = C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ActiveDirectory_log.ldf 
VERBOSE: [11:16:15][Select-DbaBackupInformation] processing diffs
VERBOSE: [11:16:15][Select-DbaBackupInformation] Found LogBaseLsn: 9614000000159200001 and FirstRecoveryForkID: 
VERBOSE: [11:16:15][Restore-DbaDatabase] VerifyOnly = False
VERBOSE: [11:16:15][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:15][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:16][Test-DbaBackupInformation] Testing restore for ActiveDirectory
VERBOSE: [11:16:16][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:16][Test-DbaBackupInformation] VerifyOnly = False
VERBOSE: [11:16:16][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:16][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:16][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:16][Test-DbaLsnChain] Testing LSN Chain
VERBOSE: [11:16:16][Test-DbaLsnChain] Testing LSN Chain - Type Type
VERBOSE: [11:16:16][Test-DbaLsnChain] Passed LSN Chain checks
VERBOSE: [11:16:16][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:17][Test-DbaBackupInformation] Marking ActiveDirectory as verified
VERBOSE: [11:16:17][Restore-DbaDatabase] ActiveDirectory passed testing
VERBOSE: [11:16:17][Restore-DbaDatabase] Passing in to restore
VERBOSE: [11:16:17][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:18][Invoke-DbaAdvancedRestore] Performing restore action
VERBOSE: [11:16:19][Invoke-DbaAdvancedRestore] Succeeded, Closing Server connection
VERBOSE: [11:16:19][Invoke-DbaAdvancedRestore] Performing restore action
VERBOSE: [11:16:21][Invoke-DbaAdvancedRestore] Succeeded, Closing Server connection
VERBOSE: [11:16:22][Add-DbaAgDatabase] Step 3/5: Add the database to the Availability Group on the primary replica.
VERBOSE: Performing the operation "Add database ActiveDirectory to Availability Group 2019-SQL on the primary replica" on target "[2019-SQL1]".
VERBOSE: [11:16:22][Add-DbaAgDatabase] Object of type AvailabilityDatabase for ActiveDirectory will be created. State of AvailabilityDatabase for ActiveDirectory on is not yet known.
VERBOSE: [11:16:22][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:22][Add-DbaAgDatabase] Object of type AvailabilityDatabase for ActiveDirectory is created. State of AvailabilityDatabase for ActiveDirectory is Creating.
VERBOSE: [11:16:22][Add-DbaAgDatabase] Method Create of AvailabilityDatabase for ActiveDirectory is executed. State of AvailabilityDatabase for ActiveDirectory is Existing.
VERBOSE: [11:16:22][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:22][Add-DbaAgDatabase] Step 4/5: Add the database to the Availability Group on the secondary replicas.
VERBOSE: Performing the operation "Add database ActiveDirectory to Availability Group 2019-SQL on replica 2019-SQL2" on target "[2019-SQL2]".
VERBOSE: [11:16:22][Add-DbaAgDatabase] State of AvailabilityDatabase for ActiveDirectory on replica 2019-SQL2 is not yet known.
VERBOSE: [11:16:22][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [11:16:23][Add-DbaAgDatabase] State of AvailabilityDatabase for ActiveDirectory on replica 2019-SQL2 is Existing.
VERBOSE: [11:16:23][Add-DbaAgDatabase] Joining database ActiveDirectory on replica 2019-SQL2.
VERBOSE: [11:16:24][Add-DbaAgDatabase] Step 5/5: Wait for the database to finish joining the Availability Group on the secondary replicas.
VERBOSE: Performing the operation "Wait for the database ActiveDirectory to finish joining the Availability Group 2019-SQL on the secondary replicas." on target "[2019-SQL1]".
VERBOSE: [11:16:24][Add-DbaAgDatabase] IsJoined is True, SynchronizationState is Initializing, waiting for Synchronized.
VERBOSE: [11:16:25][Add-DbaAgDatabase] IsJoined is True, SynchronizationState is Initializing, waiting for Synchronized.
VERBOSE: [11:16:26][Add-DbaAgDatabase] IsJoined is True, SynchronizationState is Initializing, waiting for Synchronized.
VERBOSE: [11:16:26][Add-DbaAgDatabase] IsJoined is True, SynchronizationState is Initializing, waiting for Synchronized.
VERBOSE: [11:16:27][Add-DbaAgDatabase] IsJoined is True, SynchronizationState is Synchronized, replica is in desired state.

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                            
----                           -----                                                            
PSVersion                      5.1.17763.1                                                      
PSEdition                      Desktop                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                          
BuildVersion                   10.0.17763.1                                                     
CLRVersion                     4.0.30319.42000                                                  
WSManStackVersion              3.0                                                              
PSRemotingProtocolVersion      2.3                                                              
SerializationVersion           1.1.0.1                                                          

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU9) (KB5000642) - 15.0.4102.2 (X64)   Jan 25 2021 20:16:12   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.7.3740.0

**Comment by andreasjordan** [comment]
Does the command throw an error? The Verbose output looks like everything works fine...

Or do you just complain about the "wrong" location of the database files after the restore? That is "by design" as we only use `$backups | Restore-DbaDatabase -SqlInstance $replicaServerSMO[$replicaName] -NoRecovery -TrustDbBackupHistory -EnableException`. 

But as we introduced the parameter -AdvancedBackupParams some versions ago, we could also implement -AdvancedRestoreParams as a new parameter. Then you could use `-AdvancedRestoreParams @{ ReuseSourceFolderStructure = $true }`. Would that help you?

**Comment by JDA65** [comment]
Thanks for the quick response

After posting the perceived issue, I change the SeedMode to Auto and it worked as expected. The database went to the same path as where the backup was created. 

I was always under impression that that when you placed a database in the AG Group (Always On) that it had to replicate the folder structure. At least if you use SMSS to add a database to the AG, it will bark if the folders structures do not match between servers.

**Comment by andreasjordan** [comment]
@potatoqualitee - What do you think: Should we also add `-AdvancedRestoreParams` and an example on how to reuse the source folder structure? Or should we change the command to always use `-ReuseSourceFolderStructure` when restoring? The later would change the behavoir, but for a typical AG, having the same folder structure on all replicas is best practice (I think).

**Comment by potatoqualitee** [comment]
I soooo want to say the second one (all of my test AGs had the same folder structures), but I'm concerned it'd be such a big deviation. @niphlod @jpomfret @wsmelton what do you all think?

**Comment by JDA65** [comment]
Food for thought here:
Using the Seeding: Automatic is does use the folder structure. 
But the Seeding: Manual where it does the backup/restore is does not do it. 

I would think that either method should produce the same end result.

**Comment by potatoqualitee** [comment]
i do like that there's a precedent 👌🏼  im leaning heavy yes now

**Comment by andreasjordan** [comment]
And as you mentioned the SSMS wizard would do the same. It's only our restore command that defaults NOT to reuse the folder structure but place the files in the default location. The "normal" RESTORE DATABASE T-SQL defaults to reuse the folder structure as well.

**Comment by potatoqualitee** [comment]
ah great, okay, please implement if you would like 🙏🏼 . i often prefer doing it how SSMS does it unless we can make things more convenient.

**Comment by andreasjordan** [comment]
Ok, will open a pull request.

**Comment by jpomfret** [comment]
Just catching up but makes sense to me - looks like a good improvement!
