### ISSUE TITLE
Consistency on credential parameter name on multiple commands

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [dataplat/dbatools#8193]
### Verified issue does not already exist?

Yes

### What error did you receive?

No error really. 
Writing the demo code for the SQLBits Training Day and we are using `PSDefaultParameters`. I had set one for the `DestinationSqlCredential` parameter but then got a failure with  `Test-DbaLastBackup`.   

Checking the code it looks like 
- `Test-DbaLastBackup`
- `Remove-DbaDatabaseSafely ` 
- ~~`Invoke-DbaDbLogShipping`~~
Following Shawns comments below removed this one

all have `DestinationCredential` whilst all the other commands use `DestinationSqlCredential`

### Steps to Reproduce

```powershell
  $PSDefaultParameterValues = @{
    "*dba*:SqlCredential"            = $continercredential
    "*dba*:SourceSqlCredential"      = $continercredential
    "*dba*:DestinationSqlCredential" = $continercredential
    "*dba*:PrimarySqlCredential"     = $continercredential
    "*dba*:SecondarySqlCredential"   = $continercredential
}

Test-DbaLastBackup -SqlInstance $dbatools1 -Destination $dbatools2
```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Linux 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

**Comment by wsmelton** [comment]
Test-DbaLastBackup

https://github.com/dataplat/dbatools/blob/b00a92ff78d32a8d3f2731462d0bdd16302bc3e1/functions/Test-DbaLastBackup.ps1#L268

Remove-DbaDatabaseSafely

https://github.com/dataplat/dbatools/blob/b00a92ff78d32a8d3f2731462d0bdd16302bc3e1/functions/Remove-DbaDatabaseSafely.ps1#L164

Invoke-DbaDbLogShipping

This would stay as-is because it is being used for calling `Invoke-Command2` unless we are going to standardize to the same parameter name across the board. Seem to recall this was brought up previously.

https://github.com/dataplat/dbatools/blob/b00a92ff78d32a8d3f2731462d0bdd16302bc3e1/functions/Invoke-DbaDbLogShipping.ps1#L936

**Comment by SQLDBAWithABeard** [comment]
Thank you for checking those, excellent spot on the logshippnig command.

**Comment by andreasjordan** [comment]
I personally would consider this a bug as the name of the parameter is "wrong". We don't have those rules written down, but "Destination", "Source" (and others) should always be just prefixes. And we use "Credential" to login to a computer (mostly via Invoke-Command2) and "SqlCredential" to login to a sql server instance. The user should be able to rely on it, even when some users will have to change their code when upgrading to the new version.

**Comment by SQLDBAWithABeard** [comment]
How do you define two different Sql Credentials for two different instances though?

**Comment by andreasjordan** [comment]
I don't understand. Within the same command? Give me an example.

**Comment by SQLDBAWithABeard** [comment]
Something like this? Or any of the copy commands.

Test-DbaLastBackup -SourceSqlInstance sql1 -SourceSqlCredential $cred -DestinationSqlInatance sql2 -DestinationSqlCredential $cred2

**Comment by andreasjordan** [comment]
"SourceSqlCredential" and "DestinationSqlCredential" are totally ok. "Source" and "Destination" are the prefixes and "SqlCredential" tells us that it is used to login to the corresponding "(Source|Destination)SqlInstance".

**Comment by SQLDBAWithABeard** [comment]
I think we are on the same side 😉
