### ISSUE TITLE
Import-Module 1.1.73 fails with Assembly with same name is already loaded. Microsoft.SqlServer.XE.Core.dll

### ISSUE THREAD

**Issue by wsuhoey** [dataplat/dbatools#8195]
### Verified issue does not already exist?

Yes

### What error did you receive?

Could not import C:\Program
     | Files\WindowsPowerShell\Modules\dbatools\1.1.73\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll

**********************
PowerShell transcript start
Start time: 20220223113713
Username: OBERTO\sqlsvcdev
RunAs User: OBERTO\sqlsvcdev
Configuration Name: 
Machine: KED-SQL01 (Microsoft Windows NT 10.0.14393.0)
Host Application: C:\Program Files\PowerShell\7\pwsh.dll -File \\localhost\SQLROOT\PowerShell\Test Import-Module dbatools.ps1
Process ID: 8488
PSVersion: 7.2.1
PSEdition: Core
GitCommitId: 7.2.1
OS: Microsoft Windows 10.0.14393
Platform: Win32NT
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0, 7.1.0, 7.2.1
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************
Transcript started, output file is D:\SQLROOT\PowerShell\Test Import-Module dbatools.log
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\dbatools.psd1'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\xml\dbatools.Types.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\xml\dbatools.Format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module dbatools.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\dbatools.psm1'.
**********************
Command start time: 20220223113714
**********************
PS>TerminatingError(Import-Module): "Assembly with same name is already loaded"
**********************
Command start time: 20220223113715
**********************
PS>TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not import C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll : 
[91mMethodInvocationException: [0mC:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\internal\scripts\libraryimport.ps1:144
[96mLine |
[96m 144 | [0m                     [96m[Reflection.Assembly]::LoadFrom($assemblyPath)[0m
[96m     | [91m                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mException calling "LoadFrom" with "1" argument(s): "Assembly with same name is already loaded"
[0m
"
>> TerminatingError(): "Exception calling "Invoke" with "3" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not import C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll : 
[91mMethodInvocationException: [0mC:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\internal\scripts\libraryimport.ps1:144
[96mLine |
[96m 144 | [0m                     [96m[Reflection.Assembly]::LoadFrom($assemblyPath)[0m
[96m     | [91m                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mException calling "LoadFrom" with "1" argument(s): "Assembly with same name is already loaded"
[0m
""
>> TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception calling "Invoke" with "3" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not import C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll : 
[91mMethodInvocationException: [0mC:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\internal\scripts\libraryimport.ps1:144
[96mLine |
[96m 144 | [0m                     [96m[Reflection.Assembly]::LoadFrom($assemblyPath)[0m
[96m     | [91m                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mException calling "LoadFrom" with "1" argument(s): "Assembly with same name is already loaded"
[0m
""
>> TerminatingError(): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception calling "Invoke" with "3" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not import C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll : 
[91mMethodInvocationException: [0mC:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\internal\scripts\libraryimport.ps1:144
[96mLine |
[96m 144 | [0m                     [96m[Reflection.Assembly]::LoadFrom($assemblyPath)[0m
[96m     | [91m                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mException calling "LoadFrom" with "1" argument(s): "Assembly with same name is already loaded"
[0m
""
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception calling "Invoke" with "3" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not import C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll : 
MethodInvocationException: C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\internal\scripts\libraryimport.ps1:144
Line |
 144 |                      [Reflection.Assembly]::LoadFrom($assemblyPath)
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "LoadFrom" with "1" argument(s): "Assembly with same name is already loaded"

"

ParentContainsErrorRecordException: C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\internal\scripts\libraryimport.ps1:155
Line |
 155 |  … Invoke($script:PSModuleRoot, "$(Join-Path $script:DllRoot smo)", $scr …
     |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Invoke" with "3" argument(s): "The running command stopped because the preference
     | variable "ErrorActionPreference" or common parameter is set to Stop: Could not import C:\Program
     | Files\WindowsPowerShell\Modules\dbatools\1.1.73\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll :
     | MethodInvocationException: C:\Program
     | Files\WindowsPowerShell\Modules\dbatools\1.1.73\internal\scripts\libraryimport.ps1:144 Line |
     |  144 |                      [Reflection.Assembly]::LoadFrom($assemblyPath) 
     | |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      |
     | Exception calling "LoadFrom" with "1" argument(s): "Assembly with same name is already loaded"
     |  "

**********************
PowerShell transcript end
End time: 20220223113715
**********************

### Steps to Reproduce

```powershell
Start-Transcript -Path "D:\SQLROOT\PowerShell\Test Import-Module dbatools.log" -Append -IncludeInvocationHeader
$ErrorActionPreference = 'Stop' # enables Agent Job to properly fail if PowerShell throws an error.
Import-Module dbatools -Verbose
$error[0] | select *
Stop-Transcript
```

### Are you running the latest release?

Yes

### Other details or mentions

Executed via CmdExec job step calling pwsh.exe

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

[32;1mName                           Value[0m
[32;1m----                           -----[0m
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2017 (RTM-CU28) (KB5008084) - 14.0.3430.2 (X64) 
	Dec 17 2021 14:30:27 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

### .NET Framework Version

.NET 6.0.0-rtm.21522.10

**Comment by wsuhoey** [comment]
Some additional information.
I tried rolling back to an older version that I know works in Production, 1.1.21.
Curiously, I still get the error on that older version in my Dev environment (where this error is happening).
Two things I can think of, the Dev environment has PS 7.2.1, and the Test and Prod environments are on PS 7.1.3 and PS 7.1.4, respectively.

So maybe it's a PS 7.2.1 issue?

**Comment by wsuhoey** [comment]
I've tried to uninstall PS 7.2.1 on the affected server, downgrading to PS 7.2.0, then 7.1.5, then 7.1.4 (which Prod uses) and the error still persists. I'm not sure how else to troubleshoot this :(

**Comment by wsuhoey** [comment]
On a related note, after downgrading to 7.1.4 (probably also was in 7.1.5 but I didn't check), the .NET framework seems to now be:
`.NET 5.0.9`

**Comment by wsuhoey** [comment]
Another strange point of interest... when I do `Import-Module dbatools` myself in an RDP session, it imports fine. So perhaps it's something to do with the Agent Job and Service Account?

**Comment by wsuhoey** [comment]
I decided to add the below commands to the `Test Import-Module dbatools.ps1` file before the `Import-Module`:

```Get-Module dbatools -ListAvailable
Get-Module dbatools -ListAvailable | Select Path```

And I got the version 1.1.73 which I didn't expect, from the path I didn't expect:
`C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.73\dbatools.psd1`
since I had uninstalled the 1.1.73 version (using my admin account), it seems that it was using a different path:
`C:\Users\<myusername>\Documents\PowerShell\Modules\dbatools\1.1.21\dbatools.psd1`

So it seems my tests of trying older dbatools versions weren't really testing older dbatools versions.

**Comment by wsuhoey** [comment]
I had to downgrade dbatools to 1.0.114 (a version I know that works in other environment) and I don't get that error from agent job :(

**Comment by wsuhoey** [comment]
So any ideas why it's trying to load the \bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dl 3 times?

**Comment by mattcargile** [comment]
I get this too with the below.

```powershell
Enter-PSSession server -ConfigurationName Powershell.7
Import-Module dbatools
```

#### Config
Windows Server 2012 R2
dbatools 1.1.74
pwsh.exe 7.1.4

**Comment by wsuhoey** [comment]
Despite it saying trying to load from `C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.xx\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll` ?

You're saying it loads it from `C:\Windows\Microsoft.NET\assembly\GAC_64\Microsoft.SqlServer.XE.Core\v4.0_14.0.0.0__89845dcd8080cc91\Microsoft.SqlServer.XE.Core.dll` first, then later again tries to load it from dbatools' packaged dll?

**Comment by mattcargile** [comment]
That is my guess.

When I commented out the `XE.Core` from the `$names` variable in `libraryimport.ps1` for the `Core` `if` block . The import of the module was successful and the loaded assemblies, after the fact, showed that location. I'm assuming some other `.dll` that is loaded prior is auto loading the `XE.Core` somehow but only on Server builds of Windows.

My next steps, if I get to it, would be to `procmon64.exe` the `Import-Module` `pwsh.exe` process to try to figure out which one. There may be a better way to trace it and I would love to hear any others.

**Comment by tfrijsewijk** [comment]
I'm having similar errors when running DBATools from a Windows Docker container.

```
Could not import C:\Users\ContainerAdministrator\Documents\PowerShell\Modules\dbatools\1.1.95\bin\smo\coreclr\Microsoft.SqlServer.XEvent.Linq.dll : 
MethodInvocationException: C:\Users\ContainerAdministrator\Documents\PowerShell\Modules\dbatools\1.1.95\internal\scripts\libraryimport.ps1:144
Line |
 144 |                      [Reflection.Assembly]::LoadFrom($assemblyPath)
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "LoadFrom" with "1" argument(s): "Could not
     | load file or assembly
     | 'C:\Users\ContainerAdministrator\Documents\PowerShell\Modules\dbatools\1.1.95\bin\smo\coreclr\Microsoft.SqlServer.XEvent.Linq.dll'. The specified module could not be found."

Could not import C:\Users\ContainerAdministrator\Documents\PowerShell\Modules\dbatools\1.1.95\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll : 
MethodInvocationException: C:\Users\ContainerAdministrator\Documents\PowerShell\Modules\dbatools\1.1.95\internal\scripts\libraryimport.ps1:144
Line |
 144 |                      [Reflection.Assembly]::LoadFrom($assemblyPath)
     |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "LoadFrom" with "1" argument(s): "Could not
     | load file or assembly
     | 'C:\Users\ContainerAdministrator\Documents\PowerShell\Modules\dbatools\1.1.95\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll'. The specified module could not be found."
```

**Comment by j0nathontayl0r** [comment]
Adding my own experience with this bug, though I'm not certain it's the same. I'm configuring a Windows SQL build using Packer which uses WinRM to invoke commands against a remote server. 

During the `Import-Module "dbatools"` command through WinRM. I get:

```==> TrakkaServerLocalJT.amazon-ebs.TrakkaServer:      | Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly
==> TrakkaServerLocalJT.amazon-ebs.TrakkaServer:      | 'C:\Users\Administrator\Documents\PowerShell\Modules\dbatools\1.1.95\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll'. The specified module could not be found."```

Note: my error is different, my error says the module doesn't exist, _not_ that it is already loaded. So my issue may well be different. I'll run some more troubleshooting and tests and report back. 

Similar to @wsuhoey, this only occurs when I'm importing dbatools over WinRM. But not over RDP. I'm about to try rolling back to pwsh core version 7.1.3 and dbatools 1.0.114 to see if the issue reoccurs of if you're suggested work around works, @wsuhoey.

The second work around is to comment out `'Microsoft.SqlServer.XE.Core'`, @mattcargile. I'll try both out and report back.

**Comment by lowlydba** [comment]
To add some more interesting data - I've got a github workflow that has a matrix for sql server versions. The only difference between the two jobs is that one is using SQL 2017 and the other SQL 2019. I only get a problem on the 2017 version:

https://github.com/lowlydba/dba-multitool/actions/runs/2417094275

```
Run Import-Module dbatools -Verbose
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.101\dbatools.psd1'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.101\xml\dbatools.Types.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.101\xml\dbatools.Format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module dbatools.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.101\dbatools.psm1'.
ParentContainsErrorRecordException: C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.101\internal\scripts\libraryimport.ps1:161
Line |
 161 |  … Invoke($script:PSModuleRoot, "$(Join-Path $script:DllRoot smo)", $scr …
     |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Invoke" with "3" argument(s): "The running command stopped because the preference
     | variable "ErrorActionPreference" or common parameter is set to Stop: Could not import C:\Program
     | Files\WindowsPowerShell\Modules\dbatools\1.1.101\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll : 
     | MethodInvocationException: C:\Program
     | Files\WindowsPowerShell\Modules\dbatools\1.1.101\internal\scripts\libraryimport.ps1:[15](https://github.com/lowlydba/dba-multitool/runs/6676843805?check_suite_focus=true#step:7:16)0 Line |
     |  150 |                      [Reflection.Assembly]::LoadFrom($assemblyPath)     
     | |                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~      |
     | Exception calling "LoadFrom" with "1" argument(s): "Assembly with same name is already loaded"
     |  "

Error: Process completed with exit code 1.
```

**Comment by simonsabin** [comment]
The issue is that the import of Microsoft.SqlServer.XEvent.Linq using import-module loads XECore from the GAC. 

Don't know why import-module is used over LoadFrom.

The resolution is to load the XECore assembly first so its already loaded

Happy to make the change, but no idea what tests would be appropriate.

**Comment by potatoqualitee** [comment]
Yes, thank you, happy to accept a PR, @simonsabin. I can write the test on github.

**Comment by simonsabin** [comment]
Looks like dbatools could be reintroduced into https://github.com/lowlydba/dba-multitool/blob/f0447bd3ef796e5023352ef9528474c08bc126e9/.github/workflows/sqlserver-unit.yml

**Comment by Guba88** [comment]
Did this issue is resolve? I still experiencing it in   PSVersion                      7.3.7

**Comment by mattcargile** [comment]
> Did this issue is resolve? I still experiencing it in PSVersion 7.3.7

@Guba88 , I'd open a new issue if you are on the current release and experiencing this issue.
