### ISSUE TITLE
Import-DbaCsv -AutoCreateTable not create Nvarchar but varchar

### ISSUE THREAD

**Issue by GithubPGA** [dataplat/dbatools#8202]
### Verified issue does not already exist?

Yes

### What error did you receive?

Hi Team,
When i use Import-DbaCsv -AutoCreateTable , table are created with varchar data type instead of Nvarchar.
in the file from Github "import-dbacsv.ps1"  
/Import-DbaCsv.ps1dbatools/Import-DbaCsv.ps1 at development · dataplat/dbatools

Line 359 : $sqldatatypes += "[$column] varchar(MAX)"

could you update with Nvarchar(MAX) ?

Thanks a lot for this and the very great tools :)

Best regards

### Steps to Reproduce

Get-ChildItem -Path $path -Filter toto.csv| Import-DbaCsv -Delimiter ";" -SqlInstance $InstanceName -Database $Database -Table $table -AutoCreateTable

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                                               
----                           -----                                                                                                                                                                                               
PSVersion                      5.1.14409.1018                                                                                                                                                                                      
PSEdition                      Desktop                                                                                                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                             
BuildVersion                   10.0.14409.1018                                                                                                                                                                                     
CLRVersion                     4.0.30319.42000                                                                                                                                                                                     
WSManStackVersion              3.0                                                                                                                                                                                                 
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                 
SerializationVersion           1.1.0.1                                                                                                                                                                                             

### SQL Server Edition and Build number

Microsoft SQL Server 2017 (RTM-GDR) (KB4583456) - 14.0.2037.2 (X64)   Nov  2 2020 19:19:59   Copyright (C) 2017 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64> (Build 9600: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.8.4480.0

**Comment by andreasjordan** [comment]
As we use NVARCHAR in Write-DbaDbTableData, I think we should do the same in Import-DbaCsv...

**Comment by andreasjordan** [comment]
And the documentation already talks about nvarchar(max)...
