### ISSUE TITLE
New-DbaAvailabilityGroup on German SQL Instance

### ISSUE THREAD

**Issue by AndiM1976** [dataplat/dbatools#8206]
### Verified issue does not already exist?

Yes

### What error did you receive?

WARNING: [11:53:02][New-DbaAvailabilityGroup] Failure adding cluster service account permissions | Error connecting to [vm-x\anwendung]: Suchen des Anmeldung-Objekts "NT AUTHORITY\SYSTEM" ist nicht möglich, weil das Objekt nicht vorhanden ist oder Sie nicht die erforderliche Berechtigung haben.
Suchen des Anmeldung-Objekts "NT AUTHORITY\SYSTEM" ist nicht möglich, weil das Objekt nicht vorhanden ist oder Sie nicht die erforderliche Berechtigung haben.
Suchen des Anmeldung-Objekts "NT AUTHORITY\SYSTEM" ist nicht möglich, weil das Objekt nicht vorhanden ist oder Sie nicht die erforderliche Berechtigung haben.

### Steps to Reproduce

1. Setup up two German Windows Server 2019 OS and two MSSQL 2019 Instances with CU15 on a wsfc Cluster.
2. Check if you have a login NT-AUTORITÄT\SYSTEM instead of NT AUTHORITY\SYSTEM.
3. Grant NT-AUTORITÄT\SYSTEM alter an d create Availability Group rights on every two instances.

### Are you running the latest release?

Yes

### Other details or mentions

I think dbatools does not look for regional infos by creating an ag.
Please setup up these these functionality.

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value                                                                                                                                                                                                
----                           -----                                                                                                                                                                                                
PSVersion                      5.1.17763.2268                                                                                                                                                                                       
PSEdition                      Desktop                                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                              
BuildVersion                   10.0.17763.2268                                                                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                  
SerializationVersion           1.1.0.1                                                                                                                                                                                              

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64)   Jan 12 2022 22:30:08   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.7.3875.0

**Comment by andreasjordan** [comment]
Hi! Thanks for reporting this. Although I am from Germany, I unfortunately only have English systems in my lab. Will have a look soon and provide a fix for that.

**Comment by AndiM1976** [comment]
@andreasjordan Two german Andreas working on the same issue ;-)

**Comment by andreasjordan** [comment]
Maybe we get name of system account with `(New-Object System.Security.Principal.SecurityIdentifier("S-1-5-18")).Translate([System.Security.Principal.NTAccount])`? 

But what if the system running dbatools is german and the server running sql server is english? We will have to test...

**Comment by andreasjordan** [comment]
Are you on the latest version? We moved some of the security stuff around. Please update dbatools and try again. It will probably fail again, but just to be sure where to look...

**Comment by andreasjordan** [comment]
Hi @AndiM1976 can you test that code on your german system?

```
Import-Module -Name dbatools

$server = Connect-DbaInstance -SqlInstance vm-sql902\ANWENDUNG

"WSFC Cluster requires granting [NT AUTHORITY\SYSTEM] a few things. Setting now."
# To support non-english systems, get the name of SYSTEM login by the sid
# See SECURITY_LOCAL_SYSTEM_RID on https://docs.microsoft.com/en-us/windows/win32/secauthz/well-known-sids
$systemLoginSidString = '1-1-0-0-0-0-0-5-18-0-0-0'
$systemLoginName = ($server.Logins | Where-Object { ($_.Sid -join '-') -eq $systemLoginSidString }).Name
if (-not $systemLoginName) {
    "SYSTEM login not found, so we hope system language is english and create login [NT AUTHORITY\SYSTEM]"
    try {
        $null = New-DbaLogin -SqlInstance $server -Login 'NT AUTHORITY\SYSTEM'
        $systemLoginName = 'NT AUTHORITY\SYSTEM'
    } catch {
        Throw "Failed to add login [NT AUTHORITY\SYSTEM]. If it's a non-english system you have to add the equivalent login manually."
    }
}
$permissionSet = New-Object -TypeName Microsoft.SqlServer.Management.SMO.ServerPermissionSet(
    [Microsoft.SqlServer.Management.SMO.ServerPermission]::AlterAnyAvailabilityGroup,
    [Microsoft.SqlServer.Management.SMO.ServerPermission]::ConnectSql,
    [Microsoft.SqlServer.Management.SMO.ServerPermission]::ViewServerState
)
try {
    $server.Grant($permissionSet, $systemLoginName)
} catch {
    Throw "Failure adding cluster service account permissions."
}
```

It only works if you already have the login [NT-AUTORITÄT\SYSTEM] but should find the login and grant the permissions.

To check the permissions:

```
$server.EnumServerPermissions('NT-AUTORITÄT\SYSTEM') | Format-Table
```

**Comment by AndiM1976** [comment]
Hi @andreasjordan ,
thanks for working on that.
Your Script don't throw an error. I think it should add an new login for NT AUTHORITY\SYSTEM. But it didn't.
new-dbaavailabiltiygroup shows the error from yesterday.

Any idea?

**Comment by andreasjordan** [comment]
New-DbaAvailabilityGroup will work until we ship the fix.

This script should not add the login - adding the login only works on english systems.

Let's do small steps: What's the output of `$server.EnumServerPermissions('NT-AUTORITÄT\SYSTEM') | Format-Table`?

**Comment by andreasjordan** [comment]
Better not reply by mail - I just deleted the last comment as it was only your mail footer...

**Comment by AndiM1976** [comment]
@andreasjordan Please alter my instances with fake names.

**Comment by andreasjordan** [comment]
Ok, removed server names and not relevant error messages.
