### ISSUE TITLE
Unable to specify SqlCredential

### ISSUE THREAD

**Issue by alexgurman** [dataplat/dbatools#8207]
### Verified issue does not already exist?

Yes, does NOT exist

### What error did you receive?

Export-DbaUser: Cannot process argument transformation on parameter 'SqlCredential'. userName

Full details:
PS C:\Program Files\PowerShell\7>  $error[0] | select *

PSMessageDetails      :
Exception             : System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process
                        argument transformation on parameter 'SqlCredential'. userName
                         ---> System.Management.Automation.PSArgumentException: userName
                           at System.Management.Automation.CredentialAttribute.Transform(EngineIntrinsics
                        engineIntrinsics, Object inputData)
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
                        parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ParameterBinderBase.BindParameter(CommandParameterInternal
                        parameter, CompiledCommandParameter parameterMetadata, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameter(CommandParamet
                        erInternal argument, MergedCompiledCommandParameter parameter, ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindParameter(UInt32
                        parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter,
                        ParameterBindingFlags flags)
                           at System.Management.Automation.CmdletParameterBinderController.BindNamedParameter(UInt32
                        parameterSets, CommandParameterInternal argument, MergedCompiledCommandParameter parameter)
                           at System.Management.Automation.ParameterBinderController.BindNamedParameters(UInt32
                        parameterSets, Collection`1 arguments)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParametersNoV
                        alidation(Collection`1 arguments)
                           at System.Management.Automation.CmdletParameterBinderController.BindCommandLineParameters(Co
                        llection`1 arguments)
                           at System.Management.Automation.CommandProcessor.BindCommandLineParameters()
                           at System.Management.Automation.CommandProcessor.Prepare(IDictionary
                        psDefaultParameterValues)
                           at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary
                        psDefaultParameterValues)
                           at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
                           at
                        System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                        input)
                        --- End of stack trace from previous location ---
                           at
                        System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object
                        input)
                           at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean
                        ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts,
                        CommandRedirection[][] commandRedirections, FunctionContext funcContext)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame
                        frame)
                           at
                        System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame
                        frame)
TargetObject          :
CategoryInfo          : InvalidData: (:) [Export-DbaUser], ParameterBindingArgumentTransformationException
FullyQualifiedErrorId : ParameterArgumentTransformationError,Export-DbaUser
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
$SecureUser = ConvertTo-SecureString 'UpdaterUser' -asplaintext -force
$SecurePassword = ConvertTo-SecureString 'SecretPWD' -asplaintext -force
$SecurePassword.MakeReadOnly()
$sqlCred = New-Object System.Data.SqlClient.SqlCredential($SecureUser,$SecurePassword)

Export-DbaUser -SqlInstance MySqlServer -SqlCredential $sqlCred -User LDSWebService, WSO_Global -Database LDS, WSO_Global -Path C:\Temp

### Are you running the latest release?

Yes

### Other details or mentions

Also tried using following, same error. Without specifying SqlCredential option works just fine.

$cred = Get-Credential
$cred.Password.MakeReadOnly()
$sqlCred = New-Object System.Data.SqlClient.SqlCredential($cred.username,$cred.password)

Export-DbaUser -SqlInstance MySqlServer -SqlCredential $sqlCred -User LDSWebService, WSO_Global -Database LDS, WSO_Global -Path C:\Temp

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

### .NET Framework Version

.NET 6.0.0-rtm.21522.10

**Comment by ACALVETT** [comment]
Hi,

This is expected, the help states that PowerShell credentials are accepted. The PSCredential type has username and password properties but sqlCredential has userID and password properties and because of the mismatch you get the error.

You can use the following instead of get-credentials 

`$secpasswd = ConvertTo-SecureString 'myFakePassword' -AsPlainText -Force
$mycreds = New-object -typename System.Management.Automation.PSCredential('MyUser', $secpasswd)`

**Comment by niphlod** [comment]
@alexgurman : I'm closing this, feel free to reopen in case of additional issues
