### ISSUE TITLE
Backup-DbaDatabase

### ISSUE THREAD

**Issue by JDA65** [dataplat/dbatools#8209]
### Verified issue does not already exist?

Yes

### What error did you receive?

Not really an error, but more function didn't work as expected based upon using Microsoft SQL Module. 

WARNING: [08:27:11][Backup-DbaDatabase] Backup Failed | The target database, 'Columbus_Master', is participating in an availability group and is currently not accessible for queries. Either data movement is suspen
ded or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in
 the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

### Steps to Reproduce

Running the following command on the secondary SQL Server

Backup-DbaDatabase -SqlInstance $Server -Database $DBName -FilePath ($DBBackupFile+".bak") -Type Full -CopyOnly -CompressBackup

### Are you running the latest release?

Yes

### Other details or mentions

To standardize our process with using DbaTools as our primary module, I was converting my backup script to use DbaTools and during the testing I got the warning message that didn't allow the backup on the secondary SQL Server.  

Backup-DbaDatabase -SqlInstance $Server -Database $DBName -FilePath ($DBBackupFile+".bak") -Type Full -CopyOnly -CompressBackup

WARNING: [08:27:11][Backup-DbaDatabase] Backup Failed | The target database, 'Columbus_Master', is participating in an availability group and is currently not accessible for queries. Either data movement is suspen
ded or the availability replica is not enabled for read access. To allow read-only access to this and other databases in the availability group, enable read access to one or more secondary availability replicas in
 the group.  For more information, see the ALTER AVAILABILITY GROUP statement in SQL Server Books Online.

Before I take action on the SQL servers, I want to pass this on to the group that: 

Backup-SqlDatabase -ServerInstance $Server -Database $DBName -BackupFile ($DBBackupFile+".bak") -CopyOnly

Works fine, 

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                                
----                           -----                                                                                                                                                                                
PSVersion                      5.1.17763.1                                                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                              
BuildVersion                   10.0.17763.1                                                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                                                  
SerializationVersion           1.1.0.1                                                                                                                                                                              

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU9) (KB5000642) - 15.0.4102.2 (X64)   Jan 25 2021 20:16:12   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.7.3740.0

**Comment by ACALVETT** [comment]
Hi,

I recreated the problem using a secondary that is not readable.

The problem is caused by the fact dbaTools is retrieving the data & log file paths just before initiating the backup. The file paths are then used later in the backup verification process.

This is also going to be a problem if the database is not readable for any reason so i think a way to maintain this functionality would be to get the data after the backup by read the header with "Read-DbaBackupHeader"

Would be good to get some input on this potential approach from the core developers, i can put something together.

**Impacted code**
```
                            $Filelist = @()
                            $FileList += $server.Databases[$dbName].FileGroups.Files | Select-Object @{ Name = "FileType"; Expression = { "D" } }, @{ Name = "Type"; Expression = { "D" } }, @{ Name = "LogicalName"; Expression = { $_.Name } }, @{ Name = "PhysicalName"; Expression = { $_.FileName } }
                            $FileList += $server.Databases[$dbName].LogFiles | Select-Object @{ Name = "FileType"; Expression = { "L" } }, @{ Name = "Type"; Expression = { "L" } }, @{ Name = "LogicalName"; Expression = { $_.Name } }, @{ Name = "PhysicalName"; Expression = { $_.FileName } }

```

**Comment by ACALVETT** [comment]
Actually i see there is a call to Get-DbaDbBackupHistory already and that also contains the required filelist in the necessary format so its a very small change to use it.

I will make the change and see what the dev team says

**Comment by JDA65** [comment]
I don't understand why is this relevant to process? 

When you create the AG Group - you can specified where backups happen by default. But all of by testing, I found that 
the Backup-SqlDatabase command would work from either (Primary or Secondary servers). 

In the backup command, we specify the server, database and backup file. What does history have to do with a new backup?

**Comment by ACALVETT** [comment]
Hi,

If you set verify to true there is a section of code that then calls a restore with appropriate parameters and one of those is the filelist so we need it but we need to change how we get it so as to avoid your error.  Get-DbaDbBackupHistory has the filelist and is already being called which is why i proposed using it.
