### ISSUE TITLE
Get-DecryptedObject.ps1 internal function issue.

### ISSUE THREAD

**Issue by MWHeier** [dataplat/dbatools#8218]
### Verified issue does not already exist?

Yes

### What error did you receive?

The SQL select command below returns multiple rows which match the thumbprint:

SELECT substring(crypt_property,9,len(crypt_property)-8) as smk FROM sys.key_encryptions WHERE key_id=102 and (thumbprint=0x03 or thumbprint=0x0300000001)

Our issue could have been caused by past migrations where the master database was moved/copy to a new SQL Instance.  Then when the new Instance was first started a new key_encryptions table entry was created with thumbprint "0x0300000001" but the old record with thumbprint "0x03" still exists.  I know it is not really a dbaTools issue since our team probably caused this rare situation by some migration in the past.  I have been working with Microsoft to clean-up this old entry but do not have a solution for this yet.

Since I believe the thumbprint "0x03" is for older versions of SQL my recommendation would to be first to select the entry with the "0x0300000001" thumbprint and if an entry is not found then try and match on the "0x03" thumbprint.  This would require 2 selects against SQL instead of 1.  Thoughts?  Thanks in Advance,  Mark Heier  (State of South Dakota, DBA).

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
#  I don't think you can reproduce this issue as even Microsoft can not and can not explain how this could have occurred.  
#  They do believe that the thumbprint of "0x03" is most likely an old invalid entry.

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                
----                           -----                                                                                                                                                
PSVersion                      5.1.19041.1320                                                                                                                                       
PSEdition                      Desktop                                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                              
BuildVersion                   10.0.19041.1320                                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                                      
WSManStackVersion              3.0                                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                                  
SerializationVersion           1.1.0.1                                                                                                                                              

### SQL Server Edition and Build number

Microsoft SQL Server 2014 (SP3-CU4-GDR) (KB4583462) - 12.0.6433.1 (X64)   Oct 31 2020 02:54:45   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.8.4420.0

**Comment by andreasjordan** [comment]
I can code that - no problem. But I would like to hear what the others say: @potatoqualitee ?

**Comment by MWHeier** [comment]
It appears regenerating the master key will resolve this issue but I will perform more testing. Very unlikely any change needs to be made but thank you in advance. Mark
________________________________

**Comment by andreasjordan** [comment]
Just in case:

```
    $sql = "SELECT substring(crypt_property,9,len(crypt_property)-8) as smk FROM sys.key_encryptions WHERE key_id=102 and (thumbprint=0x03 or thumbprint=0x0300000001)"
    try {
        $smkBytes = $server.Query($sql).smk
    } catch {
        Stop-Function -Message "Can't execute query on $sourceName" -Target $server -ErrorRecord $_
        return
    }
```


could be changed to 

```
    try {
        $sql = "SELECT substring(crypt_property,9,len(crypt_property)-8) as smk FROM sys.key_encryptions WHERE key_id=102 and thumbprint=0x0300000001"
        $smkBytes = $server.Query($sql).smk
        if (-not $smkBytes) {
            $sql = "SELECT substring(crypt_property,9,len(crypt_property)-8) as smk FROM sys.key_encryptions WHERE key_id=102 and thumbprint=0x03"
            $smkBytes = $server.Query($sql).smk
        }
    } catch {
        Stop-Function -Message "Can't execute query on $sourceName" -Target $server -ErrorRecord $_
        return
    }
```

**Comment by potatoqualitee** [comment]
great solution, @andreasjordan !

**Comment by MWHeier** [comment]
Yeah that looks good thank you
________________________________
