### ISSUE TITLE
Issue with Get-DbaDatabase -NoFullBackup and Compare-DbaCollationSensitiveObject

### ISSUE THREAD

**Issue by packfan73** [dataplat/dbatools#8225]
### Verified issue does not already exist?

Yes

### What error did you receive?

Compare-DbaCollationSensitiveObject : Cannot bind argument to parameter 'Value' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.65\allcommands.ps1:22813 char:109
+ ... bject -Property Name -In -Value $lastCopyOnlyBackups.Database -Collat ...
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Compare-DbaCollationSensitiveObject], ParameterBindingValidationExcept
   ion
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Compare-DbaCollationSensitiveObject

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
Get-DbaDatabase -sqlinstance server01 -NoFullBackup
```

### Are you running the latest release?

Yes

### Other details or mentions

I have run this command on Server 2012 R2 and Server 2019 with the same errors. PowerShell 5.1 versions and PowerShell 7.2 give the same error.

dbatools 1.1.36 works, but doesn't use the Compare-DbaCollationSensitiveObject function.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

2012 R2 Server:
Name                           Value                                                                                                             
----                           -----                                                                                                             
PSVersion                      5.1.14409.1005                                                                                                    
PSEdition                      Desktop                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                           
BuildVersion                   10.0.14409.1005                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                   
WSManStackVersion              3.0                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                               
SerializationVersion           1.1.0.1                                                                                                           

2019 Server:
Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.17763.2268                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.17763.2268                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                   

### SQL Server Edition and Build number

Multiple versions and patch levels ranging from 2008 R2 through 2019 CU15.

### .NET Framework Version

2012 R2 Server:
.NET Framework 4.8.3928.0

2019 Server:
.NET Framework 4.8.4420.0

**Comment by ACALVETT** [comment]
I can reproduce on the latest build and it only occurs when there are no databases without a full backup which then leads to a null being passed to Compare-DbaCollationSensitiveObject. 

This functionality was introduced recently in #7945 so we just need to decide on the best approach for null handling. @chightow Do you have any comments on this issue? I was thinking test for null before calling Compare-DbaCollationSensitiveObject

**Comment by ACALVETT** [comment]
I think the simplest way to fix this is to make the value parameter of Compare-DbaCollationSensitiveObject not mandatory as it does not affect the output of the function.
