### ISSUE TITLE
Restore-DbaDatabase lacks LogicalName parameter

### ISSUE THREAD

**Issue by smholvoet** [dataplat/dbatools#8253]
### Verified issue does not already exist?

Yes

### What error did you receive?

```powershell
Restore-DbaDatabase : A parameter cannot be found that matches parameter name 'LogicalName'.
At line:1 char:140
+ ... 00001_6629353.bak' -DatabaseName AxDB_22-03-2022 -LogicalName "<DBN>_ ...
+                                                      ~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Restore-DbaDatabase], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Restore-DbaDatabase

```

### Steps to Reproduce

```powershell
Restore-DbaDatabase -SqlInstance localhost -Path 'path\to\backup.bak' -DatabaseName database -LogicalName "<DBN>_<FT>" -verbose
```

### Are you running the latest release?

Yes

### Other details or mentions

This parameter is mentioned in the [docs](https://docs.dbatools.io/Restore-DbaDatabase) (example 14), as well as in the examples mentioned in the [cmdlet](https://github.com/dataplat/dbatools/blob/324db843ce4bde71959b446150577c6eea4a2c24/functions/Restore-DbaDatabase.ps1#L331) itself... but is nowhere to be found in the actual code.

I would like to rename the logical names of the database upon restoring.. which is exactly what this parameter is for judging by the examples😁.

What's the workaround for this?

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```text
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

```text
Microsoft SQL Server 2016 (SP2-CU15-GDR) (KB4583461) - 13.0.5865.1 (X64)   Oct 31 2020 02:43:57   
Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
```

### .NET Framework Version

```text
.NET Framework 4.8.4410.0
```

**Comment by andreasjordan** [comment]
The parameter `-LogicalName`is part of the command `Rename-DbaDatabase` - as it is written in the docs.

**Comment by smholvoet** [comment]
Ok, sorry for that... it seems like I'm blind 😎

Is there however a way to assign these files a different name _before_ restoring? I'm running into an issue where a previously restored backup conflicts with the new backup:

```powershell
WARNING: [11:41:21][Test-DbaBackupInformation] File G:\MSSQL_DATA\AxDB_new_Primary.mdf already exists on <dbserver> and owned by another database, cannot restore
WARNING: [11:41:21][Test-DbaBackupInformation] File H:\MSSQL_LOGS\AxDB_new_Primary.ldf already exists on <dbserver> and owned by another database, cannot restore
```

**Comment by smholvoet** [comment]
I wrongfully assumed that parameter would change the database name to the original database name which was backupped. So this will replace the naming of the `.mdf` and `.ldf.` files with whatever I specify in the `-DatabaseName`?

**Comment by andreasjordan** [comment]
Yes.
