### ISSUE TITLE
Install-DbaMaintenanceSolution CleanupTime specified without InstallJobs flag

### ISSUE THREAD

**Issue by luke-mckee-ol** [dataplat/dbatools#8254]
In the documentation for [Install-DbaMaintenanceSolution](https://docs.dbatools.io/Install-DbaMaintenanceSolution) a number of the examples specify the CleanupTime parameter but not the InstallJobs parameter. When you run one of those, e.g. `Install-DbaMaintenanceSolution -SqlInstance $instance -Database $db -BackupLocation $location -CleanupTime 72` you receive the warning  `WARNING: [12:10:46][Install-DbaMaintenanceSolution] CleanupTime is only useful when installing jobs. To install jobs, please use '-InstallJobs' in addition to CleanupTime.` 
It won't execute further without the parameter.

I think it's appropriate to just update the examples to include InstallJobs parameter, or maybe don't include CleanUpTime?

**Comment by andreasjordan** [comment]
Thanks for the issue, have opended a PR to address this.
