### ISSUE TITLE
Set-DbaAgentSchedule - No output returned

### ISSUE THREAD

**Issue by lowlydba** [dataplat/dbatools#8256]
### Verified issue does not already exist?

Yes

### What error did you receive?

Command returns no output.

Not sure if it should return all schedules by the schedule name passed in, or only ones that apply to the job(s) passed in with the schedule name.

### Steps to Reproduce

```powershell
New-DbaAgentJob -SqlInstance localhost -Job again
New-DBaAgentSchedule -SqlInstance localhost -Schedule testsched -Job again -Force
$x = Set-DbaAgentSchedule -SqlInstance localhost -Schedule testsched -Job again -Disabled

$x -eq $null
```

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

N/A

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

**Comment by andreasjordan** [comment]
I opened a PR for that.
