### ISSUE TITLE
Service restart warning (or full restart) with Set-DbaNetworkCertificate

### ISSUE THREAD

**Issue by alevyinroc** [dataplat/dbatools#8273]
### Summarize Functionality

When setting a new certificate for network encryption, `Set-DbaNetworkCertificate` should warn the user that the new certificate will not be used until the SQL Server engine service is restarted.

Additional idea/feature - add a `-Restart` switch parameter which will invoke `Restart-DbaService` on the target instance.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

`Write-Warning "New certificate will not take effect until SQL Server services are restarted for $instancename"`

```
if ($Restart) {
    Restart-DbaService -SqlInstance $instancename;
}
```

**Comment by andreasjordan** [comment]
Thanks for the feature request, just opened a PR for that.
