### ISSUE TITLE
Get-DbaKbUpdate not working

### ISSUE THREAD

**Issue by bigbearzhu** [dataplat/dbatools#8275]
### Verified issue does not already exist?

Yes

### What error did you receive?

```
VERBOSE: GET http://www.catalog.update.microsoft.com/Search.aspx?q=KB4577194 with 0-byte payload
VERBOSE: received 45150-byte response of content type text/html; charset=utf-8
VERBOSE: [10:20:15][Get-DbaKbUpdate] 1b006ac2-a397-420b-b4d9-d6b13f053a52
VERBOSE: [10:20:15][Get-DbaKbUpdate] Downloading information for 1b006ac2-a397-420b-b4d9-d6b13f053a52
VERBOSE: POST https://www.catalog.update.microsoft.com/DownloadDialog.aspx with -1-byte payload
VERBOSE: received 37320-byte response of content type text/html; charset=utf-8
VERBOSE: GET
https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=1b006ac2-a397-420b-b4d9-d6b13f053a52 with
0-byte payload
VERBOSE: received 27804-byte response of content type text/html; charset=utf-8
WARNING: [10:20:18][Get-DbaKbUpdate] Failure | You cannot call a method on a null-valued expression.
```

### Steps to Reproduce

try `Get-DbaKbUpdate -Name KB4577194 -Verbose` with latest dbatools, currently 1.1.85.

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.1320                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.1320                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64)   Nov  6 2020 16:50:01   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19043: ) 

### .NET Framework Version

```
PSChildName                      Version        Release
-----------                      -------        -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.04084      528372
Full                             4.8.04084      528372
Client                           4.0.0.0
```

**Comment by andreasjordan** [comment]
There is probably an issue with the webserver - it sometimes works, and sometimes not.

This is my verbose output when it works:
```
VERBOSE: GET http://www.catalog.update.microsoft.com/Search.aspx?q=KB4577194 with 0-byte payload
VERBOSE: received 45150-byte response of content type text/html; charset=utf-8
VERBOSE: [08:57:56][Get-DbaKbUpdate] 1b006ac2-a397-420b-b4d9-d6b13f053a52
VERBOSE: [08:57:56][Get-DbaKbUpdate] Downloading information for 1b006ac2-a397-420b-b4d9-d6b13f053a52
VERBOSE: POST https://www.catalog.update.microsoft.com/DownloadDialog.aspx with -1-byte payload
VERBOSE: received 37320-byte response of content type text/html; charset=utf-8
VERBOSE: GET https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=1b006ac2-a397-420b-b4d9-d6b13f053a52 with 0-byte payload
VERBOSE: received 32285-byte response of content type text/html; charset=utf-8
```

But in any case the output is empty. So maybe the way microsoft provides the information has changed in the last days.

I will have a look...

**Comment by andreasjordan** [comment]
This is how we search for the links:
```
$links = $downloaddialog | Select-String -AllMatches -Pattern "(http[s]?\://download\.windowsupdate\.com\/[^\'\""]*)" | Select-Object -Unique
```

But now the links look like this: https://catalog.s.download.windowsupdate.com/c/msdownload/update/software/updt/2020/10/sqlserver2019-kb4577194-x64_a09e2537b854ae384d965e998e53ce33cdc34f16.exe

Will update the regex...
