### ISSUE TITLE
Test-DbaBuild - Add a switch to exclude on demand builds

### ISSUE THREAD

**Issue by bigbearzhu** [dataplat/dbatools#8276]
### Verified issue does not already exist?

Yes

### What error did you receive?

```
Build          : 13.0.6300
BuildLevel     : 13.0.6300
BuildTarget    : 13.0.6404
Compliant      : False
CULevel        :
CUTarget       :
KBLevel        : 5003279
MatchType      : Exact
MaxBehind      :
NameLevel      : 2016
SPLevel        : SP3
SPTarget       :
SupportedUntil : 14/07/2026 12:00:00 AM
Warning        :
```

### Steps to Reproduce

`Test-DbaBuild -Build 13.0.6300 -Latest`

### Are you running the latest release?

Yes

### Other details or mentions

13.0.6404 ([KB5006943](https://duckduckgo.com/?q=kb5006943)) is an on demand build which not every one need, also it won't have a download link in microsoft update catalog (`Get-DbaKbUpdate` won't work). Do we need list them in the build references? 
If yes, is there any way to filter them out, e.g. only get latest build that is not on demand build?

I have tried to get the build title so that I can check if there is `on demand` in the title but doesn't seem find a way to do that. `Get-DbaBuild` doesn't have extra information about build other than kb level.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

```

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.1320                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.1320                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 



```

### SQL Server Edition and Build number

`Microsoft SQL Server 2019 (RTM-GDR) (KB4583458) - 15.0.2080.9 (X64)   Nov  6 2020 16:50:01   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19043: ) `

### .NET Framework Version

```
PSChildName                      Version        Release
-----------                      -------        -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.04084      528372
Full                             4.8.04084      528372
Client                           4.0.0.0
```

**Comment by andreasjordan** [comment]
@niphlod / @MikeyBronowski - can you have a look at this?

**Comment by niphlod** [comment]
ahum, that kb links https://download.microsoft.com/download/1/7/c/17c5d1d2-726c-4c62-868c-2b1c7f34636e/SQLServer2016-KB5006943-x64.exe so I don't get why is that a problem. One thing is knowing what release/sp/kb level you're on, the other is fetching the aforementioned "setup.exe"

**Comment by andreasjordan** [comment]
This got a bit stale. So let me bring this issue to you attention again...

**Comment by andreasjordan** [comment]
In dbatools-buildref-index.json we currently don't have a flag for "on demand builds". We would have to add that and then change the command to include a switch to filter those out. 

I don't see this as a bug but a feature request, so I will change the label.

**Comment by niphlod** [comment]
I'd say maintaining "what is downloadable" vs "what is not downloadable" is too much of a hassle. IMHO this should be closed as "wontfix".
