### ISSUE TITLE
Get-DbaDbMailServer runs nested loops

### ISSUE THREAD

**Issue by PowerDBAKlaas** [dataplat/dbatools#8278]
### Verified issue does not already exist?

No

### What error did you receive?

No error, just too many objects

### Steps to Reproduce

```powershell
Get-DbaDbMailServer -SqlInstance $sqlcollection
```

### Are you running the latest release?

Yes

### Other details or mentions

I have 8 sql servers in the $sqlcollection, and 9 DBMailAccounts,
and get 72 DBMailServers returned.

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

SQL Server 2014
SQL Server 2016
Azure SQL DB
Azure Managed Instance

### .NET Framework Version

.NET 6.0.3

**Comment by andreasjordan** [comment]
This is by design. If you need a unique list of mail servers accross all the instances, you would have to filter that yourself.

**Comment by PowerDBAKlaas** [comment]
The intended design is to return 9 duplicates of each object?
Why is that?

**Comment by andreasjordan** [comment]
Sorry, I don't have an environment to test that.

To get the mail server for each sql server this code is used: `$mailserver = $server.Mail`. So it looks like this returns 9 objects for each sql server. Is that correct? Can you tell me more about the content of `$server.Mail`. Maybe that helps me to understand the issue.

But we likely need a contributur with a simmilar configuration...

**Comment by PowerDBAKlaas** [comment]
I'm sorry, my description was not clear. I have 9 mail servers in total, not on each sql server.
`$sqlcollection` holds 8 sql servers
```powershel
Get-DbaDBMail $sqlcollection # 9 obj = correct
Get-DbaDBMailAccounts $sqlcollection # 9 obj = correct
Get-DbaDBMail $sqlcollection | Get-DBMailServer # 9 obj = correct
Get-DBMailServer $sqlcollection # 72 obj  = 9x8 duplicates
````
