### ISSUE TITLE
Add DbaToolsConfig Item for  "Trust certificate"  to use when  psremoting.pssession.usessl' -Value $true  or add addition parameter to psremoting.pssession.usessl to enable Trust Cert

### ISSUE THREAD

**Issue by mganci350** [dataplat/dbatools#8281]
### Summarize Functionality

Requesting new Feature:
This behavior is observed on dbatools  V 1.1.75    
Remote Connections Failing due to The SSL certificate is signed by an unknown certificate authority. 
Need a parameter to enable "TrustCerticate"  (found in Connect-DbaInstance) or  -SkipCACheck  for Remote Server Connections
Example:
When using  Update-DbaInstance  against a remote Server with only WinRM HTTPS an error message occurs:
_[Update-DbaInstance] Error while looking for SQL Server installations on Server1 | Connecting to remote server Server1
 failed with the following error message : WinRM cannot complete the operation._
The remote connection is trying to use non SSL connection to server that only accepts SSL.
The correct thing to do is to set the following:
_Set-DbaToolsConfig -Name 'psremoting.pssession.usessl' -Value $true_

The connection now uses SSL but now we face a different issue:
_WARNING: [13:52:40][Update-DbaInstance] Error while looking for SQL Server installations on Server1 | Connecting to remote server Server1 failed with th
e following error message : The server certificate on the destination computer (Server1:5986) has the following errors:    
The SSL certificate is signed by an unknown certificate authority. For more information, see the about_Remote_Troubleshooting Help topic._

The Remote server is using a self signed certificate and must be trusted.

In our connection we need the ability to set "Trust Certificate" or  -SkipCACheck whether its a new item for Set-DbaToolsConfig 'psremoting.pssession'  or an additional parameter for  'psremoting.pssession.usessl'

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

The following example uses  -TrustServerCertificate when EncryptConnection is invoked to connect to SQL Instance.

$server = Connect-DbaInstance -SqlInstance SQL123\SQL_123 -EncryptConnection  -TrustServerCertificate
Restore-DbaDatabase   -SqlInstance $server   -Path "\\network\share" -WithReplace

Connections to Hosts do not seem to have that option.
It seem you can enable encryption but not trust certificate.
Set-DbaToolsConfig -Name 'psremoting.pssession.usessl' -Value $true

**Comment by potatoqualitee** [comment]
🤔  @ClaudioESSilva can you please take a look? btw @mganci350 you can also set the cert trust for all sql connections in option in lieu of using the param

**Comment by ClaudioESSilva** [comment]
Yes, I will take a look and come back here 😊

**Comment by ClaudioESSilva** [comment]
Hi @mganci350 ,

> Connections to Hosts do not seem to have that option.

They have, when using the `New-PSSessionOption` we already have it for the `-IncludePortInSPN` parameter.

I have added support for 
``` powershell
-SkipCACheck
-SkipCNCheck
-SkipRevocationCheck
```

The full configuration names are:
``` powershell
'PSRemoting.PsSessionOption.SkipCACheck'
'PSRemoting.PsSessionOption.SkipCNCheck'
'PSRemoting.PsSessionOption.SkipRevocationCheck'
```

The default is `$false` but you can change it using `Set-DbaToolsConfig`

Can you please test it using the https://github.com/dataplat/dbatools/tree/TrustCert_SkipCheck branch?

I have submitted PR #8336

**Comment by potatoqualitee** [comment]
Thanks again for this claudio 🙇🏼

**Comment by andreasjordan** [comment]
Currently testing this in Azure using Install-DbaInstance - and we need some more changes...

Found so far:
* Invoke-DbaAdvancedInstall: The session opend to copy the ConfigFile needs these as well (maybe a new internal command just to open a session and use it for Invoke-Command2 as well?)
* Test-PSRemoting: This command uses Test-WSMan, but Test-WSMan has no option to use these options, to as a fallback, the test has to use Invoke-Command2.

**Comment by andreasjordan** [comment]
Next problem:
* Restart-Computer does not work, because testing for WinRM failes: "Fail to retrieve its LastBootUpTime via the WMI service with 
the following error message: WinRM cannot complete the operation..."

I don't see an easy solution here...
