### ISSUE TITLE
Start-DbaDbEncryption cmdlet NOT FOUND

### ISSUE THREAD

**Issue by sbsmool** [dataplat/dbatools#8285]
My dbatools version is 1.1.84. I could not find the cmdlet Start-DbaDbEncryption to encrypt database as mentioned in documentation. Even the online book has an example with this cmdlet, but however, when I type "Start-Dba", I only see the cmdlet options as shown in the screenshot below. When can this feature be expected to be working again?

![image](https://user-images.githubusercontent.com/69294166/161640864-b1b1c160-9683-48a2-bfce-be988d423e96.png)

**Comment by potatoqualitee** [comment]
That looks like you're using the ISE, which I don't know much about. You may need to `Import-Module dbatools` to get that working. There are a number of Start-Dba commands that should show up.

![image](https://user-images.githubusercontent.com/8278033/161693961-bb8a25ca-a986-470e-842a-1e7806860e3f.png)

**Comment by sbsmool** [comment]
Does it make a difference if it just PowerShell or PowerShell ISE? I used Import-Module dbatools and also updated dbatools to its latest version.

Let me try this on PowerShell only.

Thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sbsmool** [comment]
Here is what I get in PowerShell after updating to latest version.

[X]


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sbsmool** [comment]
Here is the screenshot
[X]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sbsmool** [comment]
I sent it again, but seems like copy/paste didn't work. I have attached with this email.[Image.jpeg]

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wsmelton** [comment]
Please provide the image this issue via GitHub's site (we don't use email).
