### ISSUE TITLE
Invoke-DbaQuery adds spurious newlines when running query consisting of multiple batches

### ISSUE THREAD

**Issue by Tisit** [dataplat/dbatools#8287]
### Verified issue does not already exist?

Yes

### What error did you receive?

Run script:
```
$Query = "
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROC RegexTest AS
SELECT 1
"

Invoke-DbaQuery -Query $Query -Database YourDatabase -SqlInstance .
```

Next try to script out this procedure for SSMS. You will get a warning that line endings are inconsistent.
Additionally there is an empty line between GO and CREATE now. This newline won't appear, if I run the SQL in SSMS directly.

### Steps to Reproduce

See What error did you receive

### Are you running the latest release?

Yes

### Other details or mentions

It seems the problem lies in code splitting batches in Invoke-DbaAsync function. Extracting only the relevant parts:

```
$Query = "
SET QUOTED_IDENTIFIER ON
GO
CREATE OR ALTER PROC RegexTest AS
SELECT 1
"

$GoSplitterRegex = [regex]'(?smi)^[\s]*GO[\s]*$'

$Pieces = $GoSplitterRegex.Split($Query)

$Pieces | Format-Hex
```
I can see the query was split so that there is \n just before CREATE, which to me is unexpected

>            00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
> 
> 00000000   0D 0A 53 45 54 20 51 55 4F 54 45 44 5F 49 44 45  ..SET QUOTED_IDE
> 00000010   4E 54 49 46 49 45 52 20 4F 4E 0D 0A              NTIFIER ON..    
> 
> 
>            00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
> 
> 00000000   0A 43 52 45 41 54 45 20 4F 52 20 41 4C 54 45 52  .CREATE OR ALTER
> 00000010   20 50 52 4F 43 20 52 65 67 65 78 54 65 73 74 20   PROC RegexTest 
> 00000020   41 53 0D 0A 53 45 4C 45 43 54 20 31 0D 0A        AS..SELECT 1..  

Replacing $ in regex with \r\n fixes the problem for me. But I'm not sure this would be the right fix.

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.1320                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.1320                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU14) (KB5007182) - 15.0.4188.2 (X64)   Nov  3 2021 19:19:51   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19044: ) 

### .NET Framework Version

Cannot run command to check .NET version

**Comment by niphlod** [comment]
that wouldn't work in some cases. 
Requiring that Invoke-DbaQuery honours batch separators AND doesn't change the literal string imho is kinda of an outreach, also, if you want character-by-character idempotency, just use $database.Query(yourstatements).
Once again, Invoke-DbaQuery is for running queries, not complex statements. It's working on a completely different interface and is NOT a replacement for SQLCMD, but it has the great feature that is nowhere else in SMO's and in SQLCMD, which is the ability to work with parameters.

**Comment by Tisit** [comment]
I mean, sure I can use alternatives to workaround this issue. But from position of an end user I wouldn't expect such behavior.

**Comment by niphlod** [comment]
It's not strictly about alternatives, it's just the wrong tool for the job ^_^ . 
We tried to signal its intended usecase renaming it from Invoke-SqlCmd2 to something more apt, but, again, this is "yet another cornercase scenario", which is "Using it to create procedures ". 
Invoke-DbaQuery has another intended purpose and covers a lot of things SMO doesn't. 
If we can find a better regex then fine, just don't expect Invoke-DbaQuery to enforce char-by-char exactness, cause its ultimate goal is to be usable and functional for a total different endgoal, which is:
- running queries
- with parameters
- fast
- optionally converting data to PS objects in the most straightforward way

**Comment by andreasjordan** [comment]
So I will close this for now - but you can reopen the issue if needed.
