### ISSUE TITLE
Could Copy-DbaAgentJob include the ability to alter the @schedule_uid or @job_id to be unique?

### ISSUE THREAD

**Issue by arsqldba** [dataplat/dbatools#8290]
### Summarize Functionality

While it's not an issue if the same job has the same @schedule_uid or @job_id and it's on different servers, when rolling up reporting it's often nice to have those be unique in some cases.

This may not even be possible, but I thought I'd present the topic to see.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

I'm not sure it's possible. Maybe it ties in to adding a Job_id or schedule_uid to Set-DbaAgentSchedule and require that to be used after Copy-DbaAgentJob.

**Comment by niphlod** [comment]
dunno perfectly the internals of this specific command but the verb `Copy-` "dictates" that what's in the source ends up untouched on the dest. If the requirement is altering the entity before it gets pushed to the dest, then it's definitely not a job for `Copy-` but for a `Get-` then `Set-`

**Comment by andreasjordan** [comment]
I agree with @niphlod - so can we close this issue?

**Comment by andreasjordan** [comment]
I am closing this issue now, but can reopen if there is still the need to discuss this.
