### ISSUE TITLE
Cmdlet not found

### ISSUE THREAD

**Issue by sbsmool** [dataplat/dbatools#8293]
I couldn't find cmdlet for database encryption : Start-DbaDbEncryption. I have updated dbatools to the latest version.

We are in the process of encrypting databases and this cmdlet would be very helpful. Even online book has example on it, but I am struggling to find this function.

![8ABA1DEE-7514-452E-A16D-CE7B99BDADC3](https://user-images.githubusercontent.com/69294166/162111750-11c4d4b8-48be-4ee1-aeda-1da5db78ee60.png)

Attached is the screenshot.

**Comment by potatoqualitee** [comment]
Hey Sbs,
Thank you for the screenshot. This part can be confusing (tho I hear future version of .NET may help) -- you still have the older version of dbatools in memory. 

![image](https://user-images.githubusercontent.com/8278033/162137943-bed28dc7-381c-437e-aa5a-bab01f8e1c43.png)

While you can often use `Import-Module dbatools -Force` to import the latest version, this this case, we changed some DLLs later on i think, so I recommend closing and opening your PowerShell window.
