### ISSUE TITLE
Running build.ps1 shows that HelpOut is missing

### ISSUE THREAD

**Issue by nohwnd** [dataplat/dbatools#8296]
### Verified issue does not already exist?

Yes

### What error did you receive?

![image](https://user-images.githubusercontent.com/5735905/162590427-573b2815-9c57-4ef3-9086-da8b9f7cd1ca.png)

### Steps to Reproduce

```powershell
.\build.ps1
```

### Other details or mentions

I just cloned your repo and run .\build.ps1 and HelpOut is missing for the build. It should probably obtain it and use it when not present. Not a big issue, I just installed it myself.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Microsoft Windows 10.0.22593
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

none.

### .NET Framework Version

I am on windows11, so I have 4.8. But I am using powershell7, so .NET5

**Comment by nohwnd** [comment]
I spoke too soon, I installed it and I see this now: 

![image](https://user-images.githubusercontent.com/5735905/162590565-8871414b-ccd0-4735-94d9-f252cc513e83.png)
 
 
 Still seems to build fine. I can work with that.

**Comment by niphlod** [comment]
@nohwnd : build.ps1 is not meant to be run by anyone if not @potatoqualitee doing a release. There's nothing to build to use dbatools.

**Comment by potatoqualitee** [comment]
Oh yeah, I don't use that. We can probably delete it.

This is what I use to "build" 

https://github.com/potatoqualitee/releases/actions/workflows/dbatools.yml

As far as the dbatools.dll goes, I build that using Visual Studio 😬

**Comment by nohwnd** [comment]
Ah okay, using restore, build, and test scripts (or subset of that) in root is rather common way to give people way to do those basic tasks. I probably should have checked out contribution guide first.
