### ISSUE TITLE
Get-DbaDBMailConfig runs nested loops

### ISSUE THREAD

**Issue by PowerDBAKlaas** [dataplat/dbatools#8298]
### Verified issue does not already exist?

No

### What error did you receive?

no error, just too many objects

probably same issue as in Get-DbaDBMailServer:
Get-DbaDbMailServer runs nested loops #8278 

@andreasjordan 

### Steps to Reproduce

```powershell
# $ConnectedSQLs holds 8 sql instances
Get-DbaDbMail -SqlInstance $ConnectedSQLs | Get-DbaDbMailConfig # 40 rows
Get-DbaDbMailConfig -SqlInstance $ConnectedSQLs # 240 rows
```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Azure (RTM) - 12.0.2000.8 
	Feb 25 2022 16:04:35 
	Copyright (C) 2021 Microsoft Corporation

### .NET Framework Version

.NET 6.0.3

**Comment by andreasjordan** [comment]
Thanks for the report and sorry for the delay. Fix is on its way...

**Comment by PowerDBAKlaas** [comment]
Thank you, @andreasjordan 
don't apologize, you're making a huge difference! We're glad and thankful for the massive contribution.
