### ISSUE TITLE
Get-DbaBackupInformation - Sizes are incorrectly summed

### ISSUE THREAD

**Issue by lowlydba** [dataplat/dbatools#8302]
### Verified issue does not already exist?

Yes

### What error did you receive?

Incorrect size results from the command. For a striped full backup, it looks like it is summing the compressed/backup size for all files when each file contains the proper value for the group:

https://github.com/dataplat/dbatools/blob/05b91475db7db2b25a49bc1b4b54e3af9b7a45fc/functions/Get-DbaBackupInformation.ps1#L326-L327

So you end up with size values that are multiplied by the number of striped files.

### Steps to Reproduce

```powershell
$stripedPath = 'your-path-to-all-full-striped-backups'
$singleStripedFilePath = 'your-path-to-a-striped-full-backup-file'
$result = Get-DbaBackupInformation -Path $stripedPath
$result2 = Get-DbaBackupInformation -Path $singleStripedFilePath

# Returns values that are size * num striped files
$result.TotalSize 
$result.CompressedBackupSize

# returns correct values for the entire striped backup
$result2.TotalSize
$result2.CompressedBackupSize
```

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

N/A

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

**Comment by andreasjordan** [comment]
I think we can only get the size from the first file and have opened a PR for that. Or am I overlooking something?

**Comment by lowlydba** [comment]
Yeah that should work as an approach! 👍🏻
