### ISSUE TITLE
An attempt was made to load a program with an incorrect format. (0x8007000B)

### ISSUE THREAD

**Issue by drounsville** [dataplat/dbatools#8306]
### Verified issue does not already exist?

Yes

### What error did you receive?

2022-04-14T16:33:26.908 [Warning] WARNING: [16:33:26][Connect-DbaInstance] Failure | Error connecting to [<ServerFQDN]: An attempt was made to load a program with an incorrect format. (0x8007000B)
2022-04-14T16:33:27.160 [Warning] WARNING: [16:33:26][Get-DbaDatabase] Failure | An attempt was made to load a program with an incorrect format. (0x8007000B)

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
# Connect to the database servers
$SourceInstance = '<FQDN of Instance>' # PROD Database

$pSqlPw = convertto-securestring $ProdSQLPw -asplaintext -force  #Password is pulled from keyvault and confirmed to be accurate
$pscred = new-object system.management.automation.pscredential -argumentlist ($sqlUser, $pSQLPw) #$sqlUser is the SQL login to access the database.  The username and password are confirmed to work in SSMS to login to the instance.

#running the following commandlet alone fails with the first half of the reported error
$dbconnet = connect-dbainstance -sqlinstance $SourceInstance -slqcredentials $pscred
#running the following command alone fails with the full reported error. 
$dbList = get-dbadatabase -sqlinstance $SourceInstance

### Are you running the latest release?

Yes

### Other details or mentions

I am writing an Azure function app to do our SQL backups in parallel. The function app is running in PowerShell 7 runtime, and I had this function working 6 months ago (around version 1.1.29) in a test environment. Since confirming that the function app worked, I have deleted the test environment.
I have confirmed that the function has network path access to the SQL instance through TCPPING.
From my research, this is due to trying to load a 32-bit DLL in a 64-bit environment.
Any ideas what might be going on here?
Thank you.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

7.0

### SQL Server Edition and Build number

SQL Server 2016 running on Windows Server 2016 Enterprise on an Azure VM

### .NET Framework Version

~4 (current)

**Comment by wsmelton** [comment]
Did anything change other than the version of dbatools you are using in your Function?

If you can share the base project for the function deployment so that we can attempt replication in our Azure tenant? (Azure Function plan/tier being used, settings files, etc.)

**Comment by drounsville** [comment]
Hi, Shawn.
Thanks for the follow up, but you can go ahead and close the issue.

This one was on me...  When I set up the function app, I didn't notice that I had set it up as 32-bit.  I guess my test environment was 64-bit.  I changed the current one to 64-bit, and was able to successfully connect to the database and list the databases.

I love the DBATools tool set, and am happy that it wasn't an issue with the module after all.

Drew Rounsville | Cloud Ops Engineer
(m) 360.471.4967
***@***.***

**Comment by wsmelton** [comment]
I wonder if we can put in a check on import to detect what architecture the module was loaded into? I'm not sure how clean it would be but recall this is detail in a system variable somewhere. If we detect it is not x64 just spit out a warning about "not all things are as you believe" or something.

// @potatoqualitee @andreasjordan

**Comment by potatoqualitee** [comment]
mmm there are a number of arches that are supported, including arm. when i saw this title, i knew it'd be an arch problem. we can just address it in future issues, i think
