### ISSUE TITLE
rename-dbalogin fails to rename dbusers 

### ISSUE THREAD

**Issue by richardimenes** [dataplat/dbatools#8310]
### Verified issue does not already exist?

Yes

### What error did you receive?

PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: Cannot index into a null array.
                           at CallSite.Target(Closure , CallSite , Object , String )
                           at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
                           at System.Management.Automation.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          : 
CategoryInfo          : InvalidOperation: (:) [], RuntimeException
FullyQualifiedErrorId : NullArray
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Rename-DbaLogin<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.88\allcommands.ps1: line 66452
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

### Steps to Reproduce

1. The login Testuseer123 can be a AD-account or group or even just an SQL Login that you want to rename. It must have a related user in a database. *Renaming SQL Logins that only has server level access rights does not cause an issue.*
2. Rename the SQL Login and database user by running the Rename-DbaLogin command with the -Force parameter: 
```powershell
Rename-DbaLogin -SqlInstance InstanceName -Login Testuseer123 -NewLogin Testuser -Force
```
3. If the SQL Login has database users, the function will rename the SQL Login, but it will fail unable to rename any database users. 

### Are you running the latest release?

Yes

### Other details or mentions

I did test this on a few servers, to make sure it was not related to privileges, or missing .net version. 

I am a novice at Powershell, but it seems to me that the statement
```powershell
$db = $databases[$db.DBName]
```
might not compare the correct values, and thus not populating the *$db* array as expected. 

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

| Name       |                    Value |
| ----           |                -----   |
| PSVersion  |                    5.1.17763.2268  |
| PSEdition   |                   Desktop  |
| PSCompatibleVersions |          {1.0, 2.0, 3.0, 4.0...} |
| BuildVersion                 |  10.0.17763.2268 |
| CLRVersion                   |  4.0.30319.42000 |
| WSManStackVersion    |          3.0 |
| PSRemotingProtocolVersion |     2.3 |
| SerializationVersion         |  1.1.0.1 | 

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64)   Jan 12 2022 22:30:08   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 

### .NET Framework Version

CBS           : 1
Install       : 1
InstallPath   : C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
Release       : 528049
Servicing     : 0
TargetVersion : 4.0.0
Version       : 4.8.03761
PSPath        : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full
PSParentPath  : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4
PSChildName   : Full
PSDrive       : HKLM
PSProvider    : Microsoft.PowerShell.Core\Registry

**Comment by ben-thul** [comment]
> I am a novice at Powershell, but it seems to me that the statement
> 
> `$db = $databases[$db.DBName]`
> 
> might not compare the correct values, and thus not populating the $db array as expected.

Does it work for you if you change that line to `$db = $databases | where-object Name -eq $db.DBName;`?

**Comment by richardimenes** [comment]
It seems like that resolves the issue and that the compare is done correctly. The database users are now renamed correctly.

**Comment by ben-thul** [comment]
Congrats! If you're comfortable doing it, I'd submit a pull request that references this issue.

**Comment by richardimenes** [comment]
Not entirely comfortable, but there is a lot of good documentation here and I want to learn this process, so let me give it a shot. :)

**Comment by potatoqualitee** [comment]
My pleasure. My apologies for the steamroll -- I was going to give it more time but I have a rare burst of energy and wanted to take advantage.

I personally use GitHub Desktop, you may like it too https://desktop.github.com. What I like about it is that it allows you to ease into fully understanding the whole process by making it visual.
