### ISSUE TITLE
No data in output file after Restore-DBADatabase with invoke-command using New-PSSession 

### ISSUE THREAD

**Issue by Memoi** [dataplat/dbatools#8315]
### Verified issue does not already exist?

No

### What error did you receive?

Hello,

I execute a scriptblock inside an invoke-command with the session parameter to another server (SQL).

The scriptblock do a write-information / warning / host just before the restore command and the output are displayed in the console and go in the log file (start-Transcript) then after the restore command every write-information / warning / host are still displayed in the console but the **[console]::ForegroundColor is not working** and there is **nothing in the log file**. 

When I'm out of this invoke-command everything from the rest of the script go in the log file and color is working well.

If I remove the session parameter to execute the scriptblock localy everything is working well.

Thanks for your help

### Steps to Reproduce

```powershell
Start-Transcript
$cred = get-Credential -Credential "Domain\Account"
$session = New-PSSession -Computername "HostA" -Credential $cred -Authentication Credssp

[ScriptBlock] $Restore =
{
[console]::ForegroundColor = "Cyan"
Write-Host "Test"
Write-Warning "Test2"
Write-Information "Test3"

Restore-DbaDatabase -SQLInstance "Instance" -Path "Path" -WithReplace

Write-Host "Test4"
Write-Warning "Test5"
Write-Information "Test6"
[console]::ResetColor()
}
Invoke-Command -ScriptBlock $Restore -Session $session

Stop-Transcript
```
### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

PS : 5.1.17763.2268

### SQL Server Edition and Build number

Enterprise 15.0.4102.2

### .NET Framework Version

4.7.2

**Comment by potatoqualitee** [comment]
hey @Memoi - perhaps you're encountering an error that you can't see on your side.

This works for me:

![image](https://user-images.githubusercontent.com/8278033/165927046-5c89bb65-9871-4340-9a1d-9b4939a3bcac.png)

Throw an `| Out-String` or `| Out-Host` at the end of your restore command to see if a warning is getting gobbled up.

```
$session = New-PSSession -Computername sql01 -Credential $cred

[ScriptBlock]$Restore =
{
    [console]::ForegroundColor = "Cyan"
    Write-Host "Test"
    Write-Warning "Test2"
    Write-Information "Test3"

    Restore-DbaDatabase -SqlInstance sqlcluster -Path "\\san\sql\backups\sqlcs\testdev\FULL\sqlcs_testdev_FULL_20220111_115203.bak" -WithReplace

    Write-Host "Test4"
    Write-Warning "Test5"
    Write-Information "Test6"
    [console]::ResetColor()
}
Invoke-Command -ScriptBlock $Restore -Session $session
```

Granted, I'm not using CredSSP. 

Does this work for you?

```
$session = New-PSSession -Computername sql01 -Credential $cred

[ScriptBlock]$Restore =
{
    [console]::ForegroundColor = "Cyan"
    Write-Host "Test"
    Write-Warning "Test2"
    Write-Information "Test3"

    [pscustomobject]@{
        Name  = "Test"
        Other = "Test"
    }

    Write-Host "Test4"
    Write-Warning "Test5"
    Write-Information "Test6"
    [console]::ResetColor()
}
Invoke-Command -ScriptBlock $Restore -Session $session

Stop-Transcript
```

gonna close as this works on our side but please feel free to keep commenting with updates.
