### ISSUE TITLE
New-DbaDbMaskingConfig: Table name not included in filename when using -Table parameter

### ISSUE THREAD

**Issue by imaginetobe** [dataplat/dbatools#8316]
### Verified issue does not already exist?

Yes

### What error did you receive?

The parameter help for Path indicates that the table name should be appended to the filename if Table parameter is used

https://github.com/dataplat/dbatools/blob/41eccc4d9cf9f80bef680df4e1cb1677a4742e42/functions/New-DbaDbMaskingConfig.ps1#L41-L43

but the function code doesn't seems to include this

https://github.com/dataplat/dbatools/blob/41eccc4d9cf9f80bef680df4e1cb1677a4742e42/functions/New-DbaDbMaskingConfig.ps1#L608

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference

New-DbaDbDataMaskConfig -SqlInstance  mySql -Database myDb -Table myTable -Path .\configFiles

```
Shouldn't this create a file named mySql.myDb.myTable.DataMaskingConfig.json ?

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

PSVersion                      7.2.2
PSEdition                      Core
GitCommitId                    7.2.2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP3) (KB5003279) - 13.0.6300.2 (X64) 	Aug  7 2021 01:20:37 	Copyright (c) Microsoft Corporation	Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

### .NET Framework Version

.NET 6.0.3

**Comment by potatoqualitee** [comment]
thank you, @imaginetobe - @sanderstad can you take a look?

**Comment by potatoqualitee** [comment]
actually this seems easy, ill derrr it
