### ISSUE TITLE
Repair-DbaDbOrphanUser to accept piping from Get-DbaRegServer

### ISSUE THREAD

**Issue by tboggiano** [dataplat/dbatools#8327]
### Summarize Command's Functionality

I tried to do this:

Get-DbaRegServer -SQLInstance CMSServerName |  Repair-DbaDbOrphanUser -RemoveNotExisting

and it does nothing, I figured it would take all my instances from my CMS server and fix my orphaned users for my CIS audit yet I had to write a ForEach like below to accomplish this, maybe this is a bug, but since I didn't get an error, I but it as a feature.

$instances = Get-DbaRegServer -SQLInstance CMSServerName
ForEach ($instance in $instances) {
    Repair-DbaDbOrphanUser -SQLInstance $instance -RemoveNotExisting | Format-Table
}

### Is there a command that is similiar or close to what you are looking for?

No

**Comment by andreasjordan** [comment]
Sorry to say: It works on my maschine.

**Comment by tboggiano** [comment]
That is sad, you can close issue if my code I gave above is correct and I'll try to figure out what mine is doing.
