### ISSUE TITLE
Get-DbaInstanceProperty - Error Writing to a Database Table

### ISSUE THREAD

**Issue by MrRichWray** [dataplat/dbatools#8329]
### Verified issue does not already exist?

No

### What error did you receive?

WARNING: [12:42:01][ConvertTo-DbaDataTable] Failed to add property Value from @{ComputerName=RWRAYPC; InstanceName=V19DEV01; SqlInstance=RWRAYPC\V19DEV01; PropertyType=Setting; Name=DefaultFile; Value=D:\V19DEV01\MSSQL15.V19DEV01\MSSQL\DATA\; Type=string; Writable=True; Readable=True; Expensive=False; Dirty=False; Retrieved=True; IsNull=False; Enabled=False; Required=False; Attributes=System.ComponentModel.AttributeCollection; Value2=Value; LoadDate=2022-04-29 12:42:01; LoadedBy=brawt} | Input string was not in a correct format.
WARNING: [12:42:01][ConvertTo-DbaDataTable] Failed to add property Value from @{ComputerName=RWRAYPC; InstanceName=V19DEV01; SqlInstance=RWRAYPC\V19DEV01; PropertyType=Setting; Name=DefaultLog; Value=D:\V19DEV01\MSSQL15.V19DEV01\MSSQL\DATA\; Type=string; Writable=True; Readable=True; Expensive=False; Dirty=False; Retrieved=True; IsNull=False; Enabled=False; Required=False; Attributes=System.ComponentModel.AttributeCollection; Value2=Value; LoadDate=2022-04-29 12:42:01; LoadedBy=brawt} | Input string was not in a correct format.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Get-DbaInstanceProperty -SqlInstance $SqlServer | Select-Object * | Write-DbaDataTable @ParamsWriteToDB

When writing to the database table, I have autocreate on.

The issue is that the table is created with the Value column being of type INT but the Get-DbaInstanceProperty also returns strings in the Value column.  Therefore we get an error when we try to write string values to anint column.

### Are you running the latest release?

Yes

### Other details or mentions

N/A

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

[32;1mName                           Value[0m
[32;1m----                           -----[0m
PSVersion                      7.2.3
PSEdition                      Core
GitCommitId                    7.2.3
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU10) (KB5001090) - 15.0.4123.1 (X64) 
	Mar 22 2021 18:10:24 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19044: ) (Hypervisor)

### .NET Framework Version

.NET 6.0.4

**Comment by andreasjordan** [comment]
The parameter `-AutoCreateTable` uses the first row to "guess" the data types. So in your case you have to create the table yourself with the suitable data types.

**Comment by MrRichWray** [comment]
Still didn't work.

**Comment by andreasjordan** [comment]
What error message did you receive this time? Can you share the CREATE TABLE?

**Comment by MrRichWray** [comment]
CREATE TABLE dbo.DbaTools_InstanceProperty (
               ComputerName VARCHAR(128) NULL,
               SqlInstance VARCHAR(128) NULL,
               PropertyType VARCHAR(64) NULL,
               PropertyName SYSNAME NULL,
               [Value] VARCHAR(1024)NULL,
               [LoadDate] [datetime] NOT NULL,
               [LoadedBy] [varchar](64) NOT NULL
);
GO

ALTER TABLE dbo.DbaTools_InstanceProperty
               ADD  CONSTRAINT [DF_InstanceProperty_LoadDate]  DEFAULT (getdate()) FOR [LoadDate]
GO

ALTER TABLE dbo.DbaTools_InstanceProperty
               ADD  CONSTRAINT [DF_InstanceProperty_LoadedBy]  DEFAULT (suser_name()) FOR [LoadedBy]
GO

***@***.***


$ParamsSelectObject =@{
    Property =  "ComputerName",
                "SqlInstance",
                "PropertyType",
                @{ Name = "PropertyName"; Expression = "Name" },
                "Value",
                #@{ Name = "PropertyValue"; Expression = {Value} },
                @{ Name = "LoadDate";  Expression = {Get-Date -Format "yyyy-MM-dd HH:mm:ss"}},
                @{ Name = "LoadedBy"; Expression = {"$Env:UserName"} }
}

# Enumerate
Write-Output "Enumerating:"
foreach($SqlServer in $SqlInstances)
{
    Write-Output "$($SqlServer)"
    Get-DbaInstanceProperty -SqlInstance $SqlServer | Select-Object @ParamsSelectObject | Write-DbaDataTable @ParamsWriteToDB
}


AutoCreateTable is off.
Only numeric values load in the database table.
For other data types, it is NULL.

***@***.***


Richard Wray
SQL Server/Azure Cloud Database Administrator

**Comment by andreasjordan** [comment]
You have to cast the value to a string before using `Write-DbaDataTable`.

Use `@{ Name = "Value"; Expression = { [string]$_.Value } }` inside of `$ParamsSelectObject`.

Then it works on my lab.

**Comment by MrRichWray** [comment]
Thank you!

I tried this earlier but my cast syntax was incorrect.

Thank you thank you!
This was a very big deal for us.


Richard Wray
SQL Server/Azure Cloud Database Administrator
