### ISSUE TITLE
Set-DbaAgentSchedule: Update FrequencySubdayType options

### ISSUE THREAD

**Issue by lowlydba** [dataplat/dbatools#8349]
### Verified issue does not already exist?

Yes

### What error did you receive?

It looks like the parameter validation updates from https://github.com/dataplat/dbatools/issues/6636 / https://github.com/dataplat/dbatools/pull/6872 never made it into Set-DbaAgentSchedule, so it still doesn't accept some of the values output by Get-DbaAgentSchedule.

### Are you running the latest release?

Yes

**Comment by ClaudioESSilva** [comment]
Hi @lowlydba thanks for reporting it!

I will submit a fix 😃
