### ISSUE TITLE
Connect-DbaInstance with universal MFA using a user@domain login not working

### ISSUE THREAD

**Issue by jakub-auger** [dataplat/dbatools#8371]
### Verified issue does not already exist?

No

### What error did you receive?

Error connecting to [xxxxxxxxx-ondemand.sql.azuresynapse.net]: Windows logins are not supported in
this version of SQL Server.

### Steps to Reproduce

set up an azure db (eg synapse serverless) using AAD interactive as the authentication type
the docs say to use Connect-DbaInstance when using AD with universal MFA but it doesn't work
the -AuthenticationType flag that's mentioned in this dbatools 1.0 release notes no longer exists https://dbatools.io/dbatools10/

Connect-DbaInstance -SqlInstance xxxxxxxx-ondemand.sql.azuresynapse.net -Database xxxxx
Connect-DbaInstance -SqlInstance xxxxxxxx-ondemand.sql.azuresynapse.net -Database xxxxx -sqlCredential user@domain

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.22000.653                                                                           
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.22000.653                                                                          
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Azure (RTM) - 12.0.2000.8   May 11 2022 08:03:52   Copyright (C) 2022 Microsoft Corporation 

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.8.04161
Full        4.8.04161
Client      4.0.0.0

**Comment by andreasjordan** [comment]
Is this still an issue? The error says "Windows logins are not supported in this version of SQL Server". So you have to use `-SqlCredential` with a SQL Login.

**Comment by jakub-auger** [comment]
yes, still an issue

win auth with mfa universal is supported by the server because i can connect using that auth type via ssms, powerbi, ssis

dbatools doesn't seem to support it

**Comment by andreasjordan** [comment]
Thanks for the response.

First of all: dbatools is not a replacement for SSMS, so if something works with SSMS and does not work with dbatools, that is not always a bug but can also be a feature request.

Can you please show me where "the docs say to use Connect-DbaInstance when using AD with universal MFA"?

And maybe our test for Azure does not work here because of the different URL for Synapse. Try using `-AzureDomain sql.azuresynapse.net` and see if that helps.

**Comment by jakub-auger** [comment]
Hi @andreasjordan 

https://dbatools.io/dbatools10/

under the authentication support heading where it says it now supports all methods of authentication to sql server and it has a screenshot of ssms with the AD - with universal MFA selected (the method that I cant get working)

**Comment by andreasjordan** [comment]
Hi @potatoqualitee , can you have a look at that https://dbatools.io/dbatools10/ and see if there are parts that need to be changed?

Hi @jakub-auger , there were a lot of changes from 1.0 to 1.1 - so that is kind of an old documentation not related to the current version.

**Comment by potatoqualitee** [comment]
Yeah I think we had to remove those DLLs because of a VS Code issue. I got them to work in a sketchy way, anyway. This will be investigated prior to 2.0

**Comment by wsmelton** [comment]
The functionality is in place, and currently works, for connection to Azure SQL DB and MI services. While SMO states support of the Azure Synapse Analytics, I have not seen any indication it supports connecting to the workspace for Synapse but only the SQL DB itself. (Azure Synapse is the old Azure SQL DW service renamed/rebranded.) You can connect to the database behind the Synapse workspace by using the FQDN of the Azure SQL DB logical server.

@jakub-auger You can connect using the latest release (1.1.143) to an Azure SQL DB by passing in your credential for the tenant and use the FQDN for the Azure SQL DB logical server.
