### ISSUE TITLE
Pathing issue when using DBAtools from Ubuntu

### ISSUE THREAD

**Issue by robison-scott** [dataplat/dbatools#8373]
### Verified issue does not already exist?

No

### What error did you receive?

I have redacted the domain, but here is the debug output

DEBUG: [14:29:13][Connect-DbaInstance] Starting process block
DEBUG: [14:29:13][Connect-DbaInstance] Immediately checking for Azure
DEBUG: [14:29:13][Test-Azure] Test for Azure is negative
DEBUG: [14:29:13][Connect-DbaInstance] Starting loop for 'S02.DOMAIN.LOCAL\S02': ComputerName = 'S02.DOMAIN.LOCAL', InstanceName = 'S02', IsLocalHost = 'False', Type = 'Default'
DEBUG: [14:29:13][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
DEBUG: [14:29:13][Test-Azure] Test for Azure is negative
DEBUG: [14:29:13][Connect-DbaInstance] authentication method is 'local sql'
DEBUG: [14:29:13][Connect-DbaInstance] ApplicationName will be set to 'dbatools PowerShell module - dbatools.io'
DEBUG: [14:29:13][Connect-DbaInstance] ConnectionTimeout will be set to '15'
DEBUG: [14:29:13][Connect-DbaInstance] Database will be set to 'master'
DEBUG: [14:29:13][Connect-DbaInstance] PacketSize will be set to '4096'
DEBUG: [14:29:13][Connect-DbaInstance] Pooled will be set to 'True'
DEBUG: [14:29:13][Connect-DbaInstance] SecurePassword will be set
DEBUG: [14:29:13][Connect-DbaInstance] UserName will be set to 'automationUser'
DEBUG: [14:29:13][Connect-DbaInstance] Building ServerConnection from SqlConnectionInfo
DEBUG: [14:29:13][Connect-DbaInstance] ServerConnection was built
DEBUG: [14:29:13][Connect-DbaInstance] Building Server from ServerConnection
DEBUG: [14:29:13][Connect-DbaInstance] Server was built
DEBUG: [14:29:13][Connect-DbaInstance] Setting ConnectionContext.StatementTimeout to '0'
DEBUG: [14:29:13][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=S02.DOMAIN.LOCAL\S02;Initial Catalog=master;User ID=automationUser;Password=********;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: [14:29:13][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [14:29:13][Connect-DbaInstance] We have a connected server object
DEBUG: [14:29:13][Connect-DbaInstance] We will set server.ComputerName to server.NetName
DEBUG: [14:29:13][Connect-DbaInstance] ComputerName will be set to S02
DEBUG: [14:29:13][Test-Azure] Test for Azure is negative
DEBUG: [14:29:13][Connect-DbaInstance] We added IsAzure = 'False', DbaInstanceName = instance.InstanceName = 'S02', SqlInstance = server.DomainInstanceName = '', NetPort = instance.Port = '0', ConnectedAs = server.ConnectionContext.TrueLogin = 'automationUser'
DEBUG: [14:29:13][Connect-DbaInstance] We return the server object
DEBUG: [14:29:13][Connect-DbaInstance] SetDefaultInitFields will be used
DEBUG: [14:29:13][Add-ConnectionHashValue] Adding to connection hash
DEBUG: [14:29:13][Connect-DbaInstance] We are finished with this instance
DEBUG: [14:29:13][Restore-DbaDatabase] Changing statement timeout to infinity
DEBUG: [14:29:13][Restore-DbaDatabase] ParameterSet  = Restore
DEBUG: [14:29:13][Restore-DbaDatabase] Unverified input, full scans - \\amznfsxvddkl46k.DOMAIN.LOCAL\S02-backups\UNKNOWN-20.bak
DEBUG: [14:29:13][Get-DbaBackupInformation] Starting
DEBUG: [14:29:13][Get-DbaBackupInformation] Parameters bound: SqlInstance, SqlCredential, Path, DirectoryRecurse, MaintenanceSolution, IgnoreDiffBackup, IgnoreLogBackup, AzureCredential, NoXpDirRecurse
DEBUG: [14:29:13][Connect-DbaInstance] Starting process block
DEBUG: [14:29:13][Connect-DbaInstance] Immediately checking for Azure
DEBUG: [14:29:13][Test-Azure] Test for Azure is negative
DEBUG: [14:29:13][Connect-DbaInstance] Starting loop for 'S02\S02': ComputerName = 'S02', InstanceName = 'S02', IsLocalHost = 'False', Type = 'Server'
DEBUG: [14:29:13][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
DEBUG: [14:29:13][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=S02.DOMAIN.LOCAL\S02;Initial Catalog=master;User ID=automationUser;Password=********;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: [14:29:13][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [14:29:13][Connect-DbaInstance] We have a connected server object
DEBUG: [14:29:13][Test-Azure] Test for Azure is negative
DEBUG: [14:29:13][Connect-DbaInstance] We added IsAzure = 'False', DbaInstanceName = instance.InstanceName = 'S02', SqlInstance = server.DomainInstanceName = '', NetPort = instance.Port = '0', ConnectedAs = server.ConnectionContext.TrueLogin = 'automationUser'
DEBUG: [14:29:13][Connect-DbaInstance] We return the server object
DEBUG: [14:29:13][Connect-DbaInstance] SetDefaultInitFields will be used
DEBUG: [14:29:13][Add-ConnectionHashValue] Adding to connection hash
DEBUG: [14:29:13][Connect-DbaInstance] We are finished with this instance
DEBUG: [14:29:13][Get-DbaBackupInformation] Testing a single file @{Length=65; FullName=\\amznfsxvddkl46k.DOMAIN.LOCAL\S02-backups\UNKNOWN-20.bak} 
DEBUG: [14:29:13][Connect-DbaInstance] Starting process block
DEBUG: [14:29:13][Connect-DbaInstance] Immediately checking for Azure
DEBUG: [14:29:13][Test-Azure] Test for Azure is negative
DEBUG: [14:29:13][Connect-DbaInstance] Starting loop for 'S02\S02': ComputerName = 'S02', InstanceName = 'S02', IsLocalHost = 'False', Type = 'Server'
DEBUG: [14:29:13][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
DEBUG: [14:29:13][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=S02.DOMAIN.LOCAL\S02;Initial Catalog=master;User ID=automationUser;Password=********;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: [14:29:13][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [14:29:13][Connect-DbaInstance] We have a connected server object
DEBUG: [14:29:13][Test-Azure] Test for Azure is negative
DEBUG: [14:29:13][Connect-DbaInstance] We added IsAzure = 'False', DbaInstanceName = instance.InstanceName = 'S02', SqlInstance = server.DomainInstanceName = '', NetPort = instance.Port = '0', ConnectedAs = server.ConnectionContext.TrueLogin = 'automationUser'
DEBUG: [14:29:13][Connect-DbaInstance] We return the server object
DEBUG: [14:29:13][Connect-DbaInstance] SetDefaultInitFields will be used
DEBUG: [14:29:13][Add-ConnectionHashValue] Adding to connection hash
DEBUG: [14:29:13][Connect-DbaInstance] We are finished with this instance
DEBUG: [14:29:13][Get-DbaBackupInformation] Reading backup headers of 1 files
DEBUG: [14:29:13][Read-DbaBackupHeader] Checking: @{Length=65; FullName=\\amznfsxvddkl46k.DOMAIN.LOCAL\S02-backups\UNKNOWN-20.bak}
DEBUG: [14:29:13][Read-DbaBackupHeader] Starting reading headers
DEBUG: [14:29:13][Connect-DbaInstance] Starting process block
DEBUG: [14:29:13][Connect-DbaInstance] Immediately checking for Azure
DEBUG: [14:29:13][Test-Azure] Test for Azure is negative
DEBUG: [14:29:13][Connect-DbaInstance] Starting loop for 'S02\S02': ComputerName = 'S02', InstanceName = 'S02', IsLocalHost = 'False', Type = 'Server'
DEBUG: [14:29:13][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
DEBUG: [14:29:13][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=S02.DOMAIN.LOCAL\S02;Initial Catalog=master;User ID=automationUser;Password=********;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: [14:29:13][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [14:29:13][Connect-DbaInstance] We have a connected server object
DEBUG: [14:29:13][Test-Azure] Test for Azure is negative
DEBUG: [14:29:13][Connect-DbaInstance] We added IsAzure = 'False', DbaInstanceName = instance.InstanceName = 'S02', SqlInstance = server.DomainInstanceName = '', NetPort = instance.Port = '0', ConnectedAs = server.ConnectionContext.TrueLogin = 'automationUser'
DEBUG: [14:29:13][Connect-DbaInstance] We return the server object
DEBUG: [14:29:13][Connect-DbaInstance] SetDefaultInitFields will be used
DEBUG: [14:29:13][Add-ConnectionHashValue] Adding to connection hash
DEBUG: [14:29:13][Connect-DbaInstance] We are finished with this instance
DEBUG: [14:29:13][Read-DbaBackupHeader] 1 unique files to scan.
DEBUG: [14:29:13][Read-DbaBackupHeader] Checking accessibility for all the files.
DEBUG: [14:29:13][Connect-DbaInstance] Starting process block
DEBUG: [14:29:13][Connect-DbaInstance] Immediately checking for Azure
DEBUG: [14:29:13][Test-Azure] Test for Azure is negative
DEBUG: [14:29:13][Connect-DbaInstance] Starting loop for 'S02\S02': ComputerName = 'S02', InstanceName = 'S02', IsLocalHost = 'False', Type = 'Server'
DEBUG: [14:29:13][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
DEBUG: [14:29:13][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=S02.DOMAIN.LOCAL\S02;Initial Catalog=master;User ID=automationUser;Password=********;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: [14:29:13][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [14:29:13][Connect-DbaInstance] We have a connected server object
DEBUG: [14:29:13][Test-Azure] Test for Azure is negative
DEBUG: [14:29:13][Connect-DbaInstance] We added IsAzure = 'False', DbaInstanceName = instance.InstanceName = 'S02', SqlInstance = server.DomainInstanceName = '', NetPort = instance.Port = '0', ConnectedAs = server.ConnectionContext.TrueLogin = 'automationUser'
DEBUG: [14:29:13][Connect-DbaInstance] We return the server object
DEBUG: [14:29:13][Connect-DbaInstance] SetDefaultInitFields will be used
DEBUG: [14:29:13][Add-ConnectionHashValue] Adding to connection hash
DEBUG: [14:29:13][Connect-DbaInstance] We are finished with this instance
DEBUG: [14:29:13][Read-DbaBackupHeader] Scanning file \\amznfsxvddkl46k.DOMAIN.LOCAL\S02-backups\UNKNOWN-20.bak.
DEBUG: [14:29:14][Restore-DbaDatabase] Processing DatabaseName - UNKNOWN-20                                             
DEBUG: [14:29:14][Format-DbaBackupInformation] Starting                                                                 
DEBUG: [14:29:15][Format-DbaBackupInformation] String passed in for DB rename                                           
DEBUG: [14:29:15][Format-DbaBackupInformation] New DbName (String) = UNKNOWN-20                                         
DEBUG: [14:29:15][Format-DbaBackupInformation]  1 PhysicalName = D:\rdsdbdata\DATA\UNKNOWN-20.mdf                       
DEBUG: [14:29:16][Format-DbaBackupInformation] PhysicalName = \\amznfsxvddkl46k.DOMAIN.LOCAL\S02-data\7192D:\rdsdbdata\DATA\UNKNOWN-20.mdf 
DEBUG: [14:29:16][Format-DbaBackupInformation]  1 PhysicalName = D:\rdsdbdata\DATA\UNKNOWN-20_log.ldf                   
DEBUG: [14:29:16][Format-DbaBackupInformation] PhysicalName = \\amznfsxvddkl46k.DOMAIN.LOCAL\S02-logs\7192D:\rdsdbdata\DATA\UNKNOWN-20_log.ldf 
DEBUG: [14:29:16][Select-DbaBackupInformation] Filtering by DatabaseName                                                
DEBUG: [14:29:17][Select-DbaBackupInformation] processing diffs                                                         
DEBUG: [14:29:17][Select-DbaBackupInformation] Found LogBaseLsn: 38000000342300001 and FirstRecoveryForkID:             
DEBUG: [14:29:18][Restore-DbaDatabase] VerifyOnly = False                                                               
DEBUG: [14:29:18][Connect-DbaInstance] Starting process block                                                           
DEBUG: [14:29:18][Connect-DbaInstance] Immediately checking for Azure                                                   
DEBUG: [14:29:19][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:19][Connect-DbaInstance] Starting loop for 'S02\S02': ComputerName = 'S02', InstanceName = 'S02', IsLocalHost = 'False', Type = 'Server'
DEBUG: [14:29:19][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object 
DEBUG: [14:29:20][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=S02.DOMAIN.LOCALS02;Initial Catalog=master;User ID=automationUser;Password=********;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: [14:29:20][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [14:29:20][Connect-DbaInstance] We have a connected server object                                                
DEBUG: [14:29:21][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:21][Connect-DbaInstance] We added IsAzure = 'False', DbaInstanceName = instance.InstanceName = 'S02', SqlInstance = server.DomainInstanceName = '', NetPort = instance.Port = '0', ConnectedAs = server.ConnectionContext.TrueLogin = 'automationUser'
DEBUG: [14:29:21][Connect-DbaInstance] We return the server object                                                      
DEBUG: [14:29:22][Connect-DbaInstance] SetDefaultInitFields will be used                                                
DEBUG: [14:29:22][Add-ConnectionHashValue] Adding to connection hash                                                    
DEBUG: [14:29:22][Connect-DbaInstance] We are finished with this instance                                               
DEBUG: [14:29:23][Connect-DbaInstance] Starting process block                                                           
DEBUG: [14:29:23][Connect-DbaInstance] Immediately checking for Azure                                                   
DEBUG: [14:29:23][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:24][Connect-DbaInstance] Starting loop for 'S02\S02': ComputerName = 'S02', InstanceName = 'S02', IsLocalHost = 'False', Type = 'Server'
DEBUG: [14:29:24][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object 
DEBUG: [14:29:24][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=S02.DOMAIN.LOCAL\S02;Initial Catalog=master;User ID=automationUser;Password=********;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: [14:29:25][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [14:29:25][Connect-DbaInstance] We have a connected server object                                                
DEBUG: [14:29:25][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:26][Connect-DbaInstance] We added IsAzure = 'False', DbaInstanceName = instance.InstanceName = 'S02', SqlInstance = server.DomainInstanceName = '', NetPort = instance.Port = '0', ConnectedAs = server.ConnectionContext.TrueLogin = 'automationUser'
DEBUG: [14:29:26][Connect-DbaInstance] We return the server object                                                      
DEBUG: [14:29:26][Connect-DbaInstance] SetDefaultInitFields will be used                                                
DEBUG: [14:29:27][Add-ConnectionHashValue] Adding to connection hash                                                    
DEBUG: [14:29:27][Connect-DbaInstance] We are finished with this instance                                               
DEBUG: [14:29:27][Get-DbaDbPhysicalFile] SELECT DB_NAME(database_id) AS Name, name AS LogicalName, physical_name AS PhysicalName, type FROM sys.master_files
DEBUG: [14:29:28][Test-DbaBackupInformation] Testing restore for UNKNOWN-20                                             
DEBUG: [14:29:28][Connect-DbaInstance] Starting process block                                                           
DEBUG: [14:29:28][Connect-DbaInstance] Immediately checking for Azure                                                   
DEBUG: [14:29:29][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:29][Connect-DbaInstance] Starting loop for 'S02\S02': ComputerName = 'S02', InstanceName = 'S02', IsLocalHost = 'False', Type = 'Server'
DEBUG: [14:29:29][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object 
DEBUG: [14:29:30][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=S02.DOMAIN.LOCAL\S02;Initial Catalog=master;User ID=automationUser;Password=********;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: [14:29:30][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [14:29:30][Connect-DbaInstance] We have a connected server object                                                
DEBUG: [14:29:31][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:31][Connect-DbaInstance] We added IsAzure = 'False', DbaInstanceName = instance.InstanceName = 'S02', SqlInstance = server.DomainInstanceName = '', NetPort = instance.Port = '0', ConnectedAs = server.ConnectionContext.TrueLogin = 'automationUser'
DEBUG: [14:29:32][Connect-DbaInstance] We return the server object                                                      
DEBUG: [14:29:32][Connect-DbaInstance] SetDefaultInitFields will be used                                                
DEBUG: [14:29:32][Add-ConnectionHashValue] Adding to connection hash                                                    
DEBUG: [14:29:33][Connect-DbaInstance] We are finished with this instance                                               
DEBUG: [14:29:33][Test-DbaBackupInformation] VerifyOnly = False                                                         
DEBUG: [14:29:33][Connect-DbaInstance] Starting process block                                                           
DEBUG: [14:29:34][Connect-DbaInstance] Immediately checking for Azure                                                   
DEBUG: [14:29:34][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:34][Connect-DbaInstance] Starting loop for 'S02\S02': ComputerName = 'S02', InstanceName = 'S02', IsLocalHost = 'False', Type = 'Server'
DEBUG: [14:29:35][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object 
DEBUG: [14:29:35][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=S02.DOMAIN.LOCAL\S02;Initial Catalog=master;User ID=automationUser;Password=********;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: [14:29:35][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [14:29:36][Connect-DbaInstance] We have a connected server object                                                
DEBUG: [14:29:36][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:37][Connect-DbaInstance] We added IsAzure = 'False', DbaInstanceName = instance.InstanceName = 'S02', SqlInstance = server.DomainInstanceName = '', NetPort = instance.Port = '0', ConnectedAs = server.ConnectionContext.TrueLogin = 'automationUser'
DEBUG: [14:29:37][Connect-DbaInstance] We return the server object                                                      
DEBUG: [14:29:37][Connect-DbaInstance] SetDefaultInitFields will be used                                                
DEBUG: [14:29:38][Add-ConnectionHashValue] Adding to connection hash                                                    
DEBUG: [14:29:38][Connect-DbaInstance] We are finished with this instance                                               
DEBUG: [14:29:38][Connect-DbaInstance] Starting process block                                                           
DEBUG: [14:29:38][Connect-DbaInstance] Immediately checking for Azure                                                   
DEBUG: [14:29:39][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:39][Connect-DbaInstance] Starting loop for 'S02\S02': ComputerName = 'S02', InstanceName = 'S02', IsLocalHost = 'False', Type = 'Server'
DEBUG: [14:29:39][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object 
DEBUG: [14:29:40][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=S02.DOMAIN.LOCAL\S02;Initial Catalog=master;User ID=automationUser;Password=********;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: [14:29:40][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [14:29:40][Connect-DbaInstance] We have a connected server object                                                
DEBUG: [14:29:41][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:41][Connect-DbaInstance] We added IsAzure = 'False', DbaInstanceName = instance.InstanceName = 'S02', SqlInstance = server.DomainInstanceName = '', NetPort = instance.Port = '0', ConnectedAs = server.ConnectionContext.TrueLogin = 'automationUser'
DEBUG: [14:29:41][Connect-DbaInstance] We return the server object                                                      
DEBUG: [14:29:42][Connect-DbaInstance] SetDefaultInitFields will be used                                                
DEBUG: [14:29:42][Add-ConnectionHashValue] Adding to connection hash                                                    
DEBUG: [14:29:42][Connect-DbaInstance] We are finished with this instance                                               
DEBUG: [14:29:43][Connect-DbaInstance] Starting process block                                                           
DEBUG: [14:29:43][Connect-DbaInstance] Immediately checking for Azure                                                   
DEBUG: [14:29:43][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:44][Connect-DbaInstance] Starting loop for 'S02\S02': ComputerName = 'S02', InstanceName = 'S02', IsLocalHost = 'False', Type = 'Server'
DEBUG: [14:29:44][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object 
DEBUG: [14:29:44][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=S02.DOMAIN.LOCAL\S02;Initial Catalog=master;User ID=automationUser;Password=********;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: [14:29:45][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [14:29:45][Connect-DbaInstance] We have a connected server object                                                
DEBUG: [14:29:45][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:46][Connect-DbaInstance] We added IsAzure = 'False', DbaInstanceName = instance.InstanceName = 'S02', SqlInstance = server.DomainInstanceName = '', NetPort = instance.Port = '0', ConnectedAs = server.ConnectionContext.TrueLogin = 'automationUser'
DEBUG: [14:29:46][Connect-DbaInstance] We return the server object                                                      
DEBUG: [14:29:46][Connect-DbaInstance] SetDefaultInitFields will be used                                                
DEBUG: [14:29:47][Add-ConnectionHashValue] Adding to connection hash                                                    
DEBUG: [14:29:47][Connect-DbaInstance] We are finished with this instance                                               
DEBUG: [14:29:47][Connect-DbaInstance] Starting process block                                                           
DEBUG: [14:29:48][Connect-DbaInstance] Immediately checking for Azure                                                   
DEBUG: [14:29:48][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:48][Connect-DbaInstance] Starting loop for 'S02\S02': ComputerName = 'S02', InstanceName = 'S02', IsLocalHost = 'False', Type = 'Server'
DEBUG: [14:29:49][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object 
DEBUG: [14:29:49][Connect-DbaInstance] The masked server.ConnectionContext.ConnectionString is Data Source=S02.DOMAIN.LOCAL\S02;Initial Catalog=master;User ID=automationUser;Password=********;Multiple Active Result Sets=False;Encrypt=False;Trust Server Certificate=False;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"
DEBUG: [14:29:49][Connect-DbaInstance] We connect to the instance by running SELECT 'dbatools is opening a new connection'
DEBUG: [14:29:50][Connect-DbaInstance] We have a connected server object                                                
DEBUG: [14:29:50][Test-Azure] Test for Azure is negative                                                                
DEBUG: [14:29:50][Connect-DbaInstance] We added IsAzure = 'False', DbaInstanceName = instance.InstanceName = 'S02', SqlInstance = server.DomainInstanceName = '', NetPort = instance.Port = '0', ConnectedAs = server.ConnectionContext.TrueLogin = 'automationUser'
DEBUG: [14:29:51][Connect-DbaInstance] We return the server object                                                      
DEBUG: [14:29:51][Connect-DbaInstance] SetDefaultInitFields will be used                                                
DEBUG: [14:29:51][Add-ConnectionHashValue] Adding to connection hash                                                    
DEBUG: [14:29:52][Connect-DbaInstance] We are finished with this instance                                               
**DEBUG: [14:29:52][New-DbaDirectory] **EXEC master.dbo.xp_create_subdir '//amznfsxvddkl46k.DOMAIN.LOCAL/S02-data/7192D:/rdsdbdata/DATA'****
WARNING: [14:29:52][New-DbaDirectory] Failure | xp_create_subdir() returned error 161, 'The specified path is invalid.' 
WARNING: [14:29:53][Restore-DbaDatabase] Failure | The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop: [14:29:52][New-DbaDirectory] Failure | xp_create_subdir() returned error 161, 'The specified path is invalid.'

From this line, you can see that I'm passing in a windows formatted path into the command:
DEBUG: [14:29:13][Restore-DbaDatabase] Unverified input, full scans - \\amznfsxvddkl46k.DOMAIN.LOCAL\S02-backups\UNKNOWN-20.bak

But the create folder step converted it to linux pathing:
DEBUG: [14:29:52][New-DbaDirectory] EXEC master.dbo.xp_create_subdir '//amznfsxvddkl46k.DOMAIN.LOCAL/S02-data/7192D:/rdsdbdata/DATA'

Because of the linux pathing, the commandlet fails.

The next interesting question is that I cannot get rid of the D:/rdsdbdata/DATA, but I'm assuming that's because I have to use file mapping. 

### Steps to Reproduce

**HOST**
Ubuntu 22.04 LTS

**Powershell Version**
7.2.4

**DBATools Version**
Latest

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference

Restore-DbaDatabase -Path $("\\amznfsxvddkl46k.domain.local\S02-backups" + "\" + $s3ObjectName) -SqlInstance S02.DOMAIN.local\S02 -SqlCredential $credObject -WarningAction Stop -ErrorAction Stop -DatabaseName unknown-20 -DestinationFilePrefix $(Get-Random -Minimum 1000 -Maximum 9999) -DestinationLogDirectory \\amznfsxvddkl46k.domain.local\S02-logs -DestinationDataDirectory \\amznfsxvddkl46k.domain.local\S02-data  -Debug
```

### Are you running the latest release?

Yes

### Other details or mentions

Another interesting behavior is that Restore-DbaDatabase will not restore anything in a directory without me hard specifying a file. It will error out with permission denied. However specifying a file, the commandlet will continue. I have not been able to replicate this behavior on non-ubuntu based machines. 

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Linux 5.15.0-1004-aws #6-Ubuntu SMP Thu Mar 31 09:44:20 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU12) (KB5004524) - 15.0.4153.1 (X64)   Jul 19 2021 15:37:34   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

ubuntu...

**Comment by andreasjordan** [comment]
I will close this now, but can reopen if issue still exists.
