### ISSUE TITLE
Write-DBADBDataTable Throwing error: Cannot find an overload for "SqlBulkCopy" and the argument count: "3".

### ISSUE THREAD

**Issue by nathanlbell** [dataplat/dbatools#8374]
### Verified issue does not already exist?

Yes

### What error did you receive?

New-Object : Cannot find an overload for "SqlBulkCopy" and the argument count: "3".
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.88\allcommands.ps1:85143 char:21
+ ... $bulkCopy = New-Object Microsoft.Data.SqlClient.SqlBulkCopy($server.C ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
 
The property 'DestinationTableName' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.88\allcommands.ps1:85145 char:9
+         $bulkCopy.DestinationTableName = $fqtn
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'BatchSize' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.88\allcommands.ps1:85146 char:9
+         $bulkCopy.BatchSize = $BatchSize
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'NotifyAfter' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.88\allcommands.ps1:85147 char:9
+         $bulkCopy.NotifyAfter = $NotifyAfter
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
The property 'BulkCopyTimeOut' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.88\allcommands.ps1:85148 char:9
+         $bulkCopy.BulkCopyTimeOut = $BulkCopyTimeOut
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound
 
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.88\allcommands.ps1:85158 char:9
+         $bulkCopy.Add_SqlRowsCopied( {
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

### Steps to Reproduce

Write-DbaDbTableData -SqlInstance $sqlInstance -Database $databasename -InputObject $xls -Schema $stg_schema -Table $stg_table -ColumnMap $ColumnMap

### Are you running the latest release?

Yes

### Other details or mentions

Issue does NOT exist in 1.0.169 but I have confirmed that it at least exists in up to version 1.1.88.  I haver not confirmed how far back the issue goes.

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      5.1.19041.1645
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1645
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

SQL2019 cu16

### .NET Framework Version

.NET Framework 4.8.4470.0

**Comment by nathanlbell** [comment]
Last known working issue was in 1.1.15 any version 1.1.16 and above throws the error.

**Comment by potatoqualitee** [comment]
Interesting, thank you for the report. The thing that changed between the two versions was:

```powershell
$bulkCopy = New-Object Microsoft.Data.SqlClient.SqlBulkCopy($server.ConnectionContext.ConnectionString, $bulkCopyOptions)
```

to
```
$bulkCopy = New-Object Microsoft.Data.SqlClient.SqlBulkCopy($server.ConnectionContext.SqlConnectionObject, $bulkCopyOptions, $null)
```

Zero idea why your specific environment is having issues. What type of authentication are you using?

I will put in a throw/catch. That should fix it /cc @andreasjordan

**Comment by andreasjordan** [comment]
Maybe an issue with the version of the (already) loaded dll - we had this some time ago and I'll try to find the code to analyse this...

**Comment by potatoqualitee** [comment]
Agreed - @nathanlbell can you close PowerShell entirely and try with each of the versions with a freshly closed/reopend window?

**Comment by potatoqualitee** [comment]
hmm yeah, looks like it was updated to show a warning in 1.1.72

https://github.com/dataplat/dbatools/commit/57e3715bf351448a1ecd683085d74c637e03aea6
