### ISSUE TITLE
Some Get-DbaDB*-Commands were not able to successfully pull objects in latest version

### ISSUE THREAD

**Issue by jharbering** [dataplat/dbatools#8385]
I am connecting to Azure Synapse Serverless pulling
- Schema
- Table
- View
- StoredProcedure
- UserDefinedFunction

After upgrading from 1.1.95 to 1.1.101 (or 1.1.102 likewise) only UserDefinedFunctions was successfully able to execute.

StoredProcedures and Views had the following "error":
WARNING: [10:12:47][Get-DbaDbView] Database [**********] is not accessible. Skipping
WARNING: [10:12:47][Get-DbaDbStoredProcedure] Database [************] is not accessible. Skipping.

Table and Schema didnt even output any message.

After reverting to 1.1.95 everything works again.

**Comment by andreasjordan** [comment]
The commands use `$InputObject = Get-DbaDatabase -SqlInstance $SqlInstance -SqlCredential $SqlCredential -Database $Database -ExcludeDatabase $ExcludeDatabase` to get the databases. This command has been changed as well. Might get too many databases back. 

Can you run the commands with -Verbose? `Get-DbaDbView` has a line `Write-Message -Level Verbose -Message "processing $db"` in the database loop.

**Comment by Xcone** [comment]
Hi, I've noticed a similar (or perhaps the same) issue as well. And rolling back to 1.1.95 of DBAtools make things work again.

Our steps involve defining an sql connection string, invoking some SQL commands, followed by using DBAtools to generate some SQL scripts.

Some snippets of powershell script (vastly incomplete but these are the significant bits I believe:

$connectionString = "blablabla";
$sqlConnection = Connect-DbaInstance -ConnectionString $connectionString

$create = New-DbaScriptingOption
$create.ScriptSchema             = $true
#and a bunch more settings...   

#works
Invoke-Sqlcmd -ConnectionString $connectionString -Query "SELECT etcetcetcetc...." 
    
#doesnt work
Get-DbaDbUserDefinedTableType -SqlInstance $sqlConnection -Database $environmentDatabaseName `
        | Export-DbaScript -Passthru -NoPrefix -ScriptingOptionsObject $userDefinedTableTypeOptions `
        | Add-Content $createEnvironmentSchemaScriptPath

#also doesnt work
Get-DbaDbStoredProcedure -SqlInstance $sqlConnection -Database $environmentDatabaseName -ExcludeSystemSp `
        | Export-DbaScript -Passthru -NoPrefix `
        | Add-Content $createEnvironmentSchemaScriptPath

When running as part of a larger script in a azure pipeline, the error about `not accessible, skipping` like the OP mentioned applies. In our attempts to locally reproduce we noticed the failing commands show a popup to enter credentials. When using the 1.1.95 version the commands were able to use the created $sqlConnection variable without prompting for credentials again.

I hope this info helps resolve the issue.

**Comment by andreasjordan** [comment]
Do you have a chance to run the not-working-commands with `-Verbose`?

**Comment by Xcone** [comment]
Yes I can:

VERBOSE: [15:15:41][Connect-DbaInstance] Azure detected
VERBOSE: [15:15:41][Connect-DbaInstance] Server object passed in, will do some checks and then return the original
object
WARNING: [15:15:41][Get-DbaDbUserDefinedTableType] Database [RelaticsNext_833d3a3f309f474bb4b572c61f27fd45] is not
accessible. Skipping.

**Comment by Xcone** [comment]
Yes it is

**Comment by andreasjordan** [comment]
So it looks like the database is not accessible. This is the code:
```
            if (!$db.IsAccessible) {
                Write-Message -Level Warning -Message "Database $db is not accessible. Skipping."
                continue
            }
```
Is the property IsAccessible wrong? Is the database accessible or not?

**Comment by niphlod** [comment]
hum. I see "on Azure". are we completely sure the connection is not on the "master" but rather on the specific db ? no wonders a db is not accessible if the connection isn't targeted towards the specific database.

**Comment by niphlod** [comment]
@Xcone not saying it's your fault, just that Azure can't jump databases (i.e. "use database xxx"). rolling over all the databases on an azuredb server can be done but accessing each one needs a separate and "direct" connection. I was pointing out that *maybe* the difference is that dbatools used to switch the connection under the hood without you noticing, but as a best practice if you need to do something on an azure db, you are more "sure that it just works" if you do a `$connection = Connect-DbaInstance -sqlinstance servername -Database specificdatabase` and then pass that `$connection` as the `-SqlInstance` to the lower functions, as in Get-DbaDbUserDefinedTableType

**Comment by Xcone** [comment]
I've tried (with a colleague) the steps you've proposed. We've found this [test](https://github.com/dataplat/dbatools/blob/40cce7ecff42ca69f78efa3e75ef10eb8936d912/tests/Connect-DbaInstance.Tests.ps1#L25) which seems to closely match the syntax as you suggest. We locally gave it a try to connect this way and execute 'Get-DbaDbUserDefinedTableType'. It still replied with "not accessible, skipping", though.

We initially tried to include the connectionstring argument, too. The error messages that showed seem to suggest the connect command properly honours the server and database names provided in the connectionstring, which were already pointing to the exact database in question. So no hidden automatic "direct" connection would've been in order, after all (if I understand the stuff correctly).

**Comment by Xcone** [comment]
I tried both flavors. 
The first flavor lists both the specific database name in `$environmentDatabaseName` as well as `master`, and the second shows only the one specific database without `master`.

In both cases the columns, `computerName`, `SqlInstance` and `Name` as filled, and the columns `InstanceName`, `Status`, IsAccessible`, `RecoveryModel`, `LogReuseWaitStatus` and `SizeMB` are blank.

![image](https://user-images.githubusercontent.com/10597379/173025332-ecacc587-41c4-40a4-8f52-d506253e3fc8.png)

**Comment by Xcone** [comment]
I downgraded to 1.1.95 again and repeated the requested command. Some more data is populated now. Including the IsAccessble property.
![image](https://user-images.githubusercontent.com/10597379/173026982-a7e7d58f-2611-4f73-8959-2bf2da103b24.png)

**Comment by andreasjordan** [comment]
Ok, that helps. Will try to find some time to have a detailed look.

**Comment by Xcone** [comment]
Thank you for your time and effort. Looking forward to your findings. If I can run some more commands for you to pinpoint the issue further, let me know.

**Comment by andreasjordan** [comment]
I think this might be the change the caused the problem:
Old:
```
$inputObject += $server.Databases[$dt.name]
```

New: 
```
# Enumeration via $server.Databases[$dt.name] no longer works in azure
$inputObject += New-Object Microsoft.SqlServer.Management.Smo.Database $server, $dt.Name
```

In the new version, the resulting database SMO seems to have an empty property IsAccessible.

You might just try to replace `Get-DbaDatabase` with something like `New-Object Microsoft.SqlServer.Management.Smo.Database $sqlConnection, $environmentDatabaseName` or `[Microsoft.SqlServer.Management.Smo.Database]::new($sqlConnection, $environmentDatabaseName)`.

Then have a look at the resulting object. Maybe there is a method `.Refresh()` to fill the properties.

I currently don't have an AzureDB, maybe I will use this issue to re-build my AzureDB for dbatools testing at the weekend...

**Comment by andreasjordan** [comment]
We have another issue with this code: #8423
