### ISSUE TITLE
Get-DbaDependency Schemabound value not correct

### ISSUE THREAD

**Issue by ft3411** [dataplat/dbatools#8411]
### Verified issue does not already exist?

Yes

### What error did you receive?

Incorrect value in Schema or Schemabound Property

### Steps to Reproduce

```powershell
Get-DbaDbTable -SQLInstance inst1 -Database db1 -Table Tab1 | Get-DbaDependency | select *


ComputerName     : TEST100
ServiceName      : MSSQLSERVER
SqlInstance      : TEST100
Dependent        : View$VSIFT$Key4
Type             : View
Owner            : dbo
IsSchemaBound    : False
Parent           : Some-Table
ParentType       : Table
Script           :   CREATE VIEW dbo."View$VSIFT$Key4" WITH
                   SCHEMABINDING AS SELECT "99301"."Customer No_",...
                   FROM dbo."Tab1" "99301"  GROUP BY ...
                   go
Tier             : 1
Object           : [dbo].[View$VSIFT$Key4]
Urn              : ...
OriginalResource : ...

```

### Are you running the latest release?

Yes

### Other details or mentions

The value of IsSchemabound ist False, but the script shows "WITH SCHEMABINDING".
The Value of $_.Object.IsSchemabound shows the correct value. 

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                              
----                           -----                                                                                                                                              
PSVersion                      5.1.14393.5127                                                                                                                                     
PSEdition                      Desktop                                                                                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                            
BuildVersion                   10.0.14393.5127                                                                                                                                    
CLRVersion                     4.0.30319.42000                                                                                                                                    
WSManStackVersion              3.0                                                                                                                                                
PSRemotingProtocolVersion      2.3                                                                                                                                                
SerializationVersion           1.1.0.1                                                                                                                                            

### SQL Server Edition and Build number

SQL Server 2019 CU16

### .NET Framework Version

PSChildName                      Version
-----------                      -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.7.03062
Full                             4.7.03062
Client                           4.0.0.0

**Comment by andreasjordan** [comment]
Are you able to test the branch in the linked pull request?

**Comment by ft3411** [comment]
Tried it - looks good!
