### ISSUE TITLE
New-DbaLinkedServer cmdlet not exported

### ISSUE THREAD

**Issue by cborosonvertex** [dataplat/dbatools#8420]
### Verified issue does not already exist?

Yes

### What error did you receive?

There isn't an error, per se, but it appears that the New-DbaLinkedServer cmdlet is not exported in the module.  The psd1 and psm1 files appear to be missing the lines that would export the cmdlet and make it available.

### Steps to Reproduce

```powershell
get-command -module dbatools | Where-Object {$_.name -eq "New-DbaLinkedServer"}

[null response]
```

### Are you running the latest release?

Yes

### Other details or mentions

This appears to be fixed easily, but I don't know if the cmdlet was removed intentionally, or if there is additional work to enable the cmdlet (e.g. documentation).

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU16-GDR) (KB5014353) - 15.0.4236.7 (X64)   May 29 2022 15:55:47   Copyright (C) 2019 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET 6.0.6

**Comment by potatoqualitee** [comment]
Thanks for this!

```
$root = Split-Path -Path (Get-ChildItem -Path (Get-Module dbatools).Path)
$dir = Join-Path -Path $root -ChildPath functions
$files = Get-ChildItem -Path $dir | Select-Object -ExpandProperty basename
Import-Module dbatools -Force
$commands = Get-Command -Module dbatools
foreach ($file in $files) { if ($file -notin $commands.Name) { write-warning $file } }
```

Found two that are not indexed, will add a PR shortly
