### ISSUE TITLE
Get-DbaDbTable not using input from '-Table'

### ISSUE THREAD

**Issue by Zasig** [dataplat/dbatools#8423]
### Verified issue does not already exist?

Yes

### What error did you receive?

I try to get the data from a table but i cannot get the table.
With verbose i see the following output

![image](https://user-images.githubusercontent.com/15321776/176634985-26b0c314-6b62-4956-90ac-21de6f746571.png)

i tried every possible combination of "dbo.Table", dbo.Table, Table that is stated in the [documentation](https://docs.dbatools.io/Get-DbaDbTable) and some more.

What i think is that there is a longer empty space after "Could not find table " it seems like it ignores the Input that is set after -Table

### Steps to Reproduce

Get-DbaDbTable -Table TableName -SqlInstance $connstring -Database DBName -Verbose

### Are you running the latest release?

Yes

### Other details or mentions

Maybe again something special because of the AzureDB? First i tried the Database in the $connstring - but that was not enough because it only searched in [master]. Then i added the DB as a parameter and now its also searching the correct database.

Edit: 
i tried some things and this works like a charm:
`Invoke-Sqlcmd -Query "SELECT [TenantName],[TenantId],[AppId],[AppSecret]FROM [dbo].[Tenants]" -ConnectionString $connstring`

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe), VS Code (terminal), VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value

PSVersion                      5.1.14393.5066
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.5066
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

Microsoft SQL Azure (RTM) - 12.0.2000.8

### .NET Framework Version

PSChildName Version
Client      4.8.03761
Full        4.8.03761
Client      4.0.0.0

**Comment by andreasjordan** [comment]
I think it's an Azure related problem. Try to first connect to the correct database with `$server = Connect-DbaInstance ...` and then use `$server` as SqlInstance: `Get-DbaDbTable -SqlInstance $server -Table TableName`.

**Comment by andreasjordan** [comment]
The space in the verbose mesage seems to be a bug, will provide a fix for that...

**Comment by andreasjordan** [comment]
Oh, and don't use -Database with Get-DbaDbTable, only use it with Connect-DbaInstance. But as you use a connection string, you should add it there.

**Comment by Zasig** [comment]
> Can you do a select on the table? Like: `Invoke-DbaQuery -SqlInstance $server -Query "SELECT COUNT(*) FROM Tenants"`?

That works. 

If i left that -Database out its basically the same. Its still not finding the Table but now also searching in [master]

![image](https://user-images.githubusercontent.com/15321776/176663666-96685087-ef6b-43cd-93bd-7451b2605af0.png)

**Comment by andreasjordan** [comment]
Ok, have setup my Azure environment and can reproduce the issue. Will analyse and try to fix...

**Comment by Zasig** [comment]
Ok. I'm using

`Invoke-Sqlcmd -Query "SELECT [TenantName],[TenantId],[AppId],[AppSecret]FROM [dbo].[Tenants]" -ConnectionString $connstring`

at the moment. That works fine. I'm curious to see the problem.

**Comment by andreasjordan** [comment]
Looks like a bug in the SMO we use - more details later.

**Comment by andreasjordan** [comment]
This seems to break a lot of things on Azure. Will provide a fix...
