### ISSUE TITLE
New-DbaAvailabilityGroup: Force errors without secondaries passed

### ISSUE THREAD

**Issue by lowlydba** [dataplat/dbatools#8433]
### Verified issue does not already exist?

Yes

### What error did you receive?

> Cannot bind argument to parameter 'SqlInstance' because it is null.
> At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.111\allcommands.ps1:147923 char:9
>          throw $records[0]
>         ~~~~~~~~~~~~~~~~~
>         CategoryInfo          : InvalidData: (:) [], Exception
>         FullyQualifiedErrorId : dbatools_New-DbaAvailabilityGroup

### Steps to Reproduce

```powershell
 New-DbaAvailabilityGroup -Primary localhost -Force -Database MyDb ...
```
This should trigger the below section that doesn't gracefully handle `-Force` used without any `-Secondary` passed in:

https://github.com/dataplat/dbatools/blob/414cd385352990c83f02f90b703bd1c89b36ad14/functions/New-DbaAvailabilityGroup.ps1#L646-L651

### Are you running the latest release?

Yes

### Other details or mentions

Not sure if its better to flip Force back to off at the top of the function, or just add a qualifying 'if' statement in the mentioned code block to avoid the error. Happy to implement the fix either way.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

**Comment by andreasjordan** [comment]
Why do you use -Force if you don't want to delete databases from the secondary? I currently see this as a no-bug.

**Comment by wsmelton** [comment]
This would be a bug only in the sense the command is not throwing an error we control in the module.

How `-Force` is used in the command is documented and this scenario does not meet those requirements. I expect we need to expand this section out to lay down exactly what parameters are expected to be used with `-Force` so it is more clear to users:

https://github.com/dataplat/dbatools/blob/414cd385352990c83f02f90b703bd1c89b36ad14/functions/New-DbaAvailabilityGroup.ps1#L323-L326

**Comment by andreasjordan** [comment]
Will close this as no-bug.
