### ISSUE TITLE
New-DbaAvailabilityGroup fails when force used but no databases supplied

### ISSUE THREAD

**Issue by simonwhybrow** [dataplat/dbatools#8447]
### Verified issue does not already exist?

Yes

### What error did you receive?

PS c:\>New-DbaAvailabilityGroup -Primary serverA -Secondary serverB -Name new_aag -Force

WARNING: [New-SqlCmndrAvailabilityGroup][2022-07-13][18:35:22] Stopping Script | SharedPath or UseLastBackup is required when Force is used New-SqlCmndrAvailabilityGroup

### Steps to Reproduce

```powershell
PS c:\>New-DbaAvailabilityGroup -Primary serverA -Secondary serverB -Name new_aag -Force
```
It is related to this section of code:

```powershell
if ($Force -and $Secondary -and (-not $SharedPath -and -not $UseLastBackup) -and ($SeedingMode -ne 'Automatic')) {
    Stop-Function -Message "SharedPath or UseLastBackup is required when Force is used"
    return
}
```

It's assuming that if you a Forcing creation and you have specified a Secondary that you must be adding a database, but that isn't strictly true as you may just want the AAG created but not add databases at that point in time.

It would be better to use the below for this specific Force check as the parameters it's asking to be used relate to database set up within the AAG

```powershell
if ($Force -and $Database -and (-not $SharedPath -and -not $UseLastBackup) -and ($SeedingMode -ne 'Automatic')) {
    Stop-Function -Message "SharedPath or UseLastBackup is required when Force is used"
    return
}
```

### Are you running the latest release?

Yes

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

**Comment by andreasjordan** [comment]
But why do you use -Force if you don't want to remove databases? The command works without -Force as expected, doesn't it? I currently see this as a no-bug.

**Comment by wsmelton** [comment]
Your discussion point @simonwhybrow is to create an AG and join a replica, with no database involved.

As [example two shows in our docs](https://docs.dbatools.io/New-DbaAvailabilityGroup) for this command that is accomplished by not using the `-Force` parameter. That was the design decision made at the time and I don't see any reason to change that.

**Comment by simonwhybrow** [comment]
@wsmelton That's correct, but I'm also trying to do it without any confirmations (apologies missed that out in my original message) so that we can use it as part of a wider process without having the need for user interactions.

@andreasjordan  Looking at the code the Force switch is also used to change the $ConfirmPreference at the beginning:

```powershell
begin {
        if ($Force) { $ConfirmPreference = 'none' }
    }
``` 

The description of the parameter doesn't seem to match everything that it actually does.
Should there be a separate switch to change the confirmpreference? Or should the description be updated?

As it stands supplying -Force to ensure no confirmations are needed, results in the issue I described initially when you aren't adding a database at AAG creation time.

**Comment by andreasjordan** [comment]
Then you should use `-Confirm:$false` with all your commands - that's the correct way to suppress confirmation.

**Comment by simonwhybrow** [comment]
Ok, will do. 
However, the use of -Force to suppress confirmation should be removed to avoid confusion I think.
Thanks

**Comment by wsmelton** [comment]
Every module does it a bit different with relation to Force parameter and what it does. The pattern used in this module is we suppress confirmation messages, which you will find most do in the community.

**Comment by simonwhybrow** [comment]
So then there is an issue with the -Force parameter in this function as it suppresses confirmation messages, but wont work if you aren't adding a database at AAG creation time (as mentioned in my initial issue).

**Comment by wsmelton** [comment]
Please review the documentation and examples. The command is written as designed. If we need to make the documentation more clear please open a new issue and provide that feedback.
