### ISSUE TITLE
Add NoteProperty SidString to output object of Get-DbaLogin

### ISSUE THREAD

**Issue by andreasjordan** [dataplat/dbatools#8453]
### Summarize Functionality

Just today a clients asks for where the sid is which is nicely displayed in SSMS (like in "select name, sid from sys.server_principals") as for example "0xCEE0DA0790188C48BDD1589137F0142E".

My answer includes this code:
```
$sidString = @{ name = 'SidString' ; expression = { $sidString = '0x' ; foreach ($element in $_.Sid) { $sidString += '{0:X2}' -f $element } ; $sidString } }
Get-DbaLogin -SqlInstance SQL01 | Select-Object -Property Name, $sidString
```

What about adding this to the object itself?

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

In the "Add-Member" section of the code, we would have to add:
```
$sidString = '0x'
foreach ($element in $serverLogin.Sid) {
    $sidString += '{0:X2}' -f $element
}
Add-Member -Force -InputObject $serverLogin -MemberType NoteProperty -Name SidString -Value $sidString
```

We could also think about implementing a public command ConvertTo-DbaString which takes a byte array and returns the string and use this inside of Get-DbaLogin. This would help to deal with other sid-like byte arrays as well.

**Comment by andreasjordan** [comment]
Sample code for a general command:

```
function ConvertTo-DbaString {
    param (
        [parameter(ValueFromPipeline)]
        [object[]]$InputObject
    )
    begin {
        $output = '0x'
    }
    process {
        foreach ($element in $InputObject) {
            $output += '{0:X2}' -f $element
        }
    }
    end {
        if ($output.Length -gt 2) {
            $output
        }
    }
}
```

**Comment by potatoqualitee** [comment]
sounds great!

**Comment by andreasjordan** [comment]
As a starting point, let's add the NodeProperty. That is easy and don't need documentation - I've opend the PR.

I still love the idea of a command to do the conversion because there are some other byte-arrays that SSMS users only see as hex strings, like the Sid in the output of Get-DbaDbUser. 
But we would need to write some documentation and we need to agree on possible parameters or tests on the input.

**Comment by andreasjordan** [comment]
A command could also be used to work with the result from statements like `Invoke-DbaQuery -SqlInstance SQL01 -Query "SELECT sql_handle FROM sys.dm_exec_query_stats"`.

![image](https://user-images.githubusercontent.com/66946165/180248629-1b98e8b8-c803-4a1a-8a33-695087dae0f0.png)

We could also add a parameter to Invoke-DbaQuery to do this for all byte columns while converting to PSCustomObjects... (but that would probably be better implemented in the DBNullScrubber class directly)
