### ISSUE TITLE
Copy-dbacredentials error

### ISSUE THREAD

**Issue by dbatoolsuser** [dataplat/dbatools#8458]
Hi all

I am running a migration from server a to b, i am domain admin now. I log on to server a and run copy-dbacredential and i get following error

Failure | the system cannot find the specified file

Server a does  not have default insurance, could this be a cause?   As this command worked fine on another server but that had default instance.

Please help

**Comment by potatoqualitee** [comment]
Hello,
Happy to help but please fill out the correct form (this one is for the website) and also include the output of `Get-DbatoolsError`

https://github.com/dataplat/dbatools/issues/new?assignees=&labels=bugs+life%2Ctriage+required&template=bug-report.yml
