### ISSUE TITLE
Copy-dbacredentials

### ISSUE THREAD

**Issue by dbatoolsuser** [dataplat/dbatools#8462]
### Verified issue does not already exist?

Yes

### What error did you receive?

![16589104423453872916741592293859](https://user-images.githubusercontent.com/109794979/181199891-4bbd5964-6ec9-41d3-a9d9-2637ba4a78f3.jpg)

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Copy-dbacredentials
Same. Error for copy-dbalinkedserver

### Are you running the latest release?

Yes

### Other details or mentions

None

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Windows server 2012 r2

### SQL Server Edition and Build number

Sql. 2012 sp3. 

### .NET Framework Version

4.6.2

**Comment by potatoqualitee** [comment]
That generally means that one of the hostnames can't be resolved. Please try copy/pasting the hostname and pinging.

If both can be pinged, please paste the results of `Get-DbatoolsError`

**Comment by dbatoolsuser** [comment]
![16590012459487108768555837759262](https://user-images.githubusercontent.com/109794979/181474795-d466e6ba-7c57-47d5-a9bf-647840b2e261.jpg)

Looks like it is a connection issue but I can ping both servers from powershell

**Comment by dbatoolsuser** [comment]
Hi chrissy, I have found the issue and its picnic syndrome im embarassed to say :(  i wasnt declaring the instance name correctly as these are none default instance.
All working now

**Comment by potatoqualitee** [comment]
No problem! Glad you got it working 😊  Sorry the error isn't better, that's what SMO gives us.
