### ISSUE TITLE
New-DbaDacOption should support specifying option property values as a parameter

### ISSUE THREAD

**Issue by nvarscar** [dataplat/dbatools#8463]
### Summarize Functionality

When calling New-DbaDacOption, users should have an ability to specify the property values they want to see in the result object. This would help them to reduce the boilerplate of setting all those options one option at a time:

```powershell
$options = New-DbaDacOption -Type Dacpac -Action Export
$options.VerifyExtraction = $false
$options.ExtractReferencedServerScopedElements = $false
$options.IgnorePermissions = $true
$options.IgnoreUserLoginMappings = $true
``` 

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

Since all of the objects are created using New-Object, it would be possible to mirror the functionality of the -Property parameter of that function:

```powershell
$options = New-Object Microsoft.SqlServer.Dac.DacExtractOptions -Property @{VerifyExtraction = $true; IgnorePermissions = $true }
```

and support something like

```powershell
$options = New-DbaDacOption -Type Dacpac -Action Export -Property @{VerifyExtraction = $true; IgnorePermissions = $true }
```

**Comment by potatoqualitee** [comment]
sounds fab!

**Comment by chadbaldwin** [comment]
Thanks @nvarscar in case it helps (even though y'all are powershell experts already and don't need this) here's what I wrote in the meantime:

```
@{
    VerifyExtraction = $false
    ExtractReferencedServerScopedElements = $false
    IgnorePermissions = $true
    IgnoreUserLoginMappings = $true
}.GetEnumerator() | % { $options.($_.Name) = $_.Value }
```

Though obviously it would need to include some error handling so it doesn't try to set the value of a non-existent object property.
