### ISSUE TITLE
Request for comment: Defaulting Invoke-DbaQuery to Non-pooled connection

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dbatools#8491]
### Summarize Command's Functionality

Considering the solution for [Can't drop temp stored procs](https://github.com/dataplat/dbatools/issues/8472) and the fact that `Invoke-Sqlcmd` uses non-pooled by default, I'd like to propose that Invoke-DbaQuery does too.

The alternative is that we parse the SQL for temp objects and force it to Non-pooled the way we detect and force it for Credentialed (not integrated) Windows Auth.

In order to perfectly detect a temp object, we'd have to add 14MB of DLLs.

```
$parseoptions = New-Object Microsoft.SqlServer.Management.SqlParser.Parser.ParseOptions
$parseoptions .BatchSeparator = $BatchSeparator

$sql = "CREATE PROC #DropStatistics
AS
SELECT 1
GO
drop procedure #DropStatistics
go"

$parser = [Microsoft.SqlServer.Management.SqlParser.Parser.Parser]::Parse($sql, $parseoptions )
$parser.Script.Tokens | Where-Object { $PSItem.Text.StartsWith('#') }
```

We can also use the parser within our own parsing (which is currently regex, I believe).

The downside to parsing is that it will slow down the import of dbatools by 130ms and increase the size by 14MB uncompressed.

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by andreasjordan** [comment]
The more I work with connections, the more I dislike connection pooling. For the normal admin work, we just need one connection and fire up some statements to get some data or change some config. We are all alone - so there is no need for connection pooling.

We could change Invoke-DbaQuery to have a deeper look at the $SqlInstance parameter. And if it is just a string, the open a non-pooled connection. But if it is already a Server SMO object, then don't touch it but just use it.

**Comment by potatoqualitee** [comment]
Perfect!

**Comment by andreasjordan** [comment]
This would also prevent a Server SMO object going again through Connect-DbaInstance. This would speed up things a lot if you use Invoke-DbaQuery for massive querys. Because now, every call also runs the connect part in Connect-DbaInstance and issues a "SELECT 'dbatools is opening a new connection''' - so you always have two roundtrips to the server for every call to Invoke-DbaQuery.
