### ISSUE TITLE
-StandbyDirectory parm not restoring DB in Standby mode

### ISSUE THREAD

**Issue by skreebydba** [dataplat/dbatools#8499]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

No error encountered.  Command not behaving as expected.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
$files = Get-ChildItem C:\temp\ftp;
$params = @{
SqlInstance = 'localhost'
DestinationFilePrefix = 'FTP'
DatabaseName ='WWI_FTP'
NoRecovery = $true
WithReplace = $true
Continue = $true
StandbyDirectory = 'C:\temp\ftp\standby'
}

$files | Restore-DbaDatabase @params ;
```

### Please confirm that you are running the most recent version of dbatools

1.1.81

### Other details or mentions

According to the documentation, including parm -StandbyDirectory should restore the database in standby mode.  I've generated the scripts and the STANDBY = stanbydirectory parm is not being added.

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                           
----                           -----                                                                           
PSVersion                      5.1.19041.1682                                                                  
PSEdition                      Desktop                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                         
BuildVersion                   10.0.19041.1682                                                                 
CLRVersion                     4.0.30319.42000                                                                 
WSManStackVersion              3.0                                                                             
PSRemotingProtocolVersion      2.3                                                                             
SerializationVersion           1.1.0.1                                                                         

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU16-GDR) (KB5014353) - 15.0.4236.7 (X64)   May 29 2022 15:55:47   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19044: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.8.4510.0

**Comment by ALZDBA** [comment]
what good would a standby directory be if you use the parameter "NoRecovery = $true" 
I guess these parameters are mutually excluding and norecovery precedes standby.
Try it not specifying the parameter NoRecovery

**Comment by ALZDBA** [comment]
on top of that it does not rename the filenames making restores to the same location with an alternate dbname impossible without explicitly specifying all filenames

**Comment by skreebydba** [comment]
I did start from that example and removing the norecovery parm worked.  I get blinded by the power of DBATools!  :)  Thanks much for the reply.
