### ISSUE TITLE
Backupset Description field

### ISSUE THREAD

**Issue by ChrisWoods1977** [dataplat/dbatools#8505]
### Summarize Functionality

We have several jobs/processes that create backups. For all those jobs/processes within tsql, we populate the Description field in the msdb..backupset table with the job/process name. I'd like to be able to do the same with my powershell processes that create backups. 

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

For the Backup-DbaDatabase command, please add a new param called -Description that is a free form string value that is then used to execute the WITH description = 'blah' feature when taking a backup.

**Comment by andreasjordan** [comment]
That should be easy, as the SMO we use (Microsoft.SqlServer.Management.Smo.Backup) has a property BackupSetDescription that we can set.
