### ISSUE TITLE
Import-DbaCsv failed in VSCode

### ISSUE THREAD

**Issue by akselbork** [dataplat/dbatools#8512]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

VERBOSE: [10:34:07][Import-DbaCsv] Started at 08/31/2022 10:34:07
VERBOSE: [10:34:07][Import-DbaCsv] Schema not specified, using dbo
VERBOSE: [10:34:07][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server 
object
VERBOSE: [10:34:07][Connect-DbaInstance] authentication method is 'local integrated'
VERBOSE: Performing the operation "Starting transaction in test" on target "computer\testsql".
New-Object : Cannot find type [Microsoft.Data.SqlClient.SqlCommand]: verify that the assembly containing this type is loaded.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.127\allcommands.ps1:64791 char:27
+ ...   $sqlcmd = New-Object Microsoft.Data.SqlClient.SqlCommand($sql, $sql ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.127\allcommands.ps1:64795 char:21
+                 if (($sqlcmd.ExecuteScalar()) -eq 0) {
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

New-Object : Cannot find type [Microsoft.Data.SqlClient.SqlCommand]: verify that the assembly containing this type is loaded.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.127\allcommands.ps1:64812 char:27
+ ...   $sqlcmd = New-Object Microsoft.Data.SqlClient.SqlCommand($sql, $sql ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

New-Object : Cannot find type [Microsoft.Data.SqlClient.SqlCommand]: verify that the assembly containing this type is loaded.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.127\allcommands.ps1:64815 char:28
+ ...  $sqlcmd2 = New-Object Microsoft.Data.SqlClient.SqlCommand($sql2, $sq ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.127\allcommands.ps1:64819 char:21
+ ...         if (($sqlcmd.ExecuteScalar()) -eq 0 -and ($sqlcmd2.ExecuteSca ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

VERBOSE: [10:34:08][Import-DbaCsv] users.csv
Unable to find type [Microsoft.Data.SqlClient.SqlBulkCopyOptions].
At C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.127\allcommands.ps1:64853 char:42
+ ... kCopyOptions = ([Microsoft.Data.SqlClient.SqlBulkCopyOptions]::Defaul ...
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Data....BulkCopyOptions:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

VERBOSE: Performing the operation "Performing import from C:\Users\admin\test\users.csv" on target "computer\testsql".
WARNING: [10:34:08][Import-DbaCsv] Failure | Unable to find type [Microsoft.Data.SqlClient.SqlBulkCopyOptions].
VERBOSE: [10:34:08][Import-DbaCsv] Total Elapsed Time for everything: 0.22 seconds

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

$PARAM = @{
    Path            = "C:\Users\admin\test\users.csv"
    SqlInstance     = "computer\testsql"
    Database        = "test"
    AutoCreateTable = $true
    Delimiter       = ";"
    encoding        = "UTF7"
    Table           = "test"
}

Import-DbaCsv @param -Verbose

### Please confirm that you are running the most recent version of dbatools

1.1.127

### Other details or mentions

It works if I run the command in the "old" PowerShell consol or PowerShell ISE (both normal or as administrator)

I ♥ PS > $PARAM = @{
    Path            = "C:\Users\admin\test\users.csv"
    SqlInstance     = "computer\testsql"
    Database        = "test"
    AutoCreateTable = $true
    Delimiter       = ";"
    encoding        = "UTF7"
    Table           = "test"
}

Import-DbaCsv @param -Verbose
VERBOSE: [11:33:06][Import-DbaCsv] Started at 08/31/2022 11:33:06
VERBOSE: [11:33:06][Import-DbaCsv] Schema not specified, using dbo
VERBOSE: [11:33:06][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
VERBOSE: [11:33:06][Connect-DbaInstance] authentication method is 'local integrated'
VERBOSE: Performing the operation "Starting transaction in test" on target "computer\testsql".
VERBOSE: [11:33:06][Import-DbaCsv] Table does not exist
VERBOSE: Performing the operation "Creating table test" on target "computer\testsql".
VERBOSE: [11:33:06][New-SqlTable] Successfully created table dbo.test with the following column definitions:
 [Project Code] nvarchar(MAX)
 [Customer Name] nvarchar(MAX)
 [Street] nvarchar(MAX)
 [City] nvarchar(MAX)
 [Postal Code] nvarchar(MAX)
 [Item Description] nvarchar(MAX)
 [Serial Number] nvarchar(MAX)
 [MAC address] nvarchar(MAX)
 [Actual Arrival at Customer] nvarchar(MAX)
 [Shipping Instructions] nvarchar(MAX)
 [Contact First Name] nvarchar(MAX)
 [Contact Last Name] nvarchar(MAX)
 [Contact Number] nvarchar(MAX)
VERBOSE: [11:33:06][New-SqlTable] This is inefficient but allows the script to import without issues.
VERBOSE: [11:33:06][New-SqlTable] Consider creating the table first using best practices if the data will be used in production.
VERBOSE: [11:33:06][Import-DbaCsv] Starting bulk copy for users.csv
VERBOSE: Performing the operation "Performing import from C:\Users\admin\test\users.csv" on target "computer\testsql".
VERBOSE: Performing the operation "Finalizing import" on target "computer\testsql".
VERBOSE: [11:33:06][Import-DbaCsv] 219 total rows copied

ComputerName  : computer
InstanceName  : TESTSQL
SqlInstance   : computer\TESTSQL
Database      : test
Table         : test
Schema        : dbo
RowsCopied    : 219
Elapsed       : 133,64 ms
RowsPerSecond : 1659,1
Path          : C:\Users\admin\test\users.csv

VERBOSE: [11:33:07][Import-DbaCsv] Total Elapsed Time for everything: 0.16 seconds

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64) 
Sep 24 2019 13:48:23 
Copyright (C) 2019 Microsoft Corporation
Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19044: ) (Hypervisor)

### .NET Framework Version

.NET Framework 4.8.4515.0

**Comment by potatoqualitee** [comment]
Thanks for the report. Can you please open/close VS Code, Run `Get-Module`, paste it here, run the PowerShell command, then run `Get-Module` again and paste that too.

If `SqlServer` is never loaded, I'm going to lean to this being an issue with have to file with microsoft re: https://github.com/dataplat/dbatools/issues/8478

**Comment by andreasjordan** [comment]
I am closing this issue now, but can reopen is problem still exists.
