### ISSUE TITLE
[Update-DbaInstance] Error while looking for SQL Server installations on <---ComputerName--->

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dbatools#8524]
### Discussed in https://github.com/dataplat/dbatools/discussions/8523

<div type='discussions-op-text'>

<sup>Originally posted by **DavidRaphaelP** September  5, 2022</sup>
Hello !
I want to use the Update-DbaInstance function.
When I am using, it I've got these messages:
![image](https://user-images.githubusercontent.com/65810259/188497415-cc32884e-1006-4e1c-8538-10f6cb624668.png)
I use the Install-DbaInstance function to get the Instance installed.
I setup the "Path.SQLServerUpdates" before execute the Update-DbaInstance command.
What I have to do to fix this problem ?</div>

**Comment by andreasjordan** [comment]
The command is failing inside of the internal command Get-SQLInstanceComponent while reading the registry. There is not exception, but just no instance found.

Seeing the computername starting with "WIN-": Is it a Windows 10 installation? There might be different registry keys.

The internal command have some debug logging, but as it throws an exeption, I think that the messages are not logged. So one plan would be to refactor this command to definitly write some messages that could help us.

Other plan would be to have a look at the registry on that maschine without dbatools.

**Comment by andreasjordan** [comment]
Will try to find some time in the next days, but can not guarantee....

**Comment by DavidRaphaelP** [comment]
To give you more details, it's a "Windows Server 2016 Evaluation"

**Comment by andreasjordan** [comment]
I grabbed the relevant code from Get-SQLInstanceComponent and added some Write-Host lines:

```

$Component = 'SSDS'
$componentNameMap = @(
    [pscustomobject]@{
        ComponentName = 'SSAS';
        DisplayName   = 'Analysis Services';
        RegKeyName    = "OLAP";
    },
    [pscustomobject]@{
        ComponentName = 'SSDS';
        DisplayName   = 'Database Engine';
        RegKeyName    = 'SQL';
    },
    [pscustomobject]@{
        ComponentName = 'SSRS';
        DisplayName   = 'Reporting Services';
        RegKeyName    = 'RS';
    }
);

$reg = [Microsoft.Win32.RegistryKey]::OpenBaseKey('LocalMachine', 'Default')
$baseKeys = "SOFTWARE\\Microsoft\\Microsoft SQL Server", "SOFTWARE\\Wow6432Node\\Microsoft\\Microsoft SQL Server";
if ($reg.OpenSubKey($baseKeys[0])) {
    $regPath = $baseKeys[0];
} elseif ($reg.OpenSubKey($baseKeys[1])) {
    $regPath = $baseKeys[1];
} else {
    throw "Failed to find any regkeys on $env:computername"
}

Write-Host "Using regPath: $regPath"

$regKey = $reg.OpenSubKey("$regPath");
if ($regKey.GetSubKeyNames() -contains "Instance Names") {
    foreach ($componentName in $Component) {
        $componentRegKeyName = $componentNameMap |
            Where-Object { $_.ComponentName -eq $componentName } |
            Select-Object -ExpandProperty RegKeyName;
        $regKey = $reg.OpenSubKey("$regPath\\Instance Names\\{0}" -f $componentRegKeyName);
        if ($regKey) {
            foreach ($regValueName in $regKey.GetValueNames()) {
                if ($componentRegKeyName -eq 'RS' -and $regValueName -eq 'PBIRS') { continue } #filtering out Power BI - not supported
                if ($componentRegKeyName -eq 'RS' -and $regValueName -eq 'SSRS') { continue }  #filtering out SSRS2017+ - not supported
                            
                Write-Host "Found Instance Name: $regValueName in $regPath"
                            
                #$result = Get-SQLInstanceDetail -RegPath $regPath -Reg $reg -RegKey $regKey -Instance $regValueName;
                #$result | Add-Member -Type NoteProperty -Name InstanceType -Value ($componentNameMap | Where-Object { $_.ComponentName -eq $componentName }).DisplayName -PassThru
            }
        }
    }
} elseif ($regKey.GetValueNames() -contains 'InstalledInstances') {
    $isCluster = $false;
    $regKey.GetValue('InstalledInstances') | ForEach-Object {
                    
        Write-Host "Found InstalledInstance: $_ in $regPath"

        #Get-SQLInstanceDetail -RegPath $regPath -Reg $reg -RegKey $regKey -Instance $_
    };
} else {
    throw "Failed to find any instance names on $env:computername"
}

```

Please execute this code on the target server to see if we can read the registry.

You can also execute it from another computer using `Invoke-Command -ComputerName SQL01 -ScriptBlock { ... }`

**Comment by DavidRaphaelP** [comment]
Yes, I have access to regedit.exe

**Comment by andreasjordan** [comment]
On my lab it looks like this:

![image](https://user-images.githubusercontent.com/66946165/189096848-0d0dd543-69ec-4702-aee6-2c056f4b08a6.png)

**Comment by DavidRaphaelP** [comment]
Mine look like this:
![image](https://user-images.githubusercontent.com/65810259/189097262-837bef32-b18e-448e-b796-9f8506a44e50.png)

**Comment by andreasjordan** [comment]
So this should return "MSS_DAVID_PPR":

```
$reg = [Microsoft.Win32.RegistryKey]::OpenBaseKey('LocalMachine', 'Default')
$regKey = $reg.OpenSubKey("SOFTWARE\\Microsoft\\Microsoft SQL Server\\Instance Names\\SQL")
$regKey.GetValueNames()
```

**Comment by DavidRaphaelP** [comment]
![image](https://user-images.githubusercontent.com/65810259/189099024-b7f5c593-2ebc-4d5f-8d53-1310a912d7e9.png)
"Impossible d’appeler une méthode dans une expression Null" means "Impossible to call a method in a Null expression"

**Comment by andreasjordan** [comment]
So we can not access that part of the registry.

How about:

```
$reg = [Microsoft.Win32.RegistryKey]::OpenBaseKey('LocalMachine', 'Default')
$regKey = $reg.OpenSubKey("SOFTWARE\\Microsoft\\Microsoft SQL Server")
$regKey.GetSubKeyNames()
```

```
$reg = [Microsoft.Win32.RegistryKey]::OpenBaseKey('LocalMachine', 'Default')
$regKey = $reg.OpenSubKey("SOFTWARE\\Microsoft\\Microsoft SQL Server\\Instance Names")
$regKey.GetSubKeyNames()
```

**Comment by DavidRaphaelP** [comment]
![image](https://user-images.githubusercontent.com/65810259/189099912-100d8fd0-e4a4-4ffc-849b-a3493c7510a2.png)

**Comment by andreasjordan** [comment]
So you don't get the subkey "Instance Names" returned. As you run this locally: Are you using an elevated powershell?

**Comment by DavidRaphaelP** [comment]
No, it's not an elevated powershell

**Comment by andreasjordan** [comment]
Then try that.

**Comment by andreasjordan** [comment]
Or try to run the code from an other computer using Invoke-Command.

**Comment by DavidRaphaelP** [comment]
Same result with an elevated powershell:
![image](https://user-images.githubusercontent.com/65810259/189102406-f653b587-088c-4053-b500-6b933bdf0fd8.png)

**Comment by andreasjordan** [comment]
Can you try from a different system with Invoke-Command? And do you have other SQL Server maschines where you can try that?
Looks like there is something wrong with the registry...

**Comment by potatoqualitee** [comment]
yeah unfortunately this looks like a bad system. we'll keep an eye out to see if faulty system installs continue. Thanks so much for taking a look at this, @andreasjordan .

**Comment by potatoqualitee** [comment]
(This may also be a localization issue in install-dbainstance? we should keep an eye out)
