### ISSUE TITLE
Server object and a database properties retain old value

### ISSUE THREAD

**Issue by olegstrutinskii** [dataplat/dbatools#8528]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

It not error, it is most likely behavior, how server object created, manipulated and cached in PowerShell.

### Steps to Reproduce

```powershell

#we run this under Active Directory Account [LOCAL\MyUser]

#create server connection object 
$server = Connect-DbaInstance -SqlInstance 'SQLServer1'

$backupFiles | Restore-DbaDatabase -SqlInstance $server  -Database 'db1'

# After restore, the user [LOCAL\MyUser] will be the owner of the database 'db1'

Set-DbaDbOwner -SqlInstance $server -Database 'db1' -TargetLogin 'sa'

Test-DbaDbOwner -SqlInstance $server -Database 'db1' -TargetLogin 'db1Owner'

ComputerName : SQLServer1
CurrentOwner : LOCAL\MyUser
Database     : db1
DBState      : Normal
InstanceName : MSSQLSERVER
OwnerMatch   : False
SqlInstance  : SQLServer1
TargetOwner  : db1Owner

# We see an user [LOCAL\MyUser] still database owner

#Lets try another way to check a database owner
#Will use server name instead of connection object - $server.name or 'SQLServer1'

Test-DbaDbOwner -SqlInstance 'SQLServer1' -Database 'db1' -TargetLogin 'db1Owner'

ComputerName : SQLServer1
CurrentOwner : sa
Database     : db1
DBState      : Normal
InstanceName : MSSQLSERVER
OwnerMatch   : False
SqlInstance  : SQLServer1
TargetOwner  : db1Owner

# as you can see, in second run with server name specified as string we get current data

```

### Please confirm that you are running the most recent version of dbatools

1.1.129

### Other details or mentions

Think this behavior with server object may affect commands to function properly

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                   
----                           -----                                                                                                                                                   
PSVersion                      5.1.19041.1645                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                 
BuildVersion                   10.0.19041.1645                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                         
WSManStackVersion              3.0                                                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                                                     
SerializationVersion           1.1.0.1                                                                                                                                                 

### SQL Server Edition and Build number

does not matter

### .NET Framework Version

.NET Framework 4.8.4470.0

**Comment by potatoqualitee** [comment]
thanks @olegstrutinskii -- can you try without creating a $server object first?

**Comment by andreasjordan** [comment]
This is a bug in the SMO: https://github.com/microsoft/sqlmanagementobjects/issues/40

I hoped to have provided a workaround in our code:
https://github.com/dataplat/dbatools/blob/1ab9070d4161c519f5c242989cfcc351b87b19d4/functions/Set-DbaDbOwner.ps1#L148-L150

But maybe it does not work, will have a look...

**Comment by andreasjordan** [comment]
I can reproduce, if I open the connection before creating the database (like you did):

![image](https://user-images.githubusercontent.com/66946165/189140364-49a03862-6adb-4408-8dd9-9bd0213f91de.png)


But if I open the connection after I created the database, it works:

![image](https://user-images.githubusercontent.com/66946165/189140493-e5e37c65-ddd7-409c-86e8-41bb5abc11be.png)

**Comment by andreasjordan** [comment]
The `.Alter()` is failing to set the new Owner if the database was created using the `$server` SMO. Will try to find the root cause...

**Comment by olegstrutinskii** [comment]
W/o use of the server object it will work normally

> This is a bug in the SMO: [microsoft/sqlmanagementobjects#40](https://github.com/microsoft/sqlmanagementobjects/issues/40)
> 
> I hoped to have provided a workaround in our code:
> 
> https://github.com/dataplat/dbatools/blob/1ab9070d4161c519f5c242989cfcc351b87b19d4/functions/Set-DbaDbOwner.ps1#L148-L150
> 
> But maybe it does not work, will have a look...

I know about this "bug"

In my situation even $server.Refresh() not working, you still get wrong dbowner.

I saw this situation in one of my scripts, usually i'm not using the "connection object"

**Comment by andreasjordan** [comment]
I guess: If we create the database using $server, the SMO is not filled - especially the Owner property. `.SetOwner()` only changes the setting in the database, but not in the SMO. The `.Alter()` then does not notice that there is a missmatch as the property in the SMO is not filled.

I can fix this by getting the Owner right in front of the .SetOwner() to fill the SMO. Will provide a PR.

![image](https://user-images.githubusercontent.com/66946165/189144285-3f3943b9-1af0-472b-a9cc-2b9031782ce9.png)

![image](https://user-images.githubusercontent.com/66946165/189144361-0348b1a1-2509-43a0-bd6f-8d689ef2f917.png)
