### ISSUE TITLE
Export-DbaBinaryFile - Description for Example #4 doesn't match code

### ISSUE THREAD

**Issue by paschott** [dataplat/dbatools#8533]
We see this in the Get-Help:

    -------------------------- EXAMPLE 4 --------------------------

     PS C:\> Export-DbaBinaryFile -SqlInstance sqlcs -Database employees -Table photos -Query "SELECT [FileName],
    [Data] FROM [employees].[dbo].[photos] WHERE FirstName = 'Potato' and LastName = 'Qualitee'" -FilePath
    C:\temp\PotatoQualitee.jpg

    Exports all binary files from the photos table in the employees database on sqlcs to C:\temp\exports. Uses the
    fname and data columns for the filename and binary data.

I would expect something more like:
Export the Data from the photos table in the employees database on the sqlcs server for FirstName "Potato" and LastName "Qualitee". Export to a file named "C:\temp\PotatoQualitee.jpg"

I'm guessing a little bit at what this should do. Not sure if there's some way to use a column or computed value from the Query to pass over as a filename parameter.

**Comment by potatoqualitee** [comment]
Thank you! Fixing this today with some help generated by GitHub Copilot :O

**Comment by andreasjordan** [comment]
Can we close this as fixed?

**Comment by andreasjordan** [comment]
Will close this now, but can reopen if needed.
