### ISSUE TITLE
Get-DbaDbView does not return InstanceName

### ISSUE THREAD

**Issue by PowerDBAKlaas** [dataplat/dbatools#8538]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

no error

### Steps to Reproduce

```powershell
Get-DbaDbView -SqlInstance MySQLServer | Select-Object InstanceName, Schema, Name
```

### Please confirm that you are running the most recent version of dbatools

Major  Minor  Build  Revision
-----  -----  -----  --------
1      1      132    -1

### Other details or mentions

The value of [InstanceName] should be identical to other functions that query the Database level, such as Get-DbaDbUser.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      5.1.17763.2931
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.2931
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU17) (KB5016394) - 15.0.4249.2 (X64)   Jul 22 2022 12:11:33   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.8.03761
Full        4.8.03761
Client      4.0.0.0

**Comment by andreasjordan** [comment]
Thanks for reporting this, I'll open a PR to fix this in a second...

**Comment by PowerDBAKlaas** [comment]
Thank you @andreasjordan @potatoqualitee !
