### ISSUE TITLE
`Get-DbaUserPermission` - `$dbSQL` Mismatched Case 

### ISSUE THREAD

**Issue by mattcargile** [dataplat/dbatools#8539]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?
```powershell
WARNING: [17:02:51][Get-DbaUserPermission] Failed to create or use STIG schema for 
database [case-sensitive-db] on caseSenstiveSql | Invalid column name 'member'.
```
### Steps to Reproduce

```powershell
# Run below on Case Sensitive collation instance/database
Get-DbaUserPermission -SqlInstance caseSenstiveSql -Database case-sensitive-db
```

### Please confirm that you are running the most recent version of dbatools

Issue exists in current iteration of `development` branch.

### Other details or mentions

This line should be corrected from `member` to `Member`.

https://github.com/dataplat/dbatools/blob/master/functions/Get-DbaUserPermission.ps1#L170

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2014 (SP3) (KB4022619) - 12.0.6024.0 (X64)
        Sep  7 2018 01:37:51
        Copyright (c) Microsoft Corporation
        Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: )

### .NET Framework Version

.NET 6.0.8

**Comment by potatoqualitee** [comment]
TY! This will be fixed in the next release 👍🏼
