### ISSUE TITLE
Copy-DbaDatabase -SetSourceReadOnly  and -WithReplace bug or feature?

### ISSUE THREAD

**Issue by MuschPu** [dataplat/dbatools#8548]
Copy-DbaDatabase -Source $old -Destination $new -Database dba -BackupRestore -SharedPath \\xyz\restore -SetSourceReadOnly

=> the destination database is (ReadOnly)

Copy-DbaDatabase -Source $old -Destination $new -Database dba -BackupRestore -SharedPath \\xyz\restore -SetSourceReadOnly  **-WithReplace**

=> the destination database is (ReadWrite)

regardless of whether the destination database existed or not

**Comment by potatoqualitee** [comment]
Hey @MuschPu,  we do not take the destination database properties into account when determining the ultimate state of the destination. If you would like it to be readonly, you would have to use Set-DbaDbState -ReadOnly first, then execute copy -- that way, it can see that the source is readonly and then set it that way in the destination. alternatively, you can set the destination's db state using the same command.
