### ISSUE TITLE
Request - Import CSV - read CSVs compressed with gzip

### ISSUE THREAD

**Issue by match-gabeflores** [dataplat/dbatools#8554]
### Summarize Functionality

We handle several files that are about 200mbs compressed with gzip. Uncompressed, they're over a gigabytes. Request is for a new flag to enable importing CSVs compressed with gzip. 

Pandas has this feature and it's very convenient.

If this is out of scope of the project, feel free to close. 

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by potatoqualitee** [comment]
hey gabe, thanks for the  request! we use LumenWorksCsvReader behind the scenes and it doesn't look like it supports compression :/

**Comment by potatoqualitee** [comment]
oh, awesome! do you know how to do that, @MarkPflug ? We do not have Export-DbaCsv but I'm not sure I see a need. Importing needed to be sped up in a specific way for SQL Server, whereas Export can be Invoke-DbaQuery | Export-Csv

**Comment by potatoqualitee** [comment]
i recall you making the c# mod to invoke-dbacsv -- you can do more in C# there too if you'd like

**Comment by match-gabeflores** [comment]
> @match-gabeflores Do your files normally end with .csv.gz, or something else?

Yes, the standard is typically `.csv.gz`

**Comment by match-gabeflores** [comment]
Thanks @MarkPflug ! Can't wait to try this out. This will simplify our workflow considerably

**Comment by AntiTenzor** [comment]
> @match-gabeflores this will be part of dbatools 2.0 which will be available in a couple weeks or a month

This is extremely necessary and "must have" option.
In nowdays nobody transmits huge uncompressed CSV as raw text.

Direct export to CSV.GZ is also almost the default usecase.
(Default GZipStream makes this modification very straightforward)

I'm very happy to hear this.
Nice job!

**Comment by potatoqualitee** [comment]
hmm! maybe we'll do an Export-DbaCsv that does that. I already have the code for GZipStream
