### ISSUE TITLE
Invoke-DbaDbMirroring restore database on the witness by default

### ISSUE THREAD

**Issue by rferraton** [dataplat/dbatools#8573]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When using default behavior of the Invoke-DbaDbMirroring, using -Force, the source database is restore on the witness

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Invoke-DbaDbMirroring -Primary "server1" -Mirror "server2" -Witness "server3" -SharedPath "\\\\SHARE\sqlmirror" -Database "adventurework" -Force

### Please confirm that you are running the most recent version of dbatools

1.1.136

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                                      
----                           -----                                                                                                                                                                                      
PSVersion                      5.1.17763.1007                                                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                    
BuildVersion                   10.0.17763.1007                                                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                                                            
WSManStackVersion              3.0                                                                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                                                                        
SerializationVersion           1.1.0.1                                                                                                                                                                                    

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU18) (KB5017593) - 15.0.4261.1 (X64)   Sep 12 2022 15:07:06   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.7.03190
Full        4.7.03190
Client      4.0.0.0

**Comment by potatoqualitee** [comment]
Thanks for the report! I put in a PR to fix the issue.
