### ISSUE TITLE
Using SQLInstance of .\<instance> doesn't resolve 

### ISSUE THREAD

**Issue by simonsabin** [dataplat/dbatools#8574]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

```
WARNING: [19:51:13][Invoke-DbaQuery] Failure | A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SNI_PN11, error: 26 - Error Locating Server/Instance Specified)
```

### Steps to Reproduce

```powershell
new-object Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter(".\instance")
```

### Please confirm that you are running the most recent version of dbatools

1.1.137

### Other details or mentions

Old issue that was never resolved https://github.com/dataplat/dbatools/issues/5968 

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

any

### SQL Server Edition and Build number

n/a

### .NET Framework Version

.NET 6.0.6

**Comment by simonsabin** [comment]
The issue is with https://github.com/dataplat/dbatools/blob/588e3cbce6bb90b3744cd19d0f0b939f3335e85d/bin/projects/dbatools/dbatools/Parameter/DbaInstanceParameter.cs#L267-L273

The _ComputerName should be "."

**Comment by potatoqualitee** [comment]
aw yeah, works now and i also added an integration test to prove it!
