### ISSUE TITLE
Invoke-DbaAgFailover.ps1 to include -Database switch

### ISSUE THREAD

**Issue by bimbaba** [dataplat/dbatools#8578]
### Summarize Command's Functionality

I would like to request for the Invoke-DbaAgFailover cmdlet to include a switch to select specific databases to be failed over as part of the AVG. I have a case where dbatools wont work because all the databases in the AVG arent primary replicas and there's no option to failover specific databases

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

Invoke-DbaAgFailover -SqlInstance myinstance  -AvailabilityGroup myAG1 -Databases testdb,testdb1

**Comment by andreasjordan** [comment]
I don't understand this. You can only failover AvailabilityGroups and not individual databases.

**Comment by potatoqualitee** [comment]
gonna close since it is not possible but we can reopen if it is and we didnt know
