### ISSUE TITLE
Copy-DbaLinkedServer does not use credential passed by -SourceSqlCredential 

### ISSUE THREAD

**Issue by ghkamfung** [dataplat/dbatools#8586]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

I use a variable to pass a credential to -SourceSqlCredential but the cmdlet does not use it.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
PS > $devadm=Get-Credential 
**User is domain\dba**
PS > Copy-DbaLinkedServer -SourceSqlCredential $devadm -Source DUATSQL\PROJECT1 -Destination 10.161.0.145 -DestinationSqlCredential $devadm
WARNING: [17:38:49][Get-DecryptedObject] Can't establish local DAC connection on DUATSQL\PROJECT1. | Login failed for
user 'domain\<current desktop user>'.

### Please confirm that you are running the most recent version of dbatools

0.0

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      5.1.14393.5127
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.5127
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

SQL Server 2014 Standard Edition

### .NET Framework Version

.NET Framework 4.7.3946.0

**Comment by potatoqualitee** [comment]
Thanks for the report! I'll check this out

**Comment by potatoqualitee** [comment]
Looks like DAC does need not use the credential, that may be a limitation of DAC that we need to document. Do you know, @andreasjordan ?

Also, @ghkamfung -- if your module version is showing 0.0, that may mean that you're importing the psm1. We recommend importing the psd1 as that one exports only the commands that are needed externally as an end-user.

**Comment by andreasjordan** [comment]
The $connString is used in a scriptblock on the remote side via Invoke-Command2 (see line 130). This Invoke-Command2 call is using the given credential, so we can use integrated security here.

But there is also a code for a pre opened DAC - so @ghkamfung could try this:
```
$devadm = Get-Credential
$source = Connect-DbaInstance -SqlInstance DUATSQL\PROJECT1 -SqlCredential $devadm -DedicatedAdminConnection
Copy-DbaLinkedServer -Source $source -Destination 10.161.0.145 -DestinationSqlCredential $devadm
```

**Comment by potatoqualitee** [comment]
ahh so invoke-command2 is indeed being initiated by the non sourcecredential (which is sql auth and not windows auth?) but should still work becauase it's a DAC and presumably, the account has admin access to the machine?

**Comment by andreasjordan** [comment]
"User is domain\dba" - so it's windows auth.

**Comment by ghkamfung** [comment]
Thanks for your quick response.
I will try the .psd1 (I still beginner level in PowerShell)
and will also try the $source approach.
Kam Fung


Andreas Jordan ***@***.***> 於 2022年10月12日週三 下午7:25寫道：

**Comment by andreasjordan** [comment]
Hi @ghkamfung - did you have a chance to test this?

**Comment by andreasjordan** [comment]
Will close this now, but can reopen if needed.
