### ISSUE TITLE
Set-DbaSpConfigure - Value out of range

### ISSUE THREAD

**Issue by ksl28** [dataplat/dbatools#8588]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

PSMessageDetails      : 
Exception             : System.Exception: Value out of range for emeadkhovsql32 ( <-> )
TargetObject          : 
CategoryInfo          : InvalidArgument: (:) [Write-Error], Exception
FullyQualifiedErrorId : dbatools_Set-DbaSpConfigure,Stop-Function
ErrorDetails          : Value out of range for emeadkhovsql32 ( <-> )
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Stop-Function, C:\Users\krle\Documents\PowerShell\Modules\dbatools\1.1.139\allcommands.ps1: line 149023
                        at Set-DbaSpConfigure<Process>, C:\Users\krle\Documents\PowerShell\Modules\dbatools\1.1.139\allcommands.ps1: line 120793
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}

### Steps to Reproduce

```powershell
$SQLConnection = Connect-DbaInstance -SqlInstance "emeadkhovsql32"
$SQLConnection | Set-DbaSpConfigure -Name RemoteDacConnectionsEnabled -Value 0
```

If you use the -SQLInstance directly with Set-DbaSpConfigure then it works.
```powershell
Set-DbaSpConfigure -Name RemoteDacConnectionsEnabled -Value 0 -SQLInstance "emeadkhovsql32"
```

### Please confirm that you are running the most recent version of dbatools

1.1.139

### Other details or mentions

If you use the -SQLInstance directly with Set-DbaSpConfigure then it works.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), VS Code (terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU3) (KB4538853) - 15.0.4023.6 (X64)   Mar  4 2020 00:59:26   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET 6.0.8

**Comment by potatoqualitee** [comment]
Hello @ksl28  - Set-DbaSpConfigure does not support a $server object being piped in -- it supports Get-DbaSpConfigure, so you'd do

```
Get-DbaSpConfigure -SqlInstance $server -Name XPCmdShellEnabled, IsSqlClrEnabled | Set-DbaSpConfigure -Value $false
```
