### ISSUE TITLE
Exemple(s) need for New-DbaAvailabilityGroup with -ReadonlyRoutingConnectionUrl

### ISSUE THREAD

**Issue by rferraton** [dataplat/dbatools#8589]
### Summarize Functionality

There is no exemple of New-DbaAvailabilityGroup with **-ReadonlyRoutingConnectionUrl** 
Because this is not obvious I think it could help

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

May be something like :

`New-DbaAvailabilityGroup -Primary sql1 -Secondary sql2 -Name ag1 -Database pubs, adventurework -ClusterType Wsfc -SeedingMode Manual -FailoverMode Manual -ReadonlyRoutingConnectionUrl "tcp://sql2.domain.lan:1433,tcp://sql1.domain.lan:1433"`

**Comment by potatoqualitee** [comment]
thank you @rferraton -- would you liek to add this PR? If not, I can do it if @andreasjordan approves of this example. I have not used this functionality myself and cannot confirm it works. Or alternatively, if you provide a screenshot that it works, I can add it in a PR if you do not wish to do it.

**Comment by rferraton** [comment]
No I prefer that someone double check the exemple. I did not try it already.
