### ISSUE TITLE
Export-DbaInstance : add switch to hide progress bar

### ISSUE THREAD

**Issue by tivivi63** [dataplat/dbatools#8590]
### Summarize Functionality

`Export-DbaInstance` feature provides progressbar to indicate which topic is being processed while scripting SQL Server instance.
When `Export-DbaInstance` feature is being embedded in custom Powershell method, it might not be worth this progressbar to be displayed.

Can some -HideProgress switch be added to `Export-DbaInstance` parameters, so both standalone and embedded modes can be used?

Thanks,

### Is there a command that is similiar or close to what you are looking for?

No

**Comment by potatoqualitee** [comment]
hey @tivivi63 -- in this case, I tend to use `$ProgressPreference = "SilentlyContinue"`. While we could add a `-Quiet` parameter, our other commands with progress bars do not have this option so it'd deviate from the standard. So I'd just do  `$ProgressPreference = "SilentlyContinue"` at the beginning of the script then  `$ProgressPreference = "Continue"` at the end if you want to change it back.
