### ISSUE TITLE
Export-DbaInstance : add switch to skip automatic subfolder creation

### ISSUE THREAD

**Issue by tivivi63** [dataplat/dbatools#8591]
### Summarize Command's Functionality

`Export-DbaInstance` feature generates scripting files in a folder. Even if `-Path`  value is provided, `Export-DbaInstance` creates its own subfolder. 

When feature is being embedded in custom Powershell method, where timestamped-dedicated folders are already being created, it might be worth deactivating this behavior.

Can some `-SkipSubfolder` switch be added to `Export-DbaInstance` parameters, so both standalone and embedded modes can be used?

Thanks,

### Is there a command that is similiar or close to what you are looking for?

No

**Comment by lancasteradam** [comment]
Hi @tivivi63, there is the option to use the -Force param. What are your thoughts on using this for the different modes you described? It does create a folder with the Server Name, but it does not create the timestamped folder.

https://docs.dbatools.io/Export-DbaInstance

![Export-DbaInstance Force param](https://user-images.githubusercontent.com/68036988/197342919-de9759dd-e7f5-41f1-b3e2-81dc7fee3b07.png)

**Comment by tivivi63** [comment]
`-Force` switch works fine, indeed 👍
Thanks,
