### ISSUE TITLE
Import-DbaCsv: PR 8393 (Add actual progress) causes file lock on CSV, even after Import-DbaCsv command completes or fails

### ISSUE THREAD

**Issue by wsuhoey** [dataplat/dbatools#8593]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

After the addition of https://github.com/dataplat/dbatools/pull/8393 (dbatools version 1.1.105 or higher, through to at least 1.1.140), a file lock is not released on the CSV after the `Import-DbaCsv` command completes (loads all rows), fails or errors out.
A simple `Move-Item` command after the `Import-DbaCsv` command shows this.

`The process cannot access the file because it is being used by another process.`

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Import-DbaCsv ... etc
Move-Item ... etc

This was done in a foreach loop, but I assume it would happen not in a loop.

### Please confirm that you are running the most recent version of dbatools

1.1.140

### Other details or mentions

The new progress bar remains in the integrated console in VS Code even after the file fails, hovering at the bottom below the error. Doing a `Ctrl + C` to cancel it to escape it is required. Confirmed downgrading to `dbatools v1.1.104` (the last release prior to the implementation of the new progress code) does not have the lock on the file.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe), VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2017 (RTM-CU31) (KB5016884) - 14.0.3456.2 (X64) 
	Sep  2 2022 11:01:50 
	Copyright (C) 2017 Microsoft Corporation
	Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

### .NET Framework Version

.NET 6.0.8

**Comment by potatoqualitee** [comment]
Thank you, 👞 ! @MarkPflug  can you take a look? Maybe we just need to write-progress complete? (i havent looked)
