### ISSUE TITLE
Update-DbaMaintenanceSolution -database is case sensitive

### ISSUE THREAD

**Issue by frodr1k** [dataplat/dbatools#8598]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When running "Update-DbaMaintenanceSolution" and providing an optional database name (we dont use master-database for this solution) it always throws the following error  IF we use the wrong case for the naming of the database. Since SQL Server isn't case sensitive with database naming, this is a quite odd problem which causes som problems if differens persons has set up their databases using different caseing scheme. 

```
ComputerName : serverXXXX
InstanceName : MSSQLSERVER
SqlInstance  : serverXXXX
Solution     : CommandExecute
Procedure    : CommandExecute
IsUpdated    : False
Results      : Procedure not installed
```

But if I use the correct casing on the database name it will run through as expected. 

Example:

`Databasename: **MaintDB**`

Wont't work:
`Update-DbaMaintenanceSolution -SqlInstance . -Database maintdb `

Will work: 
` Update-DbaMaintenanceSolution -SqlInstance . -Database MaintDB`

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Must have an external maintenance database such as MaintDB 

Run: `Update-DbaMaintenanceSolution -SqlInstance . -Database maintdb ` 

note the WRONG caseing! You will not get this error on a database using correct caseing. 

### Please confirm that you are running the most recent version of dbatools

Major  Minor  Build  Revision
-----  -----  -----  --------
1      1      136    -1

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), VS Code (terminal)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.1682                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.1682                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Different versions in our estate, same error.

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.8.04084
Full        4.8.04084
Client      4.0.0.0

**Comment by potatoqualitee** [comment]
thanks for the report @frodr1k - can you install the actual ola hallengren directly with the wrong casing, per chance?

**Comment by frodr1k** [comment]
I made a test now:

Database name: "Maint"

```
PS C:\WINDOWS\system32> Install-DbaMaintenanceSolution -SqlInstance . -InstallJobs -BackupLocation "\\some\unc" -cleanuptime 48 -LogToTable -Database MAINT

ComputerName InstanceName SqlInstance Results
------------ ------------ ----------- -------
CLIENTxxx    MSSQLSERVER  CLIENTxxx   Success

```

**Comment by potatoqualitee** [comment]
oh sorry i wasnt clear. i mean can you go to ola.hallengren.com and grab his scripts and put in a miscased db name? I dont think this is on our side, but rather ola's side.

**Comment by frodr1k** [comment]
I hope I understood you correct now. 

I did install on the testserver as outlined in the screenshot. Afterwards I tried to perform an update with the same error when performing upgrade.
![image](https://user-images.githubusercontent.com/24543416/196686599-c44d2e78-9acb-45bd-8243-b6a4fe6a7cef.png)

**Comment by potatoqualitee** [comment]
Thank you for testing! Soto confirm, this appears not to be a problem with the underlying script as it only errors on dbatools?

**Comment by frodr1k** [comment]
Yes the error is in DBAtools. 

I did some more troubleshooting.  It seems to be an error in how Get-DbaModule is connecting the database(s)

I took some of the code from the function and did som testing to prove it. 

Databasename is as in the picture above (Maintdb). If I let the variable $database='Maintdb' it will return a full list of expected functions. But if I change the databasename to 'maintdb' it will output nothing.

Just to be on the safe side. If I use a totally wrong name on the database, that will actually be caught in the logic. 


```
        $SqlInstance=@('.')
        $database='Maintdb'
        foreach ($instance in $SqlInstance) {
            try {
                $server = Connect-DbaInstance -SqlInstance $instance -SqlCredential $SqlCredential -NonPooledConnection
            } catch {
                Stop-Function -Message "Failure" -Category ConnectionError -ErrorRecord $_ -Target $instance -Continue
            }

            $db = $server.Databases[$Database]
            if ($null -eq $db) {
                Stop-Function -Message "Database $Database not found on $instance. Skipping." -Target $instance -Continue
            }
        }
#            $installedProcedures = Get-DbaModule -SqlInstance $server -Database $Database | Where-Object Name -in 'CommandExecute', 'DatabaseBackup', 'DatabaseIntegrityCheck', 'IndexOptimize'
            Get-DbaModule -SqlInstance $server -Database $Database | Where-Object Name -in 'CommandExecute', 'DatabaseBackup', 'DatabaseIntegrityCheck', 'IndexOptimize'

```

**Comment by potatoqualitee** [comment]
i was finding that too! I jumped in to work on it then it got too time consuming

**Comment by frodr1k** [comment]
Thank you both of you! :) Looking forward to test the fix (in next release?)

**Comment by potatoqualitee** [comment]
yep! it's already in v1.1.141
