### ISSUE TITLE
New failure check for Add-DbaAgDatabase 

### ISSUE THREAD

**Issue by begin-dba** [dataplat/dbatools#8603]
### Summarize Functionality

I'm using Add-DbaAgDatabase to rebuild an AG after a restore of all its databases with seeding mode set to automatic..

From times to times the seeding of some dbs fails on sqlserver side with a failure state = 21. In such a case, the seeding never starts and the dmv dm_hadr_physical_seeding_stats is never populated. 

The command never sees that the seeding has failed and waits, a new check could avoid this issue.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

During the step 5/5 of this command, the view dm_hadr_physical_seeding_stats  is used to track failure and progress of the seedings, but, as this view is never populated with this kind of errors, the command just waits for the value of $timeoutSynchronization ( 24 hours ) to fail. 

After a few minutes another dmv dm_hadr_automatic_seeding is updated with 'FAILED' in the current_state field. 

Could you please add a new test in the fifth part of the command, to check also this dmv when the first one doesn't return any row ?

**Comment by andreasjordan** [comment]
Thanks for this feature request - I will have a look. It will just be hard to test...

**Comment by begin-dba** [comment]
Agree :)
At the moment I'm unfortunately able to test it very often ( one out of two time ). 
If needed I can do some tests.

**Comment by andreasjordan** [comment]
I just opened a pull request. Maybe you are able to use this branch for your tests.

**Comment by begin-dba** [comment]
Hi @andreasjordan,

It works like a charm :) 
VERBOSE: [11:19:11][Add-DbaAgDatabase] IsJoined is False, SynchronizationState is NotSynchronizing, waiting for Synchronized.
VERBOSE: [11:19:11][Add-DbaAgDatabase] Current automatic seeding state: CHECK_IF_SEEDING_NEEDED
VERBOSE: [11:19:11][Add-DbaAgDatabase] IsJoined is False, SynchronizationState is NotSynchronizing, waiting for Synchronized.
VERBOSE: [11:19:12][Add-DbaAgDatabase] Current automatic seeding state: CHECK_IF_SEEDING_NEEDED
VERBOSE: [11:19:12][Add-DbaAgDatabase] IsJoined is False, SynchronizationState is NotSynchronizing, waiting for Synchronized.
VERBOSE: [11:19:12][Add-DbaAgDatabase] Current automatic seeding state: FAILED
WARNING: [11:19:12][Add-DbaAgDatabase] Failed while seeding database databasename to server2\InstName. failure_message: Seeding Check Message Timeout.
VERBOSE: [11:19:13][Add-DbaAgDatabase] Current automatic seeding state: FAILED
WARNING: [11:19:13][Add-DbaAgDatabase] Failed while seeding database databasename to server3\InstName. failure_message: Seeding Check Message Timeout.
VERBOSE: [11:19:13][Add-DbaAgDatabase] Current automatic seeding state: FAILED
WARNING: [11:19:13][Add-DbaAgDatabase] Failed while seeding database databasename to server4\InstName. failure_message: Seeding Check Message Timeout.
WARNING: [11:19:13][Add-DbaAgDatabase] Failed while seeding database databasename.
WARNING: [11:19:13][Add-DbaAgDatabase] Failed to join or synchronize database databasename.


Thank you very much 


Best regards

**Comment by begin-dba** [comment]
[dm_hadr_automatic_seeding.csv](https://github.com/dataplat/dbatools/files/9851544/dm_hadr_automatic_seeding.csv)

Here is an extract of the dmv, seems that this columns receives a different value for each attempt. ( This is a 4 node cluster so 3 rows per test ).
