### ISSUE TITLE
Watch-DbaDbLogin trying to write in audited Instance

### ISSUE THREAD

**Issue by begin-dba** [dataplat/dbatools#8616]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Hi all,

I've an issue with the Watch-DbaDblogin function. 
Unless this is just a misunderstanding.

The Doc states that sqlinstance param is The SQL Server that stores the Watch database.
But when I run the command 

**
$instance1 = Connect-DbaInstance -SqlInstance instanceTowatch 
$instance2 = Connect-DbaInstance -SqlInstance instanceToTostoreWatch

$instance1 | Watch-DbaDbLogin -sqlinstance $instance2 -Database Test
**

It answers 

**WARNING: [14:35:14][Write-DbaDbTableData] Error occurred while establishing connection to instanceTowatch | Cannot open database "Test" requested by the login. The login failed.**

Looking at the code, the sqlinstance in param is added to list of servers to watch, then foreach server it tries to write in the Watch table in the audited server itself. 
from my understanding of the documentation it should audit the servers coming from pipeline, file or cms but not from sqlinstance , and store in sqlinstance but not in the servers to audit.
Am I wrong ?

Best regards 

[Test_Watch-DbaDbLogin.txt](https://github.com/dataplat/dbatools/files/9870283/Test_Watch-DbaDbLogin.txt)

### Steps to Reproduce

 $instanceToStore = Connect-DbaInstance -SqlInstance SERV9\LAW7_0009
 $instanceToWatch = Connect-DbaInstance -SqlInstance SERV5\LAW7_0001
 $instanceToWatch  | Watch-DbaDbLogin -sqlinstance $instanceToStore -Database Test

### Please confirm that you are running the most recent version of dbatools

1.1.136

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

SQLServer2019 CU 15

### .NET Framework Version

.NET 6.0.10

**Comment by mattcargile** [comment]
Yes, I just noticed this issue as I was looking at the code. It comes down to Line 191 attempting to `Write-DbaDbTableData` to the current `$instance` into the loop instead of the central `$SqlInstance` passed in. The change was made in [this PR](https://github.com/dataplat/dbatools/pull/8384).

https://github.com/dataplat/dbatools/blob/45b54cb30c8bf1230de7c9e21a3f256255fb8f92/functions/Watch-DbaDbLogin.ps1#L191

The fix appears to be changing `$instance` to `$SqlInstance` for the `-SqlInstance` _parameter_ on the `Write-DbaDbTableData` call which is the _parameter_ passed into the function.

**Comment by mattcargile** [comment]
>Looking at the code, the sqlinstance in param is added to list of servers to watch, then foreach server it tries to write in the Watch table in the audited server itself.

To your point about the below lines, I'd really like to see an `-IncludeSelf` parameter added that would allow the instance passed into `-SqlInstance` to be audited. I would think by default, the `-SqlInstance` wouldn't be audited itself.

https://github.com/dataplat/dbatools/blob/45b54cb30c8bf1230de7c9e21a3f256255fb8f92/functions/Watch-DbaDbLogin.ps1#L121-L127

**Comment by potatoqualitee** [comment]
thank you @mattcargile ! I'll take a look before 2.0

**Comment by mmaagk642** [comment]
@andreasjordan have you had a chance to look at this? I tested it and it is still not working as expected. Was just curious if you had an idea of when this might be resolved? Thanks for your help!

**Comment by andreasjordan** [comment]
Just opened a PR that should fix the issue. I have not included `-IncludeSelf` as I personally think this is not needed.
