### ISSUE TITLE
Get-DbaMemoryUsage does not show any result on non US System

### ISSUE THREAD

**Issue by DiHo78** [dataplat/dbatools#8619]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Running the command Get-DbaMemoryUsage against a German Windows/SQL Server does not return any results. Even $error[0] | select * does not show anything.

![initial error](https://user-images.githubusercontent.com/27739194/198517283-8a9069f6-8577-4c55-825a-02ff0cd80c1f.png)

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference

# Target system needs to be a non-US installation 
Get-DbaMemoryUsage -ComputerName sql2019ger -Verbose -EnableException | ft

```

### Please confirm that you are running the most recent version of dbatools

1.1.127

### Other details or mentions

The issue occurs because inside the function we have the specific counter names hard coded in English.
See: https://github.com/dataplat/dbatools/blob/534f283a26ceb58d92a9b426b301460941d1748b/functions/Get-DbaMemoryUsage.ps1#L67-L77 

I already dug a bit deeper into it and made an additional test with

```powershell

#additional test:

$comp = "sql2019ger"

$Memcounters = '(Total Server Memory |Target Server Memory |Connection Memory |Lock Memory |SQL Cache Memory |Optimizer Memory |Granted Workspace Memory |Cursor memory usage|Maximum Workspace)'

 $Scriptblock = {param ($Memcounters
                )
            <# DO NOT use Write-Message as this is inside of a script block #>
            Write-Verbose -Message "Searching for Memory Manager Counters on $Computer"
            try {
                $availablecounters = (Get-Counter -ListSet '*sql*:Memory Manager*' -ErrorAction SilentlyContinue).paths
                (Get-Counter -Counter $availablecounters -ErrorAction SilentlyContinue).countersamples | Where-Object { $_.Path -match $Memcounters } | ForEach-Object {
                    $instance = (($_.Path.split("\")[-2]).replace("mssql`$", "")).split(':')[0]
                    if ($instance -eq 'sqlserver') { $instance = 'mssqlserver' }
                    [PSCustomObject]@{
                        ComputerName    = $env:computername
                        SqlInstance     = $instance
                        CounterInstance = (($_.Path.split("\")[-2]).replace("mssql`$", "")).split(':')[1]
                        Counter         = $_.Path.split("\")[-1]
                        Pages           = $null
                        Memory          = $_.cookedvalue / 1024
                    }
                }
            } catch {
                <# DO NOT use Write-Message as this is inside of a script block #>
                Write-Verbose -Message "No Memory Manager Counters on $Computer"
            }
            }



Invoke-Command -ComputerName $comp -ScriptBlock $scriptBlock -ArgumentList $Memcounters  | ft

Invoke-Command -ComputerName $comp -ScriptBlock $scriptBlock  | ft
```

The output of commands. The first one returns nothing, second one shows the available counters on the target machine: 
![additional information](https://user-images.githubusercontent.com/27739194/198518997-5615086d-90a7-421f-81b8-5589b6a6d606.png)

Additional test: 
When extending the filter inside of the function with some of the german counter names I get an output
eg  memcounter variable now looks like this:
```powershell
   $Memcounters = '(Total Server Memory |Target Server Memory |Connection Memory |Lock Memory |SQL Cache Memory |Optimizer Memory |Granted Workspace Memory |Cursor memory usage|Maximum Workspace|serverspeicher gesamt |zielserverspeicher |verbindungsspeicher |sql-cachespeicher |optimiererspeicher| erteilter arbeitsbereichsspeicher |maximaler arbeitsbereichsspeicher)'

```
![result](https://user-images.githubusercontent.com/27739194/198521414-4206676f-6982-419e-9f4e-3f984be648a3.png)

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.17763.2931                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.17763.2931                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

For the quick test by myself: 
Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter Evaluation 10.0 <X64> (Build 17763: ) (Hypervisor) 

Error also occurred on a 
Microsoft SQL Server 2014 (SP2-CU4) (KB4010394) - 12.0.5540.0 (X64)   Jan 27 2017 03:40:25   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor) 
and
Microsoft SQL Server 2016 (SP2-CU17-GDR) (KB5014351) - 13.0.5893.48 (X64)   May 24 2022 02:58:22   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor) 

all with German Windows OS

### .NET Framework Version

.NET Framework 4.7.3946.0

**Comment by andreasjordan** [comment]
Maybe those links can help:
* https://stackoverflow.com/questions/5581859/retrieve-performance-counter-value-in-a-language-independent-way
* https://wojciechkulik.pl/csharp/get-a-performancecounter-using-english-name

**Comment by ClaudioESSilva** [comment]
Another one: 

- https://powershellmagazine.com/2013/07/19/querying-performance-counters-from-powershell/

**Comment by andreasjordan** [comment]
As we don't get individual counter instances but filtering with regex, I think the idea to get the localized version by ID will not going to work or will need massive changes to the command.

What we could to is to provide parameters with english defaults for the regex strings, so that they can be overwritten to support other languages.

The $Simple path is missing a corresponding parameter - so I would just remove that....

**Comment by andreasjordan** [comment]
See linked draft PR for my idea.

**Comment by andreasjordan** [comment]
@DiHo78 - what do you think about my idea? Would that be a solution for you?
