### ISSUE TITLE
Error on Install-DbaInstance : Variable InstancePath  = "D:\" return an error message

### ISSUE THREAD

**Issue by DanielImesch** [dataplat/dbatools#8627]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

ExitMessage       : The input setting "INSTANCEDIR" has invalid character " " ". Retry setup with valid value for "INSTANCEDIR".
Log               : {Overall summary:,   Final result:                  Failed: see details below,   Exit code (Decimal):           -2061893624,
                    Exit facility code:            1306...}

### Steps to Reproduce

Installation script
$installparams = @{
    Version             = 2019
    Path                = "G:\"
    InstanceName        = "INST"
    Feature             = "Engine"
    InstancePath        = "D:\"
    DataPath            = "E:\MSSQL15.INST\MSSQL\Data"
    LogPath             = "F:\MSSQL15.INST\MSSQL\Log"
    TempPath            = "D:\MSSQL15.INST\MSSQL\Data"
    BackupPath          = "D:\MSSQL15.INST\MSSQL\Backup"
    AdminAccount        = "DOMAIN\DBA Admin"
    EngineCredential    = "DOMAIN\servicedb"
    SaCredential        = "sa"
    AuthenticationMode  = "Mixed"
    PerformVolumeMaintenanceTasks = $true
    Verbose             = $true
    Confirm             = $false
}

Install-DbaInstance @installparams

### Please confirm that you are running the most recent version of dbatools

1.0.168

### Other details or mentions

The installation is working by setting InstancePath = "D:\SQL" for example.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                         
----                           -----                                                                                                                         
PSVersion                      5.1.14393.5127                                                                                                                
PSEdition                      Desktop                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                       
BuildVersion                   10.0.14393.5127                                                                                                               
CLRVersion                     4.0.30319.42000                                                                                                               
WSManStackVersion              3.0                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                           
SerializationVersion           1.1.0.1                                                                                                                       

### SQL Server Edition and Build number

SQL Server 2019 

### .NET Framework Version

.NET Framework 4.7.3946.0

**Comment by DanielImesch** [comment]
Updating to InstancePath  = "D:\\" the installation is running successfully.

**Comment by DanielImesch** [comment]
Setting the path for the installation source without the double "\" is working fine.
Thanks for your help

**Comment by DanielImesch** [comment]
We use the dbatools really intensively now.
Good job

**Comment by potatoqualitee** [comment]
awesome! so glad to hear.

sorry, that should have said backslash, maybe gh stripped it out. I'll fix it nevertheless 😊
