### ISSUE TITLE
Copy-DbaLogin did not copy logins with an underscore in the name

### ISSUE THREAD

**Issue by am69** [dataplat/dbatools#8634]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

The User [INT_Statistik] was not migrated, no error displayed.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Copy-DbaLogin -Source ServerA -Destination ServerB

### Please confirm that you are running the most recent version of dbatools

1.1.142

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Source: Microsoft SQL Server 2016 (SP3-CU1-GDR) (KB5015371) - 13.0.7016.1 (X64)   May 21 2022 01:00:03   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

Destination: Microsoft SQL Server 2019 (RTM-CU17) (KB5016394) - 15.0.4249.2 (X64)   Jul 22 2022 12:11:33   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.8.03761
Full        4.8.03761
Client      4.0.0.0

**Comment by wsmelton** [comment]
Please provide the verbose output.

**Comment by wsmelton** [comment]
I'm not able to replicate this between 2017 and 2019. I do not have access to a 2016 instance.

```powershell
$sql17Cn = Connect-DbaInstance -SqlInstance 'localhost,1417' -SqlCredential (Get-Secret sa) -TrustServerCertificate:$false
$sql19Cn = Connect-DbaInstance -SqlInstance 'localhost,1419' -SqlCredential (Get-Secret sa) -TrustServerCertificate:$false
New-DbaLogin -SqlInstance $sql17Cn -Login 'login_with_underscore' -SecurePassword (Get-Secret sa).Password -DefaultDatabase master


ComputerName       : localhost
InstanceName       : MSSQLSERVER
SqlInstance        : 0949388ba718
Name               : login_with_underscore
LoginType          : SqlLogin
CreateDate         : 1/8/2023 11:55:41 PM
LastLogin          :
HasAccess          : True
IsLocked           : False
IsDisabled         : False
MustChangePassword : False

Copy-DbaLogin -Source $sql17Cn -Destination $sql19Cn -Login 'login_with_underscore'

Type             Name                  Status     Notes
----             ----                  ------     -----
Login - SqlLogin login_with_underscore Successful

Get-DbaLogin -SqlInstance $sql19Cn -Login 'login_with_underscore'


ComputerName       : localhost
InstanceName       : MSSQLSERVER
SqlInstance        : 50b1ded678b7
Name               : login_with_underscore
LoginType          : SqlLogin
CreateDate         : 1/8/2023 11:56:11 PM
LastLogin          :
HasAccess          : True
IsLocked           : False
IsDisabled         : False
MustChangePassword : False
```

@am69 please provide the verbose output for your issue using the latest release of the module, 1.1.143 (PowerShell Gallery latest). If you are still experiencing the issue, please add the verbose and debug output of the command you are running.
