### ISSUE TITLE
Get-DbaBackupInformation - Reading a non-SQL backup file errors rather than skips the file

### ISSUE THREAD

**Issue by sqlslinger** [dataplat/dbatools#8636]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

WARNING: [11:28:04][Get-DbaBackupInformation] Failure on MYOTHERSQLSERVER | The media family on device '\\MYBACKSERVER\SQLBackups$\MYSQLSERVER\MYDATABASE\MYDATABASE_backup_metadata.tsv' is incorrectly formed. SQL Server cannot process this media family.
RESTORE HEADERONLY is terminating abnormally.

[Read-DbaBackupHeader_Output.txt](https://github.com/dataplat/dbatools/files/9974387/Read-DbaBackupHeader_Output.txt)

### Steps to Reproduce

```powershell
"This is a junk file that is NOT a SQL Server full, diff, or log backup." | Out-File -Path '\\MYBACKSERVER\SQLBackups$\MYSQLSERVER\MYDATABASE\\MYDATABASE_backup_metadata.tsv' -Encoding Ascii
Restore-DbaDatabase -OutputScriptOnly -SqlInstance MYOTHERSQLSERVER -DatabaseName MYDATABASE -Path '\\MYBACKSERVER\SQLBackups$\MYSQLSERVER\MYDATABASE' -MaintenanceSolutionBackup -IgnoreLogBackup -Verbose
```

### Please confirm that you are running the most recent version of dbatools

1.1.142.1
PS C:\WINDOWS\system32> Get-Module dbatools | Select -ExpandProperty Version

Major  Minor  Build  Revision
-----  -----  -----  --------
1      1      142    -1

### Other details or mentions

We have create a .tsv file containing backup metadata stored within the backup directory tree.  This is so that restores from a source server do not need rights to that source server's msdb database, only rights to the backup metadata file.  A custom stored procedure reads that .tsv file and process the metadata it contains.

The presence of the non-standard file in the backup directories breaks the restore from dbatools.

It would seem that try/catch logic around [this line](https://github.com/dataplat/dbatools/blob/e5f6c9294c950a0a11dbf47c11c0aa8fe18dd680/functions/Read-DbaBackupHeader.ps1#L136) should catch the error brought back by RESTORE HEADERONLY.  This can be presented as a Warning level message rather than a fatal error within Read-DbaBackupHeader.

**NOTE:**  This behavior is a regression error.  We have verified that if we use dbatools version 1.0.42, we get the desired behavior.  A Warning is generated for the unexpected file, but the process continues and produces valid output.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

PS C:\WINDOWS\system32> $PSVersionTable | Out-String

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU11) (KB5003249) - 15.0.4138.2 (X64)
        May 27 2021 17:34:14
        Copyright (C) 2019 Microsoft Corporation
        Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor)

### .NET Framework Version

PSChildName                      Version
-----------                      -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.04084
Full                             4.8.04084
Client                           4.0.0.0

**Comment by wsmelton** [comment]
@sqlslinger I pulled the module version 1.0.42 and compared the command to the current release (1.1.143) and there were no changes to the codebase other than adjusting the command we use to make a connection to the SQL Instance.

The code other than this is identical on workflow and how it dealt with scanning the path for files.
![image](https://user-images.githubusercontent.com/11204251/211226774-fdfa1dd4-bc3d-4a9c-b4b8-26e68d8a7f48.png)

**Comment by wsmelton** [comment]
I would also not consider this a regression as since 1.0.42 release the backup and restore commands have had a significant overhaul to improve performance and functionality. Decisions were made during that time to change certain behaviors; I recall this was one of them.
