### ISSUE TITLE
write up offline install

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dbatools#8642]
### Summarize Functionality

write up offline install

### Is there a command that is similiar or close to what you are looking for?

No

**Comment by potatoqualitee** [comment]
can use https://dbatools.io/soup2nutz/ as guides https://dbatools.io/offline, perhaps. the new version has dependencies and WILL require save-module (unless they download the .nuget and rename but i am not writing that out 😅 )

**Comment by DevGKOne** [comment]
Ok, thanks. At he moment the Link in dbatools/download is not correctly working.

But the Github version (1 1.142) works.

Solution:
Unzip, rename folder 1.1.142 to dbatools copy this folder to Psmodules folder.

**Comment by potatoqualitee** [comment]
thank you, @DevGKOne ! will modify those articles
