### ISSUE TITLE
Get-DBADiskSpace Improper Column Metric Abbreviations

### ISSUE THREAD

**Issue by datadill** [dataplat/dbatools#8654]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When executing Get-DBADiskSpace, it uses capital letters for GB, MB, etc. This implies that the metrics are Gigabytes and Megabytes respectively. I believe DBATools actually reports in GibiBits, which would be Gib.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Get-DBADiskSpace -ComputerName $myComputerName

### Please confirm that you are running the most recent version of dbatools

1.1.134

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2017 (RTM-CU31) (KB5016884) - 14.0.3456.2 (X64) 
	Sep  2 2022 11:01:50 
	Copyright (C) 2017 Microsoft Corporation
	Enterprise Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

### .NET Framework Version

.NET 6.0.8

**Comment by wsmelton** [comment]
We do not report or use binary unit of measure for size.
