### ISSUE TITLE
Get-DbaStartupParameter Fails on Second Execution

### ISSUE THREAD

**Issue by awickham10** [dataplat/dbatools#8658]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Cannot convert value "-T1117" to type "System.Int32". Error: "Input string was not in a correct format."

### Steps to Reproduce

```powershell
Get-DbaStartupParameter -SqlInstance MyServerName -EnableException
Get-DbaStartupParameter -SqlInstance MyServerName -EnableException
```

### Please confirm that you are running the most recent version of dbatools

1.1.102

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

```
Microsoft SQL Server 2014 (SP3-CU4-GDR) (KB5014164) - 12.0.6439.10 (X64)   Apr 20 2022 03:13:42   Copyright (c) Microsoft Corporation  Developer Edition (64-bit) on Windows NT 6.3 <X64> (Build 14393: ) (Hypervisor) 
```

### .NET Framework Version

```
.NET 6.0.8
```

**Comment by awickham10** [comment]
I have a fix for this and an explanation, which lead to a big TIL for PowerShell for me. This appears to be because the `$traceFlags` variable is reused and has type hinting added to it. The type hinting defines the variable differently so the next time the `$traceFlags` variable is used with an array of strings (i.e. -T1111, -T2222), it errors out that it can't be parsed as an integer.

Here are some examples of this in action.

With Type Hinting
```powershell
# success
[int[]] $test = @(1, 2, 3)

# fails with: MetadataError: Cannot convert value "a" to type "System.Int32". Error: "Input string was not in a correct format."
$test = @('a', 'b', 'c')

# resetting the type hinting requires removing the variable
Remove-Variable -Name 'test'

# success
$test = 'a', 'b', 'c'
```

Without Type Hinting
```powershell
# success
$test2 = @(1, 2, 3)

# success
$test2 = @('a', 'b', 'c')
```

Why is this so!?
```powershell
# success
[int[]] $test = @(1, 2, 3)

# success
$test2 = @(1, 2, 3)

$test.GetType()
<#
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Int32[]                                  System.Array
#>

$test2.GetType()
<#
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     Object[]                                 System.Array
#>
```

So after thinking about this, in my head I always expected the = operator to redefine the variable but that's not the case. If the variable is already defined, it reuses the variable and if it's tightly typed you're going to maybe get unexpected results.

**Comment by andreasjordan** [comment]
I can reproduce with dbatools 1.1.146, but not with dbatools 2.0.1 - so I think we don't have to change the code.
If the problem still exists, I would change `[int[]]$traceFlags = $traceFlags.substring(2)` to `$traceFlags = [int[]]$traceFlags.substring(2)`.
@awickham10 - can you test with dbatools 2.0.1 on your side?

**Comment by andreasjordan** [comment]
I will close this now, but can reopen if needed.

**Comment by awickham10** [comment]
Hi @andreasjordan, sorry for the delay on this. I was able to confirm today that this is no longer an issue using 2.0.4. Thank you for your help!
