### ISSUE TITLE
Copy-DbaDbTableData issue when trying to copy between Azure SQL Databases on the same server

### ISSUE THREAD

**Issue by Norrdec** [dataplat/dbatools#8661]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Depending on the method of trying to set it up:
When using connect-dbainstance for for destination and source (same server, different database) and SQL Authentication: 
"Source and Destination must be different"

If I used the server and database names and  SQL credentials directly in Copy-DbaDbTableData I received a **"[11:28:40][Copy-DbaDbTableData] Failure | Login failed for user 'user2'."** 

### Steps to Reproduce

$CredentialSrc = Get-Credential
$CredentialDst = Get-Credential
$SrcDatabase = "x1"
$DstDatabase = "x2"
$SrcServer = "x"
$DstServer = "x"

Depending on the method of trying to set it up:
When using connect-dbainstance for for destination and source (same server, different database) and SQL Authentication: 
$DestinationCombine = Connect-DbaInstance -SqlInstance $DstServer -Database x1 -SqlCredential $CredentialDst -DisableException
$SrcCombine = Connect-DbaInstance -SqlInstance $SrcServer -Database x2 -SqlCredential $CredentialSrc -DisableException

and trying to do the copy using the instances I just created
Copy-DbaDbTableData -SqlInstance $SrcCombine -Database $SrcDatabase  -Destination $DestinationCombine -DestinationDatabase $DstDatabase -Table 'dbo,table'  -Truncate -KeepIdentity -AutoCreateTable -KeepNulls 

getting error: "Source and Destination must be different"  - and they are different databases as destination and src - both for DbaInstance and Copy-DbaDbTableData 

If I used the server and database names and  SQL credentials directly in Copy-DbaDbTableData I received a **"[11:28:40][Copy-DbaDbTableData] Failure | Login failed for user 'user2'."** - in reality the user/pass is the same for both databases and even if I try to switch the order - still getting the same error. A query earlier in the script uses the credentials from Get-Credential and it works fine - so it's not an issue with a wrong user or pass. 
used code: Copy-DbaDbTableData -SqlInstance $SrcServer -SqlCredential $CredentialSrc -Destination $DscServer -Database $SrcDatabase -DestinationDatabase $DestServer -DestinationSqlCredential $CredentialDst -Table $TableName.Item(0)  -Truncate -KeepIdentity -AutoCreateTable -KeepNulls #-Confirm:$false

### Please confirm that you are running the most recent version of dbatools

1.1.143

### Other details or mentions

I used the same script before to copy between an AWS SQL Server database and Azure SQL Database and it worked fine.
Only issue when I had the same server as source and destination. 

In this case these are 2 Azure SQL Server databases, that have the same user and pass (as I am testing the solution only).
The Azure SQL Databases are part of the same Azure Pool, but it's not possible to interact between them with a single connection - hence why I set the Source and Destination servers/databases

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                          
----                           -----                                                                                                                                                          
PSVersion                      5.1.14393.5127                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                        
BuildVersion                   10.0.14393.5127                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                            
PSRemotingProtocolVersion      2.3                                                                                                                                                            
SerializationVersion           1.1.0.1                                                                                                                                                        

### SQL Server Edition and Build number

(No column name)
Microsoft SQL Azure (RTM) - 12.0.2000.8 
	Oct 18 2022 13:24:45 
	Copyright (C) 2022 Microsoft Corporation

### .NET Framework Version

.NET Framework 4.8.4526.0

**Comment by wsmelton** [comment]
> Source and Destination must be different

This is specifically because you are using the same Azure SQL server which we do not support. We validate that your source and destination server are both Azure SQL servers and return if that is found true. This is by design because of limitations I recall with the `Microsoft.Data.SqlClient.SqlBulkCopy` library. If the newer version of this class now supports copying data between databases on the same logical Azure SQL server, then we can look at updating the command. I'm not aware it does though.

**Comment by Norrdec** [comment]
Hi,

Thanks for the response and background. Could I then suggest, to slightly
modify the message to mention the same azure sql server?
I was under the impression that it was talking about the same database and
not the server.

Looks like I'll need to handle an exception :)

Thanks,
Norrdec
