### ISSUE TITLE
Invoke-DbaDbLogShipping not updating Secondary server fully

### ISSUE THREAD

**Issue by GrumpyVader** [dataplat/dbatools#8670]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

No error is generated by the Invoke-DbaDbLogShipping cmdlet, it indicates Successful operations. The cmdlet does indeed create the Back, Copy and Restore jobs and restores the database to the secondary server, but when you try to open the Secondary server properties for the log shipping in SSMS, it throws an error "Management Studio could not retrieve information about secondary database". Checking the status of the Copy job on the secondary server, errors such as the following can be found.

Message
2022-11-30 14:40:03.00	*** Error: Could not retrieve copy settings for secondary ID '36b404be-6296-4f30-950d-9fbb467d7acd'.(Microsoft.SqlServer.Management.LogShipping) ***
2022-11-30 14:40:03.00	*** Error: The specified agent_id 36B404BE-6296-4F30-950D-9FBB467D7ACD or agent_type 1 do not form a valid pair for log shipping monitoring processing.(.Net SqlClient Data Provider) ***
2022-11-30 14:40:03.00	*** Error: Could not log history/error message.(Microsoft.SqlServer.Management.LogShipping) ***
2022-11-30 14:40:03.00	*** Error: The specified agent_id 36B404BE-6296-4F30-950D-9FBB467D7ACD or agent_type 1 do not form a valid pair for log shipping monitoring processing.(.Net SqlClient Data Provider) ***
2022-11-30 14:40:03.00	*** Error: Could not cleanup history.(Microsoft.SqlServer.Management.LogShipping) ***
2022-11-30 14:40:03.00	*** Error: The specified agent_id 36B404BE-6296-4F30-950D-9FBB467D7ACD or agent_type 1 do not form a valid pair for log shipping monitoring processing.(.Net SqlClient Data Provider) ***
2022-11-30 14:40:03.00	----- END OF TRANSACTION LOG COPY     -----

Finally, when checking msdb.dbo.log_shipping_monitor_secondary, we find no record of the secondary database listed. This is likely the root cause of the error in SSMS and why the Copy job would fail.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference

$params = @{
SourceSqlInstance = 'Server1'
DestinationSqlInstance = 'Server2'
Database = 'TestDatabase'
BackupScheduleFrequencyType = 'daily'
BackupScheduleFrequencyInterval = 1
BackupScheduleFrequencySubdayType = 'Minutes'
BackupScheduleFrequencySubdayInterval = 5
CompressBackup = $true
SharedPath= '\\Server1\LogShippingLogFiles$\Source'
LocalPath= 'X:\Backup\LogShippingLogFiles\Source'
CopyScheduleFrequencyType = 'daily'
CopyScheduleFrequencyInterval = 1
CopyScheduleFrequencySubdayType = 'Minutes'
CopyScheduleFrequencySubdayInterval = 5
CopyDestinationFolder = '\\Server2\LogShippingLogFiles$\Destination'
GenerateFullBackup = $true
RestoreScheduleFrequencyType = 'daily'
RestoreScheduleFrequencyInterval = 1
RestoreScheduleFrequencySubdayType = 'Hours'
RestoreScheduleFrequencySubdayInterval = 4
RestoreAlertThreshold = 300
Force = $true
}
Invoke-DbaDbLogShipping @params
```

- Open database properties and try to check the properties of the secondary server. Result: Error is thrown.

- Check Status of Copy job on secondary server, Errors are logged.

- Run the following on the secondary server. Result: No record of LS database.
```sql
SELECT * FROM msdb.dbo.log_shipping_monitor_secondary
GO
```

### Please confirm that you are running the most recent version of dbatools

Version
----------
1.1.143

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      5.1.19041.1682
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1682
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

SQL Server 2016 Standard 13.0.7016.1

### .NET Framework Version

PSChildName                      Version
-----------                      -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.04084
Full                             4.8.04084
Client                           4.0.0.0

**Comment by PabOu-be** [comment]
Confirmed on 1.1.145.
