### ISSUE TITLE
Find-DbaInstance can report FCI instance availability incorrectly when run against the cluster name 

### ISSUE THREAD

**Issue by Shashtsoh** [dataplat/dbatools#8676]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

No error message.  The TL;DR is that when the node running the FCI instance is different from the node that owns the windows cluster name, running "find-dbainstance -computername <windowsclustername>" will always return unavailable.  This behavior may be intended functionality, but feels off to me.

### Steps to Reproduce

Consider the following scenario:

- We have a windows cluster Clus1
- Clus1 is comprised of nodes NodeA and NodeB
- NodeA currenlty owns the cluster
- There is one failover cluster instance installed on this cluster; it's resource name is Inst1.  
- Inst1 is hosted on NodeB.  It is online and can accept connections

In this scenario, we can run find-dbainstance against the cluster name, either node name, or the instance name.  The result we get depends on which we pick.  This is because the availability property is based off of the return from get-dbaservice  as run against the provided name.

Running this command:
```powershell
find-dbainstance -ComputerName Clus1, NodeA, NodeB, Inst1 -ScanType All | select computername, availability
```
Returns this dataset:
```powershell
ComputerName 	Availability
------------ 	------------
Clus1		Unavailable
NodeA		Unavailable
NodeB		Available
Inst1		Available
```
The status returned for NodeA and NodeB are both expected, as they accurately reflect what is happening directly on those nodes.  Likewise, the status returned for Inst1 is expected because that name routes to the node that is hosting it.

The status returned for the cluster is where things feel off to me.  Technically the status is correct because the cluster name is routed to NodeA.  This follows the same logic as using the instance name.  However, when providing a cluster name, I intuitively (naively?) expected that because the function detects that the instance is clustered (in BrowseReply), it would test for availability against either the instance name or the node currently running the instance instead of the cluster name.

### Please confirm that you are running the most recent version of dbatools

1.1.143

### Other details or mentions

Assuming this is not the intended behavior, a decision would need to be made about whether the availability for the instance should return the actual status of the instance regardless of which name is used or not.  I am looking into potential fixes, and will update as I have viable ideas.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.7
PSEdition                      Core
GitCommitId                    7.2.7
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

N/A

### .NET Framework Version

.NET 6.0.10

**Comment by wsmelton** [comment]
This is the nature of WSFC and FCIs, nothing to do with our commands. Same result would occur if you used the WSFC network name to connect to a FCI default instance. If the passive node of the FCI owns the cluster network name your connection will fail, if it does not it succeeds.

If you review the documentation on what we scan for and based on the final result SQL Server is not behind that cluster network name unless it is on the active FCI node.

**Comment by Shashtsoh** [comment]
What I gather from your comment is that this is the intended functionality of the script.  I can accept that to a point, but I want to push back just a little, because there are bugs here that need to be addressed. 

The default scan types determine availability by checking to see if the engine service is running on the OS you're connected to.  After stepping through the code, I completely agree with your assessment for the default scan - the only place we should see available is on the node that you're connecting to in the background.  

However, I specifically called out the **-ScanType All** input, as this parameter/value is supposed to attempt to connect to the instance.  I have reviewed the code for this section, and there are a couple of bugs here, as well as some logic that may need adjustment as they are fixed. 

The first bug is on line 504:
```powershell
$server = Connect-DbaInstance -SqlInstance $dataSet.FullSmoName -SqlCredential $SqlCredential
```
I have stepped through the code with runs against FCIs and standalones; the property "FullSmoName" does not exist on the $dataset object in either scenario.  This causes the connection attempt to fail 100% because the parameter can't bind to a nonexistent property.  

This issue is masked a bit by the behavior of this block on 527-531 (second bug):
```powershell
if ($_.Exception.InnerException.Errors.Class -lt 25) {
                                    # There IS an SQL Instance and it listened to network traffic
                                    $dataSet.SqlConnected = $true
                                    $dataSet.Confidence = 'High'
                                }
```
This condition evaluates to true when the InnerException object is null, despite the fact that the connection attempt failed.  Call me crazy, but I don't think we should mark a connection attempt as successful with high confidence when that attempt never actually happened. :)  Fixing the first issue should honestly prevent this one from ever being hit, but it's worth doing a null check in this condition as well just to ensure that it behaves properly.

The first issue is a bit trickier.  It could be fixed by changing the referenced property from FullSmoName to SQLInstance, but I don't think it's that simple.  That $dataSet.SqlInstance property is being auto-populated when creating the DbaInstanceReport object that $dataSet is an instance of.  That creation process assumes that SQLInstance should either be the computer name (default instance) or the concatenation of the computer name and instance name.  For standalones, this is wonderful.  However, for FCIs, not so much.

Maybe I'm missing something here, but the only way to connect to a FCI in my experience is by is using the FCI resource name; I have never successfully connected to a FCI using the cluster or node names (your comment had me double-checking in my environment just now to be sure).  Assuming my tests are accurate, simply using the value in $dataSet.SqlInstance will always fail for FCIs, as that value never has the instance resource name.  

I think it's reasonable and intuitive to expect that if a connection attempt is supposed to be made to an FCI, then that attempt should be made using the actual instance name, regardless of whether the instance is actually hosted on the current machine. This would mean that the connection attempt would need to be made against $dataSet.BrowseReply.SQLInstance instead of $dataSet.SQLInstance, assuming that BrowseReply exists.   I would argue that this is the better SQLInstance value to use in general, but it could easily be restricted to using that value only when $dataSet.BrowseReply.IsClustered is true.

My initial thought was that Availabity should be set to 'Available' on a successful connection, but after sitting on it for a bit, I don't think that's the best route.  Keeping that logic as-is should be better, as the combination of Availability and SqlConnected tells you not only whether the FCI is hosted on the node you're hitting - important info in its own right, and also maintains current intent of the field - but also whether it is truly available or not (which is what is currently broken).  

I am working on code changes in my environment to address these issues, and will update here with progress.

**Comment by Shashtsoh** [comment]
Based on this info, should we re-open this, or would you like me to submit a new one?

**Comment by wsmelton** [comment]
Please do not mix issues and change the intent. The connection issue it bug should be created as a need issue and this left as-is for others to find the details.

Regarding the original issue it is the intention of how WSFC and FCI work. It has nothing to do with our code base.

The connection issue you raised is viable to be fixed but please create that as a new issue.

**Comment by Shashtsoh** [comment]
Well...  My intent was always to be able to accurately determine whether an FCI is online and available using this cmdlet...  I just hadn't had time to dig into the code and determine the cause before the initial submission.  That said, I'm happy to submit a new one.  Thanks for your help!
