### ISSUE TITLE
Get-DbaRunningJob start time of the job is in mentioned in nvarchar

### ISSUE THREAD

**Issue by krishna2722** [dataplat/dbatools#8679]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

In DBATOOLS I am trying to use command Get-DbaRunningJob in that, the start time of the job is in mentioned in nvarchar. How do i convert it in powershell itself while selecting using selct-object

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

### Please confirm that you are running the most recent version of dbatools

Yes

### Other details or mentions

In DBATOOLS I am trying to use command Get-DbaRunningJob in that, the start time of the job is in mentioned in nvarchar. How do i convert it in powershell itself while selecting using selct-object

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

In DBATOOLS I am trying to use command Get-DbaRunningJob in that, the start time of the job is in mentioned in nvarchar. How do i convert it in powershell itself while selecting using selct-object

### SQL Server Edition and Build number

SQL 2019

### .NET Framework Version

4.5 and above

**Comment by wsmelton** [comment]
@krishna2722 we do not output any nvarchar data types in the module. All datatime values should be output as `DbaDateTime` which is our custom type from our internal library.

![image](https://user-images.githubusercontent.com/11204251/208448596-0ccc9e9e-d615-4aeb-88cc-58de01eb6e71.png)
