### ISSUE TITLE
Adding dbatools to azure runbook

### ISSUE THREAD

**Issue by wondisha** [dataplat/dbatools#8687]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Am getting error while Importing  DBATools  module to azure runbook.
Error 
Selected file 'dbatools-signed.zip' must be between 1 and 1048576 bytes.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
On azure automation just adding the module by browsing from the path available

### Please confirm that you are running the most recent version of dbatools

The module is downloaded from github

### Other details or mentions

trying to import the module downloading from github ,which is version 1.1.142

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

ps version 5.1.19041

### SQL Server Edition and Build number

2019

### .NET Framework Version

4.8

**Comment by wondisha** [comment]
Resolved by the help of Robsewell's blog

**Comment by potatoqualitee** [comment]
thanks @wondisha - can you share the link that had the solution?

**Comment by wondisha** [comment]
https://blog.robsewell.com/blog/powershell/dbatools/How-To-Import-dbatools-Into-Azure-Automation/
