### ISSUE TITLE
Get-DbaDbUserDefinedTableType -Name parameter

### ISSUE THREAD

**Issue by labyrinthsystems** [dataplat/dbatools#8691]
### Summarize Functionality

A way to select one User Defined Table Type rather than all of them, similar to many other commandlets

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by sqlarticles** [comment]
Hi @labyrinthsystems
`Get-DbaDbUserDefinedTableType` should provide everything but adding a where clause should be straight forward.

`Get-DbaDbUserDefinedTableType | Select Name -eq "Type1"`

Are you looking for a parameter within the function that does accept the type name?

**Comment by wsmelton** [comment]
@sqlarticles yes, you can view many of our other commands have a -Name parameter that accepts the name property value for filtering. You can see the pattern we use for this by viewing how other commands work.

**Comment by sqlarticles** [comment]
Thanks @wsmelton for the confirmation. Let me do the changes and raise a PR
