### ISSUE TITLE
Could not load file or assembly  'Microsoft.Data.SqlClient'

### ISSUE THREAD

**Issue by raufas** [dataplat/dbatools#8707]
Hello. I am installed the latest available version of dbatools onto Windows Server 2016 Standard edition. I am also using the latest SSMS 
and SQL Server 2017 Developer edition. Unfortunately I get the following error while trying to run any dbatools command:

```
Test-DbaConnection : Cannot process argument transformation on parameter 'SqlInstance'. Could not load file or assembly 
'Microsoft.Data.SqlClient, Version=2.0.20168.4, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5' or one of its dependencies. 
The system cannot find the file specified.
At line:1 char:20
+ Test-DbaConnection localhost
+                    ~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Test-DbaConnection], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Test-DbaConnection
```

I tried to reinstall SQL Server, SSMS and dbatools itself but no luck. Could you please help me solve this out?

**Comment by potatoqualitee** [comment]
That is very strange indeed and unfortunately, the dataplat/web repo does not have the issue template that would give us more insight into what could be wrong. I've not come across this but dbatools 2.0 will most certainly address this issue or PS/.NET is broken on that system. dbatools 2.0 will be released by feb 1, likely and the reprelease/beta will be rolled out sooner, perhaps by the end of this week.

**Comment by raufas** [comment]
@potatoqualitee thanks for your reply. I came across that issue again on production server and it took sometime to figure it out. In the last 2 years I were usually installing dbatools in offline mode by downloading the latest version from https://dbatools.io/zip. This time it threw that error. 

In this case, workaround was downloading the latest version of dbatools from https://github.com/dataplat/dbatools/releases instead of https://dbatools.io/zip. I am not sure what can be the issue with that zip from https://dbatools.io/zip.

**Comment by wsmelton** [comment]
@raufas the zip download you are downloading the repository itself from GitHub. Right now, the repository codebase is not stable enough for use in production as it has mixed changed as we get ready for a 2.0 release as Chrissy mentioned.

Going forward the offline installation should be performed using one of the following methods:
- Download from PowerShell Gallery via `Save-Module` and then push that to your servers
- Download via the release page of the repository (after 2.0 release)

Closing this issue as it seems to be resolved now.

**Comment by potatoqualitee** [comment]
pls let me know if you have any issues with the latest module version, 2.5.5
