### ISSUE TITLE
Set-DbaDbCompatibility does not Support SQLServer2022 "Version160" yet

### ISSUE THREAD

**Issue by KlugerSteffen** [dataplat/dbatools#8718]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Error Message:
Set-DbaDbCompatibility : Cannot validate argument on parameter 'TargetCompatibility'. The argument "16" does not belong to the set "9,10,11,12,13,14,15" specified
by the ValidateSet attribute. Supply an argument that is in the set and then try the command again.
At line:1 char:117

### Steps to Reproduce

```
Set-DbaDbCompatibility -SqlInstance  $instance -database $db -TargetCompatibility 16
```

### Please confirm that you are running the most recent version of dbatools

1.1.143

### Other details or mentions

Need to use SqlServer Module 22.0.30-preview to implement workaround:
```
$dbs = get-SqlDatabase -sqlInstance $instance -database $db
$dbs.Compatibility = "Version160"
$dbs.Alter()
```

Further, get-dbaDbCompatibility returns Compatibility as 160 instead of "Version160".

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                
----                           -----                                                                                                                                
PSVersion                      5.1.17763.3770                                                                                                                       
PSEdition                      Desktop                                                                                                                              
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                              
BuildVersion                   10.0.17763.3770                                                                                                                      
CLRVersion                     4.0.30319.42000                                                                                                                      
WSManStackVersion              3.0                                                                                                                                  
PSRemotingProtocolVersion      2.3                                                                                                                                  
SerializationVersion           1.1.0.1                                                                                                                              

### SQL Server Edition and Build number

Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)   Oct  8 2022 05:58:25   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.7.03190
Full        4.7.03190
Client      4.0.0.0

**Comment by ClaudioESSilva** [comment]
Hi @KlugerSteffen 

@sanderstad just created a PR #8717 to add support for `Version160`

However, we will also need to update the SMO DLLs. Those are responsible for the enumeration/valid options to be used.

I believe your workaround as a typo should be `Get-SqlDatabase` instead `Get-DbaDatabase`.

Regarding the output, we output the value directly from the SMO object. 
https://github.com/dataplat/dbatools/blob/master/functions/Get-DbaDbCompatibility.ps1#L92

I believe this is an artefact from using the old DLL.

**Comment by wsmelton** [comment]
Pending PR approval 2.0 release will remove the `-TargetCompatibility` parameter to prevent the need to maintain it with each version of SQL Server.
