### ISSUE TITLE
Restore-DBADatabase not completing when using restoretime

### ISSUE THREAD

**Issue by jeffincognito** [dataplat/dbatools#8719]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

No Error but when restoring a database to a point in time, it's not finishing. The last Log file restored is the One right before the log which has the stop date in it. As you can see in my example, the Stop time is 6:25 AM but the last processed log is the 6:00 AM log.  If I run the command for the last trn log in SQL I get the following message. 

"This backup set contains records that were logged before the designated point in time. The database is being left in the restoring state so that more roll forward can be performed.
100 percent processed."
So the backup stays in No recovery. I've tried playing around with the settings but using restore time is what affects it.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
[datetime]$RestoreTime = Get-Date("01/11/2023 6:25:00")
#(date and time should be mentioned as local server time as  per requirement.)#
$Path = 'z:\Restore\'
$RestoreParameters = @{  
SqlInstance  = 'ServerName' 
RestoreTime  = $RestoreTime  
Verbose      = $true  
WithReplace  = $true
}  
$Databases = @('DAtabase folder name in the path') <# set of databases by name #>  
foreach ($Database in $Databases) {  
Restore-DbaDatabase @RestoreParameters -Path "$Path\$Database" -DatabaseName "$Database" -ReplacedbnameInfile  -BlockSize '4096'
}  

### Please confirm that you are running the most recent version of dbatools

1.1.143

### Other details or mentions

SQL 2016, OS Server 2019

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                             
----                           -----                                                                                                                                                                             
PSVersion                      5.1.17763.3770                                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                           
BuildVersion                   10.0.17763.3770                                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                               
SerializationVersion           1.1.0.1                                                                                                                                                                           

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP3-GDR) (KB5014355) - 13.0.6419.1 (X64)   May 29 2022 21:05:29   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.7.03190
Full        4.7.03190
Client      4.0.0.0

**Comment by jeffincognito** [comment]
![restore-dbadatabase_error](https://user-images.githubusercontent.com/93724298/211880082-09fa745c-2520-47e5-a633-f4ecf90f70ee.jpg)

**Comment by wsmelton** [comment]
From 6:00 to 6:25 was there actually any changes captured in the log backup?

Notice the script has the statement you can run in SSMS to get the same result. SQL Server will not apply a log backup, even if you have a stopat referenced, if that log contains no transactions to apply.

**Comment by wsmelton** [comment]
Closing this for now. Please post more details if you are able to identify this issue is the result of our codebase.

**Comment by jeffincognito** [comment]
There are about 3 hours of trn logs beyond this point, it's stopping at the trn log before the stop time, I've tested this for a couple different databases and on a couple different utility servers with the same results, This started happening a couple week ago.

**Comment by wsmelton** [comment]
> If I copy out the finale command and run it in SQL I get the error message in my original description.

The issue you are experiencing is not from our module. There are [tricks](https://www.mssqltips.com/sqlservertip/3555/read-sql-server-transaction-log-backups-to-find-when-transactions-occurred/) that will let you see whether a transaction exist in a given log backup. I would recommend trying that to identify what (if any) are in the backup you expect to be used.

**Comment by jeffincognito** [comment]
I don't think that's correct. So in this scenario, I have the stop at time at 6:25 and the finale trn log it restores is the 6 trn log. If I change the stop time to 6:05 (which I tried) it stops at the 5:30 trn log, if I change it to 7:05 (which I also tried) it stops at the 6:30 log. The error happens because the finale command removes the "norecovery" attribute but as the stop time that doesn't align with the stop at time in the finale trn log. 

What I didn't mentioned is I manually copied the second to last statement which had a "norecovery" attribute, changed the trn log path to the 6 am trn log and ran it in SQL. Ran without errors. then I took last command that was run without norecovery, change the path to the 6:30 am trn log and it run without errors and the database is no longer in recovery mode.

I've been using restore-dbadatabase for years and this is the first time this has happened but it's happening consistently as of a couple weeks ago.

**Comment by wsmelton** [comment]
Release 1.1.143 went out November 17, 2022 (~14 weeks ago) and the last change to the restore command was back in July 2021.

**Comment by jeffincognito** [comment]
So given I know it's not the back ups that is the issue as I confirmed them manually, is there anything else I can look at to see why?

**Comment by wsmelton** [comment]
Are there transactions in the log backup we do not include?

**Comment by jeffincognito** [comment]
Yes, the manual test showed that and I did a quick confirmation this morning to see that common updated tables went up to that date.

**Comment by wsmelton** [comment]
So you run Restore-DbaDatabase with the stop at, and you are not seeing data you expect? 
If you do that process through SSMS, what log backup will it pull that we do not?

**Comment by jeffincognito** [comment]
I do restore-dbadatabase with -recovertime (if I do it without -recovertime it works as expected) the last restored trn log is two trn logs prior to the stop time, IE I set time at 6:25, the 5:30 is the last that actually restored, the 6:00 failed and the 6:30 was never attempted and the database is still in "Recovery Pending" status.

**Comment by wsmelton** [comment]
@Stuart-Moore I recall we had command to export history that we could review for this sort of thing?
