### ISSUE TITLE
Data not updated, when using Connect-DbaInstance

### ISSUE THREAD

**Issue by ksl28** [dataplat/dbatools#8720]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?
```
PSMessageDetails      : 
Exception             : System.Management.Automation.RuntimeException: Failed to copy Comments - The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop: [19:08:19][Copy-DbaDbTableData] Table [dbo].[Comments] cannot be found in db123 
                        . Use -AutoCreateTable to automatically create the table on the destination.
TargetObject          : Failed to copy Comments - The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop: [19:08:19][Copy-DbaDbTableData] Table [dbo].[Comments] cannot be found in db123. Use -AutoCreateTable to automatically create  
                        the table on the destination.
CategoryInfo          : OperationStopped: (Failed to copy Comm…on the destination.:String) [], RuntimeException
FullyQualifiedErrorId : Failed to copy Comments - The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop: [19:08:19][Copy-DbaDbTableData] Table [dbo].[Comments] cannot be found in db123. Use -AutoCreateTable to automatically create 
                        the table on the destination.
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 43
PipelineIterationInfo : {}
```
### Steps to Reproduce

```powershell

function Copy-DBTables {
    param (
        [Parameter(Mandatory = $true)][Microsoft.SqlServer.Management.Smo.SqlSmoObject]$SourceSQLConnection,
        [Parameter(Mandatory = $true)][Microsoft.SqlServer.Management.Smo.SqlSmoObject]$DestinationSQLConnection
    )
    #Hardcoded databases for the demo
    $FolderPath = "C:\SQLTempExport856"
    $SourceDatabase = "StackOverflow2010"
    $DestinationDatabase = "db123"
    #Hardcoded databases for the demo


    $SourceTables = Get-DbaDbTable -SqlInstance $SourceSQLConnection -Database $SourceDatabase -ErrorAction stop
    foreach ($SourceTable in $SourceTables) {
        
        try {
            #https://www.sqlshack.com/script-sql-server-objects-using-dbatools/
            $SQLScriptOptions = New-DbaScriptingOption
            if ($CopyConstraints) {
                $SQLScriptOptions.DriAllConstraints = $true
            }
            if ($CopyForeignKeys) {
                $SQLScriptOptions.DriForeignKeys = $true
            }
            if ($CopyNonClusteredIndexes) {
                $SQLScriptOptions.NonClusteredIndexes = $true
            }
            $FilePath = "$FolderPath" + "\" + "$($SourceTable.name)" + ".sql"
            $ExportedScript = $SourceTable | Export-DbaScript -FilePath $FilePath -ScriptingOptionsObject $SQLScriptOptions -ErrorAction stop -WarningAction stop    
        }
        catch {
            throw "Failed to export $($SourceTable.Name) as an script - $($_.Exception.Message)"
        }
    
        try {
            $TempVar = Invoke-DbaQuery -SqlInstance $DestinationSQLConnection -Database $DestinationDatabase -File $ExportedScript.FullName -ErrorAction stop -WarningAction stop
            Write-Host "Created the table $($SourceTable.Name) on $($DestinationSQLConnection.Name)" -ForegroundColor Green
        }
        catch {
            throw "Failed to create the table $($SourceTable.Name) in $DestinationDatabase on $($DestinationSQLConnection.Name) - $($_.Exception.Message)"
        }
    
        try {
            Write-Host "Copying $($SourceTable.Name)"
            $TempVar = Copy-DbaDbTableData -SqlInstance $SourceSQLConnection -Database $SourceDatabase -Table $SourceTable.Name -Destination $DestinationSQLConnection -DestinationDatabase $DestinationDatabase -KeepIdentity -KeepNulls -CheckConstraints -Truncate -ErrorAction stop -WarningAction Stop
            Write-Host "Copied $($TempVar.RowsCopied) rows for $($SourceTable.name)" -ForegroundColor green
        }
        catch {
            throw "Failed to copy $($SourceTable.Name) - $($_.Exception.Message)"
        }
    }    
}
$SourceSQLConnection = Connect-DbaInstance -SqlInstance "dk1sqlclu01ag01"
$DestinationSQLConnection = Connect-DbaInstance -SqlInstance "dk1sql02"
Copy-DBTables -SourceSQLConnection $SourceSQLConnection -DestinationSQLConnection $DestinationSQLConnection
```

The script will fail eventually, stating that the table is not present in the destination database. SSMS proves that it is present.
```powershell
#This will not show all the tables
Get-DbaDbTable -SqlInstance $DestinationSQLConnection -Database db123

#This will work - all tables are shown in the output from Get-DbaDbTable
Disconnect-DbaInstance
$DestinationSQLConnection = Connect-DbaInstance -SqlInstance "dk1sql02"
Get-DbaDbTable -SqlInstance $DestinationSQLConnection -Database db123
```

### Please confirm that you are running the most recent version of dbatools

1.1.143

### Other details or mentions

I tried to do $DestinationSQLConnection.Refresh() but that didnt resolve the issue.
How do i refresh the metadata, when im already connected to the instance?

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), VS Code (terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)   Oct  8 2022 05:58:25   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 

### .NET Framework Version

.NET 7.0.0

**Comment by wsmelton** [comment]
When you create a connection using SMO the data collected in the object is cached. Create objects in the SQL instance or database(s) and it will not update unless you tell it to.

You need to refresh the Database object that is part of your connection. `$DestinationSQLConnection.Databases.Refresh()`, or you can be more specific and refresh the specific database `$DestinationSQLConnection.Databases['databasename'].Refresh()`.

**Comment by ksl28** [comment]
@wsmelton - thanks for the comment, but it sadly didnt work.
Any suggestions?

![image](https://user-images.githubusercontent.com/53445047/212560757-e537be16-5492-4d78-97b9-c716a1cca428.png)

**Comment by wsmelton** [comment]
Create a new connection.

**Comment by ksl28** [comment]
@wsmelton - So you mean to Disconnect-Dbainstance & Connect-DbaInstance right after ?
I know that will work, but i would really prefer not to, since it ruins the entire concept of my custom SQL module, based on dbatools. :)

**Comment by wsmelton** [comment]
Why would it ruin it?

**Comment by ClaudioESSilva** [comment]
Iirc, you need to do the refresh at the object collection level. In this case tables and not database.

Give it a try:
`$DestinationSQLConnection.Databases['databasename'].Tables.Refresh()`

**Comment by wsmelton** [comment]
Why does your input on the function expecting `Microsoft.SqlServer.Management.Smo.SqlSmoObject`?

Our commands do not depend on that, and the Connection function outputs `Microsoft.SqlServer.Management.Smo.Server` which all of our commands expect for input.

We cannot offer any guarantee that the refresh method will work or is properly available on that object type. It may work completely different.

```powershell
Import-Module dbatools.core.library,.\dbatools.psd1

$sql19 = Connect-DbaInstance -SqlInstance 'localhost,1419' -SqlCredential (Get-Secret sa) -TrustServerCertificate
$sql22 = Connect-DbaInstance -SqlInstance 'localhost,1406' -SqlCredential (Get-Secret sa) -TrustServerCertificate

$sql19TempTableCount = Get-DbaDbTable -SqlInstance $sql19 -Database tempdb
$sql22TempTableCount = Get-DbaDbTable -SqlInstance $sql22 -Database tempdb
Write-Output "sql19: $($sql19TempTableCount.Count)"
Write-Output "sql22: $($sql22TempTableCount.Count)"

$columns = @(@{
        Name      = 'col1'
        Type      = 'varchar'
        MaxLength = 20
        Nullable  = $true
    }
    @{
        Name      = 'col2'
        Type      = 'varchar'
        MaxLength = 20
        Nullable  = $true
    })
1..5 | ForEach-Object {
    New-DbaDbTable -SqlInstance $sql19 -Database tempdb -Name "testtable_$($_)" -ColumnMap $columns >$null
    New-DbaDbTable -SqlInstance $sql22 -Database tempdb -Name "testtable_$($_)" -ColumnMap $columns >$null
}
Write-Output "New tables added"

$sql19TempTableCount = Get-DbaDbTable -SqlInstance $sql19 -Database tempdb
$sql22TempTableCount = Get-DbaDbTable -SqlInstance $sql22 -Database tempdb
Write-Output "sql19: $($sql19TempTableCount.Count)"
Write-Output "sql22: $($sql22TempTableCount.Count)"

Get-DbaDbTable -SqlInstance $sql19 -Database tempdb | Remove-DbaDbTable -Confirm:$false >$null
Get-DbaDbTable -SqlInstance $sql22 -Database tempdb | Remove-DbaDbTable -Confirm:$false >$null
```

Output:
```console
❯ C:\tmp\tableCheck.ps1
sql19: 0
sql22: 0
New tables added
sql19: 5
sql22: 5
```

**Comment by ksl28** [comment]
@wsmelton  - Im trying to build a toolbox, that contains custom functions based on dbatools cmdlets, to help me fix the most recurring tasks i see every week. So things like Copy databases, Copy Tables, Get database info for management, etc - so all my functions are build based on that you connect to a instance ($DestinationSQLConnection), which supports both Windows and SQL Login. This function, was the last issue i had :) 

@ClaudioESSilva - That worked perfectly! I had hoped that `$DestinationSQLConnection.Databases.Tables.refresh()` would work - but you have to specify the database, like you did - `$DestinationSQLConnection.Databases[$($DestinationDatabase)].Tables.Refresh()`

**Comment by wsmelton** [comment]
> -ErrorAction stop -WarningAction Stop

Be aware that these have no affect on our commands becasue we manipulate the streams in PowerShell for our module. If you want to truly hit an exception with a catch block, then any call you make needs to have `-EnableException` added (except for Connect-DbaInstance).

**Comment by ksl28** [comment]
@wsmelton - Thanks for the guidance! Really appreciate it! 👍 
Is it by design that `$DestinationSQLConnection.Databases.Tables.refresh()` dosent work, but `$DestinationSQLConnection.Databases[$($DestinationDatabase)].Tables.Refresh()` does?

**Comment by wsmelton** [comment]
That would be something Microsoft would have to answer and explain how they implemented that refresh() method.

**Comment by Shashtsoh** [comment]
I'd like to re-open this discussion for just a bit.  Back in Jan '23 on this thread, @wsmelton asked a great question about why folks would pass an SMO object when their commands didn't require that and would do it for them.  At that point in time, I would have fully agreed.  Unfortunately, the world changed a bit with the release of 2.0 and all of the TLS changes.  Unless you've implemented proper certs on your servers, you only have two options to use the vast majority of the module.  
1. Turn off encryption checking in the module.  This makes the problem go away, but is a really big hammer that hides a security issue.  
2. Use connect-dbainstance with the -TrustServerCertificate flag, then pass that connection object to the rest of the cmdlets.  _This is necessary because connect-dbainstance is the **only** cmdlet with that flag._ 

Those organizations that do not have certs deployed everywhere end up stuck between a rock and a hard place.  Do they hide a security issue with the setting, or try to acknowledge and work with it within the current framework?  I get that the easy/right answer is to just deploy certs and be done, but there are situations where that isn't possible for political and/or technical reasons.  I don't believe they can effectively use the module if the solution is 'Don't pre-create the SMO object that we were going to create at runtime for you anyway.'  

I know there's a lot of nuance in this, and I don't pretend to have a good answer here.  I'm just hoping that more discussion - especially with the new realities of 2.x - will turn over some new rocks.
