### ISSUE TITLE
Install-DbaInstance - support for SQL Server 2022

### ISSUE THREAD

**Issue by StefanC162** [dataplat/dbatools#8727]
### Verified issue does not already exist?

No, I did not search

### What error did you receive?

Install-DbaInstance : Cannot validate argument on parameter 'Version'. The argument "2022" does not belong to the set "2008,2008R2,2012,2014,2016,2017,2019" specified by the ValidateSet attribute. Supply an 
argument that is in the set and then try the command again.

### Steps to Reproduce

Try
Tried to install a SQL Server 2022 default instance, Developer edition on a Standalone server.

### Please confirm that you are running the most recent version of dbatools

1.1.143

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                             
----                           -----                                                                                                                                                                             
PSVersion                      5.1.14409.1027                                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                           
BuildVersion                   10.0.14409.1027                                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                               
SerializationVersion           1.1.0.1                                                                                                                                                                           

### SQL Server Edition and Build number

SQL Server 2022 RTM (16.0.1000.6)

### .NET Framework Version

.NET Framework 4.8.4526.0

**Comment by wsmelton** [comment]
Please see the discussion [here](https://github.com/dataplat/dbatools/discussions/8569)
