### ISSUE TITLE
Support Get-DbaDatabase input to Get-DbaDbBackupHistory Database parameter

### ISSUE THREAD

**Issue by GeorgePalacios** [dataplat/dbatools#8728]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

No error - no value was returned at all.

As can be seen below output, for the same database name, using the output from Get-DbaDatabase as the input to -Database produces no objects at all. Replacing with the name in text however works, and returns backup records as expected.

Also included the verbose logs

### Steps to Reproduce

```powershell
PS C:\Source\dba-automation> $sqlinstance = connect-dbainstance localhost
PS C:\Source\dba-automation> $db = get-dbadatabase -SqlInstance $sqlinstance -Database TestCatalogueTarget
PS C:\Source\dba-automation> $db

ComputerName       : WLB210841  
InstanceName       : MSSQLSERVER
SqlInstance        : WLB210841  
Name               : TestCatalogueTarget
Status             : Normal
IsAccessible       : True
RecoveryModel      : Full
LogReuseWaitStatus : Nothing
SizeMB             : 16
Compatibility      : Version150
Collation          : Latin1_General_CI_AS
Owner              : REDACTED\George.Palacios
Encrypted          : False
LastFullBackup     : 22/01/2023 10:33:20
LastDiffBackup     : 01/01/0001 00:00:00
LastLogBackup      : 01/01/0001 00:00:00


PS C:\Source\dba-automation> get-dbadbbackuphistory -sqlinstance $sqlinstance -Database $db -LastFull
PS C:\Source\dba-automation> get-dbadbbackuphistory -sqlinstance $sqlinstance -Database $db
PS C:\Source\dba-automation> get-dbadbbackuphistory -sqlinstance $sqlinstance -Database TestCatalogueTarget

SqlInstance Database            Type TotalSize DeviceType Start                   Duration End
----------- --------            ---- --------- ---------- -----                   -------- ---
WLB210841   TestCatalogueTarget Full 3.34 MB   Disk       2023-01-10 16:18:17.000 00:00:00 2023-01-10 16:18:17.000
WLB210841   TestCatalogueTarget Full 3.40 MB   Disk       2023-01-22 10:33:20.000 00:00:00 2023-01-22 10:33:20.000
```

```powershell
PS C:\Source\dba-automation> get-dbadbbackuphistory -sqlinstance $sqlinstance -Database TestCatalogueTarget -Verbose
VERBOSE: [10:44:20][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [10:44:20][Get-DbaDbBackupHistory] Executing sql query on [WLB210841].
VERBOSE: [10:44:20][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [10:44:20][Get-DbaDbBackupHistory] 2 result-groups found.

SqlInstance Database            Type TotalSize DeviceType Start                   Duration End
----------- --------            ---- --------- ---------- -----                   -------- ---
WLB210841   TestCatalogueTarget Full 3.34 MB   Disk       2023-01-10 16:18:17.000 00:00:00 2023-01-10 16:18:17.000
WLB210841   TestCatalogueTarget Full 3.40 MB   Disk       2023-01-22 10:33:20.000 00:00:00 2023-01-22 10:33:20.000

PS C:\Source\dba-automation> get-dbadbbackuphistory -sqlinstance $sqlinstance -Database $db -Verbose
VERBOSE: [10:44:28][Connect-DbaInstance] Server object passed in, will do some checks and then return the original object
VERBOSE: [10:44:28][Get-DbaDbBackupHistory] Executing sql query on [WLB210841].
VERBOSE: [10:44:28][Get-DbaDbBackupHistory] Processing as grouped output.
VERBOSE: [10:44:28][Get-DbaDbBackupHistory] 0 result-groups found.
```

### Please confirm that you are running the most recent version of dbatools

1.1.143

### Other details or mentions

Doesn't seem to be related to any other flags - this happens by simply passing the output object from Get-DbaDatabase

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), VS Code (integrated terminal)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU18) (KB5017593) - 15.0.4261.1 (X64)   Sep 12 2022 15:07:06   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19044: ) 

### .NET Framework Version

.NET 7.0.0
```
PSChildName                      Version
-----------                      -------       
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926 
Windows Presentation Foundation  3.0.6920.4902 
v3.5                             3.5.30729.4926
Client                           4.8.04084
Full                             4.8.04084
Client                           4.0.0.0
```

**Comment by GeorgePalacios** [comment]
This seems like it might be related to how the query is constructed.

Databases added to array here:

```powershell
           $databases = @()
            if ($null -ne $Database) {
                foreach ($db in $Database) {
                    $databases += [PSCustomObject]@{ name = $db }
                }
            } else {
                $databases = $server.Databases
            }
```

If the object passed in is from get-dbadatabase, the object itself is now assigned to name.

Queries then use the line

```tsql
WHERE database_name='$($db.name)'
```

$db.name in this case I believe would invoke (Get-DbaDatabase).ToString - this includes square brackets - EG [master]. This would then fail the check.

Does this seem right?

**Comment by wsmelton** [comment]
This is by design for the module as it is not written to accept input for `Microsoft.SqlServer.Smo.Database` class:

https://github.com/dataplat/dbatools/blob/5cde6e64d13bda6ecaa32ef5ac23142789f3b8b7/functions/Get-DbaDbBackupHistory.ps1#L159

We expect an array/object of Database **names** as-is and is the pattern we use across all of commands. Users can specify the property (`-Database $db.Name`) as input from `Get-DbaDatabase` or cleaner option would be to use pipeline method but I'm seeing this command was not updated to use that pattern:

```powershell
Get-DbaDatabase -SqlInstance $sqlinstance -Database TestCatalogueTarget | Get-DbaDbBackupHistory -LastFull
```

In most of our commands this should pipe the SQL connection object and the Database object but it does not.

![image](https://user-images.githubusercontent.com/11204251/213925849-8bcdd2b1-aa8b-4e16-89b2-69716f29861f.png)

**Comment by wsmelton** [comment]
As it stands our commands do not support passing in full objects to the various parameters such as `-Database`, and others. The input expects an array of databases (strings) to be input as [documentation examples show](https://docs.dbatools.io/Get-DbaDatabase).
