### ISSUE TITLE
Test-DbaComputerCertificateExpiration always shows cert is expired

### ISSUE THREAD

**Issue by allenheydari2019** [dataplat/dbatools#8730]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

For valid cert still shows this 
ExpiredOrExpiring : True
Note              : This certificate has expired and is no longer valid

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

### Please confirm that you are running the most recent version of dbatools

Test-DbaComputerCertificateExpiration -ComputerName servername -Threshold 30

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Version 5.2

### SQL Server Edition and Build number

EC2 SQL 2019

### .NET Framework Version

already have the latest version of .NET

**Comment by allenheydari2019** [comment]
hope @potatoqualitee will look into it.

**Comment by wsmelton** [comment]
Please provide the verbose output of the command.

**Comment by potatoqualitee** [comment]
agreed, need some verbose feedback as i am unable to repro

**Comment by andreasjordan** [comment]
Will close this now, but can reopen when needed.
