### ISSUE TITLE
Dbatools offline install does not work

### ISSUE THREAD

**Issue by DevGKOne** [dataplat/dbatools#8731]
### Verified issue does not already exist?

No, I did not search

### What error did you receive?

Offline installation from zip file does not work .
Version:latest stable release.
System:On windows 2019 with SQL 2019, SSMS 17.9 installed
Procedure:downloaded dbatools-master, renamed it to dbatools copied to C:\Program Files\WindowsPowerShell\Modules

tried to use Get-DbaDbBackupHistory -sqlinstance server1, import-dbatools or restarting server did not help.

Error:
Get-DbaDbBackupHistory : The 'Get-DbaDbBackupHistory' command was found in the module 'dbatools', but the module c
not be loaded. For more information, run 'Import-Module dbatools'.
At line:1 char:1

Get-DbaDbBackupHistory -sqlinstance server1
  + CategoryInfo          : ObjectNotFound: (Get-DbaDbBackupHistory:String) [], CommandNotFoundException
  + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule
  
Other Test: Old zipped Version.: 1.1.132 dbatools works

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

### Please confirm that you are running the most recent version of dbatools

Last downloaded thia morning

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

5.1

### SQL Server Edition and Build number

2019

### .NET Framework Version

.net 4.8

**Comment by wsmelton** [comment]
Please run `Import-Module` and you will more details on why the module could not be loaded. If you do not have .NET 4.6 installed on the device it may also be an issue.

**Comment by DevGKOne** [comment]
If you install.net 4.8. .net 4.6 is already is installed.

If you take  fresh win 2019 server with .net 4.8 and  installing the new release does not work, but old releases all works. So something was changed. Import-module does not help.Module could not be loaded.So my answers won't help. Just testing will solve the problem, deep in the module there is a bug.

**Comment by wsmelton** [comment]
Our module depends on .NET 4.6 because that is the target framework we compiled our library for right now. It won't work with 4.8.

**Comment by wsmelton** [comment]
The module download from GitHub branch (master-dbatools.zip) is not a stable state to use at this time. We are preparing for a 2.0 release so master and developer. You can perform an offline install by download using `Save-Module` (on Internet device) or download via the releases [here](https://github.com/dataplat/dbatools/releases).

Ref: #8642
