### ISSUE TITLE
Module import fails on Azure DevOps self-hosted agent

### ISSUE THREAD

**Issue by sjmoden** [dataplat/dbatools#8733]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When running `Import-Module dbatools -verbose` on an self hosted Azure Agent I get the following error:

```
VERBOSE: Loading module from path 'C:\Users\AzDevOps\Documents\PowerShell\Modules\dbatools\1.1.143\dbatools.psd1'.
VERBOSE: Loading 'TypesToProcess' from path 'C:\Users\AzDevOps\Documents\PowerShell\Modules\dbatools\1.1.143\xml\dbatools.Types.ps1xml'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Users\AzDevOps\Documents\PowerShell\Modules\dbatools\1.1.143\xml\dbatools.Format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module dbatools.
VERBOSE: Loading module from path 'C:\Users\AzDevOps\Documents\PowerShell\Modules\dbatools\1.1.143\dbatools.psm1'.
Exception calling "Invoke" with "3" argument(s): "The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not import C:\Users\AzDevOps\Documents\PowerShell\Modules\dbatools\1.1.143\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll : Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly 'C:\Users\AzDevOps\Documents\PowerShell\Modules\dbatools\1.1.143\bin\smo\coreclr\Microsoft.SqlServer.XE.Core.dll'. The specified module could not be found."
At C:\Users\AzDevOps\Documents\PowerShell\Modules\dbatools\1.1.143\internal\scripts\libraryimport.ps1:150 char:21
+                     [Reflection.Assembly]::LoadFrom($assemblyPath)
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : FileNotFoundException
"
At C:\Users\AzDevOps\Documents\PowerShell\Modules\dbatools\1.1.143\internal\scripts\libraryimport.ps1:161 char:50
+ … Invoke($script:PSModuleRoot, "$(Join-Path $script:DllRoot smo)", $scr …
+                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : ActionPreferenceStopException
##[error]PowerShell exited with code '1'.

```

### Steps to Reproduce

```powershell
Install-Module dbatools -Force -Confirm:$false -AllowClobber -Repository psgallery
Import-Module dbatools -verbose
```

### Please confirm that you are running the most recent version of dbatools

This is using the latest version (1.1.143)

### Other details or mentions

This is being run on a VM Agent in Azure Devops with the following set up:

# Microsoft Windows Server 2022 Datacenter
- OS Version: 10.0.20348 Build 1487
- Image Version: dev

### Language and Runtime
- Node 18.13.0
- Python 3.11.0

### Package Management
- Chocolatey 1.2.1
- NPM 8.19.3
- NuGet 6.4.0.123
- pip 22.3 (python 3.11)

#### Environment variables
| Name                    | Value |
| ----------------------- | ----- |
| VCPKG_INSTALLATION_ROOT |       |

### Tools
- 7zip 22.01
- azcopy 10.16.2
- Bicep 0.13.1
- Docker 20.10.22
- Docker Compose 2.15.1
- Docker-wincred 0.7.0
- Git 2.39.1
- Git LFS 3.3.0
- Packer 1.8.4
- VSWhere 3.1.1

### CLI Tools
- Azure CLI 2.44.1
- Azure DevOps CLI extension 0.25.0

#### SQL Server
| Version     | ServiceName | Edition                    | FileVersion     |
| ----------- | ----------- | -------------------------- | --------------- |
| 15.0.2000.5 | SQL Server  | Developer Edition (64-bit) | 2019.150.2095.3 |

### Database tools
- DacFx 16.1.6374.0

### Visual Studio Build Tools 2022
| Name                           | Version        | Path                                                           |
| ------------------------------ | -------------- | -------------------------------------------------------------- |
| Visual Studio Build Tools 2022 | 17.4.33213.308 | C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools |

#### Workloads, components and extensions:

| Package                                                                             | Version        |
| ----------------------------------------------------------------------------------- | -------------- |
| android                                                                             | 33.0.4.0       |
| Component.Android.SDK.MAUI                                                          | 17.4.33118.351 |
| Component.OpenJDK                                                                   | 17.4.33006.217 |
| ios                                                                                 | 16.1.17.0      |
| maccatalyst                                                                         | 16.1.17.0      |
| maui.android                                                                        | 7.0.52.0       |
| maui.blazor                                                                         | 7.0.52.0       |
| maui.core                                                                           | 7.0.52.0       |
| maui.ios                                                                            | 7.0.52.0       |
| maui.maccatalyst                                                                    | 7.0.52.0       |
| maui.windows                                                                        | 7.0.52.0       |
| Microsoft.Component.ClickOnce.MSBuild                                               | 17.4.33006.217 |
| Microsoft.Component.MSBuild                                                         | 17.4.33006.217 |
| Microsoft.Component.NetFX.Native                                                    | 17.4.33006.217 |
| Microsoft.Net.Component.4.6.1.TargetingPack                                         | 17.4.33006.217 |
| Microsoft.Net.Component.4.6.TargetingPack                                           | 17.4.33006.217 |
| Microsoft.Net.Component.4.7.2.TargetingPack                                         | 17.4.33006.217 |
| Microsoft.Net.Component.4.8.SDK                                                     | 17.4.33006.217 |
| Microsoft.Net.Component.4.8.TargetingPack                                           | 17.4.33006.217 |
| Microsoft.Net.ComponentGroup.4.8.DeveloperTools                                     | 17.4.33006.217 |
| Microsoft.Net.ComponentGroup.DevelopmentPrerequisites                               | 17.4.33006.217 |
| Microsoft.Net.ComponentGroup.TargetingPacks.Common                                  | 17.4.33006.217 |
| microsoft.net.runtime.android                                                       | 7.0.222.60605  |
| microsoft.net.runtime.android.aot                                                   | 7.0.222.60605  |
| microsoft.net.runtime.android.aot.net6                                              | 7.0.222.60605  |
| microsoft.net.runtime.android.net6                                                  | 7.0.222.60605  |
| microsoft.net.runtime.ios                                                           | 7.0.222.60605  |
| microsoft.net.runtime.ios.net6                                                      | 7.0.222.60605  |
| microsoft.net.runtime.maccatalyst                                                   | 7.0.222.60605  |
| microsoft.net.runtime.maccatalyst.net6                                              | 7.0.222.60605  |
| microsoft.net.runtime.mono.tooling                                                  | 7.0.222.60605  |
| microsoft.net.runtime.mono.tooling.net6                                             | 7.0.222.60605  |
| Microsoft.NetCore.Component.Runtime.6.0                                             | 17.4.33213.308 |
| Microsoft.NetCore.Component.Runtime.7.0                                             | 17.4.33213.308 |
| Microsoft.NetCore.Component.SDK                                                     | 17.4.33213.308 |
| Microsoft.VisualStudio.Component.Azure.AuthoringTools                               | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.Azure.ClientLibs                                   | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.Azure.Waverton.BuildTools                          | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.CoreBuildTools                                     | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.DockerTools.BuildTools                             | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.Node.Build                                         | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.NuGet                                              | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.NuGet.BuildTools                                   | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.Roslyn.Compiler                                    | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.Roslyn.LanguageServices                            | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.Sharepoint.BuildTools                              | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.SQL.SSDTBuildSku                                   | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.TeamOffice.BuildTools                              | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.TestTools.BuildTools                               | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.TextTemplating                                     | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.TypeScript.TSServer                                | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.VC.ASAN                                            | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.VC.CMake.Project                                   | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.VC.CoreBuildTools                                  | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.VC.CoreIde                                         | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.VC.Redist.14.Latest                                | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.VC.Tools.x86.x64                                   | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.VSSDKBuildTools                                    | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.WebDeploy                                          | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.Windows10SDK                                       | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.Windows11SDK.22000                                 | 17.4.33006.217 |
| Microsoft.VisualStudio.Component.Workflow.BuildTools                                | 17.4.33006.217 |
| Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core                            | 17.4.33006.217 |
| Microsoft.VisualStudio.ComponentGroup.UWP.BuildTools                                | 17.4.33006.217 |
| Microsoft.VisualStudio.ComponentGroup.VisualStudioExtensionBuildTools.Prerequisites | 17.4.33006.217 |
| Microsoft.VisualStudio.Wcf.BuildTools.ComponentGroup                                | 17.4.33006.217 |
| Microsoft.VisualStudio.Web.BuildTools.ComponentGroup                                | 17.4.33006.217 |
| Microsoft.VisualStudio.Workload.AzureBuildTools                                     | 17.4.33006.217 |
| Microsoft.VisualStudio.Workload.DataBuildTools                                      | 17.4.33006.217 |
| Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools                            | 17.4.33006.217 |
| Microsoft.VisualStudio.Workload.MSBuildTools                                        | 17.4.33006.217 |
| Microsoft.VisualStudio.Workload.NodeBuildTools                                      | 17.4.33006.217 |
| Microsoft.VisualStudio.Workload.OfficeBuildTools                                    | 17.4.33006.217 |
| Microsoft.VisualStudio.Workload.UniversalBuildTools                                 | 17.4.33006.217 |
| Microsoft.VisualStudio.Workload.VCTools                                             | 17.4.33006.217 |
| Microsoft.VisualStudio.Workload.VisualStudioExtensionBuildTools                     | 17.4.33006.217 |
| Microsoft.VisualStudio.Workload.WebBuildTools                                       | 17.4.33006.217 |
| Microsoft.VisualStudio.Workload.XamarinBuildTools                                   | 17.4.33006.217 |
| runtimes.ios                                                                        | 7.0.222.60605  |
| runtimes.ios.net6                                                                   | 7.0.222.60605  |
| runtimes.maccatalyst                                                                | 7.0.222.60605  |
| runtimes.maccatalyst.net6                                                           | 7.0.222.60605  |

### .NET Core SDK
`Location C:\Program Files\dotnet\sdk`
- 6.0.113 6.0.203 6.0.308 6.0.405 7.0.102

### .NET Core Runtime
`Location: C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App`
- 6.0.5 6.0.13 7.0.2

`Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App`
- 6.0.5 6.0.13 7.0.2

`Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App`
- 6.0.5 6.0.13 7.0.2

### .NET Framework
`Type: Developer Pack`
`Location C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX <version> Tools`
- 4.8 4.8.1

### PowerShell Tools
- PowerShell 7.3.1

#### Azure Powershell Modules
| Module | Version            | Path                      |
| ------ | ------------------ | ------------------------- |
| Az     | 7.5.0.zip<br>9.2.0 | C:\Modules\az_\<version\> |

#### Powershell Modules
| Module             | Version          |
| ------------------ | ---------------- |
| DockerMsftProvider | 1.0.0.8          |
| MarkdownPS         | 1.9              |
| Pester             | 3.4.0<br>5.4.0   |
| PowerShellGet      | 1.0.0.1<br>2.2.5 |
| SqlServer          | 21.1.18256       |
| VSSetup            | 2.2.16           |

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

|Name    |                       Value|
|----                           |-----|
|PSVersion         |             7.3.1|
|PSEdition         |             Core|
|GitCommitId        |            7.3.1|
|OS                      |       Microsoft Windows 10.0.20348|
|Platform               |        Win32NT|
|PSCompatibleVersions     |      {1.0, 2.0, 3.0, 4.0…}|
|PSRemotingProtocolVersion  |    2.3|
|SerializationVersion     |      1.1.0.1|
|WSManStackVersion |             3.0|

### SQL Server Edition and Build number

Version: 15.0.2000.5
Edition: Developer Edition (64-bit)

### .NET Framework Version

**.NET Core SDK**
Location C:\Program Files\dotnet\sdk

- 6.0.113 6.0.203 6.0.308 6.0.405 7.0.102

**.NET Core Runtime**
Location: C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App

- 6.0.5 6.0.13 7.0.2

Location: C:\Program Files\dotnet\shared\Microsoft.NETCore.App

- 6.0.5 6.0.13 7.0.2

Location: C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App

- 6.0.5 6.0.13 7.0.2

**.NET Framework**
Type: Developer Pack Location C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX <version> Tools

- 4.8 4.8.1

**Comment by wsmelton** [comment]
The target framework for our module is 4.6 which that VM Agent version does not show to have installed. 4.8 Framework is not backward compatibility to 4.6.

You will need to install .NET 4.6 runtime before you try to import the module.

**Comment by sjmoden** [comment]
@wsmelton I can confirm that this has resolved the issue. Thank you!

@potatoqualitee What you suggested also works.

**Comment by potatoqualitee** [comment]
Can you pls try with 2.5.5 and let me know if it has issues. If so, I'll kindly ask @SQLDBAWithABeard if he can reach out to the Azure team. I saw someone got this recently:

<img width="504" height="378" alt="Image" src="https://github.com/user-attachments/assets/d6b6d62e-55b2-4fd3-9c75-8f4289392f16" />

In order to get out timely releases, we had to include all packages from SMO, SqlClient, etc. So the library can now easily stay up to date. For a while there, many of our dependencies had CVEs so I hope Microsoft takes this into account but perhaps it is a resource issue.
