### ISSUE TITLE
Insert multiple rows in one INSERT (Export-DbaDbTableData output file)

### ISSUE THREAD

**Issue by Santanachia** [dataplat/dbatools#8739]
### Summarize Functionality

currently there is one command for each row in the table
```sql
INSERT EmployeePayHistory(BusinessEntityID, RateChangeDate, Rate, PayFrequency, ModifiedDate) VALUES (data1)
GO
INSERT EmployeePayHistory(BusinessEntityID, RateChangeDate, Rate, PayFrequency, ModifiedDate) VALUES (data2)
GO
INSERT EmployeePayHistory(BusinessEntityID, RateChangeDate, Rate, PayFrequency, ModifiedDate) VALUES (data3)
GO
```
it would be good to combine them into one command
```sql
INSERT EmployeePayHistory(BusinessEntityID, RateChangeDate, Rate, PayFrequency, ModifiedDate) VALUES
  (data1),
  (data2),
  (data3)
GO
```

Executing such a single command instead of many will speed up the execution of the entire file.
It would be good to be able to pass the number of rows per command as a parameter (1000 by default)

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

```powershell
PS C:\> Get-DbaDbTable -SqlInstance sql2017 -Database AdventureWorks2014 -Table EmployeePayHistory | Export-DbaDbTableData -RowsPerBatch 100
```

**Comment by wsmelton** [comment]
This command is a simple wrapper to `Export-DbaScript` and uses `Microsoft.SqlServer.Management.Smo.ScriptingOptions` to determine in what structure it is formatted.

What you are asking for is not supported by Scripting options in SMO. It will always output the data inserts as individual statements, you can only control the batch size which is just controlling where it puts the `GO` terminator.
