### ISSUE TITLE
Remove-DbaDbTable with Confirm is not work

### ISSUE THREAD

**Issue by qpowjohn** [dataplat/dbatools#8743]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Remove-DbaDbTable : Cannot process argument transformation on parameter 'SqlCredential'. userName
At line:4 char:84
+ ... qlInstance $SqlInstance -Database Database -Confirm $false
+                                                                    ~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-DbaDbTable], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Remove-DbaDbTable

### Steps to Reproduce

not writeout on console, and not deleted any table
SQL Account
```powershell
$Username = 'sa'
$Password = ConvertTo-SecureString 'P@ssW0rd' -AsPlainText -Force
$Credential = New-Object System.Management.Automation.PSCredential ($Username,$Password)
Remove-DbaDbTable -SqlInstance 127.0.0.1 -SqlCredential $Credential -Database Database -Confirm $false
```

incomprehensible error
Windows Account (Grant Administrator permissions)
```powershell
$SqlInstance = Connect-DbaInstance -SqlInstance 127.0.0.1
Remove-DbaDbTable -SqlInstance $SqlInstance -Database Database -Confirm $false

Remove-DbaDbTable : Cannot process argument transformation on parameter 'SqlCredential'. userName
At line:4 char:84
+ ... qlInstance $SqlInstance -Database Database -Confirm $false
+                                                         ~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-DbaDbTable], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Remove-DbaDbTable

#try $SqlInstance is work?
Get-DbaDbTable -SqlInstance $SqlInstance -Database Database 

ComputerName          : ComputerName
InstanceName          : MSSQLSERVER
SqlInstance           : SqlInstance
Database              : Database
Schema                : dbo
Name                  : TableName
IndexSpaceUsed        : 0
DataSpaceUsed         : 0
RowCount              : 0
HasClusteredIndex     : False
IsFileTable           : False
IsMemoryOptimized     : False
IsPartitioned         : False
FullTextIndex         : 
ChangeTrackingEnabled : False
```
****

### Please confirm that you are running the most recent version of dbatools

1.1.143

### Other details or mentions

sql-2016-standard-windows-2019-dc-v20230111 on GCP

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                     
----                           -----                                                                                                                                     
PSVersion                      5.1.17763.3770                                                                                                                            
PSEdition                      Desktop                                                                                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                   
BuildVersion                   10.0.17763.3770                                                                                                                           
CLRVersion                     4.0.30319.42000                                                                                                                           
WSManStackVersion              3.0                                                                                                                                       
PSRemotingProtocolVersion      2.3                                                                                                                                       
SerializationVersion           1.1.0.1                                                                                                                                   

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP3-CU1-GDR) (KB5015371) - 13.0.7016.1 (X64)   May 21 2022 01:00:03   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.8.4515.0

**Comment by potatoqualitee** [comment]
hey @qpowjohn - it's unfortunate but the explicit false syntax is ugly and is: `-Confirm:$false`. 

So instead of a space, you'd add a colon.
