### ISSUE TITLE
FQDN needed on instances with SSL/TLS 

### ISSUE THREAD

**Issue by Skodaddy** [dataplat/dbatools#8744]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When we run commands to SQL server instances that are encrypted with SSL (connection encryption); these always fail if we don't use the FQDN.
Commands from the SQLSERVER module run without FQDN.

Example:
SQLSERVER: Sqldatabase -ServerInstance 'SERVER\INSTANCE' --> works
SQLSERVER: Sqldatabase -ServerInstance 'SERVER.domain.com\INSTANCE' --> works
DBATOOLS: Get-dbadatabase -SqlInstance 'SERVER\INSTANCE' --> WARNING: [09:51:44][Get-DbaDatabase] Failure | The target principal name is incorrect
DBATOOLS: Get-dbadatabase -SqlInstance 'SERVER.domain.com\INSTANCE' --> Works

This gives a lot of issues when you pipe to next step:
example: Get-DbaAvailabilityGroup -SqlInstance 'SERVER.domain.com\INSTANCE' | Sync-DbaAvailabilityGroup -Whatif
will give an error for each AG:
What if: Performing the operation "Set variable" on target "Name: __dbatools_interrupt_function_78Q9VPrM6999g6zo24Qn83m0
9XF56InEn4hFrA8Fwhu5xJrs6r Value: True".
WARNING: [09:59:01][Sync-DbaAvailabilityGroup] Failure | The target principal name is incorrect
What if: Performing the operation "Set variable" on target "Name: __dbatools_interrupt_function_78Q9VPrM6999g6zo24Qn83m0
9XF56InEn4hFrA8Fwhu5xJrs6r Value: True".
WARNING: [09:59:01][Sync-DbaAvailabilityGroup] Failure | The target principal name is incorrect

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Get-dbadatabase -SqlInstance 'SERVER\INSTANCE'  # gives WARNING: [09:51:44][Get-DbaDatabase] Failure | The target principal name is incorrect
Get-dbadatabase -SqlInstance 'SERVER.domain.com\INSTANCE'  # Works

### Please confirm that you are running the most recent version of dbatools

1.1.145

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

**
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.5582                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.5582                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

**

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64)   Jan 12 2022 22:30:08   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.8.4526.0

**Comment by potatoqualitee** [comment]
Thanks for the report, can you check to see if the connections from the sql server module are encrypted?

```
SELECT session_id, connect_time, net_transport, encrypt_option, auth_scheme, client_net_address 
FROM sys.dm_exec_connections
```

Did you set both hostnames in your SSL cert (using a SAN)?

**Comment by Skodaddy** [comment]
invoke-dbaquery  -SqlInstance 'SERVER\INSTANCE' -query 'SELECT session_id, connect_time, net_transport, encrypt_option, auth_scheme, client_net_address FROM sys.dm_exec_connections WHERE session_id = @@spid'
net_transport      : TCP
encrypt_option     : TRUE
auth_scheme        : KERBEROS

invoke-dbaquery  -SqlInstance 'SERVER.domain.com\INSTANCE' -query 'SELECT session_id, connect_time, net_transport, encrypt_option, auth_scheme, client_net_address FROM sys.dm_exec_connections WHERE session_id = @@spid'
net_transport      : TCP
encrypt_option     : TRUE
auth_scheme        : KERBEROS

Only the FQDN names (Server, AG listeners,...) are in the certificate san names, NETBIOS names are not

**Comment by niphlod** [comment]
this is the same as asking for the browser to go to https://google and figure out you'd really like to go to www.google.com instead.
If you want encryption (which you should at this day and age) you need to use the name covered by the SAN in the cert.
If you want to use NETBIOS, you need to loose the ssl cert verification.

**Comment by potatoqualitee** [comment]
> invoke-dbaquery

I meant the SqlServer module, please let me know what invoke-sqlcmd says. Like @niphlod said, I'm thinking their setting is set to trust the cert whereas ours is not.

**Comment by Skodaddy** [comment]
Sorry for that, correct output this time (hopefully):

Invoke-Sqlcmd  -ServerInstance 'SERVER\INSTANCE' -query 'SELECT session_id, connect_time, net_transport, encrypt_option, auth_scheme, client_net_address FROM sys.dm_exec_connections WHERE session_id = @@spid'
net_transport      : TCP
encrypt_option     : TRUE
auth_scheme        : KERBEROS

Invoke-Sqlcmd  -ServerInstance 'SERVER.domain.com\INSTANCE' -query 'SELECT session_id, connect_time, net_transport, encrypt_option, auth_scheme, client_net_address FROM sys.dm_exec_connections WHERE session_id = @@spid'
net_transport      : TCP
encrypt_option     : TRUE
auth_scheme        : KERBEROS

Underlying problem is, that even if we use FQDN, we will still get issues if we pipe our commands, since those are not returned with FQDN:
Get-DbaAvailabilityGroup -SqlInstance 'SERVER.domain.com\INSTANCE' | Sync-DbaAvailabilityGroup -Whatif
What if: Performing the operation "Set variable" on target "Name: __dbatools_interrupt_function_78Q9VPrM6999g6zo24Qn83m0
9XF56InEn4hFrA8Fwhu5xJrs6r Value: True".
WARNING: [09:59:01][Sync-DbaAvailabilityGroup] Failure | The target principal name is incorrect

**Comment by potatoqualitee** [comment]
Can you try and let me know if this works?

```
Set-DbatoolsConfig -FullName 'sql.connection.trustcert' -Value $true -Register
```

**Comment by Skodaddy** [comment]
Chrissy,

yeps, then it works:

First tested that issue is still there:
PS C:\WINDOWS\system32>Get-DbaAvailabilityGroup -SqlInstance 'SERVER.domain.com\INSTANCE' | Sync-DbaAvailabilityGroup -Whatif
What if: Performing the operation "Set variable" on target "Name: __dbatools_interrupt_function_78Q9VPrM6999g6zo24Qn83m0
9XF56InEn4hFrA8Fwhu5xJrs6r Value: True".
WARNING: [09:59:01][Sync-DbaAvailabilityGroup] Failure | The target principal name is incorrect

PS C:\WINDOWS\system32> Set-DbatoolsConfig -FullName 'sql.connection.trustcert' -Value $true -Register

PS C:\WINDOWS\system32>Get-DbaAvailabilityGroup -SqlInstance 'SERVER.domain.com\INSTANCE' | Sync-DbaAvailabilityGroup -Whatif
What if: Performing the operation "Sync-DbaAvailabilityGroup" on target "Syncing SQL Server Configuration from SERVER1.domain.com\INSTANCE to SERVER2\INSTANCE".

**Comment by potatoqualitee** [comment]
okay, that makes sense. those are the defaults for older versions of SMO/SqlClient and we're using the newer one. Microsoft is big changes to this space, which also impacts ADS and will probably impacts SSMS soon. you can read more here:

**Comment by Skodaddy** [comment]
Okido, thnx a million for the help!!
