### ISSUE TITLE
Backup-DbaDatabase - Include Database name on untested failure warnings when invoked with multiple Databases

### ISSUE THREAD

**Issue by wain13001** [dataplat/dbatools#8745]
### Summarize Functionality

This is a request to adjust the Warning notification that happens on a backup failure caused by an untested condition when backing up multiple databases using Backup-DbaDatabase.  It would be preferable for the warning to include the the name of the database that failed backup.

Example:
I have multiple databases on multiple Always On Availability Groups on a server.  Not all availability groups are primary on the same SQLinstance.

If I run a command such as the following (including only essential parameters for explanation)
Backup-DBADatabase -database @('dbONE','dbTWO','dbTHREE') -backuptype DIFF

If dbTWO is on an AOAG that is secondary on this instance, the backup will fail and Backup-DbaDatabase will push a warning to the warning stream with the following message:

WARNING: [19:52:32][Backup-DbaDatabase] Backup Failed | Microsoft.Data.SqlClient.SqlError: This BACKUP or RESTORE command is not supported on a database mirror or secondary replica. 
---

The problem is the SQL Error doesn't include the database name, and neither does the warning message from Backup-DbaDatabase.  So now it is significantly more difficult to determine which Databases from the array passed into Backup-DbaDatabase are the ones that failed, and to associate the correct failure messages with the correct databases (in the case of multiple differing issues) for additional error handling.

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

I suspect it would require a minor change to 

https://github.com/dataplat/dbatools/blob/f2d98f398b87af9a349c2d7817a4e03b04d6c6da/public/Backup-DbaDatabase.ps1#L818

to something like

`Stop-Function -message "$dbName Backup Failed" -ErrorRecord $_ -Continue`

**Comment by wsmelton** [comment]
The call to Stop command should have -Target with the database name passed in.

**Comment by andreasjordan** [comment]
Target is only incuded in logging, not in message to user. So message must be changed as well. Will open an PR for that...
