### ISSUE TITLE
Get-DbaAgBackupHistory - Raw parameter use causes exception thrown on AvailabilityGroupName

### ISSUE THREAD

**Issue by daarrn** [dataplat/dbatools#8747]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

PSMessageDetails      : 
Exception             : System.Management.Automation.SetValueInvocationException: Exception setting "AvailabilityGroupName": "The property 'AvailabilityGroupName' cannot be found on this object. Verify that 
                        the property exists and can be set." ---> System.Management.Automation.RuntimeException: The property 'AvailabilityGroupName' cannot be found on this object. Verify that the property 
                        exists and can be set.
                           at System.Management.Automation.Language.PSSetMemberBinder.SetAdaptedValue(Object obj, String member, Object value)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.ConvertToMethodInvocationException(Exception exception, Type typeToThrow, String methodName, Int32 numArgs, MemberInfo 
                        memberInfo)
                           at System.Management.Automation.Language.PSSetMemberBinder.SetAdaptedValue(Object obj, String member, Object value)
                           at lambda_method(Closure , Object[] , StrongBox`1[] , InterpretedFrame )
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
FullyQualifiedErrorId : ExceptionWhenSetting
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-DbaAgBackupHistory<End>, C:\Program Files\WindowsPowerShell\Modules\dbatools\1.1.145\allcommands.ps1: line 19748
                        at <ScriptBlock>, <No file>: line 7
PipelineIterationInfo : {}

### Steps to Reproduce

```powershell
$pServerName = '<obfuscated>' 
$AGName = '<obfuscated>'  
$pDatabaseName = '<obfuscated>'

Get-DbaAGBackupHistory -SqlInstance $pServerName -AvailabilityGroup $AGName -Database $pDatabaseName -Type Full -DeviceType Disk -Raw -EnableException
```

### Please confirm that you are running the most recent version of dbatools

1.1.145

### Other details or mentions

[debug.txt](https://github.com/dataplat/dbatools/files/10572390/debug.txt)

output of -verbose and -debug switch attached

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                             
----                           -----                                                                                                                                                                             
PSVersion                      5.1.17763.3770                                                                                                                                                                    
PSEdition                      Desktop                                                                                                                                                                           
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                           
BuildVersion                   10.0.17763.3770                                                                                                                                                                   
CLRVersion                     4.0.30319.42000                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                               
PSRemotingProtocolVersion      2.3                                                                                                                                                                               
SerializationVersion           1.1.0.1 

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU18) (KB5017593) - 15.0.4261.1 (X64)   Sep 12 2022 15:07:06   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.7.3946.0

**Comment by andreasjordan** [comment]
Could you please retest with the current version 2.0.3?

**Comment by andreasjordan** [comment]
I can reproduce the issue, but it works without `-Raw`. Will have a look now...

**Comment by andreasjordan** [comment]
Opened a PR with a fix to Get-DbaDbBackupHistory with an empty AvailabilityGroupName like in the other code path.
