### ISSUE TITLE
The Releases page is not updated and changelog is severly outdated. 

### ISSUE THREAD

**Issue by frodr1k** [dataplat/dbatools#8749]
### Verified issue does not already exist?

No, I did not search

### What error did you receive?

The Releases page is not updated, it lags behind and only shows 1.1.142 , despite currecnt version is 145. 

also,  changelog is very outdated: https://github.com/dataplat/dbatools/blob/development/changelog.md

### Steps to Reproduce

just go to https://github.com/dataplat/dbatools/releases

### Please confirm that you are running the most recent version of dbatools

I going to the full URL of releases

https://github.com/dataplat/dbatools/releases

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

NA

### SQL Server Edition and Build number

NA

### .NET Framework Version

NA

**Comment by wsmelton** [comment]
Yes. It will be corrected when 2.0 is released.
