### ISSUE TITLE
Test-DbaSpn doesn't work against SQL Server 2014 instances "SQL Server WMI provider is not available"

### ISSUE THREAD

**Issue by berki7867** [dataplat/dbatools#8750]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When you do a Test-DbaSpn it doesn't work against SQL Server 2014 instances you get a 
"SQL Server WMI provider is not available"

but for SQL Server 2016+ it works fine.

This issue was fixed as part of Development #5072

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Test-DbaSpn -ComputerName 'SQL 14 instance' -Verbose

### Please confirm that you are running the most recent version of dbatools

1.1.81

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

PSVersion                      7.2.5
PSEdition                      Core
GitCommitId                    7.2.5
OS                             Microsoft Windows 10.0.14393
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2014 (SP3-CU4-GDR) (KB5014164) - 12.0.6439.10 (X64)   Apr 20 2022 03:13:42   Copyright (c) Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.3 <X64> (Build 14393: ) (Hypervisor) 

### .NET Framework Version

.NET 6.0.6

**Comment by wsmelton** [comment]
Please use the latest version of the module and retest.

**Comment by berki7867** [comment]
Sorry still the same error on version 1.1.145

**Comment by wsmelton** [comment]
Is SQL WMI functioning correctly on the server? (meaning opening SQL Server 2014 Configuration Manager without errors)

**Comment by berki7867** [comment]
Yep - opens fine on the servers, no errors. 
I've tried it on two different SQL 2014 instances.

**Comment by wsmelton** [comment]
Are you on Windows Server 2012 R2 by chance? 

Do you have any SQL Server 2014 on 2016 or 2019 OS that have the same issue?

**Comment by mattcargile** [comment]
I've seen kind of this issue when different SQL Server versions are installed/uninstalled. In order to fix, I followed [this guide](https://learn.microsoft.com/en-us/troubleshoot/sql/tools/error-message-when-you-open-configuration-manager) for all the applicable _Configuration Manager_ versions that I had. I even did it for a newer version of SQL Server that was uninstalled.

**Comment by berki7867** [comment]
No, for both SQL 2014 instances the two servers are Windows server 2016

**Comment by mattcargile** [comment]
I'm not referring to Windows Server versions. At any rate, we need more information from you to troubleshoot. I ran `test-dbaspn` on 14 _prod_ and _test_ _2014_ instances without this error. 

Can you look the guide I referenced above? Can you run the below local to the machine that is impacted either through _RDP_ or `Enter-PSSession`?
```powershell
[reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.SqlWmiManagement")
[Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer]::new().serverinstances
```
These pieces of code are run during `Test-DbaSpn`.

**Comment by berki7867** [comment]
Hi,

I tried mofcomp "sqlmgmproviderxpsp2up.mof" which completed successfully with Done!
Gave the WMI service a restart even rebooted the VM but the Test-DBASPN still gives the same error.

Running 

[reflection.assembly]::LoadWithPartialName("Microsoft.SqlServer.SqlWmiManagement")
[Microsoft.SqlServer.Management.Smo.Wmi.ManagedComputer]::new().serverinstances

Gives the error 
GAC    Version        Location                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
True   v2.0.50727     C:\Windows\assembly\GAC_MSIL\Microsoft.SqlServer.SqlWmiManagement\13.0.0.0__89845dcd8080cc91\Microsoft.SqlServer.SqlWmiManagement.dll
The following exception occurred while trying to enumerate the collection: "SQL Server WMI provider is not available on XXXXXXXXXX.".

But it must be a "local" problem.
I'm happy to close this issue .
