### ISSUE TITLE
Enable/Disable DbaAgentJob

### ISSUE THREAD

**Issue by irfancharania** [dataplat/dbatools#8753]
### Summarize Command's Functionality

It would be really handy to have the ability to enable or disable a SQL Server Agent job.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

Methods to enable or disable an agent job are described here:
https://learn.microsoft.com/en-us/sql/ssms/agent/disable-or-enable-a-job?view=sql-server-ver16

**Comment by wsmelton** [comment]
This functionally exist in the [Set-DbaAgentJob](https://docs.dbatools.io/Set-DbaAgentJob).

**Comment by irfancharania** [comment]
Thank you for pointing it out! I had searched but didn't find it...
