### ISSUE TITLE
Get-DbaAgHadr should return the IsHadrEnabled property by default

### ISSUE THREAD

**Issue by jpomfret** [dataplat/dbatools#8754]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Running the following doesn't show the `IsHadrEnabled` property by default

`Get-DbaAgHadr -SqlInstance mssql1`

But it is on the object as expected
`Get-DbaAgHadr -SqlInstance Beard2019AG1 | select IsHadrEnabled`

![image](https://user-images.githubusercontent.com/981370/217737676-2abbb613-2c95-4ce3-80a2-7c9d8b6753ad.png)

### Steps to Reproduce

```powershell
Get-DbaAgHadr -SqlInstance mssql1
```

### Please confirm that you are running the most recent version of dbatools

1.1.145

### Other details or mentions

Does look like it's using `Select-DefaultView` not sure why 

https://github.com/dataplat/dbatools/blob/development/public/Get-DbaAgHadr.ps1#L59

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe)

### PowerShell Host Version

Tested in both these versions:
----

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.22000.1335                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.22000.1335                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

15.0.4261

### .NET Framework Version

.NET 7.0.2

**Comment by andreasjordan** [comment]
The code just uses Connect-DbaInstance and then at last: `Select-DefaultView -InputObject $server -Property 'ComputerName', 'InstanceName', 'SqlInstance', 'IsHadrEnabled'` which does indeed not works as it should.
Maybe this has something to do with the way we now set the default properties by object type? I think @wsmelton is one of the experts in this case.

Would it be an option to just return as PSCustomObject with the properties 'ComputerName', 'InstanceName', 'SqlInstance', 'IsHadrEnabled'? I could code that...

By the way: These lines should be removed as not needed:
```
            Add-Member -Force -InputObject $server -MemberType NoteProperty -Name ComputerName -value $server.ComputerName
            Add-Member -Force -InputObject $server -MemberType NoteProperty -Name InstanceName -value $server.ServiceName
            Add-Member -Force -InputObject $server -MemberType NoteProperty -Name SqlInstance -value $server.DomainInstanceName
```

**Comment by wsmelton** [comment]
This is not working because we added a format file for `Connect-DbaInstance` so that overwrites what any command will output if they match the same class of `Microsoft.SqlServer.Management.Smo.Server`

**Comment by wsmelton** [comment]
Quick fix is just adding the property to the format for this class name

https://github.com/dataplat/dbatools/blob/0433f3260cc448b8ca932b8da4a4b777a656768a/xml/dbatools.Format.ps1xml#L27-L84

**Comment by andreasjordan** [comment]
But that would add it to the normal output of Connect-DbaInstance - which I don't want to change.

So I would vote for just returning a PSCustomObject with the needed properties. @jpomfret in what cases and context do you use the command? You don't need the full server SMO object, or do you?

**Comment by wsmelton** [comment]
Why would we not want to have this as a default property for Connect? We output `IsClustered`; which Microsoft pushes less now than use of AGs.

**Comment by andreasjordan** [comment]
Ok, good point. Then lets add IsHadrEnabled. I'll open a PR.

**Comment by jpomfret** [comment]
Makes sense to me - would rather keep server objects where possible
