### ISSUE TITLE
`Get-DbaStartupParameter` - `Write-Message` Doesn't Exist On Remote

### ISSUE THREAD

**Issue by mattcargile** [dataplat/dbatools#8756]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Code below throws _The term 'Write-Message' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again._ 

https://github.com/dataplat/dbatools/blob/1652adcea1e6baf997f425ae22535e30355320fc/public/Get-DbaStartupParameter.ps1#L89-L91

### Steps to Reproduce

```powershell
get-dbastartupparameter remotesql # Where `-t` is used on remotesql
```

### Please confirm that you are running the most recent version of dbatools

Running the below on local and remote.

```log
Major  Minor  Build  Revision
-----  -----  -----  --------
1      1      142    -1
```

### Other details or mentions

`Write-Message` is used inside the `$scriptblock` where it _probably_ won't exist when called remotely.

https://github.com/dataplat/dbatools/blob/1652adcea1e6baf997f425ae22535e30355320fc/public/Get-DbaStartupParameter.ps1#L178-L182

Not sure what the procedure us for this. Maybe a simpler `Write-Warning` would bubble up to `Invoke-ManagedComputerCommand`. I think @andreasjordan is familiar with this command.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe)

### PowerShell Host Version

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.17763.1852
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.1852
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

```sql
Microsoft SQL Server 2014 (SP3) (KB4022619) - 12.0.6024.0 (X64)
        Sep  7 2018 01:37:51
        Copyright (c) Microsoft Corporation
        Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: )
```
```sql
Microsoft SQL Server 2017 (RTM-CU20) (KB4541283) - 14.0.3294.2 (X64) 
	Mar 13 2020 14:53:45 
	Copyright (C) 2017 Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)
```

### .NET Framework Version

`.NET Framework 4.7.3946.0`
`.NET 6.0.8`

**Comment by wsmelton** [comment]
It needs to be removed. None of our codebase should be using any messaging in script blocks, especially internal functions. Warning and Verbose calls in the ScriptBlock parameter for Invoke-Command does not honor the preference settings a user may have in their local session. We should not be causing additional output they didn't ask for.

**Comment by andreasjordan** [comment]
I removed the warning and instead added the debug flags to the output like the trace flags. See linked PR...
