### ISSUE TITLE
`New-DbaEndpoint` - Allow Setting `Payload.DatabaseMirroring.EndpointAuthenticationOrder`

### ISSUE THREAD

**Issue by mattcargile** [dataplat/dbatools#8759]
### Summarize Functionality

Add new _Authentication_ parameter to accept `Negotiate` , `Kerberos` , or `Ntlm` within the _enum_ `[Microsoft.SqlServer.Management.Smo.EndpointAuthenticationOrder]`. Currently it _defaults_ to `Negotiate`. Additionally, it may be beneficial to have an _SPN_ component. I'm not sure how that works. I assume it would have to be `MSSQLSvc/db1.dmn.net:5022` where `5022` is the `ENDPOINT` port.

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

The modification of the `EndpointAuthenticationOrder` is fairly straightforward and could be set prior to the `Create` method being called like the other properties are set.

For the SPN, I can't find any direct docs on how that works. I found the [below ](https://learn.microsoft.com/en-us/sql/database-engine/availability-groups/windows/specify-endpoint-url-adding-or-modifying-availability-replica?view=sql-server-ver16) saying that is required.

[This ](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/d699fb11-febb-4790-be05-099f7d075f5d/cannot-set-partner-nt-authorityanonymous-logon-failed?forum=sqldatabasemirroring)old forum post from Remus suggests the SPN is in the format previously described.

**Comment by wsmelton** [comment]
Yeah if any specific option requires additional inputs that would need to be handled as well.

**Comment by andreasjordan** [comment]
Will try to work on this in the next days.

**Comment by andreasjordan** [comment]
This is not so easy. https://learn.microsoft.com/de-de/dotnet/api/microsoft.sqlserver.management.smo.endpointauthenticationorder?view=sql-smo-160 lists a lot of possible values:

![image](https://github.com/dataplat/dbatools/assets/66946165/55270a72-7656-4d45-9dc2-8a8e75c8f736)

We would need all of the as possive values in the ValidateSet, don't we?

And we should name the parameter AuthenticationOrder, as the type is named.
