### ISSUE TITLE
Odd issue with Get-DbaAvailabilityGroup after Get-DbaLogin

### ISSUE THREAD

**Issue by RobBittner** [dataplat/dbatools#8765]
This is a puzzling one, but when I run the following command:
Get-DbaAvailabilityGroup -SqlInstance MyInstance

It runs fine.

If I run a Get-DbaLogin -SQLInstance MyInstance first, the Get-DbaAvailabilityGroup only returns the Availability Group Name.

This seems like a pretty obscure edge case, but I need to do the above steps in order to achieve what I'm trying to do.

Thanks,
Rob

**Comment by andreasjordan** [comment]
Can you run this please?

```
Get-DbaLogin -SQLInstance MyInstance | Format-Table
Get-DbaAvailabilityGroup -SqlInstance MyInstance | Formt-Table
```

**Comment by andreasjordan** [comment]
@RobBittner - is this still an issue? Or can we close it?

**Comment by andreasjordan** [comment]
Closing this now, but can reopen if needed.
