### ISSUE TITLE
Add Property DefaultDatabase to Get-DbaLogin output

### ISSUE THREAD

**Issue by RobBittner** [dataplat/dbatools#8766]
### Summarize Functionality

For the properties returned, could you add DefaultDatabase?  That would be most helpful.

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by wsmelton** [comment]
Are you using the command interactively, in a script, just because? Please provide more details on purpose and justification why it is needed.

**Comment by RobBittner** [comment]
I'm running this in a script.  I am working on synchronizing logins between my Availability Group replicas and I need to be able to create a new user (with a default database).

If I could be really picky, I'd love to grab the hash of both the password and sid since I'm using that to create the user.
  upper(sys.fn_varbintohexstr(convert(varbinary(max), LOGINPROPERTY('<loginName>', 'PasswordHash'))))

and
 select upper(sys.fn_varbintohexstr(sid) from sys.syslogins where loginname='<loginName>'

**Comment by wsmelton** [comment]
In scripts the default properties added to an object are inherited by the object SMO outputs. We do not manipulate that in the commands except for adding a few standard properties. `Get-DbaLogin` contains the DefaultDatabase property out-of-the-box so to speak. You see all the properties available to you by piping the command to `Get-Member`.

In reference to synchronizing logins for Availability Groups we have commands in the module for managing that without having to reinvent the wheel.

- [Sync-DbaAvailabilityGroup](https://docs.dbatools.io/Sync-DbaAvailabilityGroup): covers everything needed to synchronize AG objects from primary to N+ replicas
- [Copy-DbaLogin](https://docs.dbatools.io/Copy-DbaLogin): covers strictly duplicating logins to another instance. We take care of copying the password and SID, there are other parameter options to manipulate some things if you wish as well.

**Comment by RobBittner** [comment]
This is wandering off from the original post, but Sync-DbaAvailabilityGroup is EXACTLY what I'm looking for.  It doesn't seem to sync my agent jobs though.  I tried Copy-DbaAgentJob and that worked one time, but on subsequent runs it's not doing anything (no output or anything).

**Comment by wsmelton** [comment]
Please review the documentation for the command, you can also use `-Verbose` to see more details on what the command is doing.
