### ISSUE TITLE
Invoke-DbaQuery throws error: Property NonPooledConnection cannot be changed or read after a connection string has been set.

### ISSUE THREAD

**Issue by hcuk94** [dataplat/dbatools#8772]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

This appears to be a similar issue to #4946 
I am trying to run dbatools in an Azure Automation, so I can run certain SQL commands on Azure PaaS databases on schedules etc.
I get this error:
[20:43:10][Invoke-DbaQuery] Failure | Property NonPooledConnection cannot be changed or read after a connection string has been set.

I have pasted my code in the 'steps to reproduce' below. The Azure Run As Account has the correct permissions to the database.
I have tried adding -NonPooledConnection to my Connect-DbaInstance command but to no avail.

### Steps to Reproduce

`# SQL Query
$SqlStatement = @"
SELECT * FROM Sample
WHERE StartDate > '2023-01-20'
"@
$Cred = Get-AzAccessToken -ResourceUrl https://database.windows.net
$Token = $Cred.Token
$SQLServer = Connect-DbaInstance -SqlInstance $server -AccessToken $Token
$Result = Invoke-DbaQuery -SqlInstance $SQLServer -Database $database -Query $SqlStatement

Write-Output $Result`

### Please confirm that you are running the most recent version of dbatools

Yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

5.1

### SQL Server Edition and Build number

Azure SQL PaaS

### .NET Framework Version

4.6

**Comment by andreasjordan** [comment]
Will close this now, but can reopen if needed.
