### ISSUE TITLE
Read-DbaTransactionLog function return "System.Data.DataRow"

### ISSUE THREAD

**Issue by cstratton144** [dataplat/dbatools#8773]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

"System.Data.DataRow"

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
$Log = Read-DbaTransactionLog -SqlInstance sqlserver1 -Database database1
Write-Host $Log

### Please confirm that you are running the most recent version of dbatools

1.1.88

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                        
----                           -----                                                                                                                                                        
PSVersion                      5.1.19041.2364                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                      
BuildVersion                   10.0.19041.2364                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                          
SerializationVersion           1.1.0.1                                                                                                                                                      

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP3-OD) (KB5006943) - 13.0.6404.1 (X64)   Oct 18 2021 09:37:01   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.8.9105.0

**Comment by wsmelton** [comment]
Please update to the latest version of the module, ensure .NET 4.6 is installed on the device.

**Comment by cstratton144** [comment]
How do I update to the latest version?

**Comment by cstratton144** [comment]
Hi Shawn,

I updated to the latest version and get the same error just repeats “System.Data.DataRow”

***@***.***


From: Charles Stratton
Sent: Wednesday, February 22, 2023 3:05 PM
To: dataplat/dbatools ***@***.***>; dataplat/dbatools ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [dataplat/dbatools] Read-DbaTransactionLog function return "System.Data.DataRow" (Issue #8773)

How do I update to the latest version?

**Comment by wsmelton** [comment]
Is the .NET 4.6 runtime installed on the device?

**Comment by cstratton144** [comment]
Just checked yes it is

***@***.***

**Comment by cstratton144** [comment]
Version 4.8.09037

Chuck Stratton | Database Administration | IT Professional IV | Agency I.T. Services
State of Nevada | Department of Administration | Enterprise I.T. Services Division
Email: ***@***.******@***.***> | Microsoft Teams: Chat or Call me on MS ***@***.***>

From: Charles Stratton
Sent: Wednesday, February 22, 2023 3:28 PM
To: dataplat/dbatools ***@***.***>; dataplat/dbatools ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [dataplat/dbatools] Read-DbaTransactionLog function return "System.Data.DataRow" (Issue #8773)

Just checked yes it is

***@***.***

**Comment by wsmelton** [comment]
Module requires .NET 4.6 runtime to be installed. Not having it installed is where the error you are getting generally comes from.

**Comment by cstratton144** [comment]
I am on windows 10 4.6 is no longer supported and windows updates update to 4.8. how can I run this targeting the .net 4.6 developer targeting pack or SDK?



Chuck Stratton | Database Administration | IT Professional IV | Agency I.T. Services
State of Nevada | Department of Administration | Enterprise I.T. Services Division
Email: ***@***.******@***.***> | Microsoft Teams: Chat or Call me on MS ***@***.***>

**Comment by wsmelton** [comment]
.NET 4.6 is still under support. You can download the patch version 4.6.2 from Microsoft's site.

**Comment by cstratton144** [comment]
I’ve uninstalled a lot of .net 4.8 and later and the 4.6 runtime still won’t let me install it. How can I get the source code so I can update it to work on 4.8?


Thanks,
Chuck

**Comment by wsmelton** [comment]
All our code is on GitHub under the dataplat org.

We no longer have the same code base that exist in 1.1.145. 

The library code is under dbatools.library repo and module is under this repo.

**Comment by wsmelton** [comment]
I can tell you the build version of Windows your details show you are on (`BuildVersion 10.0.19041.2364`) went out of support last year sometime. [documentation](https://learn.microsoft.com/en-us/windows/release-health/release-information#windows-10-current-versions-by-servicing-option)

You may be having issues installing .NET 4.6 because of that.

I'm running on Windows 10.0.19042 which is goes out of support in May. You might try installing the .NET 4.6.2 SDK and see if that will install on your machine.

**Comment by potatoqualitee** [comment]
i believe the problem is because write-host will make it a string, and when you make it a string, it'll just output the type. please try without write-host

$Log = Read-DbaTransactionLog -SqlInstance sqlserver1 -Database database1
$Log
