### ISSUE TITLE
Provide an option to get unformated byte information ie: remove the KB|MB|GB text

### ISSUE THREAD

**Issue by DavidLean** [dataplat/dbatools#8774]
### Summarize Functionality

Many commands **eg: Get-DbaDBFile** provide output conveniently formatted for human readability. eg: the field **UsedSpace** is rounded to the nearest thousand metric then displayed with the appropriate units. ie 4.12 KB, 4.12 MB, 4.12 GB

This is great if you are a human & dispose of the information soon after. 
This is a pain if you want to, store the information, plot trends over time, do any sort of further computational comparison. Including cutting/pasting the output into Excel. 

**_Request:_** 
I'd like an optional parameter ie: -Unformatted or -Raw or -bytes or similar that shows the actual values as numeric values, (most often integers) eg: I want the int value "2304" bytes & not the string "2.25 KB"
This request is relevant to all DBATools commands that retrieve & display formatted byte information. 

I expect that returning these values as the Long datatype would likely be preferable. I realise that using Long to store bytes would constrains the output value to 8 Exabytes. And string would be unlimited. And the datatype Numeric (38,0) could go higher. So I leave the datatype choice up to you. For most use cases 8 EB would be more than adequate. Should someone want to sum all the bytes in their enterprise. They will need to cast it to a more suitable datatype. 

**_Workarounds today:_**
1. Strip the Units extension (MB/GB), cast to an int, multiply by 1024 as appropriate. (this creates rounding errors)
2. Reverse Engineer the base query that the DBATools command is using, then write my own queries. This is annoying given DBATools is so close. It has the data I want & then destroys it in the final format clause. 

**_Use case: Capacity Planning_**
Each week I gather :-
a. The number of rows in each table, bytes used for data, bytes used for index. 
b. Size of database files; Used, unused, data, index
c. Size of O/S drive, & unused space. 
Armed with that I can do extremely accurate Capacity planning. Including mapping the Business projection terms eg "Orders per second" into a database consumption terms; Avg rows per business transaction & Avg bytes per row. 

**_Final point_**
The current Unit formatting approach is great when you just want the output in GridView to get quick answers. It should still be the default. 

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by wsmelton** [comment]
The functionality to obtain what you are asking already exists in the module. You can explore the `Get-DbatoolsConfig` and look at the formatting configurations. There you will find a style setting for the use of DbaSize.

![image](https://user-images.githubusercontent.com/11204251/221389542-40e9d863-afd2-4b29-818a-5f95f4742284.png)

By default, we set this to `Dynamic` hence you see the various unit size conversions in output. If you also examine the property that is set to DbaSize you will see a nested object that includes your the Raw value you are seeking.

Another option is converting the object that any given commands outputs using `ConvertTo-DbaDataTable` as this would be used for exporting data to Excel allows you to format that DbaSize property.

I can work on creating a Wiki page if an example of how to deal with this is needed.

**Comment by wsmelton** [comment]
If you are still having issues or need further help in how the above works start up a new [discussion](https://github.com/dataplat/dbatools/discussions).
