### ISSUE TITLE
[Get-DbaKbUpdate] No results found for 5022375

### ISSUE THREAD

**Issue by rvsuresh19** [dataplat/dbatools#8782]
### Verified issue does not already exist?

No, I did not search

### What error did you receive?

Hi Champs,

I was trying to install the latest sql patch for 2022 and end up with this message
[Get-DbaKbUpdate] No results found for 5022375

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Update-DbaInstance -ComputerName sqlvm2022 -Path \\azurestorage\sql -Credential $cred -Version $version  -Download -Restart

### Please confirm that you are running the most recent version of dbatools

Yes I'm using the latest DBATools

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      17763  3770    

### SQL Server Edition and Build number

SQL 2022 
16.0.1050.5

### .NET Framework Version

PSChildName                      Version       
-----------                      -------       
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926 
Windows Presentation Foundation  3.0.6920.4902 
v3.5                             3.5.30729.4926
Client                           4.7.03190     
Full                             4.7.03190     
Client                           4.0.0.0

**Comment by andreasjordan** [comment]
We use the update catalog as source and the KB has still not landed there. See: https://twitter.com/JordanOrdix/status/1628281074513059842

So I will close this as we can only wait...
