### ISSUE TITLE
No output if Backup-DbaDatabase is used with AzureBaseUrl

### ISSUE THREAD

**Issue by andreasjordan** [dataplat/dbatools#8784]
### Verified issue does not already exist?

No, I did not search

### What error did you receive?

Not error, only no output.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

### Please confirm that you are running the most recent version of dbatools

yes

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

5.1

### SQL Server Edition and Build number

2022 - That could be a problem - I'll check that first.

### .NET Framework Version

x

**Comment by wsmelton** [comment]
How are you using it, what parameters? (Need to actually fill out the issue template please)

**Comment by andreasjordan** [comment]
Sorry that you invested time - now it works.

**Comment by wsmelton** [comment]
No worries it was a good read to see what storage changes (or more I guess enhancements) are in 2022. There are S3 storage account support in preview in 2022...which didn't know they were doing "preview" features now in major releases of SQL Server.
