### ISSUE TITLE
Test-dbaspn support for multiple ports

### ISSUE THREAD

**Issue by crummel4** [dataplat/dbatools#8790]
### Summarize Functionality

Enhance test-dbaspn to support named instances configured to listen on multiple ports.

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

For a named instance “myinst” listening on both ports 1433 and 1533 I would expect test-dbaspn to return 3 entries, one for the name and one for each port, such as
MSSQLSvc/srv1.company.com:myinst
MSSQLSvc/srv1.company.com:1433
MSSQLSvc/srv1.company.com:1533
but instead for the ports it returns 
MSSQLSvc/srv1.company.com:1433,1533

**Comment by andreasjordan** [comment]
Thanks for the feature request. I will have a look later.

**Comment by andreasjordan** [comment]
Line 182 has to be changed to `$ports = $ports.Split(',') | Select-Object -Unique`. Will open a PR shortly.
