### ISSUE TITLE
New-DbaScriptingOption - ScriptForCreateDrop option not being honored

### ISSUE THREAD

**Issue by Shashahan** [dataplat/dbatools#8799]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Only the Create object is scripted out but not Drop object.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
$options=New-DbaScriptingOption
$options.ExtendedProperties=$true
$options.ScriptForCreateDrop=$true

Get-DbaDbTable -SqlInstance Instance -Database database -Table table | Export-DbaScript -ScriptingOptionsObject $options -Path path

### Please confirm that you are running the most recent version of dbatools

1.1.145

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

```
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.17763.3770                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.17763.3770                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                            
```     

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64)   Jan 12 2022 22:30:08   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

```
PSChildName                      Version
-----------                      -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.7.03190
Full                             4.7.03190
Client                           4.0.0.0
```

**Comment by StefanescuCristian** [comment]
Either I'm having the same issue, either I'm not understanding how ScriptForCreateDrop works.
In my opinion it should create a script with 
```
DELETE FROM <table>
INSERT <table> <data>
```
syntax but it only creates the INSERT statement.

**Comment by andreasjordan** [comment]
I can reproduce the issue. But there is nothing we can do as we only pass the given scripting options object to the script method.
You test without our export function with:
```
$options=New-DbaScriptingOption
$options.ExtendedProperties=$true
$options.ScriptForCreateDrop=$true
$table = Get-DbaDbTable -SqlInstance Instance -Database database -Table table
$table.Script($options)
```

To get the DROP statement, you can use `$options.ScriptDrops=$true`, but that will only create the drop statement and ignore the other options.

So I think this is a bug in the used SMO - you may open an issue here: https://github.com/microsoft/sqlmanagementobjects/issues

But there are already known problems with scripting objects like: https://github.com/microsoft/sqlmanagementobjects/issues/126

**Comment by andreasjordan** [comment]
I will close this, as we can do nothing to fix this.

**Comment by mattcargile** [comment]
For future folks seeing this, you can use `(New-DbaScriptingOption).EnforceScriptingOptions = $true` to get this to work. `ScriptForAlter` is still broke though.
