### ISSUE TITLE
Copy-DbaDatabase -WhatIf still Drops destination DB

### ISSUE THREAD

**Issue by Paul-Wasilewski-CT** [dataplat/dbatools#8800]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Command:
Copy-DbaDatabase -Source $server1 -Destination $server2 -Database $dbname -BackupRestore -SharedPath $uncshare -ReuseSourceFolderStructure -Force -Whatif

Issue:
output says it *would* perform the correct actions, but it in fact does *drop* the target database if it exists even though -WhatIf is specified.  It does not proceed to perform the restore, but that is expected due to -WhatIf.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Copy-DbaDatabase -Source $server1 -Destination $server2 -Database $dbname -BackupRestore -SharedPath $uncshare -ReuseSourceFolderStructure -Force -Whatif

### Please confirm that you are running the most recent version of dbatools

![image](https://user-images.githubusercontent.com/127446334/224155219-e2fcdcd0-e1d1-42b5-b75c-f5e0157bfa5d.png)
pasted

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

![image](https://user-images.githubusercontent.com/127446334/224155160-26b0cf57-9234-4fb1-9d57-fe071cd03606.png)
pasted

### SQL Server Edition and Build number

![image](https://user-images.githubusercontent.com/127446334/224155637-f2d516c0-0e29-4525-85d3-18af6e80902d.png)

### .NET Framework Version

.NET Framework 4.7.3468.0

**Comment by potatoqualitee** [comment]
oh thats horrifying, i will fix both of your issues before the next preview

**Comment by potatoqualitee** [comment]
Fortunately, I was unable to reproduce this issue

![image](https://user-images.githubusercontent.com/8278033/229286299-b1e31ddc-9170-48f5-9ac3-0b72fdf02644.png)
