### ISSUE TITLE
Copy-DbaDatabase: prevent dropping of destination databases unless and until a backup is confirmed first

### ISSUE THREAD

**Issue by Paul-Wasilewski-CT** [dataplat/dbatools#8801]
### Summarize Functionality

If you accidentally specify the same destination server as the source (which I did this week), Copy-DbaDatabase will drop the DB(s) before it backs up, causing total data loss.  Luckily I had an alternate backup which was close enough to up to date to restore from.

I didn't submit this as a bug because I made the logical error of specifying the same destination as the source.  This is just a request for some idiot-proofing.  But still, what if your -SharedPath runs out of disk space during the backup, the copy command would still have dropped the destination DB first, leaving you with neither a backup nor the destination server's DB in place, despite runtime errors.

### Is there a command that is similiar or close to what you are looking for?

No

### Technical Details

Suggest not allowing this combination of command switches since it does nothing useful and causes data loss.
Copy-DbaDatabase -Source $SameServer -Destination $SameServer -BackupRestore -Force -SharedPath $UncSmbShare
That said I love this toolset and am so glad I finally took the plunge to use something non-Ms-Shipped!

**Comment by potatoqualitee** [comment]
thanks for the report! im going to check for source being the same as destination and throw an error since it does not make sense
