### ISSUE TITLE
Export-DbaDbRole -IncludeRoleMember generate unusable SQL for member "dbo"

### ISSUE THREAD

**Issue by itcsoft54** [dataplat/dbatools#8805]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

```powershell
AVERTISSEMENT : [19:29:11][Invoke-DbaQuery] [srv-sqldest/inst1] Failed during execution | Cannot use special principal 'dbo'
```

### Steps to Reproduce

```powershell
Export-DbaDbRole -SqlInstance srv-sqlsrc/inst1 -Database existing_src_database -Role db_owner -IncludeRoleMember -FilePath ./role.sql
Invoke-DbaQuery -SqlInstance srv-sqldest/inst1 -File ./role.sql
```

### Please confirm that you are running the most recent version of dbatools

1.1.145

### Other details or mentions

File content ./role.sql :
```SQL
USE [Inst1]
GO
IF NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = N'db_owner' AND type = 'R')
CREATE ROLE [db_owner]
GO
ALTER AUTHORIZATION ON SCHEMA::[db_owner] TO [db_owner];
GO
ALTER ROLE [db_owner] ADD MEMBER [dbo];
GO
ALTER ROLE [db_owner] ADD MEMBER [MYDOMAIN\User1];
GO
ALTER ROLE [db_owner] ADD MEMBER [MYDOMAIN\User2];
GO
ALTER ROLE [db_owner] ADD MEMBER [MYDOMAIN\User3];
GO

```
Issue with line :
 ```SQL
ALTER ROLE [db_owner] ADD MEMBER [dbo];
```
Maybe using sp_changedbowner instead of ALTER ROLE [db_owner] 

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                        
----                           -----                                                                                                                                                                        
PSVersion                      5.1.17763.3770                                                                                                                                                               
PSEdition                      Desktop                                                                                                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                      
BuildVersion                   10.0.17763.3770                                                                                                                                                              
CLRVersion                     4.0.30319.42000                                                                                                                                                              
WSManStackVersion              3.0                                                                                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                                                                          
SerializationVersion           1.1.0.1                                                                                                                                                                      

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU17) (KB5016394) - 15.0.4249.2 (X64)   Jul 22 2022 12:11:33   Copyright (C) 2019 Microsoft Corporation  Standard Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.7.4038.0

**Comment by andreasjordan** [comment]
"sp_changedbowner" is to set the owner of the database, "ALTER ROLE [db_owner] ADD MEMBER [dbo]" just adds the user to the role. But as the user dbo is always a member of the role db_owner, this statement must be excluded.

I just opened a PR for that.
