### ISSUE TITLE
Move-DbaDbFile shows incorrect SourceFileDeleted status when -DeleteAfterMove flag is ommited

### ISSUE THREAD

**Issue by Tisit** [dataplat/dbatools#8807]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When Move-DbaDbFile is used without -DeleteAfterMove flag it always shows 
SourceFileDeleted    : True
Which is incorrect

Please see steps to reproduce for an example command used and output

### Command

```powershell
 Move-DbaDbFile -SqlInstance localhost -Database playground -FileType Both -FileDestination D:\databases\subfolder
```

### Output

Instance             : localhost
Database             : playground
LogicalName          : playground
Source               : D:\databases\playground.mdf
Destination          : D:\databases\subfolder\playground.mdf
Result               : Success
DatabaseFileMetadata : Updated
SourceFileDeleted    : True

Instance             : localhost
Database             : playground
LogicalName          : playground_log
Source               : D:\databases\playground_log.ldf
Destination          : D:\databases\subfolder\playground_log.ldf
Result               : Success
DatabaseFileMetadata : Updated
SourceFileDeleted    : True

### Original files still there

PS C:\WINDOWS\system32> ls D:\databases\pla*

Directory: D:\databases

Mode                 LastWriteTime         Length Name                                                                                                                                                                                  
----                 -------------         ------ ----                                                                                                                                                                                  
-a----         3/12/2023   7:04 PM    34084618240 playground.mdf                                                                                                                                                                        
-a----         3/12/2023   7:04 PM    40592474112 playground_log.ldf                                                                                                                                                                    

PS C:\WINDOWS\system32> ls D:\databases\subfolder\pla*

Directory: D:\databases\subfolder

Mode                 LastWriteTime         Length Name                                                                                                                                                                                  
----                 -------------         ------ ----                                                                                                                                                                                  
-a----         3/12/2023   7:10 PM    34084618240 playground.mdf                                                                                                                                                                        
-a----         3/12/2023   7:10 PM    40592474112 playground_log.ldf

### Please confirm that you are running the most recent version of dbatools

1.1.145

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                                                    
----                           -----                                                                                                                                                                                                    
PSVersion                      5.1.19041.2364                                                                                                                                                                                           
PSEdition                      Desktop                                                                                                                                                                                                  
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                  
BuildVersion                   10.0.19041.2364                                                                                                                                                                                          
CLRVersion                     4.0.30319.42000                                                                                                                                                                                          
WSManStackVersion              3.0                                                                                                                                                                                                      
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                      
SerializationVersion           1.1.0.1                                                                                                                                                                                                  

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU16-GDR) (KB5014353) - 15.0.4236.7 (X64)   May 29 2022 15:55:47   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19045: ) 

The SQL Server version should not matter

### .NET Framework Version

PSChildName                      Version       
-----------                      -------       
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926 
Windows Presentation Foundation  3.0.6920.4902 
v3.5                             3.5.30729.4926
Client                           4.8.04084     
Full                             4.8.04084     
Client                           4.0.0.0

**Comment by HCRitter** [comment]
to remove some clutter you also could define the return object one in a variable and return it after changing properties which you can define above in each situation, like:
```PowerShell
if (-not $failed) {
    $returnObject = [PSCustomObject]@{
        Instance             = $SqlInstance
        Database             = $Database
        LogicalName          = $LogicalName
        Source               = $physicalName
        Destination          = $destination
        Result               = "Success"
        DatabaseFileMetadata = "Updated"
        SourceFileDeleted    = $true
    }
    $query = "ALTER DATABASE [$Database] MODIFY FILE (name=[$LogicalName], filename='$destination'); "

    if ($PSCmdlet.ShouldProcess($Database, "Executing ALTER DATABASE query - $query")) {
        # Change database file path
        $server.Databases["master"].Query($query)
    }

    if ($DeleteAfterMove) {
        try {
            if ($PSCmdlet.ShouldProcess($database, "Deleting source file $physicalName")) {
                if ($locally) {
                    Remove-Item -Path $physicalName -ErrorAction Stop
                } else {
                    $scriptBlock = {
                        $source = $args[0]
                        Remove-Item -Path $source -ErrorAction Stop
                    }
                    Invoke-Command2 -ComputerName $ComputerName -Credential $SqlCredential -ScriptBlock $scriptBlock -ArgumentList $physicalName
                }
                $returnObject
            }
        } catch {
            $returnObject = $returnObject.SourceFileDeleted = $false
            $returnObject

            Stop-Function -Message "ERROR:" -ErrorRecord $_
        }
    }else{
        $returnObject = $returnObject.SourceFileDeleted = $false
        $returnObject
    }
} else {

        $returnObject = $returnObject.SourceFileDeleted = "N/A"
        $returnObject = $returnObject.DatabaseFileMetadata = "N/A"
        $returnObject = $returnObject.Result = "Failed"
        $returnObject
}
```
