### ISSUE TITLE
install-dbainstance: 'SNAC_SDK' is not a valid value for setting 'FEATURES' 

### ISSUE THREAD

**Issue by Fisico** [dataplat/dbatools#8811]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Error installing SQL Server 2022 Standard on Windows Server 2022

The following is an exception stack listing the exceptions in outermost to innermost order
Inner exceptions are being indented

```
Exception type: Microsoft.SqlServer.Chainer.Infrastructure.InputSettingValidationException
    Message: 
        'SNAC_SDK' is not a valid value for setting 'FEATURES'. Refer to Help for more information.
    HResult : 0x84b40002
        FacilityCode : 1204 (4b4)
        ErrorCode : 2 (0002)
    Data: 
      SQL.Setup.FailureCategory = InputSettingValidationFailure
      DisableWatson = true
    Stack: 
        at Microsoft.SqlServer.Chainer.Infrastructure.InputSettingService.LogAllValidationErrorsAndThrowFirstOne(ValidationState vs)
        at Microsoft.SqlServer.Configuration.BootstrapExtension.ValidateChainerSettingAction.ExecuteAction(String actionId)
        at Microsoft.SqlServer.Chainer.Infrastructure.Action.Execute(String actionId, TextWriter errorStream)
        at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.<>c__DisplayClass2_1.<ExecuteActionWithRetryHelper>b__0()
        at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.ExecuteActionHelper(ActionWorker workerDelegate)
```

### Steps to Reproduce

```powershell
Install-DbaInstance -SqlInstance "hotname.constoso.com" -Version "2022" -Credential "contoso\user" -Path "G:" -DataPath "D:\Database" -LogPath "E:\Logs" -BackupPath "F:\Backups" -SaCredential $sacred -AuthenticationMode "Mixed" -Confirm:$false
```

### Please confirm that you are running the most recent version of dbatools

Version 2.0.0 preview 2

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Host:
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0                                                                          

### SQL Server Edition and Build number

SQL Server 2022 Standard

### .NET Framework Version

Hostsystem: 
.NET 7.0.3

Target: 
PSChildName Version
----------- -------
Client      4.8.04161
Full        4.8.04161
Client      4.0.0.0

**Comment by andreasjordan** [comment]
As a workaround you will have to use the parameter -Feature and specify all the needed features.

But we will have a look at the code that puts together the features by group and add a new rule for version 2022.

**Comment by wsmelton** [comment]
@Fisico SQL Server tools are no longer included in installation media for SQL Server. You will need to perform that installation separate to dbatools module with `Install-DbaInstance`.

**Comment by andreasjordan** [comment]
Sorry, Shawn, I disagree here. The user has not requested any features so using the default. With the default there is code to seleft the "common" features for that version. We have to change that code.

Sorry, no time today to look deeper.

**Comment by andreasjordan** [comment]
This is the file that needs changes: 

```
$components = Get-Content -Path $Script:PSModuleRoot\bin\dbatools-sqlinstallationcomponents.json -Raw | ConvertFrom-Json
```

**Comment by wsmelton** [comment]
I would prefer we remove that functionality. We need to get out of the practice of maintaining things by versions of SQL Server.

**Comment by Fisico** [comment]
I would only add the "Database Engine Services" to the default configuration:
![image](https://user-images.githubusercontent.com/329471/225023299-cfb84d99-d43a-4a34-9b3a-ed45ab2f5239.png)

If I interpret the config json correctly, you install a lot more with the "default" setting. With SQL 2022 this causes a problem.

**Comment by andreasjordan** [comment]
I personally don't use the default but use `-Feature Engine` to install a SQL Server Instance.

@nvarscar is the author of the command....

**Comment by nvarscar** [comment]
If we change the feature set for all versions, this should be a 2.0 change, as it's breaking. I'm hoping this could be as simple as adding MaximumVersion to the SNAC component in `bin\dbatools-sqlinstallationcomponents.json`

**Comment by nvarscar** [comment]
That list was based on the SqlServer setup defaults, so if we're enforcing anything, we're enforcing what comes from MS. If those defaults have changed again, we might as well adjust.

**Comment by andreasjordan** [comment]
Currently testing the change of dbatools-sqlinstallationcomponents.json in my lab....

**Comment by andreasjordan** [comment]
Test successful.

The change:
![image](https://user-images.githubusercontent.com/66946165/225044504-46f21559-81fd-41d2-8969-241bfbdb0c06.png)

@nvarscar - Do you have time to open the PR? I would approve.

**Comment by nvarscar** [comment]
not earlier than in about 10 hours, today is a busy day :|
