### ISSUE TITLE
Test-DbaLastBackup support SQL 2022 as Destination

### ISSUE THREAD

**Issue by WizPsk** [dataplat/dbatools#8814]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Test-DbaLastBackup reports skiped if a Server 2022  is used as Destination parameter

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
# Test 1
$Database ="YourDatabase"
$SourceInstance="XXX\YYY"   #ANY SQL Instance
$DestinationInstance="ZZZ\QQQ" # ANY SQL 2022 INSTANCE
Test-DbaLastBackup -SqlInstance $SourceInstance -Destination $DestinationInstance  -CopyFile -IgnoreLogBackup -IgnoreDiffBackup -Database $Database -EnableException

![skiped](https://user-images.githubusercontent.com/128364794/226303011-95fde98b-71fa-421f-9cb0-e499078b85ee.jpg)

# Test 2
$Database ="YourDatabase"
$SourceInstance="XXX\YYY"   #ANY SQL Instance
$DestinationInstance="TTT\QQQ" # ANY SQL NONE 2022 INSTANCE
Test-DbaLastBackup -SqlInstance $SourceInstance -Destination $DestinationInstance  -CopyFile -IgnoreLogBackup -IgnoreDiffBackup -Database $Database -EnableException

![works](https://user-images.githubusercontent.com/128364794/226303631-df0dfb31-4422-437f-9700-c00ccb2eccb8.jpg)

### Please confirm that you are running the most recent version of dbatools

1.1.145

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                          
----                           -----                                                          
PSVersion                      5.1.19041.2364                                                 
PSEdition                      Desktop                                                        
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                        
BuildVersion                   10.0.19041.2364                                                
CLRVersion                     4.0.30319.42000                                                
WSManStackVersion              3.0                                                            
PSRemotingProtocolVersion      2.3                                                            
SerializationVersion           1.1.0.1                                                        

### SQL Server Edition and Build number

Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)   Oct  8 2022 05:58:25   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Datacenter 10.0 <X64> (Build 20348: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.8.4515.0

**Comment by WizPsk** [comment]
I have found some more info!! The error colud be unreleated to the server version!
My new findings are: If the Destination server does not have access to the fileshare the same message is show: RestoreResult: Skipped. DbccResult: Skipped.
I would have expceted a error message showing the lack of access to the backup file.

**Comment by wsmelton** [comment]
You can try running the command with `-EnableException`, this parameter reverts the module to providing errors like built-in commands in PowerShell will do. There is also use of `-Verbose` to view more detailed output.

In regard to throwing an error our module's design is Test commands provide a status over just outputting an error. If you were doing say a Restore process then you will get an error in some format but running a test it is meant to provide pass, fail, or skipped.

**Comment by andreasjordan** [comment]
Hi @WizPsk - can this issue be closed?

**Comment by andreasjordan** [comment]
Will close this now, but can reopen if needed.
