### ISSUE TITLE
`Invoke-ManagedComputerCommand` - Multiple Versions of `Microsoft.SqlServer.SqlWmiManagement`

### ISSUE THREAD

**Issue by mattcargile** [dataplat/dbatools#8833]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Error is bubbled up in `Test-DbaSpn` and other commands that use this private command. The error is related to lack of data inside the `$wmi` variable in the below code; more specifically, it will throw on line 57 for failed to initialze.

https://github.com/dataplat/dbatools/blob/6b88dcc9492a326727376b7c43990d705d423833/private/functions/Invoke-ManagedComputerCommand.ps1#L55-L57

#### Warning Received

```powershell
WARNING: [20:38:43][Test-DbaSpn] Couldn't connect to server| Exception calling "Initialize" with "0" argument(s): "SQL Server WMI provider is not available on 10.10.10.10."
```

### Steps to Reproduce

```powershell
# Install SQL Server 2014 or the like. In my case, it was 2012.
# Install SQL Local DB version 2016 or above. In my case, it was SQLLocalDB 2016.
# The key is to have multiple versions here `C:\Windows\assembly\GAC_MSIL\Microsoft.SqlServer.SqlWmiManagement\`
Test-DbaSpn -ComputerName server
```

### Please confirm that you are running the most recent version of dbatools

`1.1.142`
Version doesn't matter here. I checked the most recent version of the code.

### Other details or mentions

The `LoadWithPartialName` appears to load the most recent version even if the Instance is on an earlier version. When `$wmi` is called it can't find an `ServerInstances` because they are older?

Maybe there can be a check of `C:\Windows\assembly\GAC_MSIL\Microsoft.SqlServer.SqlWmiManagement\` first? Or an attempt to check wmi elsewhere for the versions of SQL Server that exist on the server?

Lastly, this is partially related to #8438 . It isn't quite related because in that case the `SqlWmiManagement` library won't load.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe)

#### Local Version
```powershell
Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
#### Server Version
```powershell
Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.0.10586.51                                                                            
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.10586.51                                                                           
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 
```

### SQL Server Edition and Build number

```sql
Microsoft SQL Server 2012 (SP4) (KB4018073) - 11.0.7001.0 (X64) 
	Aug 15 2017 10:23:29 
	Copyright (c) Microsoft Corporation
	Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (Hypervisor)
```

#### Local Version
.NET 7.0.3

#### Server Version
.NET Framework 4.7.4038.0

**Comment by wsmelton** [comment]
To clarify you installed so noted items on the server?

**Comment by wsmelton** [comment]
Please also add the error (unless I'm missing it in your post).

**Comment by mattcargile** [comment]
> To clarify you installed the noted items on the server?

Someone installed the items on the server. The install was before my time.

> Please also add the error (unless I'm missing it in your post).

Just added it. It was actually `Warning`.

**Comment by potatoqualitee** [comment]
This is a tough one -- you can see that we try a couple different ways to get WMI to work (first remote to the IP then using remoting). I'm not sure it's possible to load a DLL, fail an initalization, then fail again but what I could maybe do is ensure a session isn't reused and iterate through. ill try. would you be able to use a branched version against the server, matt?

**Comment by mattcargile** [comment]
Sorry I never got to this! Love the fix! It works great.
