### ISSUE TITLE
Bringing back old SSIS commands (I can't get it to work)

### ISSUE THREAD

**Issue by potatoqualitee** [dataplat/dbatools#8838]
### Summarize Functionality

People ask about these commands all the time but I can't figure out how to get them back. If anyone wants to take a stab, here are the binaries and the code. I had to remove Core DLLs bc it made the files too big to attach to this issue.

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

Here's what I'm running

```
ipmo C:\gallery\dbatools.library; ipmo C:\github\dbatools -force; New-DbaSsisCatalog -SqlInstance localhost -Credential $cred
WARNING: [20:37:20][New-DbaSsisCatalog] Can't load server | Cannot find an overload for "IntegrationServices" and the argument count: "1".
```

No matter how I construct the SqlConnection (even with System.Data instead of Microsoft.Data), it doesn't work.

**Comment by potatoqualitee** [comment]
sweet, i got it! PR coming soon.

**Comment by chakravarthy9866** [comment]
Any update on this issue?
WARNING: [17:23:55][Copy-DbaSsisCatalog] There was an error connecting to the source integration services. | Cannot find an overload for "IntegrationServices" and the argument count: "1".

**Comment by potatoqualitee** [comment]
That's a DLL problem, which is hell right now. I don't recall the state of the SSIS commands but potentially it may be fixed with the library updates coming soon.
