### ISSUE TITLE
Update-DbaInstance Cannot process argument transformation on parameter 'ComputerName'. Cannot convert value ""ServerName1","ServerName2"" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]"

### ISSUE THREAD

**Issue by seniuka** [dataplat/dbatools#8851]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Catch Message: System.Management.Automation.ParameterBindingArgumentTransformationException: Cannot process argument transformation on parameter 'ComputerName'. Cannot convert value ""ServerName1","ServerName2"" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]". Error: "Cannot convert value ""ServerName1","ServerName2"" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to parse instance name: "ServerName1","ServerName2""" ---> System.Management.Automation.ArgumentTransformationMetadataException: Cannot convert value ""ServerName1","ServerName2"" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]". Error: "Cannot convert value ""ServerName1","ServerName2"" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to parse instance name: "ServerName1","ServerName2""" ---> System.Management.Automation.PSInvalidCastException: Cannot convert value ""ServerName1","ServerName2"" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[]". Error: "Cannot convert value ""ServerName1","ServerName2"" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to parse instance name: "ServerName1","ServerName2""" ---> System.Management.Automation.PSInvalidCastException: Cannot convert value ""ServerName1","ServerName2"" to type "Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter". Error: "Failed to parse instance name: "ServerName1","ServerName2"" ---> System.Management.Automation.PSArgumentException: Failed to parse instance name: "ServerName1","ServerName2"
   at Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter..ctor(String Name) in C:\github\dbatools\bin\projects\dbatools\dbatools\Parameter\DbaInstanceParameter.cs:line 395
   at lambda_method(Closure , Object )
   at System.Management.Automation.LanguagePrimitives.ConvertViaConstructor.Convert(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   --- End of inner exception stack trace ---
   at System.Management.Automation.LanguagePrimitives.ConvertViaConstructor.Convert(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.LanguagePrimitives.ConvertScalarToArray(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   --- End of inner exception stack trace ---
   at System.Management.Automation.LanguagePrimitives.ConvertScalarToArray(Object valueToConvert, Type resultType, Boolean recursion, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConversionData`1.Invoke(Object valueToConvert, Type resultType, Boolean recurse, PSObject originalValueToConvert, IFormatProvider formatProvider, TypeTable backupTable)
   at System.Management.Automation.LanguagePrimitives.ConvertTo(Object valueToConvert, Type resultType, Boolean recursion, IFormatProvider formatProvider, TypeTable backupTypeTable)
   at System.Management.Automation.ArgumentTypeConverterAttribute.Transform(EngineIntrinsics engineIntrinsics, Object inputData, Boolean bindingParameters, Boolean bindingScriptCmdlet)
   --- End of inner exception stack trace ---

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

I store the server names within a database then use a stored procedure return a list of servers 
"ServerName1","ServerName2" with a KB number associated to be updated. I can submit this same value manually but I cannot get it to run when I return the values from the database.

The procedure returns the following values.
DefaultPatchDirectory : \\\shared\DBATeam\Software\Microsoft\
DefaultBinaryFlags    : /q /IAcceptSQLServerLicenseTerms /Action=Patch /AllInstances
KBNumber              : KB5021129
ServerName            : "ServerName1","ServerName2"

If I have 1 server it executes nicely, if I have more then one it doesn't accept the string coming from the procedure.  not sure what is causing the issue as I want to be able to execute this patch from our inventory server and have it execute without any user intervention.

### Please confirm that you are running the most recent version of dbatools

1.1.146

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      5.1.14393.5582
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.5582
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

Any SQL Server and edition this occurs on.

### .NET Framework Version

.NET Framework 4.8.4614.0

**Comment by potatoqualitee** [comment]
it looks like the actual results are like `$servers = '"Server1","Server2"'` so one big string. you will need to somehow make those into an array.

**Comment by seniuka** [comment]
I have made it into an array but again it doesn't accept an array. Is there a solid example of how to covert a csv style output into an array that is accepted by the Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[] variable type.  I am kind of at a loss at how to build an array list that is accepted by the DBAInstanceParameter variable type... the is output from the database.

I have tried with this code... sadly it also doesn't like that format.
            if ($inputString -match ",") 
            {
                # Split the string into an array of values
                $inputArray = $inputString.Split(',')

                # Define an empty array to hold the output objects
                $outputArray = @()

                # Loop through the input array and create an object for each set of values
                foreach ($item in $inputArray) {    
                    $obj = New-Object -TypeName PSObject -Property @{
                        ComputerName = $item
                    }

                    $outputArray += $obj
                } 
                $serverName = $outputArray
            } 
            else 
            {
                $serverName = $inputString
            }

**Comment by potatoqualitee** [comment]
> I have made it into an array but again it doesn't accept an array.

i havent taken a closer look at the command but the brackets on the end of Sqlcollaborative.Dbatools.Parameter.DbaInstanceParameter[] means "array". It's dirty, but here's how you can clean up that string

```
$servers = '"Server1","Server2"'
# remove the quotes
$servers = $servers.Replace('"','')
$serverarray = $servers.Trim().Split(',')
```

Here's how it worked on my array

```
$servers = '"Server1","Server2"'
# remove the quotes
$servers = $servers.Replace('"','')
# create array by trimming for good measure and then splitting
$serverarray = $servers.Trim().Split(',')
# check out the results
$serverarray
Server1
Server2
# run the command
$serverarray | Update-DbaInstance
WARNING: [07:22:02][Resolve-DbaNetworkName] DNS name Server1 not found | No such host is known.
```

Ultimately, I'd figure out how to get the source to come out better but this will get you where you'd like to go. Closing but if you continue to have questions, let me know.
