### ISSUE TITLE
Get-DbaDatabase does not return databases with state_desc of "RECOVERY_PENDING" (state = 3)

### ISSUE THREAD

**Issue by sqllensman** [dataplat/dbatools#8872]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Have an instance where

Select name, state, state_desc
FROM sys.databases 
WHERE state = 3 

returns values with state_desc = 'RECOVERY_PENDING'

A call to Get-DbaDatabase -SQLInstance 'SQLInstance' -Database 'DamagedDatabase' does not return any values
If the Database parameter is omitted then none of the 'RECOVERY_PENDING' databases are returned

### Steps to Reproduce

Requires instance where 
Select name, state, state_desc
FROM sys.databases 
WHERE state = 3 

returns values

A call to 
Get-DbaDatabase -SQLInstance 'SQLInstance' -Database 'DamagedDatabase' does not return any values

If the Database parameter is omitted then none of the 'RECOVERY_PENDING' databases are returned

### Please confirm that you are running the most recent version of dbatools

Occurs on Version 1.1.46 and also  latest code

### Other details or mentions

This is occurring on all current versions as the Status parameter has been defined as

 .PARAMETER Status
        Specifies one or more database statuses to filter on. Only databases in the status(es) listed will be returned. Valid options for this parameter are 'Emergency', 'Normal', 'Offline', 'Recovering', 'Restoring', 'Standby', and 'Suspect'.

The values actually returned from the SMO object are defined by
https://learn.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.management.smo.databasestatus?view=sql-smo-160

This includes the value
RecoveryPending | 4 | Database recovery is being prepared for the referenced database.

If the definition of the parameter

[string[]]$Status = @('EmergencyMode', 'Normal', 'Offline', 'Recovering', 'Restoring', 'Standby', 'Suspect'),

is updated to include 'RecoveryPending' then these databases are returned as expected

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                        
----                           -----                                                                                        
PSVersion                      5.1.19041.2673                                                                               
PSEdition                      Desktop                                                                                      
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                      
BuildVersion                   10.0.19041.2673                                                                              
CLRVersion                     4.0.30319.42000                                                                              
WSManStackVersion              3.0                                                                                          
PSRemotingProtocolVersion      2.3                                                                                          
SerializationVersion           1.1.0.1                                                                                      

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP2-CU17-GDR) Developer edition on Windows Server 2019

### .NET Framework Version

.NET Framework 4.8.4614.0

**Comment by andreasjordan** [comment]
Thanks for the issue, a fix is on its way...
