### ISSUE TITLE
Importing 2.0.0 in Azure DevOps fails due to calling Get-DbatoolsLibraryPath in the psm1

### ISSUE THREAD

**Issue by simonsabin** [dataplat/dbatools#8884]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Get-DbatoolsLibraryPath: The term 'Get-DbatoolsLibraryPath' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

```
##[error]C:\Users\vstsagent.LinnaeusBI.DW-xxxxx.xxxxx\Documents\PowerShell\Modules\DBATools\2.0.0\dbatools.psm1(41,23): error -2146233087: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The term 'Get-DbatoolsLibraryPath' is not recognized as a name of a cmdlet, function, script file, or executable program.
```

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
https://github.com/dataplat/dbatools/blob/dd8eb389614cf8c135b1ab04c7fe23ac90c2f55e/dbatools.psm1#L41

### Please confirm that you are running the most recent version of dbatools

2.0.0

### Other details or mentions

Something about the setting of erroractionpreference in azure devops powershell task is overriding the -ignoreerror on the line 

https://github.com/dataplat/dbatools/blob/dd8eb389614cf8c135b1ab04c7fe23ac90c2f55e/dbatools.psm1#L41

### What PowerShell host was used when producing this error

Azure Devops Powershell Task, running locally, the script bypasses that

### PowerShell Host Version

|Name                         |  Value
|----                |           -----
PSVersion          |            7.3.2
PSEdition             |         Core
GitCommitId     |               7.3.2
OS                      |       Microsoft Windows 10.0.22621
Platform          |             Win32NT
PSCompatibleVersions    |       {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion  |    2.3
SerializationVersion          | 1.1.0.1
WSManStackVersion        |      3.0

### SQL Server Edition and Build number

n/a

### .NET Framework Version

n/a

**Comment by potatoqualitee** [comment]
dbatools now has a dependency. when i installed it on azure automation, i had to also install dbatools.library. let me know if this works and i'll do a blog post about it.

**Comment by simonsabin** [comment]
Dbatools.library isn't being explicitly loaded in any other environment, that implies that the automated import isn't working when loading dbatools. Thus its erroring on line 41 and thats causing the build to fail.

**Comment by potatoqualitee** [comment]
i dont use azure devops and dont know what you mean. did my previous message help at all?

**Comment by wsmelton** [comment]
@simonsabin please provide the task configuration you are using to run dbatools

**Comment by potatoqualitee** [comment]
closing until task configuration is provided, current recommendation is to ensure the latest `dbatools.library`, which provides `Get-DbatoolsLibraryPath`, is also installed in the event that the current installation does not support installing dependencies.

**Comment by wsmelton** [comment]
Running just import command in a Linux agent I don't get any issues on v2 or v2.0.1
![image](https://user-images.githubusercontent.com/11204251/236496488-a3999b7b-fcc9-4e1c-b854-a2135f55d478.png)

**Comment by simonsabin** [comment]
I'll dig into it, it was like the dependency importing wasn't working.
