### ISSUE TITLE
EnableException does not throw error correctly on Backup-DbaDatabase

### ISSUE THREAD

**Issue by sjmoden** [dataplat/dbatools#8886]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When running the command  backup-dbadatabase command for a Transaction Log backup and the database has not previously had a full backup, then the command throws a warning instead of an error.
`WARNING: [17:43:29][Backup-DbaDatabase] [DATABASE] does not have an existing full backup, cannot take log or differentialbackup ` 

I would expect that this would throw an error as the command has failed, allowing the user to create a script that handles the error or stops when an error is thrown.

### Steps to Reproduce

```powershell
$ErrorActionPreference = "Stop" 
Backup-DbaDatabase -SqlInstance "server" -Database $database  -Type Log -FilePath $backupName  -EnableException
write-output "This code should never be reached"
```

### Please confirm that you are running the most recent version of dbatools

1.1.145

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU18-GDR) (KB5021124) - 15.0.4280.7 (X64) 
	Jan 23 2023 12:37:13 
	Copyright (C) 2019 Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2022 Datacenter 10.0 <X64> (Build 20348: ) (Hypervisor)

### .NET Framework Version

.NET 7.0.0

**Comment by potatoqualitee** [comment]
hrm 🤔  lemme check this out, thanks for the report
