### ISSUE TITLE
Cannot Convert System.Data.SqlCient.SqlConnection to Microsoft.Data.SQLClient.SqlConnection

### ISSUE THREAD

**Issue by kool2zero** [dataplat/dbatools#8894]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When trying to run the following command:
`Copy-DbaDbTableData -SqlInstance $DBServerName -Database $DBDataSchema -Table $sourceTable -DestinationTable $targetTable -AutoCreateTable -KeepIdentity -KeepNulls -Truncate -debug`

Where `$DBServerName` is a string of the server name.

Other commands work and produce output but it seems there is an issue in the Invoke-DbaQuery

I receive the following message:
```
DEBUG: [12:55:32][Invoke-DbaQuery] [xxx] Failed during execution | Cannot convert the "System.Data.SqlClient.SqlConnection" value of type "System.Data.SqlClient.SqlConnection" to type "Microsoft.Data.SqlClient.SqlConnection".
WARNING: [12:55:32][Copy-DbaDbTableData] Unable to determine destination table: xxx.dbo.xxx| Cannot convert the "System.Data.SqlClient.SqlConnection" value of type "System.Data.SqlClient.SqlConnection" to type "Microsoft.Data.SqlClient.SqlConnection".
DEBUG: [12:55:32][Copy-DbaDbTableData] Unable to determine destination table: xxx.dbo.xxx| Cannot convert the "System.Data.SqlClient.SqlConnection" value of type "System.Data.SqlClient.SqlConnection" to type "Microsoft.Data.SqlClient.SqlConnection".
```

### Steps to Reproduce

```powershell
Copy-DbaDbTableData -SqlInstance $DBServerName -Database $DBDataSchema -Table $sourceTable -DestinationTable $targetTable -AutoCreateTable -KeepIdentity -KeepNulls -Truncate -debug
```

### Please confirm that you are running the most recent version of dbatools

2.0.0

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP2-GDR) (KB4583460) - 13.0.5108.50 (X64) 
	May 20 2022 20:28:29 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: )

### .NET Framework Version

.NET 7.0.5

**Comment by kool2zero** [comment]
Seems to work on Powershell 5 but not 7

**Comment by potatoqualitee** [comment]
I was able to replicate your issue on core by mixing and matching the wrong dbatools.library with dbatools. Please delete all old versions and install the latest. should be dbatools 2.0.0 and dbatools.library 2023.4.27

**Comment by potatoqualitee** [comment]
```
> Copy-DbaDbTableData -SqlInstance localhost -Database northwind -Table categories -DestinationTable cat2 -AutoCreateTable

SourceInstance        : workstationx
SourceDatabase        : Northwind
SourceDatabaseID      : 5
SourceSchema          : dbo
SourceTable           : Categories
DestinationInstance   : workstationx
DestinationDatabase   : Northwind
DestinationDatabaseID : 5
DestinationSchema     : dbo
DestinationTable      : cat2
RowsCopied            : 8
Elapsed               : 400.18 ms


> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
