### ISSUE TITLE
Import-Module dbatools sometimes fails in 2.0.0

### ISSUE THREAD

**Issue by Kehama** [dataplat/dbatools#8899]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Cannot load module. The process cannot access the file 'C:\Program Files\WindowsPowerShell\Modules\dbatools\2.0.0\dbatools.dat' because it is being used by another process.

### Steps to Reproduce

Import-Module dbatools

(but see below, it is hard to reproduce reliably)

### Please confirm that you are running the most recent version of dbatools

2.0.0

### Other details or mentions

It's a weird one, but only happens in version 2.0.0 (if I revert to 1.1.146 no errors)
I have multiple scripts scheduled that use dbatools, and with previous versions I never got this issue even when scripts ran simultaneously. When I rerun the job the module loads without issue.
It doesn't happen every time, but the first script I run each day seems impacted.
I've checked with process-explorer and the dbatools.dat file is not loaded anywhere.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.17763.3770                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.17763.3770                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

All versions of SQL are impacted from 2012 to 2022.

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.8.03761
Full        4.8.03761

**Comment by potatoqualitee** [comment]
Thank you for the report, @Kehama -- this issue has been fixed in 2.0.1. Please download the latest version and let us know how it works for you 👍🏼

**Comment by Kehama** [comment]
Hi. It does indeed look like version 2.0.1 solves this. I've had zero issues this morning. :)
Thanks!
