### ISSUE TITLE
import-DbaCsv Certificate chain issue 

### ISSUE THREAD

**Issue by nothingisshocking** [dataplat/dbatools#8902]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

 [Import-DbaCsv] Failure | The certificate chain was issued by an authority that is not trusted. 

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
 Import-DbaCsv -path 'C:\Temp\Test.csv' -SqlInstance InstanceName -Database Testing_DB -AutoCreateTable 

### Please confirm that you are running the most recent version of dbatools

2.0.1

### Other details or mentions

I have additionally tried setting the connection string to "TrustServerCertificate=true". I have no problem connecting to SQL Server via Management Studio, nor do I have a problem importing a CSV via the GUI in Management Studio, but doing it via Dbatools, I always get this error:  **[Import-DbaCsv] Failure | The certificate chain was issued by an authority that is not trusted.** 

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

5.1.19041.2673

### SQL Server Edition and Build number

SQL Server Developer. 16.0.1000.6

### .NET Framework Version

.NET Framework 4.7.4038.0

**Comment by andreasjordan** [comment]
Please have a look at: https://blog.netnerds.net/2023/03/new-defaults-for-sql-server-connections-encryption-trust-certificate/

You need to run `Set-DbatoolsConfig -FullName sql.connection.trustcert -Value $true -Register` to set the connection string "TrustServerCertificate=true" for every command.
