### ISSUE TITLE
New-DbaComputerCertificate - 6th Example is wrong in Synopsis and should be removed

### ISSUE THREAD

**Issue by HCRitter** [dataplat/dbatools#8908]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

New-DbaComputerCertificate - 6th Example is wrong in Synopsis and should be removed

is:
```powershell
<#
-------------------------- EXAMPLE 6 --------------------------

 PS C:\> Add-DbaComputerCertificate -ComputerName sql01 -Path C:\temp\sql01.pfx -Confirm:$false
-Flag NonExportable



Adds the local C:\temp\sql01.pfx to sql01's LocalMachine\My (Personal) certificate store and
marks the private key as non-exportable. Skips confirmation prompt.
#>
```
This example is pointing to another command and should be removed

### Steps to Reproduce

```powershell
(Get-Help -Examples -Name New-DbaComputerCertificate).examples.example[5]
```

### Please confirm that you are running the most recent version of dbatools

2.0.1

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

PSVersion 7.3.4
PSEdition Core
GitCommitId 7.3.4
OS Microsoft Windows 10.0.19045
Platform Win32NT
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
WSManStackVersion 3.0

### SQL Server Edition and Build number

None

### .NET Framework Version

.NET 7.0.5

**Comment by HCRitter** [comment]
if you say that this can be removed, I will create a pull request for this :)

**Comment by potatoqualitee** [comment]
merciii
