### ISSUE TITLE
Add actual sqlserver.exe build numbers to build json file

### ISSUE THREAD

**Issue by ErikEJ** [dataplat/dbatools#8914]
### Summarize Functionality

As an server administrator I look at my server services remotely, and I am not sure to connect to SQL Server instances.  But I can locate sqlserver.exe and determine the file version remotely. This information I can merge with the dbatools build json file in order to determine if the SQL instances are up to date.

Happy to help provide this information in a draft PR if this feature makes sense.

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by wsmelton** [comment]
@ErikEJ if you are not aware you can pull the version of SQL Server without having to check the file version. We support getting the version via SQLWMI commands, `Get-DbaService` and using the `-AdvancedProperties` parameter will retrieve the version running.

![image](https://github.com/dataplat/dbatools/assets/11204251/8d8b6dc1-b3ff-4c65-aaf6-72713496f129)

You can also use `Test-DbaBuild` without connecting to the instance by passing in the version value to the command.

**Comment by ErikEJ** [comment]
@wsmelton I rest my case 😅

**Comment by potatoqualitee** [comment]
wow, i did not know this 😅  gonna have to blog about it.
