### ISSUE TITLE
Copy-DbaDbTableData - Missing Test-Bound on -Query & (-Table|-View) - Missing from docs too

### ISSUE THREAD

**Issue by chadbaldwin** [dataplat/dbatools#8919]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

No error received, when one should have been thrown for required parameter.

Documentation mentions it is required when using `-Query`:

https://docs.dbatools.io/Copy-DbaDbTableData.html

> Note: The workflow in the command requires that a valid -Table or -View parameter value be specified.

However, there is no check in the function to notify the user that it is missing. It is also missing from the documentation examples / help examples.

### Steps to Reproduce

Command with missing required parameter:

```powershell
Copy-DbaDbTableData `
    -SqlInstance 'SvrFoo' -Database 'DBFoo' -Query "SELECT * FROM [dbo].[xyz] WHERE id = 1" `
    -Destination 'SvrBar' -DestinationDatabase 'DBBar' -DestinationTable '[dbo].[xyz]' `
    -KeepIdentity
```
Missing `-Table` or `-View`, but when run, no errors returned despite it being required. It simply just stops.

This is what _should_ be run:

```powershell
Copy-DbaDbTableData `
    -SqlInstance 'SvrFoo' -Database 'DBFoo' -Table '[dbo].[xyz]' -Query "SELECT * FROM [dbo].[xyz] WHERE id = 1" `
    -Destination 'SvrBar' -DestinationDatabase 'DBBar' -DestinationTable '[dbo].[xyz]' `
    -KeepIdentity
```

### Please confirm that you are running the most recent version of dbatools

2.0.2

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

Microsoft SQL Server 2017 (RTM-CU31-GDR) (KB5021126) - 14.0.3460.9 (X64) 
	Jan 25 2023 08:42:43 
	Copyright (C) 2017 Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: )

### .NET Framework Version

.NET 7.0.5

**Comment by andreasjordan** [comment]
Thanks for the issue, will open a PR to fix this shortly.
