### ISSUE TITLE
Copy-DbaDatabase is failing to delete backup files when alternate SQL method is required

### ISSUE THREAD

**Issue by bowerandy** [dataplat/dbatools#8921]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

NB: There was existing issue #8410 but this was closed as not reproducible.. see reasoning below...

When using the **-BackupRestore** method, for copying databases, I am seeing the backup files being left behind. The problem occurs when the **-SharedPath** is not available to the location that is executing the Powershell. In this case I believe that the code is intended to fall back on an `_EXEC master.sys.xp_delete__file` call but this is not happening. 

The errant code appears to be around line 1250 in **Copy-DbaDatabase.ps1** which reads:
`if (Test-Path $backupFile -ErrorAction Stop) {`
This is not allowing an exception to be throw so the alternate method in the catch block is bypassed.

### Steps to Reproduce

```powershell
$sqlInstanceName = 'NQ-SQL-01'
$sourceDbName = 'NQTestRelease_Tenant1'
$paths=Get-DbaDefaultPath -SqlInstance $sqlInstanceName
Copy-DbaDatabase -Source $sqlInstanceName -Destination $sqlInstanceName -Database $sourceDbName -Prefix "Test" -WithReplace -BackupRestore -SharedPath $paths.Backup
```
**Important: $paths.Backup is a local folder on the SQL server, inaccessible to the location executing the above code**.

### Please confirm that you are running the most recent version of dbatools

I am running the latest code directly from the development branch in the repo

### What PowerShell host was used when producing this error

VS Code (terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor) 

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.8.09037
Full        4.8.09037
Client      4.0.0.0

**Comment by andreasjordan** [comment]
Good catch, thanks for the analysis. Will provide a fix.

**Comment by bowerandy** [comment]
@andreasjordan - I'm afraid that I think this is still an issue in 2.0.4 after your fix. Although you have removed the original test (and -ErrorAction Stop) to see if the backup file was accessible the subsequent Remove-Item call still has a Stop on error. I would be expecting this remove to fail and then the exception be caught by the alternate SQL method block.
i.e. around line 1254:

```
  try {
      Write-Message -Level Verbose -Message "Deleting $backupFile."
      Remove-Item $backupFile -ErrorAction Stop
  } catch {
```

**Comment by wsmelton** [comment]
The stop action is supposed to be there and cannot be removed as it will cause an uncontrolled exception to be thrown and stop the whole script execution. We add the ErrorAction to control the workflow of the code execution.

When you run try/catch without ErrorAction the catch block is never hit

![script block code with try/catch, without error action](https://github.com/dataplat/dbatools/assets/11204251/c6d346a4-475b-4dc9-a41c-bd9f0e483fb8)

With it included we ensure the catch block code is executed:

![script block code with try/catch, with error action](https://github.com/dataplat/dbatools/assets/11204251/45836d36-9a55-498a-9871-ee5ab3291d06)

**Comment by bowerandy** [comment]
Ok, yes I can see you are right about ErrorAction. Hmm... that means I need to go back and work out why I am still seeing the Copy-DbaDatabase backup files being left behind on the server.

**Comment by bowerandy** [comment]
Hi. I believe that issue I'm seeing this time, with backup databases being retained, is caused by the current user not having proper rights to the shared backup location. I think this means that the foreach loop returns an empty collection so no delete attempt is made. I have managed to get around the problem by adding rights to this location.
