### ISSUE TITLE
`Invoke-DbaQuery` queries the wrong database after `Get-DbaDbForeignKey`

### ISSUE THREAD

**Issue by jasonmcboyd** [dataplat/dbatools#8927]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

WARNING: [10:52:37][Invoke-DbaQuery] [\<MyServer\>] Failed during execution | Invalid object name '\<MyTable\>'.

### Steps to Reproduce

```powershell
$connection = Connect-DbaInstance -ConnectionString $connectionString
# This queries the correct database
Invoke-DbaQuery -SqlInstance $connection -Query $query
Get-DbaDbForeignKey -SqlInstance $connection
# This queries a different database on the server
Invoke-DbaQuery -SqlInstance $connection -Query $query
```

### Please confirm that you are running the most recent version of dbatools

2.0.3

### Other details or mentions

After `Get-DbaDbForeignKey` subsequent queries are being invoked against a different database that exists on the server rather than the database specified in the connection string.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.8
PSEdition                      Core
GitCommitId                    7.2.8
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU18-GDR) (KB5021124) - 15.0.4280.7 (X64)   Jan 23 2023 12:37:13   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET 6.0.11

**Comment by jasonmcboyd** [comment]
It _looks_ like what is happening is that because I am not passing the `Database` parameter to `Get-DbaDbForeignKey` it is getting the foreign keys for every database on the server not just the database specified in the connection string. The final call to `Invoke-DbaQuery` is targeting the database that happens to be that last database on the server if you sort by database names alphabetically. My _guess_ is that without passing the `Database` parameter it enumerates the databases alphabetically, returning the foreign keys for each and that when it completes the connections internal state continues to point to that last database.

The first call of `Invoke-DbaQuery -SqlInstance $connection -Query $query -Verbose -Debug` yields:

> DEBUG: 80761 | [12:08:29][Invoke-DbaQuery] Bound parameters: SqlInstance, Query, Verbose, Debug
DEBUG: 80963 | [12:08:29][Invoke-DbaQuery] SqlInstance passed in, will work on: \<redacted\>
DEBUG: 80970 | [12:08:29][Invoke-DbaQuery] Current connection will be reused
DEBUG: 145736 | [12:08:29][Invoke-DbaAsync] Stripping GOs from source

The second call to `Invoke-DbaQuery -SqlInstance $connection -Query $query -Verbose -Debug` after `Get-DbaDbForeignKey` yeilds:

> DEBUG: 80761 | [12:08:11][Invoke-DbaQuery] Bound parameters: SqlInstance, Query, Verbose, Debug
DEBUG: 80963 | [12:08:11][Invoke-DbaQuery] SqlInstance passed in, will work on: \<redacted\>
DEBUG: 80970 | [12:08:11][Invoke-DbaQuery] Current connection will be reused
DEBUG: 145736 | [12:08:11][Invoke-DbaAsync] Stripping GOs from source
DEBUG: 145665 | [12:08:11][Resolve-SqlError] Capture Other Error
WARNING: [12:08:11][Invoke-DbaQuery] [\<redacted\>] Failed during execution | Invalid object name '\<redacted\>'.
DEBUG: [12:08:11][Invoke-DbaQuery] [\<redacted\>] Failed during execution | Invalid object name '\<redacted\>'.

If I watch the query in SQL profiler I can see that the first query targets the database specified initially in the connection string and the second query targets a different database.

**Comment by andreasjordan** [comment]
Ok, I can now reproduce the issue. But only if I use `-ConnectionString $connectionString` for `Connect-DbaInstance`, not if I use `-SqlInstance <computername>`. Will have a closer look.

**Comment by andreasjordan** [comment]
It looks like a issue in the used SMO. Because we do not change the database context in the code. We just access the SMO.

But the object that is returned from `Connect-DbaInstance` if different depending on the parameters. We have to find a way to return an smo object that does not change the context when accessing different parts of the object.

Will take a while...

**Comment by andreasjordan** [comment]
To reproduce the isse I use this code:

```
$connection = Connect-DbaInstance -SqlInstance SQL01
$query = 'SELECT DB_NAME()'
Invoke-DbaQuery -SqlInstance $connection -Query $query  # returns "master"
$null = Get-DbaDbForeignKey -SqlInstance $connection
Invoke-DbaQuery -SqlInstance $connection -Query $query  # returns "master"
$connection = Connect-DbaInstance -SqlInstance $connection.ConnectionContext.ConnectionString
Invoke-DbaQuery -SqlInstance $connection -Query $query  # returns "master"
$null = Get-DbaDbForeignKey -SqlInstance $connection
Invoke-DbaQuery -SqlInstance $connection -Query $query  # returns "tempdb"
```

@potatoqualitee - I don't have an idea. Maybe someone at Microsoft can help?

**Comment by niphlod** [comment]
mhhh, well... it's like it's reusing the connection like when you jump dbs with "USE dbname" .
With Azure SQL raging (where you "can't" switch dbs on the same connection) I'd wage that if you start a connection towards a database, you change context (i.e. with "USE dbname"), the connection is put back on the pool without the dbs being changed back before reuse.
What happens if you clear the pool ?
