### ISSUE TITLE
IMPORT-DBACSV Creates Column Names with Leading space

### ISSUE THREAD

**Issue by gordoncoulter** [dataplat/dbatools#8930]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Column names are created with leading spaces when there's spaces in the column headings row.

### Steps to Reproduce

Heading1,Heading2, Heading3,Heading4

Will create columns
Heading1
Heading2
 Heading3 <- Leading space because there's a trailing space after the "," on Heading2
Heading4

### Please confirm that you are running the most recent version of dbatools

2.0.3

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.22000.1335                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.22000.1335                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-GDR) (KB5021125) - 15.0.2101.7 (X64)   Jan 23 2023 13:08:05   Copyright (C) 2019 Microsoft Corporation  Express Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 22000: ) (Hypervisor) 

### .NET Framework Version

PSChildName                      Version
-----------                      -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.09037
Full                             4.8.09037
Client                           4.0.0.0

**Comment by niphlod** [comment]
in "csv-dialect", that's a "leading-space property named Heading3". fix the csv before sending it in ;-)

**Comment by gordoncoulter** [comment]
I've worked around with column mappings. The CSV is 2.5Gb, so editing it isn't easy and likely can't get it fixed at source.

**Comment by niphlod** [comment]
perfect. IMHO Import-DbaCsv shouldn't be "augmented" to allow for such scenarios, or it quickly involves realizing the "T" part of an ETL, which Import-DbaCsv by itself can't sustain. But other developers may think differently.

**Comment by potatoqualitee** [comment]
Thank you both 🙏🏼
