### ISSUE TITLE
Multiple Issues with New-DbaConnectionString on dbatools 1.1 or above

### ISSUE THREAD

**Issue by rener-exigo** [dataplat/dbatools#8935]
### Verified issue does not already exist?

No, I did not search

### What error did you receive?

Since dbatools versions 1.1 or above we started having issues with New-DbaConnectionString Command and those issues were not present in older versions of dbatools. 
Below are the issues and the workaround we had to implement to be able to use it in new dbatools versions. 

- By Default the following parameter gets added with spaces and it is not supported "Multiple Active Result Sets=False".

- By Default the following parameter gets added with spaces and it is not supported "Trust Server Certificate=True".

- By Default the command-let assumes you will use sql authentication and for some reason it changes the format of the user from ad\username to username@ad but it does not work so you have to fix that to use the right format and you must also add the parameter Integrated Security=True if you want to use windows authentication.

### Steps to Reproduce
```
$userSQLAdmin = 'ad\username'
$password = ConvertTo-SecureString 'HereIsThePassword' -AsPlainText -Force
$credentialpremise = New-Object System.Management.Automation.PSCredential($userSQLAdmin,$password)

$ins_conn=New-DbaConnectionString -SqlInstance "ServerName" -Database "DatabaseName" -Credential $credentialpremise 

$truncate=@"
    truncate table TableName
"@

    $SqltrnConn = New-Object System.Data.SqlClient.SqlConnection
    $SqltrnConn.ConnectionString = $ins_conn
    $SqltrnConn.Open();
    $SqltrnCmd = New-Object System.Data.SqlClient.SqlCommand
    $SqltrnCmd.CommandText = $truncate
    $SqltrnCmd.CommandTimeout = 600;
    $SqltrnCmd.Connection = $SqltrnConn
    $SqltrnCmd.ExecuteNonQuery();
    $SqltrnConn.Close();
```
### Please confirm that you are running the most recent version of dbatools

2.0.3

### Other details or mentions

I also found the following article https://blog.netnerds.net/2023/03/new-defaults-for-sql-server-connections-encryption-trust-certificate/ which help me to understand the new changes implemented and how to deal with them but I still had the issues I am reporting. 

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

I have implemented the following workaround
```
$userSQLAdmin = 'ad\username'
$password = ConvertTo-SecureString 'HereIsThePassword' -AsPlainText -Force
$credentialpremise = New-Object System.Management.Automation.PSCredential($userSQLAdmin,$password)

$ins_conn=New-DbaConnectionString -SqlInstance "ServerName" -Database "DatabaseName" -Credential $credentialpremise 
$test = $ins_conn.replace('Multiple Active Result Sets=False','MultipleActiveResultSets=False') 
$test2 = $test.replace('Trust Server Certificate=True','TrustServerCertificate=True;Integrated Security=True')
$test3 = $test2.replace('User ID=username@ad','User ID=ad\username')

$truncate=@"
    truncate table TableName
"@

    $SqltrnConn = New-Object System.Data.SqlClient.SqlConnection
    $SqltrnConn.ConnectionString = $test3
    $SqltrnConn.Open();
    $SqltrnCmd = New-Object System.Data.SqlClient.SqlCommand
    $SqltrnCmd.CommandText = $truncate
    $SqltrnCmd.CommandTimeout = 600;
    $SqltrnCmd.Connection = $SqltrnConn
    $SqltrnCmd.ExecuteNonQuery();
    $SqltrnConn.Close();
```
### SQL Server Edition and Build number
```
Microsoft SQL Server 2019 (RTM-CU20) (KB5024276) - 15.0.4312.2 (X64)   Apr  1 2023 12:10:46   Copyright (C) 2019 Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 
```
### .NET Framework Version

.NET Framework 4.8.4614.0

**Comment by potatoqualitee** [comment]
Hello, in the future, please check to see if this issue has been addressed in previous issues. If it has been, then you'll a resolution quicker. Ultimately, however, you're probably looking for the `-Legacy` parameter which uses System.Data instead of Microsoft.Data. Please let us know if that solves your issue.

**Comment by rener-exigo** [comment]
Hello, 
I have tried with the legacy parameter, and it continues failing. 
Exception calling "Open" with "0" argument(s): "Login failed for user 'username@ad'."
At line:20 char:5
+     $SqltrnConn.Open();
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SqlException
 
Exception calling "ExecuteNonQuery" with "0" argument(s): "ExecuteNonQuery requires an open and available Connection. The connection's current state is closed."
At line:25 char:5
+     $SqltrnCmd.ExecuteNonQuery();
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : InvalidOperationException

This is how it built the connection string
Data Source=ServerName;Initial Catalog=DatabaseName;User ID=username@ad;Password="PasswordIsHere";MultipleActiveResultSets=False;Connect Timeout=15;Encrypt=False;TrustServerCertificate=True;Packet Size=4096;Application Name="dbatools PowerShell module - dbatools.io"

If you see it is still putting the format of username@ad and it does not have the  Integrated Security=True.

Regards

**Comment by wsmelton** [comment]
@rener-exigo functionality of this command changed sometime back (not sure what version this was done) but you have to set a module configuration in order to achieve what you are looking for:

![image](https://github.com/dataplat/dbatools/assets/11204251/c5815f45-e3e2-4c80-ad4e-62aa1eaa5e32)

The following should work for your example:

```powershell
$userSQLAdmin = 'ad\username'
$password = ConvertTo-SecureString 'HereIsThePassword' -AsPlainText -Force
$credentialpremise = New-Object System.Management.Automation.PSCredential($userSQLAdmin,$password)

Set-DbatoolsConfig -FullName sql.connection.legacy -Value $true

$ins_conn=New-DbaConnectionString -SqlInstance "ServerName" -Database "DatabaseName" -Credential $credentialpremise -Legacy
```
