### ISSUE TITLE
Write-DbaDbTableData throws `SetValueInvocationException` with message "Property NonPooledConnection cannot be changed or read after a connection string has been set."

### ISSUE THREAD

**Issue by jasonmcboyd** [dataplat/dbatools#8940]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

> Exception setting "NonPooledConnection": "Property NonPooledConnection cannot be changed or read after a connection string has been set."

### Steps to Reproduce

```powershell
$connection = Connect-DbaInstance -ConnectionString $connectionString
$rowsToInsert = Invoke-DbaQuery -SqlInstance $connection -Query $queryToGetRows
Write-DbaDbTableData -InputObject $rowsToInsert -SqlInstance $connection -KeepIdentity -Table 'my-table'
```

### Please confirm that you are running the most recent version of dbatools

2.0.3

### Other details or mentions

I believe this is related to this issue: https://github.com/dataplat/dbatools/issues/7546

I stepped through the `Write-DbaDbTableData` function and the exception is being thrown at this line: https://github.com/dataplat/dbatools/blob/f0958c11f1e944aab4da6a800474c276634a7fa9/public/Write-DbaDbTableData.ps1#L458

It looks like the call to `Connect-DbaInstance` may be causing it to try and update the NonpoolConnection property of the original `$SqlInstance` object. I did not debug it further than that but I hope that helps you find the issue.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

PSVersion 7.2.8
PSEdition Core
GitCommitId 7.2.8
OS Microsoft Windows 10.0.19045
Platform Win32NT
PSCompatibleVersions {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion 2.3
SerializationVersion 1.1.0.1
WSManStackVersion 3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU18-GDR) (KB5021124) - 15.0.4280.7 (X64) Jan 23 2023 12:37:13 Copyright (C) 2019 Microsoft Corporation Enterprise Edition (64-bit) on Windows Server 2019 Standard 10.0 (Build 17763: ) (Hypervisor)

### .NET Framework Version

.NET 6.0.11

**Comment by andreasjordan** [comment]
In this case, you have to change your connection string and add "pooling=false" to request a non-pooled connection.

**Comment by jasonmcboyd** [comment]
I don't understand. Can you elaborate on why? I don't see anything in the detailed help for `Invoke-DbaQuery` or `Write-DbaDbTableData` that indicates they should be used with "pooling=false".

**Comment by andreasjordan** [comment]
It's not in the docs, it's in the code. `Write-DbaDbTableData` needs a non-pooled connection and is trying to change the connection settings. We have some other issues with connections based on connection strings (and currently no sulution), so as a workaround I see two options:
* Use `Connect-DbaInstance` with an instance name and optionally other parameters. That is the "normal" case that works best.
* Change the connection string to start with an non-pooled connection.

**Comment by wsmelton** [comment]
Can you provide the connection string you are using in your steps to reproduce?

**Comment by jasonmcboyd** [comment]
It's your basic connection string: `server=blah; database=blah; trusted_connection=true; trustservercertificate=true`.

But it sounds like using an instance name rather than a connection string is better so I'll use that going forward.
