### ISSUE TITLE
Get-DbaProductKey support SQL Server 2022

### ISSUE THREAD

**Issue by frugecn** [dataplat/dbatools#8944]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

ObjectNotFound: The term 'Stop-Function' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### Steps to Reproduce

```powershell
Get-DbaProductKey -ComputerName <computername>
```

### Please confirm that you are running the most recent version of dbatools

1.x
2.x

### Other details or mentions

switch statement against $versionMajor does not include version 16.  When manually adding the code on my local machine, adding v16, it works.  I'm just not that familiar with all of the ins and outs of contributing to the repo yet.

Add to Get-DbaProductKey function:
```powershell
                16 {
                    $key = @("$($instanceReg.Path)\Setup\DigitalProductID", "$($instanceReg.Path)\ClientSetup\DigitalProductID")
                    $sqlversion = "SQL Server 2022 $servicePack"
                }

```

Existing:

```powershell
            switch ($versionMajor) {
                9 {
                    $sqlversion = "SQL Server 2005 $servicePack"
                    $findkeys = $reg.OpenSubKey("$($instanceReg.Path)\ProductID", $false)
                    foreach ($findkey in $findkeys.GetValueNames()) {
                        if ($findkey -like "DigitalProductID*") {
                            $key = @("$($instanceReg.Path)\ProductID\$findkey")
                        }
                    }
                }
                10 {
                    $sqlversion = "SQL Server 2008 $servicePack"
                    if ($server.VersionMinor -eq 50) {
                        $sqlversion = "SQL Server 2008 R2 $servicePack"
                    }
                    $key = @("$($instanceReg.Path)\Setup\DigitalProductID")
                }
                11 {
                    $key = @("$($instanceReg.Path)\Setup\DigitalProductID", "$($instanceReg.Path)\ClientSetup\DigitalProductID")
                    $sqlversion = "SQL Server 2012 $servicePack"
                }
                12 {
                    $key = @("$($instanceReg.Path)\Setup\DigitalProductID", "$($instanceReg.Path)\ClientSetup\DigitalProductID")
                    $sqlversion = "SQL Server 2014 $servicePack"
                }
                13 {
                    $key = @("$($instanceReg.Path)\Setup\DigitalProductID", "$($instanceReg.Path)\ClientSetup\DigitalProductID")
                    $sqlversion = "SQL Server 2016 $servicePack"
                }
                14 {
                    $key = @("$($instanceReg.Path)\Setup\DigitalProductID", "$($instanceReg.Path)\ClientSetup\DigitalProductID")
                    $sqlversion = "SQL Server 2017 $servicePack"
                }
                15 {
                    $key = @("$($instanceReg.Path)\Setup\DigitalProductID", "$($instanceReg.Path)\ClientSetup\DigitalProductID")
                    $sqlversion = "SQL Server 2019 $servicePack"
                }
                default {
                    Stop-Function -Message "SQL version not currently supported." -Continue
                }
            }

```

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), VS Code (terminal), VS Code (integrated terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.3.4
PSEdition                      Core
GitCommitId                    7.3.4
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

SQL Server 2022, any build

### .NET Framework Version

PSChildName                      Version
-----------                      -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.09032
Full                             4.8.09032
Client                           4.0.0.0

**Comment by wsmelton** [comment]
We need to get out of doing the hardcoding of version numbers, so we don't have to maintain. I mean in 5 years do we want to have an extra 3-4 numbers added to that switch statement and have to keep that up forever?

**Comment by frugecn** [comment]
Agreed.  

Looks like they've maintained the same format since 2012.  Could error on using that format until it fails, adding a catch statement and returning version not supported as a quasi-future fix.

**Comment by erocpage** [comment]
I like the idea of defaulting on the current decode alogrithm until it changes.  It's been a bit since I looked at this part of the code, but IIRC that would simplify the switch logic and reduce the number of changes in the future.

**Comment by andreasjordan** [comment]
I'm working on a PR for this issue...
