### ISSUE TITLE
"dbatools.dat" "configuration.dat" - The process cannot access to file ... cacause it is being userd by antoher process

### ISSUE THREAD

**Issue by ToGoKuWr** [dataplat/dbatools#8969]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Hello, 
described below issue occur only with new DBATools 2.0.X (currently we are using the newest one: 2.0.3)

In our environment we are running script to check all SQLServer servers, all databases and save some Information to our table. During this process we are using the MULTI THREADS way, as you can see viewing below code. 

SCRIPT checks server by server. Every run among 160 server we have randomly 3 - 10 servers with errors like: 

ERROW WE RECIVE: 

Errors: The process cannot access the file 'C:\Program Files\WindowsPowerShell\Modules\dbatools\2.0.3\dbatools.dat' because it is being used by another process. The process cannot access the file 'C:\Program Files\WindowsPowerShell\Modules\dbatools\2.0.3\private\configurations\configuration.dat' because it is being used by another process. The term 'Register-DbaTeppArgumentCompleter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. The term 'Register-DbaMessageTransform' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. The term 'Register-DbaRunspace' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. The term 'Register-DbaRunspace' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. The term 'Register-DbaMaintenanceTask' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. 

The process cannot access the file 'C:\Program Files\WindowsPowerShell\Modules\dbatools\2.0.3\private\configurations\configuration.dat' because it is being used by another process.

Errors: The process cannot access the file 'C:\Program Files\WindowsPowerShell\Modules\dbatools\2.0.3\private\maintenance\maintenance.dat' because it is being used by another process.  

Errors: The process cannot access the file 'C:\Program Files\WindowsPowerShell\Modules\dbatools\2.0.3\private\configurations\configuration.dat' because it is being used by another process.  

### Steps to Reproduce

$AllJobs = @() ### List of all the Job created to get the metrics- Create one job per server - Each job will get the servername as a name.
$MaxThreads=4; ### A max of 7 simultaneous jobs can be running
$Threads=0;    ### A counter to follow how many jobs have been invoked
$MaxWaitAtEnd= 800;   ### Maximum time in seconds that we will wait for a job to report an END/finish
$SleepTimer = 500;    ### A pause time for a job in milliseconds

$ServerList | ForEach-Object{

    While ($(Get-Job -state running).count -ge $MaxThreads){
        Write-Progress  -Activity "Getting Servers Metrics" -Status "Waiting for threads to close" -CurrentOperation "$Threads threads created - $($(Get-Job -state running).count) threads open" -PercentComplete ($Threads / ($ServerList.count+1) * 100)            
        Start-Sleep -Milliseconds $SleepTimer
    }

    $Threads++

    Write-Host "Starting collect on $($_.ServerName) in a different thread"
    Add-Content -Path "$path\Main_SQLStat_Process.Log" -Value "Starting collect on $($_.ServerName) in a different thread"

    $environement = $_.Group.Substring($($_.Group.IndexOf('\')+1),$_.Group.length-$($_.Group.IndexOf('\')+1))

    Write-Host "Environment = $environement"
    Add-Content -Path "$path\Main_SQLStat_Process.Log" -Value "Environment = $environement"

    IF($_.ServerName -like '*rs*'){
        Add-Content -Path "$path\Main_SQLStat_Process.Log" -Value "Server $($_.ServerName) is RS server"
        Add-Content -Path "$path\Main_SQLStat_Process.Log" -Value "Calling Proceed-RS Function in new Thread"
        
        IF($($_.ServerName) -like '*\*'){
            $RSServer = $_.ServerName.Substring(0,$_.ServerName.IndexOf('\'))  ### Get servername from instance named SSRS server like XXXX
        }
        ELSE{
            $RSServer = $($_.ServerName)
        }

        TRY{ 
            $Job_id = Start-Job -name "$($_.ServerName)" -ScriptBlock {
                                                                        param($servername , $environement , $dateid,$path,$MainServer,$MainDatabase,$Modulepath, $Credential) 
                                                                        Import-Module "$Modulepath\SQLStatisticsModule.psm1" -Force -DisableNameChecking;
                                                                        IF ($servername -like '*XXXX*')
                                                                        {Proceed-RS -servername $servername -env $environement -dateid $dateid  -path "$path" -MainServer $MainServer -MainDatabase $MainDatabase -Credential $Credential}
                                                                        ELSE 
                                                                        {Proceed-RS -servername $servername -env $environement -dateid $dateid  -path "$path" -MainServer $MainServer -MainDatabase $MainDatabase}
                                                                
                                                                    } -ArgumentList ($($_.ServerName) , $environement ,$dateid,"$path\Proceed-RS_$RSServer.Log",$MainServer,$MainDatabase,$Modulepath, $Credential)
	        $AllJobs += $Job_id
        }
        CATCH{ 
            $Exception = $_.Exception.Message
            $FunctionError =    "`r`n" + "Function:"  + "`t"   + "Proceed_RS" +  
                                "`r`n" + "Job Name :"    + "`t`t" + $($_.ServerName) +   
                                "`r`n" + "Error:"     + "`t`t" + $Exception 
            Write-Host "Error: Cannot invoke the Proceed_RS function into new Job. Error Message : $FunctionError"
            Add-Content -Path "$path\Main_SQLStat_Process.Log" -Value "Error: Cannot invoke the Proceed_RS function into new Job. Error Message : $FunctionError"
            $Errorlogs += "<li>ERROR: Cannot treat the server $RSServer.<\li>"
         } 

    }
    ELSEIF($_.ServerName -like '*as*' -or $_.ServerName -like '*ssas*'){
        Add-Content -Path "$path\Main_SQLStat_Process.Log" -Value "Server $($_.ServerName) is AS server"
        #$WarningLogs += "<li>WARNING: The server $machine_name is not treated. Please rerun the manual script for this AS server as permissions are missing here. DATE_ID to be used $($dateid)</li>"

        IF($($_.ServerName) -like '*\*'){
            $ASServer = $_.ServerName.Substring(0,$_.ServerName.IndexOf('\'))  ### Get servername from instance named SSAS server
        }
        ELSE{
            $ASServer = $($_.ServerName)
        }

        TRY{ 
            $Job_id = Start-Job -name "$($_.ServerName)" -ScriptBlock {
                                                                 param($servername , $environement , $dateid,$path,$MainServer,$MainDatabase,$Modulepath, $Credential) 
                                                                 Import-Module "$Modulepath\SQLStatisticsModule.psm1" -Force -DisableNameChecking;
                                                                 IF ($servername -like '*extapp*')
                                                                    {Proceed-AS -servername $servername -env $environement -dateid $dateid  -path "$path" -MainServer $MainServer -MainDatabase $MainDatabase -Credential $Credential}
                                                                 ELSE 
                                                                    {Proceed-AS -servername $servername -env $environement -dateid $dateid  -path "$path" -MainServer $MainServer -MainDatabase $MainDatabase}
                                                                } -ArgumentList ($($_.ServerName) , $environement ,$dateid,"$path\Proceed-AS_$ASServer.Log",$MainServer,$MainDatabase,$Modulepath, $(if($ServerName -like '*XXXX*'){$Credential}))
	        $AllJobs += $Job_id
        }
        CATCH{ 
            $Exception = $_.Exception.Message
            $FunctionError =    "`r`n" + "Function:"  + "`t"   + "Proceed_AS" +  
                                "`r`n" + "Job Name :"    + "`t`t" + $($_.ServerName) +   
                                "`r`n" + "Error:"     + "`t`t" + $Exception 
            Write-Host "Error: Cannot invoke the Proceed_AS function into new Job. Error Message : $FunctionError"
            Add-Content -Path "$path\Main_SQLStat_Process.Log" -Value "Error: Cannot invoke the Proceed_RS function into new Job. Error Message : $FunctionError"
            $Errorlogs += "<li>ERROR: Cannot treat the server $ASServer.<\li>"
         } 
    }
    ELSE{
        Add-Content -Path "$path\Main_SQLStat_Process.Log" -Value "Server $($_.ServerName) is SQL DB Engine server"
        Add-Content -Path "$path\Main_SQLStat_Process.Log" -Value "Calling Proceed Function in new Thread"

        TRY{ 
            $Job_id = Start-Job -name "$($_.ServerName)" -ScriptBlock {
                                                                 param($servername , $environement , $dateid,$path,$MainServer,$MainDatabase,$Modulepath, $Credential) 
                                                                 Import-Module "$Modulepath\SQLStatisticsModule.psm1" -Force -DisableNameChecking;
                                                                 IF ($servername -like '*XXXX*'){
                                                                    Proceed -servername $servername -env $environement -dateid $dateid  -path "$path\Proceed_$servername.Log" -MainServer $MainServer -MainDatabase $MainDatabase -Credential $Credential
                                                                    }
                                                                 ELSE{
                                                                    Proceed -servername $servername -env $environement -dateid $dateid  -path "$path\Proceed_$servername.Log" -MainServer $MainServer -MainDatabase $MainDatabase
                                                                }
                                                             } -ArgumentList ($($_.ServerName) , $environement ,$dateid,$path,$MainServer,$MainDatabase,$Modulepath, $Credential)
	        $AllJobs += $Job_id
        }
        CATCH{ 
            $Exception = $_.Exception.Message
            $FunctionError =    "`r`n" + "Function:"  + "`t"   + "Proceed" +  
                                "`r`n" + "Job Name :"    + "`t`t" + $($_.ServerName) +   
                                "`r`n" + "Error:"     + "`t`t" + $Exception 
            Write-Host "Error: Cannot invoke the Proceed function into new Job. Error Message : $FunctionError"
            Add-Content -Path "$path\Main_SQLStat_Process.Log" -Value "Error: Cannot invoke the Proceed function into new Job. Error Message : $FunctionError"
            $Errorlogs += "<li>ERROR: Cannot treat the server $($_.ServerName).<\li>"
         } 
    }
    Write-Progress  -Activity "Getting Servers Metrics" -Status "Starting Threads" -CurrentOperation "$Threads threads created - $($(Get-Job -state running).count) threads open" -PercentComplete ($Threads / ($ServerList.count+1) * 100)
}

### Please confirm that you are running the most recent version of dbatools

DBATools 2.0.3

### Other details or mentions

On the DBATools 1.XX this script works without any problems like mentioned above. 

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

ame                           Value                                                                                                                                                                                           
----                           -----                                                                                                                                                                                           
PSVersion                      5.1.17763.3770                                                                                                                                                                                  
PSEdition                      Desktop                                                                                                                                                                                         
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                         
BuildVersion                   10.0.17763.3770                                                                                                                                                                                 
CLRVersion                     4.0.30319.42000                                                                                                                                                                                 
WSManStackVersion              3.0                                                                                                                                                                                             
PSRemotingProtocolVersion      2.3                                                                                                                                                                                             
SerializationVersion           1.1.0.1 

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU20) (KB5024276) - 15.0.4312.2 (X64)   Apr  1 2023 12:10:46   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

PSChildName Version  
----------- -------  
Client      4.8.03761
Full        4.8.03761
Client      4.0.0.0

**Comment by wsmelton** [comment]
duplicate #8964
