### ISSUE TITLE
Incomplete Commands after Module Installation

### ISSUE THREAD

**Issue by renzbagasbas** [dataplat/dbatools#8989]
Issue: dbatools commands are incomplete after module installation.

dbatools version installed: 
ModuleType: Script
Version: 2.0.4     
------------------
System Information
------------------
     Operating System: Windows 10 Pro 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)               
                   Processor: 12th Gen Intel(R) Core(TM) i7-1265U (12 CPUs), ~1.8GHz
                   Memory: 32768MB RAM
      Available OS Memory: 32196MB RAM
                Page File: 11121MB used, 53842MB available
                DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 96 DPI (100 percent)
       System DPI Setting: 144 DPI (150 percent)
         
------------------
PS Version
------------------                                                                                                    
PSVersion:                      5.1.19041.2673                                                                                                
PSEdition:                      Desktop                                                                                                       
PSCompatibleVersions:           {1.0, 2.0, 3.0, 4.0...}                                                                                       
BuildVersion:                   10.0.19041.2673                                                                                               
CLRVersion:                     4.0.30319.42000                                                                                               
WSManStackVersion:             3.0                                                                                                           
PSRemotingProtocolVersion:      2.3                                                                                                           
SerializationVersion:           1.1.0.1 

![image](https://github.com/dataplat/docs/assets/135796678/6fb3c707-1dc3-4d6b-a042-bf34ee83c163)

**Comment by potatoqualitee** [comment]
I have seen this before. Can you close out your PS window, restart and try again? If you continue to run into issues, run `$error | select *` and see what's up. If nothing, then please reinstall.

**Comment by renzbagasbas** [comment]
I'm suspecting it was incorrectly blocked by our Antivirus tool.

I confirm it thru the error logs:

Exception             : System.Management.Automation.ParseException: At line:1 char:1
                        + ### DO NOT EDIT THIS FILE DIRECTLY ###
                        + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                        This script contains malicious content and has been blocked by your antivirus software.

Thanks, Chrissy. This issue is closed

**Comment by potatoqualitee** [comment]
Please try with the latest version, too. dbatools is now signed with a Microsoft-issued certificate which has immediate reputation. You can read more here: https://blog.netnerds.net/2025/08/dbatools-azure-trusted-signing/
