### ISSUE TITLE
Test-DbaDbCompatibility - Don't trust the compatibility level of the master database

### ISSUE THREAD

**Issue by andreasjordan** [dataplat/dbatools#8991]
### Steps to Reproduce

Run Test-DbaDbCompatibility against a user database on a system that has a master database with an "old" compatibility level.

### Other details or mentions

See https://www.brentozar.com/archive/2023/06/why-are-yall-changing-the-compat-levels-on-master/ for details, especially the comments.

In-place upgrades don't change the compatibility level of the master database, so there are instances out there, where we can not get the target level from the master database.

In Invoke-DbaDbUpgrade we use this code:
```
$serverVersion = $server.VersionMajor
$serverLevel = [Microsoft.SqlServer.Management.Smo.CompatibilityLevel]"Version$($serverVersion)0"
```

I will open a PR to use this code in Test-DbaDbCompatibility as well.

**Comment by wsmelton** [comment]
That is a user problem, their environment chose to change from best practice or didn't follow normal practice for doing in-place upgrades. Most all documentation for upgrades state to change/verify the compatibility level of the databases after upgrade, that includes system databases.
