### ISSUE TITLE
documentation has "TThe" typo in several topics

### ISSUE THREAD

**Issue by mikeblas** [dataplat/dbatools#8999]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

not applicable

### Steps to Reproduce

Several topics say "TThe target SQL Server instance or instances".  Note that "The" is spelled with two capital tees:

* https://docs.dbatools.io/Get-DbaAvailableCollation
* https://docs.dbatools.io/Get-DbaDbMail
* https://docs.dbatools.io/Get-DbaDbMailConfig
* https://docs.dbatools.io/Get-DbaDbMailHistory
* https://docs.dbatools.io/Get-DbaDbMailLog
* https://docs.dbatools.io/Get-DbaDbMailServer
* https://docs.dbatools.io/Get-DbaDefaultPath
* https://docs.dbatools.io/Get-DbaErrorLog

Looks like some copy pasta placed the same error in each "Parameters" section.

### Please confirm that you are running the most recent version of dbatools

not applicable

### Other details or mentions

It seems like this is an error in the project because the *.ps1 files involved contain the typo directly. Fixing it in the docs project would just mean it needs to be fixed again and again, each time the documentation pages were regenerated.

At least, that's how I figure it works from reading the `CONTRIBUTING.md` file ... but maybe I've got it wrong.

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe), Windows PowerShell (powershell.exe)

### PowerShell Host Version

not applicable

### SQL Server Edition and Build number

not applicable

### .NET Framework Version

not applicable

**Comment by niphlod** [comment]
yup, just to confirm, there's no point in fixing docs, those are autogenerated from the .ps1 files so the fix must be in the inline help of the ps1 functions directly.
