### ISSUE TITLE
Copy-DbaDatabase using both -NewName and -SetSourceDatabaseOffline can set wrong database on source server offline

### ISSUE THREAD

**Issue by jameslegrand2** [dataplat/dbatools#9003]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When running Copy-DbaDatabase using both the -NewName and -SetSourceDatabaseOffline parameters, if the source SQL server happens to also contain a database that has the same name that will be used for the migrated database on the destination SQL server, that database will be set offline instead of the source database for the migration.

Example:
I have MyDatabase and MyDatabase_Test on the same SQL Server:
![image](https://github.com/dataplat/dbatools/assets/16070135/e2e27265-2128-45ca-a047-7dd0449dcb5a)

 I want to move MyDatabase_test to a different server (like a dedicated test server) where it will be named MyDatabase and run a command such as:
```powershell
Copy-DbaDatabase -Source MyServer\SQL2019 -Database "MyDatabase_Test" -Destination MyServer\SQL2022 -NewName "MyDatabase" -BackupRestore -SharedPath C:\SQLData\Migration -SetSourceOffline
```

MyDatabase_Test is migrated to the new SQL Server and renamed to MyDatabase as expected:
![image](https://github.com/dataplat/dbatools/assets/16070135/aa7ab5d5-65e5-4f36-b7df-e1a4941b4809)

However MyDatabase_Test is NOT set offline as expected.  Instead, MyDatabase (!!!Production!!!) is set offline:
![image](https://github.com/dataplat/dbatools/assets/16070135/bbf22625-1585-4dd8-aebd-9a8c66ed2494)

### Steps to Reproduce

```powershell
Copy-DbaDatabase -Source MyServer\SQL2019 -Database "MyDatabase_Test" -Destination MyServer\SQL2022 -NewName "MyDatabase" -BackupRestore -SharedPath C:\SQLData\Migration -SetSourceOffline
```

### Please confirm that you are running the most recent version of dbatools

1.1.145

Problem identified and confirmed in [current master branch Copy-DbaDatabase lines 1429-1432](https://github.com/dataplat/dbatools/blob/cb4fec178bdc37f6a50716769dcadce517da1199/public/Copy-DbaDatabase.ps1#L1429) where $DestinationdbName is set offline.  This should be $dbName.
![image](https://github.com/dataplat/dbatools/assets/16070135/870b2a16-79f0-46fc-92b1-cfbc65c1d716)

### Other details or mentions

-SetSourceReadOnly handles this properly

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.2673                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.2673                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

This is for the example provided in this issue which replicates issue discovered on live servers

Source: Microsoft SQL Server 2019 (RTM-CU16-GDR) (KB5014353) - 15.0.4236.7 (X64)   May 29 2022 15:55:47   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19045: ) (Hypervisor) 

Destination: Microsoft SQL Server 2022 (RTM) - 16.0.1000.6 (X64)   Oct  8 2022 05:58:25   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19045: ) (Hypervisor) 

### .NET Framework Version

PSChildName                      Version
-----------                      -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.8.04084
Full                             4.8.04084
Client                           4.0.0.0

**Comment by andreasjordan** [comment]
Thanks for the analysis. Will open a PR to fix this. Will also remove the call to `Stop-DbaProcess`, as this can be replaced by using `-Force` with `Set-DbaDbState`.
