### ISSUE TITLE
Find-DbaOrphanedFile do not accept servernames as default, it demands -sqlinstance as argument

### ISSUE THREAD

**Issue by frodr1k** [dataplat/dbatools#9008]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Find-DbaOrphanedFile do not support adding instance-name as default without using -sqlinstance. It throws an error. Probably not the most severe error but its annoying. 

PS C:\Script\git\script> Find-DbaOrphanedFile serverxxxx
Find-DbaOrphanedFile : A positional parameter cannot be found that accepts argument 'serverxxxx'.
At line:1 char:1
+ Find-DbaOrphanedFile serverxxxx
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Find-DbaOrphanedFile], ParameterBindingException                                                                                                                      
    + FullyQualifiedErrorId : PositionalParameterNotFound,Find-DbaOrphanedFile

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Find-DbaOrphanedFile  serverXXXXX

### Please confirm that you are running the most recent version of dbatools

2.0.3

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.19041.3031                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.19041.3031                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

### SQL Server Edition and Build number

n/a

### .NET Framework Version

n/a

**Comment by wsmelton** [comment]
This is not a bug, by design.
