### ISSUE TITLE
Start-DBAMigration changes two msdb schema authorizations to dbo in the target instance

### ISSUE THREAD

**Issue by EdZ99** [dataplat/dbatools#9011]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Bug - Start-DbaMigration apparently migrates schemas, but doesn't copy over the Authorization value.  In msdb there are a couple of schemas that are referenced in MS script msdb110_upgrade.sql that is part of Cumulative Update installs and after I run Start-Migration the schemas TargetServersRole and DatabaseMailUsersRole change authorizations to dbo, rather than TargetServersRole and DatabaseMailUsersRole which are the Authorization values in the Source instance.  All the instances that are the result of a Start-DbaMigration have been experiencing CU install failures with event errors citing the msdb110_upgrade.sql script and I have to drop the two schemas before the CU install will complete.  The only difference in msdb for the instances that fail compared to the ones that don't fail is the schema Authorizations.  I am using dbatools version 1.1.143 on SQL Server 2017 and 2019 on Windows.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
<# I start with both the source instance and the target instance having the same values for the msdb schemas DatabaseMailUserRole and TargetServersRole - and yes, the schema names appear to be Role names but that is how Microsoft has set these up.  In the Information_Schema.Schemata tale both the SCHEMA_NAME and SCHEMA_OWNER values are the same - the schema TargetServersRole, the SCHEMA_NAME is TargetServersRole and the SCHEMA_OWNER is TargetServersRole.  But after I run Start-DbaMigration with the following code, the SCHEMA_OWNER changes to dbo.  The same deal for the schema named DatabaseMailUserRole.  Note that the source instance and the target instance are on the same server and are the same SQL Server version.  This happens on both SQL 2017 and SQL 2019.    #>
$SourceInstance = 'SERVERName\InstanceName1'
$DestinationInstance = 'SERVERName\InstanceName2'

## Last migration step is to actually do the migration from the one instance to the other.  Excludes logins because we already took care of those.

    $ExcludeList = "SpConfigure", "Logins"

    $params = @{   
        Source = $SourceInstance
        Destination = $DestinationInstance
        UseLastBackup = $true
        Exclude = $ExcludeList
        DisableJobsOnDestination = $true
        ReuseSourceFolderStructure = $false
        Force = $true
        Whatif = $false
        }

    $params  # debug and display
    
    Start-DbaMigration @params -EnableException -Verbose -ErrorAction Stop | Format-Table Status,Type,Name -Wrap -AutoSize 

### Please confirm that you are running the most recent version of dbatools

I am running version 1.1.143.  I suspect that dbatools has been doing this Auth changing for years based on how for years I have needed to drop these schemas to get upgrades to work.

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

5.1.17763.3770

### SQL Server Edition and Build number

SQL 2019 15.0.4312.2
SQL 2017 14.0.3460.9

### .NET Framework Version

Client 4.8.03761
Full 4.8.03761
Client 4.0.0.0

**Comment by andreasjordan** [comment]
Will have a look...

**Comment by andreasjordan** [comment]
The command that does that is `Copy-DbaSystemDbUserObject`. `-Exclude SysDbUserObjects` would prevent this - so this should be your workaround in the current version of dbatools.

These are the schemas in a SQL Server 2022 msdb database:
![image](https://github.com/dataplat/dbatools/assets/66946165/52bcab65-19cf-40d0-9151-6e935900ca9b)

The marked top ones are no "system objects", so they are copied over. Because of `-Force`, they are droped and re-created.

I'm not sure if this is what we want. But I don't see a way to exclude them by any rule.
@potatoqualitee - Can you tell us more about what the command should copy over?

**Comment by andreasjordan** [comment]
But I have a fix to include the authorization and will open a PR for that.

Here is a short code to test that:
```
$server = Connect-DbaInstance -SqlInstance SQL01
$schema = $server.Databases['msdb'].Schemas['TargetServersRole']
# Code from Copy-DbaSystemDbUserObject starting line 167:
$transfer = New-Object Microsoft.SqlServer.Management.Smo.Transfer $server.Databases['msdb']
$null = $transfer.CopyAllObjects = $false
$null = $transfer.Options.WithDependencies = $true
$null = $transfer.Options.ScriptOwner = $true       # This is the new line that makes the difference
$null = $transfer.ObjectList.Add($schema)
$sql = $transfer.ScriptTransfer()
$sql  # Old: "CREATE SCHEMA [TargetServersRole]" / New: "CREATE SCHEMA [TargetServersRole] AUTHORIZATION [TargetServersRole]"
```

**Comment by EdZ99** [comment]
Thanks, guys, for taking up this issue and addressing it so quickly.  Very impressive.  😊
