### ISSUE TITLE
Copy-DbaDatabase - BackupRestore parameter misrepresents use of SharedPath parameter requirement

### ISSUE THREAD

**Issue by mikeblas** [dataplat/dbatools#9012]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

N/A

### Steps to Reproduce

In the [documentation for `Copy-DbaDatabase`](https://docs.dbatools.io/Copy-DbaDatabase.html), the `-BackupRestore` parameter says that "This method requires that you specify -SharedPath in a valid UNC format (\\server\share)."

This requirement seems to be over-stated, as the `-SharedPath` parameter can accept a URI (for Azure) or a local path (for local storage). In fact, two of the given examples used an Azure URI for the `-SharedPath` parameter with `-BackupRestore`.

In looking through the code, I can't seem to find a requirement that the `-SharedPath` is a UNC-format path. There are checks that a http-scheme URI needs Azure credentials, but I've found nothing specific to UNC.

### Please confirm that you are running the most recent version of dbatools

```
Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      4      -1
```

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.3770
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.3770
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### SQL Server Edition and Build number

N/A

### .NET Framework Version

```
PSChildName Version
----------- -------
Client      4.7.03190
Full        4.7.03190
Client      4.0.0.0
```

**Comment by wsmelton** [comment]
Processing code blocks for SharedPath param:

Path matches `https`:

https://github.com/dataplat/dbatools/blob/b1f2ba8327452f707608c312944a2cc896f45298/public/Copy-DbaDatabase.ps1#L724-L734

https://github.com/dataplat/dbatools/blob/b1f2ba8327452f707608c312944a2cc896f45298/public/Copy-DbaDatabase.ps1#L761-L769

Path matches `\\`

https://github.com/dataplat/dbatools/blob/b1f2ba8327452f707608c312944a2cc896f45298/public/Copy-DbaDatabase.ps1#L806-L818

**Comment by andreasjordan** [comment]
You can include a fix for that in your open pull request for Copy-DbaDatabase if you like. Or do you want others to fix that?
