### ISSUE TITLE
Copy-DbaDatabase - BackupRestore parameter documentation conflicts with example 3

### ISSUE THREAD

**Issue by mikeblas** [dataplat/dbatools#9013]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

N/A

### Steps to Reproduce

In the [documentation for `Copy-DbaDatabase`](https://docs.dbatools.io/Copy-DbaDatabase.html), the `-BackupRestore` option says "This method requires that you specify -SharedPath in a valid UNC format (\server\share)."

In the same topic, Example #3 uses the `-BackupRestore` option without providing a `-SharedPath` option.

From the code, it looks like the actual requirement is that `-BackupRestore` requires exactly one of `-UseLastBackup` or `-SharedPath`.

### Please confirm that you are running the most recent version of dbatools

```
Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      4      -1
```

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      5.1.17763.3770
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.3770
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### SQL Server Edition and Build number

N/A

### .NET Framework Version

```
PSChildName Version
----------- -------
Client      4.7.03190
Full        4.7.03190
Client      4.0.0.0
```

**Comment by andreasjordan** [comment]
You can include a fix for that in your open pull request for Copy-DbaDatabase if you like. Or do you want others to fix that?
