### ISSUE TITLE
Get-DbaProductKey returns wrong key

### ISSUE THREAD

**Issue by PowerDBAKlaas** [dataplat/dbatools#9022]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

no error, just wrong keys:
when an array of sql instances is passed in -ComputerName,
and for some server the key is not found (in my case, all SQL 2008 servers),
the key of the previous server in the loop is returned again.
So we probably need to set the property to $NULL somewhere.

### Steps to Reproduce

```powershell
Get-DbaProductKey -ComputerName $AllSQLServers
```

### Please confirm that you are running the most recent version of dbatools

2.0.4

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

7.3.4
Core

### SQL Server Edition and Build number

SQL 2008 + 2012 + 2016 + 2019

### .NET Framework Version

4.7.03062

**Comment by andreasjordan** [comment]
Thanks for reporting. Note for myself: `-Continue` is missing at the end of line 185. Will fix that in the next days.
