### ISSUE TITLE
Read-DbaXeFile missing XEvent library

### ISSUE THREAD

**Issue by dbaduck** [dataplat/dbatools#9033]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

SqlServer.XEvent\Read-SqlXEvent : The module 'SqlServer.XEvent' could not be loaded. For more information, run
'Import-Module SqlServer.XEvent'.
At line:98587 char:21
+             $enum = SqlServer.XEvent\Read-SqlXEvent -FileName $curren ...
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (SqlServer.XEvent\Read-SqlXEvent:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CouldNotAutoLoadModule

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

### Please confirm that you are running the most recent version of dbatools

```powershell
$data = Read-DbaXeFile -Path "path to *.xel"
```

### Other details or mentions

Looked in version 1.0.133 and the XEvent dlls are there.
Went to 2.04 and looked in the dbatools.library and the Xevent libraries are not there.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

PSVersion                      5.1.17763.2268
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.2268
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

Microsoft SQL Server 2017 (RTM-CU27) (KB5006944) - 14.0.3421.10 (X64)   Oct 14 2021 00:47:52   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) 

### .NET Framework Version

4.7.03190

**Comment by wsmelton** [comment]
You need to install sqlserver module for that command to work I recall.

**Comment by dbaduck** [comment]
That is quite a dependency. Is that going to cause issues if the sqlserver module is loaded too? I tried the older version of sqlserver and it didn't work. I will test it with the new one. It worked in 133 so it was a breaking change with a undocumented dependency?
