### ISSUE TITLE
Add-DbaServerRoleMember asks for confirmation even if switch is not set

### ISSUE THREAD

**Issue by Terr4** [dataplat/dbatools#9035]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When exeuting Add-DbaServerRoleMember it asks for confirmation to perform the action even if the -Confirm switch is not set. The -Confirm switch has no effect.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference

Add-DbaServerRoleMember -SqlInstance "SERVER01" -ServerRole sysadmin -Login "MYDOMAIN\MYDOMAINGROUP"

Confirm
Are you sure you want to perform this action?
Performing the operation "Adding login MYDOMAIN\MYDOMAINGROUP to server-level role: [sysadmin]" on target "[SERVER01]".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):`

```

### Please confirm that you are running the most recent version of dbatools

2.0.4

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.4.0-preview.3
PSEdition                      Core
GitCommitId                    7.4.0-preview.3
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 

### .NET Framework Version

.NET 8.0.0-preview.3.23174.8

**Comment by andreasjordan** [comment]
This is by design. The command uses `[CmdletBinding(SupportsShouldProcess, ConfirmImpact = 'High')]` and the `ConfirmImpact = 'High'` part sets the Confirm switch to $true by default. To suppress confirmation you have to use `-Confirm:$false`. The colon is important here.
