### ISSUE TITLE
Set-DbaDbCompatibility doesn't work

### ISSUE THREAD

**Issue by bzuidgeest** [dataplat/dbatools#9038]
### Verified issue does not already exist?

I have searched and found no existing issue, found a few closed onces refering sql2022 and Set-DbaDbCompatibility, they were not of use as setting the lower versions also did not work (though the output claims it does)

### What error did you receive?

Set-DbaDbCompatibility : Cannot process argument transformation on parameter 'Compatibility'. Cannot convert value "Version160" to type "Microsoft.SqlServer.Management.Smo
.CompatibilityLevel". Error: "Unable to match the identifier name Version160 to a valid enumerator name. Specify one of the following enumerator names and try again:
Version60, Version65, Version70, Version80, Version90, Version100, Version110, Version120, Version130, Version140, Version150"

### Steps to Reproduce

```powershell
Set-DbaDbCompatibility -SqlInstance $server -Database $toDatabase -Compatibility Version160
```

### Please confirm that you are running the most recent version of dbatools

2.0.4

### Other details or mentions

As a test I tried Set-DbaDbCompatibility -SqlInstance $server -Database $toDatabase -Compatibility Version150. 
Though I get 
ComputerName          : xxx
InstanceName          : xxx
SqlInstance           : xxxx
Database              : xxxx
Compatibility         : Version150
PreviousCompatibility : Version130

Nothing changes in the database. Running it again gets met the same output. Using a command like 
Set-DbaDbOwner -SqlInstance $server -Database $toDatabase -TargetLogin "sa"
works fine.

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                       
----                           -----                                                                                                                                       
PSVersion                      5.1.14393.5582                                                                                                                              
PSEdition                      Desktop                                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                     
BuildVersion                   10.0.14393.5582                                                                                                                             
CLRVersion                     4.0.30319.42000                                                                                                                             
WSManStackVersion              3.0                                                                                                                                         
PSRemotingProtocolVersion      2.3                                                                                                                                         
SerializationVersion           1.1.0.1                                                                                                                                     

### SQL Server Edition and Build number

Microsoft SQL Server 2022 (RTM-CU6) (KB5027505) - 16.0.4055.4 (X64)   Jun 29 2023 15:43:13   Copyright (C) 2022 Microsoft Corporation  Enterprise Edition (64-bit) on Windows Server 2022 Datacenter 10.0 <X64> (Build 20348: ) (Hypervisor) 

### .NET Framework Version

PSChildName                      Version       
-----------                      -------       
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926 
Windows Presentation Foundation  3.0.6920.4902 
v3.5                             3.5.30729.4926
Client                           4.8.03761     
Full                             4.8.03761     
Client                           4.0.0.0

**Comment by bzuidgeest** [comment]
PS C:\Users\bzs> Get-Module -Name dbatools*

ModuleType Version    Name                                ExportedCommands                                                                                                 
---------- -------    ----                                ----------------                                                                                                 
Script     2023.5.5   dbatools.library                    Get-DbatoolsLibraryPath   

I don't know how that relates to the version command in the bug report form works. That reports 2.0.4.

**Comment by andreasjordan** [comment]
The libraries are not part of dbatools. but part of dbatools.library. Do you only use dbatools or is the PowerShell module SqlServer by Microsoft maybe loaded also? Do you import dbatools at the top of you script?

**Comment by bzuidgeest** [comment]
I'm no expert in powershell. The dbatools was installed for the entire machine. It's commands are just there. Don't need an import statement or anything, Not for microsfts command for sql server, nor dbatools. I do use both in my scripts, using dbatools to plug holes in the microsoft tool set.

**Comment by bzuidgeest** [comment]
added Import-Module -Name dbatools as the first line and that fixes it. Thanks for the support!
