### ISSUE TITLE
[Copy-DbaDbTableData] REQUEST: allow applicationintent=READONLY so it connects to secondary.

### ISSUE THREAD

**Issue by mbourgon** [dataplat/dbatools#9055]
### Summarize Functionality

I was trying to copy 50gb from 50 tables (one table has 30gb, some have 5 records) from my Azure SQL DB. 

In order to minimize impact, I was going to use the ApplicationIntent=READONLY to use the secondary read-only replica. However, it doesn't appear to support it. 

I wound up using the import/export wizard, (and yes, I could use BCP) but I'd much prefer to use DBATools. Thanks!

While I do see that Invoke-DBAQuery supports it (via [-ReadOnly]), this function doesn't. I'm honestly unsure where all I'd make the changes to add that - I see that it's using connect-dbainstance (line 309), but at line 406 it's creating a new connection to the source, maybe you could add it there? 

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

Desired functionality: 

Copy-DbaDbTableData -SqlInstance sql1 -Destination sql2 -Database dbatools_from -Table dbo.test_table -ReadOnly

to copy from the RO secondary of SQL1, to SQL2

**Comment by wsmelton** [comment]
You can accomplish this by creating your connections via [Connect-DbaInstance](https://docs.dbatools.io/Connect-DbaInstance) and then passing that object to the Copy command.

```powershell
$sql1 = Connect-DbaInstance ... -ApplicationIntent ReadOnly
$sql2 = Connect-DbaInstance ... -ApplicationIntent ReadOnly
Copy-DbaDbTableData -SqlInstance $sql1 -Destination $sql2 ...
```

If you have any further questions you are welcome to open a [Q/A Discussion](https://github.com/dataplat/dbatools/discussions/categories/q-a) or ping us in SQL Community Slack around more advanced use of the module's commands.

**Comment by mbourgon** [comment]
Thank you!!
