### ISSUE TITLE
Set-DbaNetworkCertificate parameter SqlInstance is not defaulting to localhost

### ISSUE THREAD

**Issue by SQLCanuck** [dataplat/dbatools#9057]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

No error was received, however the certificate was not applied to the default instance when a value was not provided for the parameter SqlInstance.  The documentation indicates that it should default to localhost.

If the value localhost is specifically provided for parameter SqlInstance, then the certificate is applied as expected.

### Steps to Reproduce

```powershell
$FQDNCN = ("CN=$env:computername.$env:userdnsdomain").ToLower()

# Retrieve certificate information
$cert = Get-ChildItem -Recurse Cert:\LocalMachine\My\ | Where-Object { $_.Subject -match $FQDNCN }
$cert.Thumbprint

# This statement FAILS
Set-DbaNetworkCertificate -Thumbprint $cert.Thumbprint -RestartService

#This statement SUCCEEDS
Set-DbaNetworkCertificate -SqlInstance localhost -Thumbprint $cert.Thumbprint -RestartService
```

### Please confirm that you are running the most recent version of dbatools

Major  Minor  Build  Revision
-----  -----  -----  --------
2      0      4      -1      

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                         
----                           -----                                                                         
PSVersion                      5.1.20348.1850                                                                
PSEdition                      Desktop                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                       
BuildVersion                   10.0.20348.1850                                                               
CLRVersion                     4.0.30319.42000                                                               
WSManStackVersion              3.0                                                                           
PSRemotingProtocolVersion      2.3                                                                           
SerializationVersion           1.1.0.1        

### SQL Server Edition and Build number

Microsoft SQL Server 2022 (RTM-CU6) (KB5027505) - 16.0.4055.4 (X64)   Jun 29 2023 15:43:13   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Datacenter 10.0 <X64> (Build 20348: ) (Hypervisor) 

### .NET Framework Version

.NET Framework 4.8.4645.0

**Comment by andreasjordan** [comment]
I had issues with `Set-DbaNetworkCertificate -SqlInstance localhost` on a system where PS remoting was not set up as the command tried a "remote" connection to localhost. We should solve this as well. I will work on that.
