### ISSUE TITLE
Import-Module : The required module 'dbatools.library' is not loaded

### ISSUE THREAD

**Issue by msegzda** [dataplat/dbatools#9062]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

I installed dbatools with elevated powershell prompt using chocolatey. It installed without problems. However i get this error when trying to import module:

```
PS C:\Users\admin-manty> Import-Module dbatools
Import-Module : The required module 'dbatools.library' is not loaded. Load the module or remove the module from
'RequiredModules' in the file 'C:\Program Files\WindowsPowerShell\Modules\dbatools\2.0.5\dbatools.psd1'.
At line:1 char:1
+ Import-Module dbatools
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (C:\Program File...5\dbatools.psd1:String) [Import-Module], Missing
   MemberException
    + FullyQualifiedErrorId : Modules_InvalidManifest,Microsoft.PowerShell.Commands.ImportModuleCommand
```

I tried to logout and login to system. Its Windows 2012 (non R2).

Is that a bug with dbatools.psd1 module init scripting? Is reboot required?

### Steps to Reproduce

```powershell
Import-Module dbatools
```

### Please confirm that you are running the most recent version of dbatools

Version 2.0.5

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

PSVersion                      5.1.14409.1029
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1029
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

Microsoft SQL Server 2008 (SP4-GDR) (KB4057114) - 10.0.6556.0 (X64)   Dec 28 2017 15:21:01   Copyright (c) 1988-2008 Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.3 <X64> (Build 9600: ) (VM) 

### .NET Framework Version

.NET Framework 4.8.4645.0

**Comment by SQLDBAWithABeard** [comment]
Apologies @msegzda You hit a moment between version 2.0.5 being listed and then unlisted.

You should be able to import 2.0.4 which is the latest available version

**Comment by msegzda** [comment]
Its still trying to install same problematic version 2.0.5

![image](https://github.com/dataplat/dbatools/assets/130873/9f0b96a2-6876-4055-8ce4-c98a7e7ae1a8)

**Comment by SQLDBAWithABeard** [comment]
That's via choco

Please use PowerShell gallery or tell choco to use 2.0.4

**Comment by SQLDBAWithABeard** [comment]
Chocolatey have unlisted 2.0.5.

**Comment by jpomfret** [comment]
There is a PR open also to resolve the issue with the dependent module. Keep an eye on this and it should resolve your issues with 2.0+ modules.

https://github.com/pauby/ChocoPackages/pull/184

**Comment by msegzda** [comment]
Same problem with version 2.0.4; clearly something is with installer. Same problem happens on Windows server 2012 R2, Windows Server 2019 and Windows 10

![image](https://github.com/dataplat/dbatools/assets/130873/ad328101-ff91-4c7d-a29a-e868dda06429)

**Comment by wsmelton** [comment]
Please reach out to the owner of the choc package.

**Comment by SQLDBAWithABeard** [comment]
Please keep an eye on the choco pull request which will fix that or install the library from the gallery that will get you moving forward.
