### ISSUE TITLE
dbatools | Remove backup Files from Directory

### ISSUE THREAD

**Issue by AbdulRehman1982** [dataplat/dbatools#9075]
### Summarize Functionality

Hi,

I want to delete backup files as soon it restore while restoring using dbatools.

Ex: GET-DBADATABASE -SQLINSTANCE srv1 -DATABASE ADW| BACKUP-DBADATABASE -BACKUPDIRECTORY \\srv1\backup |
 RESTORE-DBADATABASE -SQLINSTANCE srv2  |Remove-Item BackupFile

I need this to keep only 1 database backup at a time in directory to restore , please help

Regards,

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by wsmelton** [comment]
Pipeline support is not planned. You can do this via `Foreach-Object` and pass the backup file path to the `Remove-Item` command.

```powershell
Restore-DbaDatabase ... | Foreach-Object {
    Remove-Item $_.BackupFile
}

**Comment by AbdulRehman1982** [comment]
Thanks a lot @wsmelton  , it is working.

Regards,
Abdul Rehman
