### ISSUE TITLE
import-module dbatools not working anymore under linux

### ISSUE THREAD

**Issue by Darknox-nl** [dataplat/dbatools#9083]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Exception: Couldn't import Microsoft.Data.SqlClient.dll | Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
import-module dbatools

### Please confirm that you are running the most recent version of dbatools

I am running dbatools 2.0.4 and dbatools.library 2023.5.5

### Other details or mentions

I haven't used dbatools for a longer period on linux. The version that did work was on 1.x.x

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

7.1.1

Currently this is the highest version available to me because of local repos

### SQL Server Edition and Build number

Not applicable, sql server is not installed on the linux host

### .NET Framework Version

.NET 5.0.2

**Comment by Darknox-nl** [comment]
Hi wsmelton,

I was afraid of such an answer. Thank you for answering so quickly.
I will notify the team that manages the repo's. Hopefully they will update them on short notice.

I shall close this issue.

Kind regards

**Comment by wsmelton** [comment]
To save you time you might go ahead and tell them to prepare for PowerShell 7.4. When it goes GA it will be the next LTS release. 😉
