### ISSUE TITLE
Get-DbaAgListener always returns all listeners of an AG

### ISSUE THREAD

**Issue by matthiaslueken** [dataplat/dbatools#9093]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

**Bugs:**
1. Specifying multiple listeners in `Get-DbaAgListener` does not work.
2. The `-Listener` parameter of  `Get-DbaAgListener` only filters the _Availbility Groups_ that have a certain listener. The function then returns _all_ listeners of the selected AGs, irrespective of the Listener parameter. 

**Context:**
The second bug usually is not an issue, since SQL Server supports adding only one listener per AG. However, multiple listeners per AG are in principle possible, when you add the cluster resource directly (see https://techcommunity.microsoft.com/t5/sql-server-blog/how-to-create-multiple-listeners-for-same-availability-group/ba-p/384028)

This is especially problematic when calling Remove-DbaAgListener, since it internally calls Get-DbaAgListener. You just deleted all listeners of your AG, even though you specified just one.

**Cause:**

1. The filtering of the AGs on line 80 of Get-DbaAgListener.ps1 does not work as intended, if `$Listener` is an array:
`$InputObject = $InputObject | Where-Object { $_.AvailabilityGroupListeners.Name -contains $Listener }`
`$_.AvailabilityGroupListeners.Name` never contains another array.

2. The second bug happens in line 85, where `$InputObject` is an array of AGs. The loop iterates over all listeners of the selected AGs:
`foreach ($aglistener in $InputObject.AvailabilityGroupListeners) {`

**Solution:**
To deal with both bugs, I suggest to directly filter the array of affacted listeners instead of taking a detour using AGs:
```powershell
...
if (Test-Bound -ParameterName Listener) {
    $AgListeners = $InputObject.AvailabilityGroupListeners | Where-Object { $Listener -contains $_.Name }
    # before: $InputObject = $InputObject | Where-Object { $_.AvailabilityGroupListeners.Name -contains $Listener }
}

$defaults = 'ComputerName', 'InstanceName', 'SqlInstance', 'AvailabilityGroup', 'Name', 'PortNumber', 'ClusterIPConfiguration'

foreach ($aglistener in $AgListeners) {
# before: foreach ($aglistener in $InputObject.AvailabilityGroupListeners) {
    $server = $aglistener.Parent.Parent
...
```

### Steps to Reproduce

```powershell
# Bug 1
# assuming there exist two listeners "ListenerA" and "ListenerB"
# will not return anything:
Get-DbaAgListener -Listener ListenerA, ListenerB
# will return the listeners:
Get-DbaAgListener -Listener ListenerA
Get-DbaAgListener -Listener ListenerB

# Bug 2
# assuming there is a single AG with listeners "ListenerA" and "ListenerB"
# will return both listeners although only one is specified:
Get-DbaAgListener -Listener ListenerA
```

### Please confirm that you are running the most recent version of dbatools

2.1.0

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      5.1.17763.592
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.592
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

Microsoft SQL Server 2022 (RTM-CU7) (KB5028743) - 16.0.4065.3 (X64)   Jul 25 2023 18:03:43   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.8.03761
Full        4.8.03761
Client      4.0.0.0

**Comment by andreasjordan** [comment]
Thanks for reporting the issue. I was able to reproduce the issue. 

Thanks for suggesting the code changes. You just don't account for the case without the parameter `-Listener`, but I will change your suggestion a bit and it should work.
