### ISSUE TITLE
Set-DbaDbCompression to do ONLINE Rebuilds

### ISSUE THREAD

**Issue by tboggiano** [dataplat/dbatools#9102]
### Summarize Functionality

The current version does all rebuilds offline, which can cause a lot of blocking; don't ask me how I found out.  

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

I think this is reasonably simple to fix, although I couldn't quite seem to verify the OnlineIndexOperation property was working on my end.  I think you can use logic for editions, as it would just convert it to OFFLINE if you wanted to throw up a warning to let people know it would be OFFLINE.

`if ($CompressionType -eq "None") {
                                        $query = "ALTER INDEX [$($index.Name)] ON $($index.Parent) REBUILD PARTITION = ALL WITH (DATA_COMPRESSION = $CompressionType, ONLINE=ON)"
                                        $Server.Query($query, $db.Name)
                                    } else {
                                        $($index.PhysicalPartitions | Where-Object { $_.PartitionNumber -eq $P.PartitionNumber }).DataCompression = $CompressionType
                                        $index.OnlineIndexOperation = true
                                        $index.Rebuild()
                                    }`

**Comment by niphlod** [comment]
hum, that query is just a fallback for seemingly a problem that was on azure targets, and it's used to "reset" compression to NONE (there's a link to it but uservoice ... disappeared, we should re-test if it's needed https://feedback.azure.com/forums/908035-sql-server/suggestions/34080112-data-compression-smo-bug).

Everything else we do with SMO, but I don't think we should switch to online by default, as it takes more space (for sure), and more time (maybe). 
If we want to "surface" an option as an opt-in, like "-PreferOnlineIndexRebuilds" then I'm good for it, and it's preeeetty simple

```
$($index.PhysicalPartitions | Where-Object { $_.PartitionNumber -eq $P.PartitionNumber }).DataCompression = $CompressionType
$index.OnlineIndexOperation = $index.IsOnlineRebuildSupported   # <-- magic bit
$index.Rebuild()
```

If we wanna do an "-ForceOnlineIndexRebuilds" that stops in its tracks as soon as `$index.IsOnlineRebuildSupported = $false` , it's another way to handle it.

@tboggiano : do you lean for one or the other ?
@potatoqualitee , @wsmelton , @andreasjordan , ideas on the matter ?

**Comment by tboggiano** [comment]
I would vote for the flag so that if you can't do online rebuilds it still would work for Standard Edition users.  I just know compressing 150 GB tables, which takes well over 20 minutes, and having a table locked for a long is not good.  Lots of things start timing and queueing up that's why Index Maintenance scripts like Ola's default to online rebuilds by default.

**Comment by tboggiano** [comment]
I would also vote we not just do this for Azure but On-prem as well.

**Comment by niphlod** [comment]
@tboggiano : if you look at #9118, it already does so for all.
