### ISSUE TITLE
Test-LastDBABackup - No exception if the files are not accessible

### ISSUE THREAD

**Issue by ksl28** [dataplat/dbatools#9103]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

We use Test-DBALastBackup quite often, but just discovered that if the -Destination SQL server does not have access to the files, it will just set the "RestoreResult" as Skipped. No matter if i put an -ErrorAction or -WarningAction to Stop.

Is this by design or shouldnt this generate a warning? If not, then how do get it to throw an error?
![image](https://github.com/dataplat/dbatools/assets/53445047/c1046671-a5f1-4602-a73f-b9cbfcfb3ab1)

### Steps to Reproduce

```powershell
$sqlConnection = Connect-DbaInstance -SqlInstance "dk1sql05"
$dest = Connect-DbaInstance -SqlInstance "dk1sql08"
try {
    Test-DbaLastBackup -SqlInstance $sqlConnection -Destination $dest -Database StackOverflow2010 -WarningAction Stop -ErrorAction stop -Verbose
}
catch {
    $_.Exception.Message
}
```

Ensure that the $dest server, does not have NTFS permissions to the folder, where the backup files are located

### Please confirm that you are running the most recent version of dbatools

2.1.1

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.3.7
PSEdition                      Core
GitCommitId                    7.3.7
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2022 (RTM-CU7) (KB5028743) - 16.0.4065.3 (X64)   Jul 25 2023 18:03:43   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 

### .NET Framework Version

.NET 7.0.11

**Comment by wsmelton** [comment]
This is by design with our module. If you review the help for the command you will find the `-EnableException` parameter. https://docs.dbatools.io/Test-DbaLastBackup

That is used for all of our commands to revert to the PowerShell native error handling. To use our commands with try/catch blocks you will need to pass that parameter to any of the commands.

```powershell
$sqlConnection = Connect-DbaInstance -SqlInstance "dk1sql05"
$dest = Connect-DbaInstance -SqlInstance "dk1sql08"
try {
    $params = @{
        SqlInstance $sqlConnection
        Destination = $dest
        Database = 'StackOverflow2010'
        WarningAction = 'Stop'
        ErrorAction = 'Stop'
        Verbose = $true
        EnableException = $true # key param to provide for try/catch blocks
    }
    Test-DbaLastBackup @params
}
catch {
    $_.Exception.Message
}
