### ISSUE TITLE
Add-DbaAgDatabase - support setting owner of database to another login

### ISSUE THREAD

**Issue by frodr1k** [dataplat/dbatools#9105]
### Summarize Functionality

When adding a database to AG's using Add-DbaAgDatabase it is executed using the sessions login, e.g. "ad\uberfredrik". The downside with this behaviour is that the secondary will get my account as owner, I need to failover to the secondary in order to be able to change ownership of the database into 'sa' (or anything else but my account). It will get nearly impossible on a high load system with multiple replicas which are sync and async. There is a big risk that we forget changing ownership otherwise. 

It's not possible to logon as SA in many enviroments (maybe blocked from login or not mixed login allowed). So trying to logon as sa to the db is not an option. (and who want's to risk having the SA account passwords in the wild).

From SSIS it's possible to in SQLCMD-mode execute the script as another login using  "EXECUTE as login = 'sa' - (See picture) that will help us a great deal when adding the databases to an AG. 

![image](https://github.com/dataplat/dbatools/assets/24543416/2fbdea64-24ef-4c1b-85bb-8a3203d29218)

Are we stuck with limitations from SMO? Can it be bypassed in a smart way? 

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

See the picture I attached in this report. That's how I achieve this from SSMS in SQLCMD mode.

**Comment by andreasjordan** [comment]
Do you use automatic or manual seeding? With automatic seeding, I can not reproduce the issue. With manual seeding I can reproduce the issue, but we may be able to solve this by changing the Restore-DbaDatabase call to use sa.

As a workaround you can do the backup-restore-part first and then use Add-DbaAgDatabase.

**Comment by andreasjordan** [comment]
Yes, I can confirm: Adding ` -ExecuteAs sa` to the Restore-DbaDatabase call inside of Add-DbaAgDatabase solves the issue. I will think of a suitable name for a new parameter for Add-DbaAgDatabase. Or we can just get the owner of the source database and use this. This would be the best as then the database has the same owner on all replicas. What to you think @potatoqualitee ? I can open a pull request for that later.

**Comment by wsmelton** [comment]
For clarity with maintaining it parameter should match the name used by the nested function call, `-ExecuteAs`. Help can denote that it is simply passed to the Restore command to set the owner.

Some scenarios may require a different user own the database so I would just let them pass in whatever value they want. If the Restore command does not have any filter or requirements around the user, parent call should not either.

**Comment by frodr1k** [comment]
> Do you use automatic or manual seeding? With automatic seeding, I can not reproduce the issue. With manual seeding I can reproduce the issue, but we may be able to solve this by changing the Restore-DbaDatabase call to use sa.
> 
> As a workaround you can do the backup-restore-part first and then use Add-DbaAgDatabase.

I use default settings withint Dbatools when doing it. So honestly I don't know.

**Comment by frodr1k** [comment]
> For clarity with maintaining it parameter should match the name used by the nested function call, `-ExecuteAs`. Help can denote that it is simply passed to the Restore command to set the owner.
> 
> Some scenarios may require a different user own the database so I would just let them pass in whatever value they want. If the Restore command does not have any filter or requirements around the user, parent call should not either.



> Yes, I can confirm: Adding ` -ExecuteAs sa` to the Restore-DbaDatabase call inside of Add-DbaAgDatabase solves the issue. I will think of a suitable name for a new parameter for Add-DbaAgDatabase. Or we can just get the owner of the source database and use this. This would be the best as then the database has the same owner on all replicas. What to you think @potatoqualitee ? I can open a pull request for that later.

Thank you for putting effort into this one. It will definitly make life easier for many of us!
