### ISSUE TITLE
`Remove-DbaDatabaseSafely` - Doesn't `Stop-Function` If Backup Fails

### ISSUE THREAD

**Issue by mattcargile** [dataplat/dbatools#9106]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

```powershell
WARNING: [10:07:13][Backup-DbaDatabase] Backup Failed | Microsoft.Data.SqlClient.SqlError: Cannot open backup device '\\server\bck\Golden\dev\DB_Final_Before_Drop_20231003_100711.bak'. Operating system error 5(Access is denied.).

ComputerName : dev
InstanceName : MSSQLSERVER
SqlInstance  : dev
Name         : Rationalisation
ID           : 100
CategoryType : LocalJob
JobCount     : 0

WARNING: [10:07:17][Restore-DbaDatabase] No backups passed through.
 This could mean the SQL instance cannot see the referenced files, the file's headers could not be read or some other issue
WARNING: [10:07:29][Remove-DbaDatabaseSafely] FAILED : Restore Job Rationalised Database Restore Script for DB failed on dev- aborting routine for DB.
WARNING: [10:07:29][Remove-DbaDatabaseSafely] Check the Agent Job History on dev - if you have SSMS2016 July release or later.
WARNING: [10:07:29][Remove-DbaDatabaseSafely] Get-DbaAgentJobHistory -SqlInstance dev -Job 'Rationalised Database Restore Script for DB'.
```

### Steps to Reproduce

```powershell
Remove-DbaDatabaseSafely -SqlInstance dev -Database db -BackupFolder \\server\bck\Golden\dev\ 
```

### Please confirm that you are running the most recent version of dbatools

```pwsh
2.0.4
# This command appears to not have been changed in 9 months.
```

### Other details or mentions

Even though `Test-DbaPath` is used , the backup operation can still fail for _Access Denied_. 

https://github.com/dataplat/dbatools/blob/5d27f6094e5cd14bb571eebbeff78b45dabaef89/public/Remove-DbaDatabaseSafely.ps1#L193

When this happens, the user is left with restoring the database from backup as it is lost. Maybe some change in the below section or maybe a change in `Test-DbaPath`?

https://github.com/dataplat/dbatools/blob/5d27f6094e5cd14bb571eebbeff78b45dabaef89/public/Remove-DbaDatabaseSafely.ps1#L336-L346

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

```sql
Microsoft SQL Server 2019 (RTM-CU14) (KB5007182) - 15.0.4188.2 (X64) 
	Nov  3 2021 19:19:51 
	Copyright (C) 2019 Microsoft Corporation
	Standard Edition (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)
```

### .NET Framework Version

```pwsh
.NET 7.0.9
```

**Comment by andreasjordan** [comment]
There are some issues with the usage of `Stop-Function`inside this command. All calls to `Stop-Function` need one of the following:
* Parameter `-Continue` inside of a loop to end the current run and continue with the next
* A `return` in the next line to end the command in case the user has not used `-EnableException`

I have seen more than one place that needs to be fixed here. I will try to open a pull request in the next days.
As a workaround, please use `-EnableException` to immediatly raise the error and stop the function.
