### ISSUE TITLE
Copy-DbaDbTableData fails when filegroup for target table doesn't exist in destination

### ISSUE THREAD

**Issue by ben-thul** [dataplat/dbatools#9121]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

While helping a new user on the community slack, it seems that if the table being copied from the source is in a filegroup that does not exist at the destination, the command errors out.

> WARNING: [14:39:13][Copy-DbaDbTableData] Unable to determine destination table: dbo.Password | Invalid filegroup 'DATA' specified.

### Steps to Reproduce

```sql
use AdventureWorks2019;
alter database current add filegroup [DATA];
alter database current add file (
	name = 'DATA_01', 
	filename = 'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AdventureWorks2019_DATA_01.ndf', 
	size = 5Mb, 
	filegrowth = 5mb
) to filegroup [DATA];

/* move table to DATA FG */
create unique clustered index [PK_Password_BusinessEntityID] on [Person].[Password]
(
	[BusinessEntityID] ASC
) with (
	drop_existing = on 
) on [DATA]
GO
```

```
PS > $copyDbaDbTableDataSplat = @{
SqlInstance = '.'
Database = 'AdventureWorks2019'
Table = '[Person].[Password]'
Destination = '.'
DestinationDatabase = 'tempdb'
DestinationTable = 'dbo.Password'
AutoCreateTable = $true
};
Copy-DbaDbTableData @copyDbaDbTableDataSplat;
```

### Please confirm that you are running the most recent version of dbatools

2.1.2

### Other details or mentions

After some discussion with @niphlod in slack, the proposal was to add a new parameter that says "create the table at the destination on the default filegroup for that database".

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      7.2.14
PSEdition                      Core
GitCommitId                    7.2.14
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU18-GDR) (KB5021124) - 15.0.4280.7 (X64)   Jan 23 2023 12:37:13   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 22621: ) (Hypervisor) 

### .NET Framework Version

.NET 6.0.22

**Comment by wsmelton** [comment]
Reviewing the linked PR that is adding functionality that will not address the issue at hand unless users are aware the switch was added.

If current functionality of the command is to use a filegroup with the same name, then if that name does not exist we need to spit a warning out and cancel the copy operation.

Then a second issue can be created for tracking adding the feature to specify the filegroup you want to use (whether we allow hashtable for custom mapping or just string input for the name). If nothing is provided **then** we fall back to the default file group.

**Comment by ben-thul** [comment]
> ... will not address the issue at hand unless users are aware the switch was added.

Is that not a tautology? That is, *all* functionality is changed in some way by what parameters are passed (which implies awareness of the same). In what way is this different?

> then if that name does not exist we need to spit a warning out and cancel the copy operation.

That is the current behavior. See section "What error did you receive?" in the bug report.

In a conversation with @niphlod on 2023-09-25 around 07:10 PST on slack, it seemed that he wanted the current default behavior of carrying over the filegroup from the source database. In cases where that is not desirable (and, for whatever reason, the user doesn't want to pre-stage the table themselves), I felt that it was a reasonable compromise to use the target database's default filegroup as that's where a new table would be created that doesn't explicitly specify a filegroup.

If you'd like me to scrub this approach entirely, I still think it's worthwhile to give current users a path for table autovivification in cases where the source and target databases don't have the same filegroups. Having looked at the code, I think that's tricky but probably doable. But before embarking on that it's worthwhile considering the edge cases you touched on in your comment above as well as what the default behavior should be.

Let me know how you'd like to proceed.

**Comment by wsmelton** [comment]
Providing a switch parameter won't fix that issue. If no one provides it, it defaults to false which means the script object property will be set to false as well. What does that benefit this issue?
