### ISSUE TITLE
Get-DbaBuildReference -LatestUpdateAvailable

### ISSUE THREAD

**Issue by ksl28** [dataplat/dbatools#9133]
### Summarize Functionality

I love the functionality of Get-DbaBuildReference, but it would be really nice query what the newest cumulative update is for a major version (2019,2022, etc) 
It seems that the info is available and updated using the -Update parameter - but its not possible to query without reading that file.

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by niphlod** [comment]
@ksl28 : unfortunately that file is necessary because there's no other (easy) place to look for . I'm intrigued though, are you asking for something among the lines of "I don't want to "remember" to pass -Update each time to be sure to have the latest info available" and everything lines up" or am I missing something (e.g. some other missing feature you'd like to have) ?

**Comment by ksl28** [comment]
@niphlod - The file locally makes perfect sense, and i really like the idea that even if i run a older version of dbatools, i can still get the updated list of updates.

I am basically looking for a way to list what the latest available CU is for a given major version - just like the CULevel is present, if the CU is installed.
![image](https://github.com/dataplat/dbatools/assets/53445047/7077671b-df8d-4c44-8985-fb6ef24816f4)


Its awesome that we can list what the current CULevel is for a SQL Instance, but once we inform the application owners of the current CU level their next question is always "What is the newest CU?" - and then i have to go to https://sqlserverbuilds.blogspot.com/ and look it up. Would be awesome, if that info could be shown in the Get-DbaBuildReference with an optional parameter.

**Comment by ksl28** [comment]
I regularly use the datasplat.github.io/builds page, but for the ease of use, i would prefer to have it in the my pwsh console :) 
But the Test-DbaBuild could work - i came up with this:
```
$(Test-DbaBuild  -Update -Build "16.0.1000" -MaxBehind "0CU").CUTarget
```

That pulls a list online and gives me the newest CUTarget to aim for 😄 

This suits my needs.

**Comment by niphlod** [comment]
ok, perfect.
