### ISSUE TITLE
Test-DbaInstanceName: Add support for TrustServerCertificate

### ISSUE THREAD

**Issue by Xyaran** [dataplat/dbatools#9140]
### Summarize Functionality

With the latests changes setting the encrypt to $true, I need to use the command with -TrustServerCertificate.

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

Connect-DbaInstance supports the flag, it would be similar to it.

**Comment by wsmelton** [comment]
Please reference #8883 

TL;DR we do not want to start adding parameters for connection level settings to all the functions. Primary reason we have the `Connect-DbaInstance` is for that to be done once and then passed into each command via `-SqlInstance` parameter.
