### ISSUE TITLE
Restore-DbaDatabase still executing even though the bak file is in use.

### ISSUE THREAD

**Issue by ryanjamesocampo** [dataplat/dbatools#9166]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Data Drive letter: R
Destination Data Directory: \\FLTMELESQL02\R$\SatBC14
Destination Log Directory: \\FLTMELESQL02\P$\SatBC14
WARNING: [11:23:56][Get-DbaBackupInformation] Failure on FLTMELESQL02 | Cannot open backup device 
'\\fltsqlbackup.file.core.windows.net\sqlbackup\FLTMELESQL01\ProdBC14\DIFF\FLTMELESQL01_ProdBC14_DIFF_20231114_112051.b
ak'. Operating system error 32(The process cannot access the file because it is being used by another process.).

RESTORE HEADERONLY is terminating abnormally.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
Restore-DbaDatabase -SqlInstance $Server -DatabaseName $Database -Path $SourceBackupPath -MaintenanceSolutionBackup -DestinationDataDirectory $DestinationDataDirectory -DestinationLogDirectory $DestinationLogDirectory -WithReplace -ReplaceDbNameInFile -NoRecovery -RestoreTime $RestoreDate -EnableException -SqlCredential $Credential -OutVariable resultNoRecovery

### Please confirm that you are running the most recent version of dbatools

I'm running version 2.0.2
![dba](https://github.com/dataplat/dbatools/assets/135186683/2229c701-4df3-4333-8f4e-e90b508bab84)

### Other details or mentions

So we have some script to back up the database in an hourly period starts at the beginning of the hour and it will take like 20-30mins to execute the back up. (this is working fine)

However, when we execute a Restore-DbaDatabase lets say it falls on the same window time the backup schedule above is executed.
Then it picks up the latest file, which is still on use(or the job on the back up is not yet done)

Is there a way or syntax to pick up the bak file which is an hour ago? This is to be sure that the file generated was completed and the backup process is done before executing the Restore-DbaDatabase.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      5.1.17763.3770
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.3770
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM-CU18-GDR) (KB5021124) - 15.0.4280.7 (X64)   Jan 23 2023 12:37:13   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

PSChildName                      Version
-----------                      -------
v2.0.50727                       2.0.50727.4927
v3.0                             3.0.30729.4926
Windows Communication Foundation 3.0.4506.4926
Windows Presentation Foundation  3.0.6920.4902
v3.5                             3.5.30729.4926
Client                           4.7.03190
Full                             4.7.03190
Client                           4.0.0.0

**Comment by andreasjordan** [comment]
Have a look at https://github.com/dataplat/dbatools/issues/7921.
