### ISSUE TITLE
Failed to decrypt credentials on ADMIN:infra-ad-mgmt.domain.com | You cannot call a method on a null-valued expression

### ISSUE THREAD

**Issue by thejammyproject** [dataplat/dbatools#9175]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

VERBOSE: [15:25:04][Copy-DbaCredential] We will try to use a dedicated admin connection.
DEBUG: 5477 | [15:25:04][Copy-DbaCredential] We will try to use a dedicated admin connection.
DEBUG: 2920 | [15:25:04][Connect-DbaInstance] Starting process block
DEBUG: 2931 | [15:25:04][Connect-DbaInstance] Immediately checking for Azure
DEBUG: 2824 | [15:25:04][Test-Azure] Test for Azure is negative
DEBUG: 2938 | [15:25:04][Connect-DbaInstance] Starting loop for 'infra-ad-mgmt.domain.com': ComputerName = 'infra-ad-mgmt.domain.com', InstanceName = 'MSSQLSERVER', IsLocalHost = 'True', Type = 'Default'
VERBOSE: [15:25:04][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
DEBUG: 2962 | [15:25:04][Connect-DbaInstance] String is passed in, will build server object from instance object and other parameters, do some checks and then return the server object
DEBUG: 2988 | [15:25:04][Connect-DbaInstance] Parameter DedicatedAdminConnection is used, so serverName will be changed and NonPooledConnection will be set.
DEBUG: 2824 | [15:25:04][Test-Azure] Test for Azure is negative
VERBOSE: [15:25:04][Connect-DbaInstance] authentication method is 'local integrated'
DEBUG: 3104 | [15:25:04][Connect-DbaInstance] authentication method is 'local integrated'
DEBUG: 3143 | [15:25:04][Connect-DbaInstance] ApplicationName will be set to 'dbatools PowerShell module - dbatools.io'
DEBUG: 3175 | [15:25:04][Connect-DbaInstance] ConnectionTimeout will be set to '15'
DEBUG: 3187 | [15:25:04][Connect-DbaInstance] EncryptConnection will be set to 'False'
DEBUG: 3207 | [15:25:04][Connect-DbaInstance] PacketSize will be set to '4096'
DEBUG: 3223 | [15:25:04][Connect-DbaInstance] Pooled will be set to 'False'
DEBUG: 3251 | [15:25:04][Connect-DbaInstance] TrustServerCertificate will be set to 'True'
DEBUG: 3293 | [15:25:04][Connect-DbaInstance] Building ServerConnection from SqlConnectionInfo
DEBUG: 3295 | [15:25:04][Connect-DbaInstance] ServerConnection was built
DEBUG: 3313 | [15:25:04][Connect-DbaInstance] Building Server from ServerConnection
DEBUG: 3315 | [15:25:04][Connect-DbaInstance] Server was built
DEBUG: 3334 | [15:25:04][Connect-DbaInstance] Setting ConnectionContext.StatementTimeout to '0'
DEBUG: 3432 | [15:25:19][Connect-DbaInstance] We return the server object
VERBOSE: [15:25:19][Copy-DbaCredential] Decrypting all Credential logins and passwords on ADMIN:infra-ad-mgmt.domain.com
DEBUG: 5493 | [15:25:19][Copy-DbaCredential] Decrypting all Credential logins and passwords on ADMIN:infra-ad-mgmt.domain.com
VERBOSE: [15:25:19][Get-DecryptedObject] Querying service master key
DEBUG: 90811 | [15:25:19][Get-DecryptedObject] Querying service master key
DEBUG: [15:25:49][Get-DecryptedObject] Can't execute query on ADMIN:infra-ad-mgmt.domain.com | You cannot call a method on a null-valued expression.

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): A
WARNING: [15:25:58][Copy-DbaCredential] Failed to decrypt credentials on ADMIN:infra-ad-mgmt.domain.com | You cannot call a method on a null-valued expression.
DEBUG: [15:25:58][Copy-DbaCredential] Failed to decrypt credentials on ADMIN:infra-ad-mgmt.domain.com | You cannot call a method on a null-valued expression.

### Steps to Reproduce

```powershell
$servers ="ia-i-sql-01.domain.com", "ia-i-sql-02.domain.com"
$sourceServer = "infra-ad-mgmt.domain.com"
$users = "copy-test1", "copy-test2"

foreach ($user in $users) {
    Copy-DbaCredential -Source $sourceServer -Destination $servers -Name $user -Force -Verbose -Debug
}

```

### Please confirm that you are running the most recent version of dbatools

Yes on the latest version, powershell on both nodes is 5.1

### Other details or mentions

- I am full domain, local and sysadmin.
- Ports 5986 are open between the nodes trying to copy creds to/from, same with Windows Firewall.
- Running from elevated powershell.
- Copy databases works fine

Ran the following on both nodes and it came back Blank:

PS C:\Windows\system32> Get-DbatoolsError
PS C:\Windows\system32>

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

5.1.17763.5122

Same across all nodes.

### SQL Server Edition and Build number

Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

Same across all nodes.

### .NET Framework Version

PS C:\Windows\system32> Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -Recurse | Get-ItemProperty -Name version -EA 0 | Where PSChildName -Match '^(?!S)\p{L}' | Select PSChildName, version

PSChildName Version
----------- -------
Client      4.8.03761
Full        4.8.03761
Client      4.0.0.0

Same across all nodes.

**Comment by thejammyproject** [comment]
> Hey @thejammyproject - thanks for the issue. (One side note - you have included server names above in your error message, not sure if that's a problem for you - but I would obfuscate them for safety anyway)
> 
> Can you confirm if the objects you are trying to copy are users or credentials - you've named the variable users, which made me wonder? Also the error is `You cannot call a method on a null-valued expression.` which makes me think it couldn't find credentials with that name.
> 
> ```powershell
> $users = "copy-test1", "copy-test2"
> ```
> 
> [Copy-DbaCredential](https://docs.dbatools.io/Copy-DbaCredential.html) is made for copying [credentials](https://learn.microsoft.com/en-us/sql/relational-databases/security/authentication-access/credentials-database-engine?view=sql-server-ver16) around.
> 
> If you're trying to copy Logins have a look at [Copy-DbaLogin](https://docs.dbatools.io/Copy-DbaLogin.html).
> 
> Let me know if this helps.

Oh deary me, it never crossed my mind at all. Yes, these are SQL logins and the Copy-DbaLogin is exactly what I should be using and I do remember now, as it was the dba assisting me that told me about that one. Newbie error, it's my 1st time using dbatools. I will give it a shot tomorrow, thank you and sorry for wasting any time.

And thank you for the safety advice. While its not a public network, better to be safe than sorry.

**Comment by jpomfret** [comment]
No problem at all, I'll close this issue but if you need any help there are plenty of dbatools folks around especially in the slack channel (dbatools.io/slack) if you need some help.
