### ISSUE TITLE
Export-DbaLogin - Only export enabled users

### ISSUE THREAD

**Issue by auchri** [dataplat/dbatools#9176]
### Summarize Functionality

It would be helpful if the command "Export-DbaLogin" has a parameter which exports only enabled users.
We currently migrate databases to a new server and on the old servers there are a lots of disabled users which we do not want do import to the new server.

### Is there a command that is similiar or close to what you are looking for?

Yes

**Comment by wsmelton** [comment]
Please see example 9 of the documentation [Export-DbaLogin](https://docs.dbatools.io/Export-DbaLogin). `Get-DbaLogin` provides the means to accomplish what you are requesting by pipling that filtered list to the Export command.
