### ISSUE TITLE
Get-DbaDatabase return SizeMB no value

### ISSUE THREAD

**Issue by OscarLai** [dataplat/dbatools#9187]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

![image](https://github.com/dataplat/dbatools/assets/8155373/fb33f05c-8e79-4fa6-9c48-e142486e5530)

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

### Please confirm that you are running the most recent version of dbatools

2.1.5

### What PowerShell host was used when producing this error

Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                 
----                           -----                                                                                                                                 
PSVersion                      5.1.19041.3693                                                                                                                        
PSEdition                      Desktop                                                                                                                               
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                               
BuildVersion                   10.0.19041.3693                                                                                                                       
CLRVersion                     4.0.30319.42000                                                                                                                       
WSManStackVersion              3.0                                                                                                                                   
PSRemotingProtocolVersion      2.3                                                                                                                                   
SerializationVersion           1.1.0.1                                                                                                                               

### SQL Server Edition and Build number

Microsoft SQL Server 2008 (SP1) - 10.0.2531.0 (X64)   Mar 29 2009 10:11:52   Copyright (c) 1988-2008 Microsoft Corporation  Enterprise Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) 

### .NET Framework Version

.NET Framework 4.8.9181.0

**Comment by wsmelton** [comment]
Can you perform that same example in an external PowerShell process? (Outside of the PowerShell ISE)

**Comment by OscarLai** [comment]
![image](https://github.com/dataplat/dbatools/assets/8155373/c89e1bfd-b159-4837-befd-244861f09369)

**Comment by andreasjordan** [comment]
To dig deeper, you could save the result for one database to a variable and have a look at the properties. "SizeMB" is just an alias for "Size" which is part of the SMO. So the command does nothing with the value and if there is a bug it is likely inside of the SMO. Do you have a newer version of SQL Server to test this with?

**Comment by wsmelton** [comment]
It can also just be that SQL Server is not populating the property, not directly related to SMO. You may need to run [update usage](https://learn.microsoft.com/en-us/sql/t-sql/database-console-commands/dbcc-updateusage-transact-sql) on your instance's databases to cause it to be populated.

**Comment by andreasjordan** [comment]
Will close this now, but can reopen if needed.

**Comment by ReeceGoding** [comment]
Just seen this myself on 2.7.3. Can we re-open?

**Comment by potatoqualitee** [comment]
@ReeceGoding did you experience it in the ISE or console? We do not support the ISE because of issues like this.

**Comment by ReeceGoding** [comment]
@potatoqualitee Console. PowerShell 7.

**Comment by potatoqualitee** [comment]
@claude can u research why this sometimes doesnt populate? and fill it in with tsql values, ensuring the tsql works for all versions of sql server
