### ISSUE TITLE
add a CU in dbatools-buildref-index.json when a CVE is being released

### ISSUE THREAD

**Issue by pluim003** [dataplat/dbatools#9212]
### Summarize Functionality

In dbatools-buildref-index.json for f.e. it shows:

        {
            "CU": "CU8",
            "Version": "16.0.4075",
            "KBList": "5029666"
        },
        {
            "Version": "16.0.4080",
            "KBList": "5029503"
        },

The 16.0.4080 was a CVE over CU8.

The same happens with CU10. We run a script to patch instances to the latest CU. In this case CU10 was the latest and the CVE came out. Added the data manually to dbatools-buildref-index.json in my fork and copied the file over to the server where I want to run my script.

So I kept the line empty but then it didn't work. By adding the entry with CU named CU10-CVE my script didn't work as well so what I came up with was:

        {
            "CU": "CU9",
            "Version": "16.0.4085",
            "KBList": "5030731"
        },
        {
            "CU": "CU10-OLD",
            "Version": "16.0.4095",
            "KBList": "5031778"
        },
        {
            "CU": "CU10",
            "Version": "16.0.4100",
            "KBList": "5033592"
        }

with this method I can apply the CU with the following script:

```powershell
# SQL_Patching_StandAlone.ps1 v2024.01.11
#
#
# script om een standalone server te patchen naar het meest-recente patchlevel.
# zorg er voor dat dit script up-to-date is met laatste patchlevels.
# Het script is ook bruikbaar voor clusters maar dan zal er in geval van actieve node een automatische failover plaatsvinden
#
# Start het script middels het commando: SQL_Patching_StandAlone.ps1 <servernaam> 
# waarbij je voor <servernaam> de servernaam invult, bijvoorbeeld server0123.
#
# Nog te doen: de cu-informatie extern opslaan en administreren zodat je niet dit script hoeft aan te passen.
#
# Versiehistorie:
#
# 2023.11.27 - Initiële versie
# 2023.12.22 - Upgrade naar SQL2019 CU24
# 2024.01.11 - Optie FORCED toegevoegd als 2e parameter wordt ingevuld.
 
$servername = $args[0]
$forced = $args[1]

if (!$servername) 
{ 
  "Geef servernaam op, bv. server0123" 
}
else
{


# eerst kijken we wat de sql-versie is van de te patchen server

$namelevel = test-dbabuild -sqlinstance $servername -update -maxbehind 0CU | select  namelevel -expandproperty namelevel

if ( $namelevel -eq "2016" ) { $cutarget = "CU9" }
elseif ( $namelevel -eq "2017" ) { $cutarget = "CU31" }
elseif ( $namelevel -eq "2019" ) { $cutarget = "CU24" }
elseif ( $namelevel -eq "2022" ) { $cutarget = "CU10" }
else { 
  "SQLServer $namelevel is geen ondersteunde SQL-versie. Exiting"
   exit 123
  }

# nu bepalen welke cu op de server actief is

# als 2e parameter is ingevuld gaan we uit van een geforceerde patch, want bij een CVE blijft CU gelijk

if ( !$forced ) 
{
   $culevel = test-dbabuild -sqlinstance $servername -update -maxbehind 0CU | select  culevel -expandproperty culevel
} 
else 
{ 
   $culevel = "FORCED" 
}

if ($culevel -ne $cutarget)

{
  "Upgrade SQLInstance op $servername van $culevel naar $cutarget" 

   $CurrentUser = 'domain\' + [Environment]::UserName
   $UserName = Get-Credential -UserName $CurrentUser -Message 'Enter your password to start the update, this enables access to the network filepath and SQL Server host'

   $Path = "\\path_to\Microsoft\SQL Server\SQL$namelevel\CU\"
   $ExtractPath = "C:\temp\"

   $VersionCU = "$namelevelRTM$cutarget" #Updates $namelevel RTM versions to $cutarget
   Update-DbaInstance -ComputerName $Servername -Version $VersionCU -Path $Path -Credential $UserName -Restart -Confirm:$false -ExtractPath $ExtractPath -Verbose
}
else
{ "Server $servername zit op het laatste patchlevel $culevel."
}

} 
```

I know there is a disadvantage with this script as it needs to be manually modified every time.

### Is there a command that is similiar or close to what you are looking for?

Yes

### Technical Details

See the story in the 'Summarize Functionality'-section.

**Comment by niphlod** [comment]
I *think* one thing is wanting instances to be patched up to the latest CU and one is patching on the very latest. 
IS the problem on get-dbabuild's side or update-dbainstance ?

**Comment by pluim003** [comment]
Can't really tell as my powershell-script complains. It's a framework around update-dbainstance. Also compliancyscript-check checks on CU's. And I don't use get-dbabuild or it must be used 'under water' by update-dbainstance.
Unfortunately those CVE's are being released without a CU-number.

**Comment by niphlod** [comment]
you're using test-dbabuild, though .... the question here is : what does dbatools need to suit your needs ?
you're using `-maxbehind 0CU`, not `-latest`, so you get back the latest CU, not the latest build (in this case, the CVE).

**Comment by niphlod** [comment]
if so, remember to close the issue/discussion if there are no issues.

**Comment by pluim003** [comment]
I need to test further, but in case no issues I will close this ofcourse. Noticed that CU11 has been released.

**Comment by pluim003** [comment]
By modifying the json-file and adding CU11 the upgrade went like a charm. Still finding something that we can store credentials (encrypted) and read them so we can patch unattended.

**Comment by pluim003** [comment]
I'll close this for now. If needed I open a new issue.
