### ISSUE TITLE
Invoke-DbaQuery - Example 9, Output from New-DbaSqlParameter not used

### ISSUE THREAD

**Issue by whoisbruce** [dataplat/dbatools#9222]
The last two lines read
PS C:\> New-DbaSqlParameter -SqlDbType structured -Value $inparamAsDataTable -TypeName 'dbatools_tabletype'
PS C:\> Invoke-DbaQuery -SqlInstance localhost -Database master -CommandType StoredProcedure -Query my_proc -SqlParameter $inparamAsDataTable

I think it should be more like 
PS C:\> _$inparamAsSQLParameter =_ New-DbaSqlParameter -SqlDbType structured -Value $inparamAsDataTable -TypeName 'dbatools_tabletype'
PS C:\> Invoke-DbaQuery -SqlInstance localhost -Database master -CommandType StoredProcedure -Query my_proc -SqlParameter _$inparamAsSQLParameter_

**Comment by niphlod** [comment]
hey @whoisbruce , thanks for the report. There's another pending PR on invoke-dbaquery so as soon as that is merged I'll push a new PR to fix the documentation issue.
