### ISSUE TITLE
update-dbainstance looking for a old build number when the newer version do exists in the dbatools-buildref-index.json

### ISSUE THREAD

**Issue by GabrielMartinezArg** [dataplat/dbatools#9239]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

When I try to deploy the update 13.0.6435.1 for SQL Server 2016 I get this warning message: "Warning: [21:49:24][Get-SqlInstanceUpdate] 13.0.6430 on computer [XXX.bcofsa.com.ar] is already the latest available."__

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

### Please confirm that you are running the most recent version of dbatools

ModuleType Version    Name                                ExportedCommands                                                                                                                  
---------- -------    ----                                ----------------                                                                                                                  
Script     2.1.6      dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, Add-DbaAgListener...}                                                   

### Other details or mentions

I have update the dbatools-buildref-index.json file, actually I can see the last update for SQL Server 2016 listed on it. 

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe), Windows PowerShell ISE (powershell_ise.exe)

### PowerShell Host Version

[32;1mName                           Value[0m
[32;1m----                           -----[0m
PSVersion                      7.2.4
PSEdition                      Core
GitCommitId                    7.2.4
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2016 (SP3-GDR) (KB5021129) - 13.0.6430.49 (X64)   Jan 22 2023 17:38:22   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

### .NET Framework Version

.NET 6.0.5

**Comment by andreasjordan** [comment]
There are multiple places for the dbatools-buildref-index.json file. You can use `Update-DbaBuildReference` with `-LocalFile` to import the newest file and place it in the correct location.

**Comment by andreasjordan** [comment]
Hi @GabrielMartinezArg - can we close this issue?

**Comment by andreasjordan** [comment]
Will close this now, but can reopen if needed.
