### ISSUE TITLE
Get-DbaRegServer - SSMS upgraded from 19.x to 20.1, reading "old" RegisteredServersStore

### ISSUE THREAD

**Issue by MartinBruegger** [dataplat/dbatools#9347]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Had an SSMS version 19.x installed with some registered servers, migrated to SSMS 20.1, deleted 2 registered servers - but Get-DbaRegServer still lists those 2 deleted servers.
**_$file = [Microsoft.SqlServer.Management.RegisteredServers.RegisteredServersStore]::LocalFileStore.DomainInstanceName_** --> points to file **_RegSrvr16.xml_** but SSMS 20.1 seems to use file **_RegSrvr17.xml_**
Had to manually update RegSrvr16.xml to get a correct list
Do not see how to fix Get-DbaRegServer.

Regards, Martin

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```

### Please confirm that you are running the most recent version of dbatools

Get-InstalledModule -name dbatools

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2.1.14     dbatools                            PSGallery            The community module that enables SQL Server Pros to automate database development and server administration

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                   
----                           -----                                                                                                                                                                   
PSVersion                      5.1.20348.2400                                                                                                                                                          
PSEdition                      Desktop                                                                                                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                 
BuildVersion                   10.0.20348.2400                                                                                                                                                         
CLRVersion                     4.0.30319.42000                                                                                                                                                         
WSManStackVersion              3.0                                                                                                                                                                     
PSRemotingProtocolVersion      2.3                                                                                                                                                                     
SerializationVersion           1.1.0.1                                                                                                                                                                 

### SQL Server Edition and Build number

Microsoft SQL Server 2022 (RTM-CU12) (KB5033663) - 16.0.4115.5 (X64)   Mar  4 2024 08:56:10   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Standard 10.0 <X64> (Build 20348: ) (Hypervisor) 

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.8.04161
Full        4.8.04161
Client      4.0.0.0

**Comment by ReeceGoding** [comment]
@potatoqualitee I think we need to reopen this. I thought that I had it fixed, but the bug came back after I cleared out some old RegSrvr XML files on my machine. I think the actual bug is in `[Microsoft.SqlServer.Management.RegisteredServers.RegisteredServersStore]::LocalFileStore.DomainInstanceName`, but I don't have the slightest clue how to fix that.

**Comment by niphlod** [comment]
this should be fixed if we bump the dbatools library. Seemingly the RegSrvr17.xml is already handled there https://github.com/microsoft/sqlmanagementobjects/blob/eb6c5fcb40ea16dc2bff8a200bb787eac129a122/src/Microsoft/SqlServer/Management/RegisteredServers/RegisteredServersStore.cs#L1198 .

It's taking a bit but we're getting there https://github.com/dataplat/dbatools.library/pull/15
