### ISSUE TITLE
Azure Automation Account - issue loading the module

### ISSUE THREAD

**Issue by Xeno468** [dataplat/dbatools#9363]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?
```
Connect-DbaInstance: Line | 9 | $Server = Connect-DbaInstance -SqlInstance $ConnString -DisableEx … | ~~~~~~~~~~~~~~~~~~~ | The 'Connect-DbaInstance' command was found in the module 'dbatools', but the module could not be loaded. For more information, run 'Import-Module dbatools'.
```
### Steps to Reproduce

I attempted to reduce possible points of failure by creating this simple piece of code, but I still encountered the error.

Here's the code:
```
$ConnString = "Data Source=TCP:[AZURE Database],1433;Database=[dbname];User ID=[Username];Password=[Password];Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;" 
$Server = Connect-DbaInstance -SqlInstance $ConnString  -ConnectTimeout 30
Write-Output  $Server
```
Additionally, I tried to manually import the module using this command: Import-Module dbatools. However, I received the following error:
```
Import-Module dbatools | ~~~~~~~~~~~~~~~~~~~~~~ | Couldn't import dbatools library | Could not load file or assembly 'System.Management.Automation, Version=7.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
```
thanks 

### Please confirm that you are running the most recent version of dbatools

Azure Automation Powershell 7.2
dbatools version 2.1.16
dbatools library 2024.4.12

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.2.0
PSEdition                      Core
GitCommitId                    7.2.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

NA

### .NET Framework Version

PSChildName Version
----------- -------
Client      4.7.03190

Full        4.7.03190

Client      4.0.0.0

**Comment by niphlod** [comment]
hi @Xeno468 , I have various degrees of failures on azure automation myself. Can you try running a 5.1 host and see if it has the same kind of errors ? In 7.2, even the "official" module from MS doesn't work https://github.com/microsoft/SQLServerPSModule/issues/72

**Comment by potatoqualitee** [comment]
Can you pls tell me how to to test this? I got it to import but dont know how to do anything else. I only use azure automation to see if dbatools can load from the Modules panel.

![image](https://github.com/dataplat/dbatools/assets/8278033/36ff63ee-dcaa-424c-a870-70025ef045ad)

**Comment by niphlod** [comment]
import goes through always, if you try to run a "simple" connect-dbainstance it *may* reveal breaking, as using invoke-sqlcmd does for SQLServerPS .

**Comment by potatoqualitee** [comment]
Thank you! Gonna try now.

**Comment by potatoqualitee** [comment]
You can try now, though I'm unsure if the library is too big. I change a whole bunch of the underlying depedencies.
