### ISSUE TITLE
Invoke-DbaQuery's parameter list is oddly formatted. This appears to break the online docs and Get-Help.

### ISSUE THREAD

**Issue by ReeceGoding** [dataplat/dbatools#9367]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

No error. The issue is visual. The website shows it best. The highlighted items are missing both brackets and line breaks.
![image](https://github.com/dataplat/dbatools/assets/67124261/029c2eb1-11b3-4bdf-a6a4-5bbee20b92e1)

Similarly, the documentation that you see when you run `Get-Help Invoke-DbaQuery -full` is missing the brackets around the parameters that are missing both brackets and line breaks in the above screenshot.

### Steps to Reproduce

Check the Syntax section at either
```powershell
Get-Help Invoke-DbaQuery -full`
```
or https://docs.dbatools.io/Invoke-DbaQuery.html

### Please confirm that you are running the most recent version of dbatools

Yes. 2.1.16.

### Other details or mentions

I see nothing obviously wrong in master/public/Invoke-DbaQuery.ps1, unless it's getting confused by the reference to "[MyTable]"? Perhaps I am looking in the wrong file?

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

I would be stunned if this matters.

### SQL Server Edition and Build number

I would be stunned if this matters.

### .NET Framework Version

I would be stunned if this matters.

**Comment by wsmelton** [comment]
<img width="1680" alt="image" src="https://github.com/dataplat/dbatools/assets/11204251/1d23567c-f1fe-4259-be03-41db3cd2efd8">

These are not expected to have brackets as they are assigned mandatory in the parameter set for each of them.

Our rendering code for the doc's site must not be able to determine/detect line break is needed which is why those are not showing on different lines.

**Comment by niphlod** [comment]
I'll see if the site can insert a newline properly so every param is on its own line (e.g. between -Database and -Query, etc)

**Comment by niphlod** [comment]
soooo, I think I fixed this AND found a way to render our docs even better.

First, as "it is" 

![image](https://github.com/dataplat/dbatools/assets/122119/f9a32a65-f266-4cfb-ba9e-db929fa5780e)

And as "it'll be"

![image](https://github.com/dataplat/dbatools/assets/122119/bc7ed693-7468-4620-b1ae-f59001f4a2ce)

Also, we weren't preserving correctly line breaks within paragraphs....

So, this is as "it is"

![image](https://github.com/dataplat/dbatools/assets/122119/79e2d929-8cef-46c6-b791-ebf4060b7db8)

while this is as "it'll be"
![image](https://github.com/dataplat/dbatools/assets/122119/549073cd-c0bb-4caf-8abc-1c6a87c4e502)

the line break are more closely related to what the inline help has as lines
![image](https://github.com/dataplat/dbatools/assets/122119/4b3f1e82-845e-47f6-bfc2-719947567492)

 so it *should* be better without breaking anything for all similar helps

Slightly different, but preserved nonetheless is, e.g., EnableException, which the inline code has as

![image](https://github.com/dataplat/dbatools/assets/122119/4db9d407-a1b0-4716-baf0-bbc35460a976)

it's now currently rendered as
![image](https://github.com/dataplat/dbatools/assets/122119/f4eafa7b-66fd-4240-850e-b04ea347e33e)

and  it'll be
![image](https://github.com/dataplat/dbatools/assets/122119/219092dc-3a0f-4b41-bdd5-d64a776a89f3)

@wsmelton , @potatoqualitee , @andreasjordan , do we wanna give it a try ?

**Comment by wsmelton** [comment]
I don't see any difference going to the [docs.dbatools.io](https://docs.dbatools.io/Invoke-DbaQuery). Is there a different want?

**Comment by niphlod** [comment]
@wsmelton  was asking BEFORE implementing the changes on the site. 
We don't have a "test site", but I can send the modified script that the GH Action runs, so you can do what the GH Action do and build it locally if you need previews of all of the pages, if needed.

**Comment by andreasjordan** [comment]
The proposed change seems good to me.

**Comment by niphlod** [comment]
if no other comments are coming I'm going to push the changes this weekend

**Comment by niphlod** [comment]
I pushed to the docs repo the new logic and manually refreshed the site. This PR https://github.com/dataplat/dbatools/pull/9377 just alignes the private, internal function, for people wanting to have a preview of how the docs page will be once built, with the new and "improved" rendering logic.

**Comment by potatoqualitee** [comment]
thank you @niphlod 😊  your docs updates are always a lifesaver.
