### ISSUE TITLE
Install-DbaFirstResponderKit is installing version 8.18, which is old

### ISSUE THREAD

**Issue by ReeceGoding** [dataplat/dbatools#9390]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

```powershell
Get-InstalledModule dbatools
```
reports that I'm on dbatools version 2.1.17.

On my server, 
```sql
DECLARE @VersionOutput VARCHAR(30), @VersionDateOutput DATETIME;
EXEC sp_BlitzIndex 
    @Version = @VersionOutput OUTPUT, 
    @VersionDate = @VersionDateOutput OUTPUT,
    @VersionCheckMode = 1;
SELECT
    @VersionOutput AS Version, 
    @VersionDateOutput AS VersionDate;
```
reports that I'm on version 8.18 of the First Responder Kit. The [latest release](https://github.com/BrentOzarULTD/SQL-Server-First-Responder-Kit/releases/tag/20240522) is version 8.20.

After running
```powershell
Install-DbaFirstResponderKit -SqlInstance MyBox
```
The above SQL reports exactly the same. The printed output also reports that we're installing `sp_BlitzQueryStore`, which is pretty odd given that I'm pretty sure it's no longer in the installer.

Overall, it appears that `Install-DbaFirstResponderKit` isn't installing the newest version. What have I stupidly missed?

### Steps to Reproduce

As above.

### Please confirm that you are running the most recent version of dbatools

Yep. `Get-Module dbatools | Select -ExpandProperty Version` confirms it.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

I doubt that's relevant.

### SQL Server Edition and Build number

I doubt that's relevant.

### .NET Framework Version

I doubt that's relevant.

**Comment by andreasjordan** [comment]
The source is cached. Please use -Force to download latest.

**Comment by ReeceGoding** [comment]
@andreasjordan I'm doing this wrong, aren't I? The below seemingly doesn't change what gets installed.
```powershell
Import-Module dbatools -Force
Install-DbaFirstResponderKit -SqlInstance MyBox
```

**Comment by andreasjordan** [comment]
Sorry, was on mobile.

Please use:
```
Import-Module dbatools
Install-DbaFirstResponderKit -SqlInstance MyBox -Force
```

**Comment by ReeceGoding** [comment]
Perfect. Thanks.
