### ISSUE TITLE
DbaCsv needs support for GUID target columns

### ISSUE THREAD

**Issue by petervandivier** [dataplat/dbatools#9433]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

> WARNING: [13:39:27][Import-DbaCsv] Failure | Invalid cast from 'System.String' to 'System.Guid'.

----

No obvious quick fix jumps out at me reading through the [SqlBulkCopy docs](https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlbulkcopy) at this time.

Possibly related: #8409 

### Steps to Reproduce

It appears that the `SqlBulkCopy` object as currently defined in `Invoke-DbaCsv` does not support inserting valid guid strings into a `uniqueidentifier` target column. 

The below repro errors out:

```powershell
Invoke-DbaQuery `
    -SqlInstance localhost `
    -Database tempdb `
    -Query "create table foo ([Guid] uniqueidentifier);"

New-Guid | Export-Csv ./foo.csv 

Import-DbaCsv `
    -SqlInstance localhost `
    -Database tempdb `
    -Table foo `
    -Path ./foo.csv `
    -SingleColumn
```

----

I tried to step through the source code to see if there was something obvious I was missing about this functionality. Extracting just the relevant code for a minimal repro appears to indicate that this may be an underlying issue with `SqlBulkCopy`

<details>
  <summary>SqlBulkCopy repro initialisation</summary>

```powershell  
$server = Connect-DbaInstance -SqlInstance localhost -Database tempdb
$sqlconn = $server.ConnectionContext.SqlConnectionObject
if ($sqlconn.State -ne 'Open') {$sqlconn.Open()}

# Import-DbaCsv.ps1#L540
# [int]$bulkCopyOptions = ([Microsoft.Data.SqlClient.SqlBulkCopyOptions]::Default)

# $bulkcopy = New-Object Microsoft.Data.SqlClient.SqlBulkCopy(
#     $sqlconn, 
#     $bulkCopyOptions, 
#     $transaction # $null
# )
# # New-Object: Cannot find an overload for "SqlBulkCopy" and the argument count: 3

$bulkcopy = New-Object Microsoft.Data.SqlClient.SqlBulkCopy($sqlconn)

$bulkcopy.DestinationTableName = 'foo'
$bulkcopy.BulkCopyTimeout = 0
$bulkCopy.BatchSize = 100
$bulkCopy.NotifyAfter = 30000
$bulkCopy.EnableStreaming = $true

$stream = [System.IO.File]::OpenRead("foo.csv")

$textReader = New-Object System.IO.StreamReader(
    $stream, 
    [System.Text.Encoding]::"UTF8"
)

$FirstRowHeader = $true
$Delimiter = ","
$Quote = '"'
$Escape = '"'
$Comment = '#'
$TrimmingOption = "None"
$BufferSize = 4096

$reader = New-Object LumenWorks.Framework.IO.Csv.CsvReader(
    $textReader,
    $FirstRowHeader,
    $Delimiter,
    $Quote,
    $Escape,
    $Comment,
    [LumenWorks.Framework.IO.Csv.ValueTrimmingOptions]::$TrimmingOption,
    $BufferSize,
    $NullValue # $null
)
```
</details>

After running the above initialisation, executing the below errors out. 

```powershell
$bulkCopy.WriteToServer($reader)
```

> MethodInvocationException: Exception calling "WriteToServer" with "1" argument(s): "The given value '8a8b0b97-bda2-4d1a-a978-5a8c1caa5cb2' of type String from the data source cannot be converted to type uniqueidentifier for Column 0 [Guid]."

### Please confirm that you are running the most recent version of dbatools

[`v2.1.15`](https://github.com/dataplat/dbatools/releases/tag/v2.1.15) - May 18, 2024

### Other details or mentions

Slack channel chat context: https://sqlcommunity.slack.com/archives/C1M2WEASG/p1721846945371649

### What PowerShell host was used when producing this error

VS Code (integrated terminal)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

```
Microsoft SQL Server 2022 (RTM-GDR) (KB5040936) - 16.0.1121.4 (X64) 
	Jul  2 2024 00:22:34 
	Copyright (C) 2022 Microsoft Corporation
	Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 22631: ) (Hypervisor)
```

### .NET Framework Version

`.NET 8.0.6`

**Comment by andreasjordan** [comment]
If you think it's an issue with SqlBulkCopy - why don't you open an issue against SqlBulkCopy? As you have shown, there is nothing dbatools can do here.

**Comment by petervandivier** [comment]
I don't believe that I've demonstrated there is nothing to be done. A cursory glance at the [SqlBulkCopy source code](https://github.com/microsoft/referencesource/blob/51cf7850defa8a17d815b4700b67116e3fa283c2/System.Data/System/Data/SqlClient/SqlBulkCopy.cs#L1390) seems to imply that GUID support exists (it would be a little shocking if it didn't). 

While I am unable at this time to parse out where the root cause exists, I'll be happy to open up an issue against either the SqlBulkCopy source or docs pages as and when the time seems ripe to do so. 

Even assuming SqlBulkCopy must be modified at source to support GUID target types, I imagine the lack of support demonstrated in this issue might warrant the addition of a unit test on resolution.

**Comment by andreasjordan** [comment]
My last comment was maybe too short. 

I don't see a quick fix. And I don't have time to do deeper investigations. So if you have the time and a solution, I would be happy to include it in the dbatools source code.

But maybe in the future, some other contributor can take the time and come up with a solution.

**Comment by petervandivier** [comment]
Idk, there appears to exist a GUID unit test](https://github.com/phatcher/CsvReader/blob/e432a6f75cf9cc6ece5377392b66c6f960fe3c07/code/LumenWorks.Framework.Tests.Unit/IO/Csv/ColumnTests.cs#L11-L21) in the LumenWorks source :thinking: 

```cs
namespace LumenWorks.Framework.Tests.Unit.IO.Csv
{
    [TestFixture]
    public class ColumnTests
    {
        [Test]
        public void ConvertGuid()
        {
            var expected = Guid.NewGuid();
            var column = new Column { Name = "A", Type = typeof(Guid) };
            var candidate = column.Convert(expected.ToString());
            Assert.IsInstanceOf<Guid>(candidate);
            Assert.That(expected == (Guid)candidate);
        }
```

**Comment by niphlod** [comment]
and what tells lumen to use a guid column when reading ? it doesn't do heuristic AFAIK, so we know that lumen supports guid, but IMHO we're not telling via Import-DbaCsv (again, AFAIK, we support playing with column mapping via NAME, nothing via TYPE)

**Comment by petervandivier** [comment]
> we know that lumen supports guid, but IMHO we're not telling via Import-DbaCsv 

This condition pops if-and-only-if we're inserting to a pre-existing table. At first thought a schema check would allow mapping of this sort.

Since it's not been reported before, perhaps this case is low-occurrence enough that it's prudent to save the schema check for a `catch{}` block if one of the known errors pops so we avoid the overhead for runs where it doesn't matter

**Comment by niphlod** [comment]
when the table gets autocreated all columns are nvarchar(max) so it's easy :D

**Comment by niphlod** [comment]
I did not forget about this, something that seemed like a 50LOC update is turning into a 500LOC one. I need to play a bit with lumen's API (fortunately there are examples to follow) directly in c# to figure out how to make it work on PS.

**Comment by niphlod** [comment]
@rezanid , @petervandivier , would you give #9479 a look, and maybe try that code as well ?
