### ISSUE TITLE
dbaTools Messing with the Background Job Queue

### ISSUE THREAD

**Issue by dpo007** [dataplat/dbatools#9434]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

No actual error, it just hangs indefinitely.

### Steps to Reproduce

Short version to see problem (fresh pwsh session):

```powershell
Import-Module dbatools

Get-Job
```

Example results:

```
Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      dbatools_Timer                  NotStarted    False                                 Get-PSSession | Where-O…
```

or

```
Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      dbatools_Timer                  Running       True                                  Get-PSSession | Where-O…
```

If you do not import dbaTools, Get-Job will be (expectedly) empty.

Long version/Example of problem it can cause:

```powershell
Import-Module dbatools

# Define the files or tasks you want to process
$files = @(
    "file1.txt",
    "file2.txt",
    "file3.txt",
    "file4.txt",
    "file5.txt",
    "file6.txt",
    "file7.txt",
    "file8.txt",
    "file9.txt"
)

# Define the number of batches
$batchSize = [math]::Ceiling($files.Count / 3) # 3 batches

# Create thread jobs for each batch
for ($i = 0; $i -lt 3; $i++) {
    $startIdx = $i * $batchSize
    $endIdx = [math]::Min(($i + 1) * $batchSize - 1, $files.Count - 1)
    $batchFiles = $files[$startIdx..$endIdx]
    
    Start-ThreadJob -ScriptBlock {
        param ($batchFiles)
        foreach ($file in $batchFiles) {
            # Simulate file processing
            Start-Sleep -Seconds (Get-Random -Minimum 1 -Maximum 5)
            Write-Host "Processed $File."
        }
    } -ArgumentList $batchFiles
}

# Wait for all jobs to complete
Get-Job | Receive-Job -Wait

Write-Host 'Done.'
```

If you import dbatools, it will never display "Done".
If you don't import it, "Done" will show after the 3 created batch jobs finish.

### Please confirm that you are running the most recent version of dbatools

```
Version              Name
-------              ----
2.1.22               dbatools
2024.4.12            dbatools.library
```

### What PowerShell host was used when producing this error

PowerShell Core (pwsh.exe)

### PowerShell Host Version

```
Name                           Value
----                           -----
PSVersion                      7.4.3
PSEdition                      Core
GitCommitId                    7.4.3
OS                             Microsoft Windows 10.0.22631
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

**Comment by andreasjordan** [comment]
This background job is part of dbatools. If you don't like this job, don't use dbatools. If you need dbatools, change your code to only test for your jobs and not all jobs.

**Comment by dpo007** [comment]
> This background job is part of dbatools.

I assessed that, hence I'm here.

> If you don't like this job, don't use dbatools.

Nice attitude Andreas. :/

> If you need dbatools, change your code to only test for your jobs and not all jobs.

Yes, I've already done that as a work-around.

So "Needs to be this way/Working as intended".  Got it.

**Comment by andreasjordan** [comment]
Maybe review your issue and think about your expectations. Or maybe I have misinterpreted your issue. I didn't want to sound rude - just quick to the point.
