### ISSUE TITLE
Test-DbaDbCompression is completely silent for empty tables

### ISSUE THREAD

**Issue by ReeceGoding** [dataplat/dbatools#9469]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

No error. It's just a case where we silently do nothing. This happens even if `-Verbose` and `EnableException` are enabled.

### Steps to Reproduce

```powershell
Test-DbaDbCompression -SqlInstance MyBox -Database MyDb -Table MyEmptyTable

Test-DbaDbCompression -SqlInstance MyBox -Database MyDb -Table MyEmptyTable -Verbose -EnableException
```

### Please confirm that you are running the most recent version of dbatools

Yes. Just updated.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Yes. Just updated.

### SQL Server Edition and Build number

SQL Server 2019. Was able to replicate on multiple versions.

### .NET Framework Version

Just updated.

**Comment by niphlod** [comment]
ahem .... there's no data to test compression so .... what output you'd expect ?

**Comment by ReeceGoding** [comment]
@niphlod I'd expect some notice, particularly when under `-verbose`.

**Comment by ReeceGoding** [comment]
@niphlod That's good practice, but it's easy to miss such things when you are checking a big number of tables. You end up in a confusing situation where some tables are doing what you expect but others don't.

As I recall, `sp_estimate_data_compression_savings` returns a row of 0s, which is better than silently doing nothing.

**Comment by niphlod** [comment]
yeah, my point is understanding what you're asking. 
either we figure out a way to insert all the tables in the result of the function, e.g. with a "N/A" or something like that, or we warn the user only via -verbose.

**Comment by niphlod** [comment]
it's all T-SQL so if it's doable it should be easy

**Comment by niphlod** [comment]
you may want to try itself, is it this filter ? https://github.com/dataplat/dbatools/blob/development/public/Test-DbaDbCompression.ps1#L218

**Comment by ReeceGoding** [comment]
@niphlod  Thanks. I may give this a try. My list of open-source work is currently long.

**Comment by niphlod** [comment]
no worries, it's still a good starting point for anyone who has enough time to look into it.
