### ISSUE TITLE
Issue with the last version of dbatools - Import-Module failed

### ISSUE THREAD

**Issue by lotrdocker** [dataplat/dbatools#9477]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

Import-Module : The required module 'dbatools.library' with version '2024.4.12' is not loaded. Load the module or remove the module from 'RequiredModules' in the file 'C:\Program
Files\WindowsPowerShell\Modules\dbatools\dbatools.psd1'.

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
After installation of dbatools and dbatools.library, I executed

**Import-Module "C:\Program Files\WindowsPowerShell\Modules\dbatools.library"
Import-Module "C:\Program Files\WindowsPowerShell\Modules\dbatools"**

### Please confirm that you are running the most recent version of dbatools

N/A

### Other details or mentions

**In dbatools.ps1 file:**
    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules    = @{ ModuleName = 'dbatools.library'; ModuleVersion = '2024.4.12' }

**In dbatools.library.ps1 file:**
    # Version number of this module.
    ModuleVersion          = '2024.3.9'

Wrong version number for dbatools.library.ps1, for both dbatools and dbatools.library, I downloaded the last version.

### What PowerShell host was used when producing this error

Windows PowerShell (powershell.exe)

### PowerShell Host Version

Name                           Value                                                                                                                                                                                      
----                           -----                                                                                                                                                                                      
PSVersion                      5.1.14393.7254                                                                                                                                                                             
PSEdition                      Desktop                                                                                                                                                                                    
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                    
BuildVersion                   10.0.14393.7254                                                                                                                                                                            
CLRVersion                     4.0.30319.42000                                                                                                                                                                            
WSManStackVersion              3.0                                                                                                                                                                                        
PSRemotingProtocolVersion      2.3                                                                                                                                                                                        
SerializationVersion           1.1.0.1                                                                                                                                                                                    

### SQL Server Edition and Build number

N/A

### .NET Framework Version

N/A

**Comment by niphlod** [comment]
are you sure you properly updated the library  ? dbatools.library is at 2024.4.12 . https://www.powershellgallery.com/packages/dbatools.library/2024.4.12

**Comment by niphlod** [comment]
download it from the official place, please

**Comment by lotrdocker** [comment]
Yes, I dowloaded it from Powershell Gallery and it's better. Problem solved, thank you.

**Comment by lotrdocker** [comment]
The module dbatools.library was downloaded from wrong repository.
