### ISSUE TITLE
dbaTools not recognizes latest sql security updates released on 8-10-24 

### ISSUE THREAD

**Issue by afzaalazizawan** [dataplat/dbatools#9502]
### Verified issue does not already exist?

I have searched and found no existing issue

### What error did you receive?

VERBOSE: [14:34:53][Resolve-DbaBuild] Looking for KB 5046059
VERBOSE: [14:34:53][Resolve-DbaBuild] We have 0 builds in store for this Release
WARNING: [14:34:53][Resolve-DbaBuild] No info in store for this Release

### Steps to Reproduce

```powershell
# provide your command(s) executed pertaining to dbatools
# please include variable values (redacted or fake if needed) for reference
```
#.... other variables
$kb = 'KB5046059'  # SQL2022 built 16.0.4150.1 CU15+GDR released on 8-10-24
Update-DbaInstance -ComputerName $server -KB $kb -Path $patchPath -Credential $cred -Verbose -Restart -Confirm:$false

### Please confirm that you are running the most recent version of dbatools

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     2.1.25                dbatools                            {Select-DbaObject, Set-DbatoolsConfig, Add-DbaAgDatabase, Add-DbaAgListener…}

### Other details or mentions

I did try to add information for latest updates into 
"C:\Program Files\PowerShell\Modules\dbatools\2.1.25\bin\dbatools-buildref-index.json" 

but it still not recognizes, am I missing anything 
Would appreciate for an advice how to manually update buildref for latest updates. 

### What PowerShell host was used when producing this error

VS Code (terminal)

### PowerShell Host Version

Name                           Value
----                           -----
PSVersion                      7.4.5
PSEdition                      Core
GitCommitId                    7.4.5
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

### SQL Server Edition and Build number

Microsoft SQL Server 2022 (RTM-CU14-GDR) (KB5042578) - 16.0.4140.3 (X64)   Aug 13 2024 13:46:25   Copyright (C) 2022 Microsoft Corporation  Developer Edition (64-bit) on Windows Server 2022 Datacenter 10.0 <X64> (Build 20348: ) (Hypervisor) 

### .NET Framework Version

.NET 8.0.8

PSChildName Version
----------- -------
Client      4.8.04161
Full        4.8.04161
Client      4.0.0.0

**Comment by niphlod** [comment]
there's a PR ready for it https://github.com/dataplat/dbatools/pull/9493 . Once it'll get merged, everything will work out of the box.

**Comment by afzaalazizawan** [comment]
Hi Simone

Many thanks for your update, Microsoft is releasing updates almost every
month and I have  to patch up my estate ASAP is there any way I can update
required build reference JSON myself

And when does  DBAtools team normally updates  dbatools after Microsoft
patch release

Regards
Afzaal
